### ISSUE TITLE
Can't pull openshift/busybox-http-app

### ISSUE THREAD

**Issue by exarkun** [moby/moby#15699]
When I try to pull this image, the Docker daemon reports it is up to date.  When I try to run a container using this image, the Docker daemon reports the image doesn't exist.  This happens every time I try the simple program attached (see below).

If I replace the image name with `openshift/busybox-http-app:latest" the problem seems to go away.

Here's a transcript of an interaction between the Docker daemon and a Python (docker-py-using) program that does a pull and a create:

```
POST /v1.19/images/create?fromImage=openshift%2Fbusybox-http-app HTTP/1.1
Host: 127.0.0.1:8118
Content-Length: 0
User-Agent: python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-48-generic
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate

HTTP/1.1 200 OK
Content-Type: application/json
Server: Docker/1.8.1 (linux)
Date: Wed, 19 Aug 2015 14:59:21 GMT
Transfer-Encoding: chunked

49
{"status":"Status: Image is up to date for openshift/busybox-http-app"}

0

POST /v1.19/containers/create?name=foo HTTP/1.1
Host: 127.0.0.1:8118
Content-Length: 185
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-48-generic
Connection: keep-alive
Content-Type: application/json

{"Tty": false, "NetworkDisabled": false, "Image": "openshift/busybox-http-app", "StdinOnce": false, "AttachStdin": false, "AttachStderr": true, "AttachStdout": true, "OpenStdin": false}HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Docker/1.8.1 (linux)
Date: Wed, 19 Aug 2015 14:59:21 GMT
Content-Length: 56

No such image: openshift/busybox-http-app (tag: latest)
```

I can reproduce this on Ubuntu 14.04 and CentOS 7 on AWS using Docker 1.8.1 from get.docker.com.

Ubuntu details:

`docker version`:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 0
Images: 26
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.305 GiB
Name: ip-172-31-44-108
ID: 3G6X:WSQ3:KGI6:YOJS:ANIO:WUB2:7L7F:U3AY:ZVB6:63T7:5UDO:AKRB
Debug mode (server): true
File Descriptors: 10
Goroutines: 18
System Time: 2015-08-19T15:09:20.151826902Z
EventsListeners: 0
Init SHA1: f03be8ef95c082e1e68bfb533064420fcfd161eb
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

`uname -a`:

```
Linux ip-172-31-44-108 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Running on AWS using ami-5189a661

Reproducer:

``` py
from docker import Client

client = Client(base_url="tcp://127.0.0.1:8118")
image_name = u"openshift/busybox-http-app"

print 'Pulling...'
client.pull(image_name)
print 'Pulled.  Creating...'
print client.create_container(
    name=u"foo",
    image=image_name,
)
print 'Created.'
```

The output of this program when I run it is:

```
Pulling...
Pulled.  Creating...
Traceback (most recent call last):
  File "create-2.py", line 11, in <module>
    image=image_name,
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/client.py", line 245, in create_container
    return self.create_container_from_config(config, name)
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/client.py", line 253, in create_container_from_config
    return self._result(res, True)
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/clientbase.py", line 108, in _result
    self._raise_for_status(response)
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/clientbase.py", line 103, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such image: openshift/busybox-http-app (tag: latest)")
```

Instead, I expect the `latest` tag of the image to be pulled and then used to run a new container.

**Comment by dmp42** [comment]
Can you provide your docker daemon logs? (preferably ran in debug with -D)

**Comment by exarkun** [comment]
```
DEBU[0306] Calling POST /images/create                  
INFO[0306] POST /v1.15/images/create?fromImage=openshift%2Fbusybox-http-app 
DEBU[0306] Trying to pull openshift/busybox-http-app from https://registry-1.docker.io v2 
```

**Comment by dmp42** [comment]
@exarkun this is not complete *daemon* logs unfortunately.

**Comment by exarkun** [comment]
It's the log from the relevant time period.  I'll post a complete log now if that's what you want.

**Comment by dmp42** [comment]
@exarkun there is necessarily something after "Trying to pull".

**Comment by exarkun** [comment]
Here's the `docker.log` file produced from this session:

```
ubuntu@ip-172-31-44-108:~$ sudo truncate --size 0 /var/log/upstart/docker.log                                                                                                                  
ubuntu@ip-172-31-44-108:~$ sudo service docker restart                                                                                                                                         
docker stop/waiting
docker start/running, process 27410
ubuntu@ip-172-31-44-108:~$ sudo chmod o+rw /var/run/docker.sock                                                                                                                                
ubuntu@ip-172-31-44-108:~$ /opt/flocker/bin/python create-2.py                                                                                                                                 
Pulling...
Pulled.  Creating...
Traceback (most recent call last):
  File "create-2.py", line 11, in <module>
    image=image_name,
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/client.py", line 245, in create_container
    return self.create_container_from_config(config, name)
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/client.py", line 253, in create_container_from_config
    return self._result(res, True)
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/clientbase.py", line 108, in _result
    self._raise_for_status(response)
  File "/opt/flocker/local/lib/python2.7/site-packages/docker/clientbase.py", line 103, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such image: openshift/busybox-http-app (tag: latest)")
ubuntu@ip-172-31-44-108:~$ sudo service docker stop
docker stop/waiting
```

https://gist.github.com/exarkun/e76fced68f8bd8178409

**Comment by exarkun** [comment]
> @exarkun there is necessarily something after "Trying to pull".

I would have thought so as well.  It doesn't appear as though anything related ever shows up, though.

**Comment by dmp42** [comment]
@exarkun these are not the daemon logs.
It's admittedly a bit confusing, but what you really need to get is the docker daemon logs (not the cli logs, and not the logs from your python client).

**Comment by thaJeztah** [comment]
Bit confused as well; I noticed that in your original description, calls are made to the v1.19 API, but your later logs are to v1.15? Or is that another API?

> INFO[0306] POST /v1.15/images/create?fromImage=openshift%2Fbusybox-http-app

**Comment by cpuguy83** [comment]
@dmp42 I repro'd this on IRC this morning against master + curl
Issues is specifically with this image when you don't specify a tag.
This is from a freshly started daemon after blowing away `/var/lib/docker`

```bash
root@29c929ffd969:/go/src/github.com/docker/docker# curl -XPOST localhost/images/create?fromImage=openshift/busybox-http-app
DEBU[0002] Calling POST /images/create
INFO[0002] POST /images/create?fromImage=openshift/busybox-http-app
DEBU[0002] Trying to pull openshift/busybox-http-app from https://registry-1.docker.io v2
{"status":"Status: Image is up to date for openshift/busybox-http-app"}
root@29c929ffd969:/go/src/github.com/docker/docker# curl localhost/images/json?all=1
DEBU[0038] Calling GET /images/json
INFO[0038] GET /images/json
[]
```
Adding the :latest tag works as expected.

**Comment by cpuguy83** [comment]
Note that I can do `curl -XPOST localhost/images/create?fromImage=cpuguy83/test` and it pulls as expected.... as does any other image I've tried.

**Comment by thaJeztah** [comment]
Looks like this has to be reported to https://support.docker.com then, perhaps they can check what's different with this repo?

**Comment by exarkun** [comment]
> It's admittedly a bit confusing, but what you really need to get is the docker daemon logs (not the cli logs, and not the logs from your python client).

@dmp42 Are you saying that what I put in the gist is not the docker daemon logs?  The lines "Daemon has completed initialization" and "Docker daemon" that appear in it seemed like strong suggestions to me that that's what it was.  I took this from /var/log/upstart/docker.log on an Ubuntu system.  If the daemon logs somewhere else, can you tell me where that is?  Thanks!

> Bit confused as well; I noticed that in your original description, calls are made to the v1.19 API, but your later logs are to v1.15? Or is that another API?

@thaJeztah Sorry about that.  I tried with different API versions to see if that made a difference and I observed the same behavior which each version I tried.  I was sloppy w/ the reporting and didn't make this clear.

> Looks like this has to be reported to https://support.docker.com then, perhaps they can check what's different with this repo?

Okay, I'll do that.  Thanks.

**Comment by thaJeztah** [comment]
> Okay, I'll do that. Thanks.

Thanks! Please keep us posted if they found something

**Comment by kizbitz** [comment]
Tested this on a new AWS Ubuntu instance:

```
ubuntu@ubuntu:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

ubuntu@ubuntu:~$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

ubuntu@ubuntu:~$ docker info
Containers: 1
Images: 14
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ubuntu
ID: XTBC:2XQW:BELM:FIPJ:TF3N:LE2S:WRPE:ZSX7:SP7R:Y7UU:6YTR:D6UQ
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2015-08-20T18:07:30.063531899Z
EventsListeners: 0
Init SHA1: f03be8ef95c082e1e68bfb533064420fcfd161eb
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```
Python test script I used (This fails):

```
from docker import Client

client = Client(base_url='unix://var/run/docker.sock')
image_name = u"openshift/busybox-http-app"

print 'Pulling...'
client.pull(image_name)
print 'Pulled.  Creating...'
print client.create_container(
    name=u"foo",
    image=image_name,
)
print 'Created.'
```

Changing the *image_name* line to: `image_name = u"openshift/busybox-http-app:latest"` works successfully

Daemon log:

```
Waiting for /var/run/docker.sock
DEBU[0000] Registering HEAD, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering PUT, /containers/{name:.*}/archive
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] docker group found. gid: 999
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
DEBU[0000] Using graph driver aufs
DEBU[0000] Using default logging driver json-file
DEBU[0000] Migrating existing containers
DEBU[0000] Creating images graph
DEBU[0000] Restored 0 elements
DEBU[0000] Creating repository list
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1
INFO[0000] Firewalld running: false
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING]
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]
DEBU[0000] Failed to Initialize Datastore due to datastore initialization requires a valid configuration. Operating in non-clustered mode
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE]
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
/var/run/docker.sock is up
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=d12ea79 execdriver=native-0.2 graphdriver=aufs version=1.8.1
DEBU[0016] Calling POST /images/create
INFO[0016] POST /v1.19/images/create?fromImage=openshift%2Fbusybox-http-app
DEBU[0016] Trying to pull openshift/busybox-http-app from https://registry-1.docker.io v2
DEBU[0016] Calling POST /containers/create
INFO[0016] POST /v1.19/containers/create?name=foo
ERRO[0016] Handler for POST /containers/create returned error: No such image: openshift/busybox-http-app (tag: latest)
ERRO[0016] HTTP Error                                    err=No such image: openshift/busybox-http-app (tag: latest) statusCode=404
DEBU[0095] Calling POST /images/create
INFO[0095] POST /v1.19/images/create?tag=latest&fromImage=openshift%2Fbusybox-http-app
DEBU[0095] Trying to pull openshift/busybox-http-app from https://registry-1.docker.io v2
DEBU[0095] Pulling tag from V2 registry: "latest"
DEBU[0095] v2 error: errcode.Error manifest unknown: manifest unknown
DEBU[0095] Error trying v2 registry: manifest unknown: manifest unknown
DEBU[0095] Trying to pull openshift/busybox-http-app from https://index.docker.io v1
DEBU[0095] hostDir: /etc/docker/certs.d/docker.io
DEBU[0095] [registry] Calling GET https://index.docker.io/v1/repositories/openshift/busybox-http-app/images
DEBU[0095] Retrieving the tag list
DEBU[0095] Got status code 200 from https://registry-1.docker.io/v1/repositories/openshift/busybox-http-app/tags/latest
DEBU[0095] Registering tags
DEBU[0095] Ancestry: [41d52a4e8dfa221b64c209984473ce3348f92a71eb33d051ffd157b5711a739e a963e46ca9a8a8fe27985df88a2a10088b19fbfdbbd78fcb658ac50c35c83828 e00c1737a1ce382079401b5fad9b9036fb19402fd20b81b0e091
7c0004cfd1fd faa6bb60018a09932884a0aad61ae73f82197146fcd47346eaa3de0d08c4bda1 e0bfe564e79b76250f6afac0e1d870114567688d63e66924a1f1887fe7e484a8 25de5aab7dcf7ee50a40e2c4858164eb5eb40fbe002a457348e57c75ebd79
7ee e99669bab669141b7b395b629ba9a5a49dfff639667907c250c960e5e3ba96b0 61ac3da04c45af9903374dc13cc7fe76d38d94e93307076eb380f1c78ef34890 e848148546bb5ab0dd7a51008ac5bad930bd195ad2e9287e085f9a658997b15e 70ee6
7c19ade9b85714627779062ffc8f7bcab04f63ce6a6f662ff2aaaf213af 24110dba3fdf94c9118db63de9d7f284231219d016329f032243123b08bfde50 1ea703a65bda96cb481aa54f6446ed7a9580a506da7a14eeedd6152d2c14cc4c b35a85c6432ebb
d00b2d9942e23adb10678242b4b2d3205619ff17a16f70b24a 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158]
DEBU[0095] server doesn't support resume
DEBU[0096] server supports resume
DEBU[0096] server supports resume
DEBU[0097] server supports resume
DEBU[0098] server supports resume
DEBU[0099] server supports resume
DEBU[0099] server supports resume
DEBU[0100] server supports resume
DEBU[0100] server supports resume
DEBU[0100] server supports resume
DEBU[0101] server supports resume
DEBU[0101] server supports resume
DEBU[0103] server supports resume
DEBU[0103] server supports resume
DEBU[0103] Calling POST /containers/create
INFO[0103] POST /v1.19/containers/create?name=foo
DEBU[0110] Calling GET /images/json
INFO[0110] GET /v1.20/images/json
DEBU[0155] Calling GET /info
INFO[0155] GET /v1.20/info
DEBU[0155] Calling GET /version
INFO[0155] GET /v1.20/version
DEBU[0155] Calling GET /info
INFO[0155] GET /v1.20/info
DEBU[0155] Calling GET /images/json
INFO[0155] GET /v1.20/images/json
DEBU[0155] Calling GET /containers/json
INFO[0155] GET /v1.20/containers/json?all=1&limit=20
DEBU[0155] Calling GET /containers/json
INFO[0155] GET /v1.20/containers/json?all=1&limit=20
DEBU[0155] Calling GET /containers/{name:.*}/json
INFO[0155] GET /v1.20/containers/2da60391c842/json
DEBU[0155] Calling GET /containers/{name:.*}/logs
INFO[0155] GET /v1.20/containers/2da60391c842/logs?stderr=1&stdout=1&tail=all
DEBU[0155] logs: begin stream
DEBU[0155] logs: end stream
DEBU[0155] Calling GET /containers/{name:.*}/json
INFO[0155] GET /v1.20/containers/2da60391c842/json
DEBU[0292] Calling GET /version
INFO[0292] GET /v1.20/version
DEBU[0296] Calling GET /info
INFO[0296] GET /v1.20/info
```

pulling directly from command line works: `docker pull openshift/busybox-http-app`

**Comment by exarkun** [comment]
The issue seems to have been resolved, perhaps by a change to Docker Hub?

**Comment by ianmiell** [comment]
Hmmm, I get this with every attempt to run applications using the openshift alpha all-in-one vm, eg:

```
Name:                   busybox-1-gdtjs
Namespace:              user2
Security Policy:        anyuid
Node:                   origin/10.0.2.15
Start Time:             Tue, 19 Jul 2016 16:11:33 -0400
Labels:                 app=busybox,deployment=busybox-1,deploymentconfig=busybox
Status:                 Pending
IP:                     172.17.0.13
Controllers:            ReplicationController/busybox-1
Containers:
  busybox:
    Container ID:
    Image:              busybox@sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
    Image ID:
    Port:
    QoS Tier:
      cpu:                      BestEffort
      memory:                   BestEffort
    State:                      Waiting
      Reason:                   ErrImagePull
    Ready:                      False
    Restart Count:              0
    Environment Variables:      <none>
Conditions:
  Type          Status
  Ready         False 
Volumes:
  default-token-2rf53:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-2rf53
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                    -------------                   --------        ------          -------
  57s           57s             1       {default-scheduler }                                    Normal          Scheduled       Successfully assigned busybox-1-gdtjs to origin
  56s           17s             3       {kubelet origin}        spec.containers{busybox}        Normal          Pulling         pulling image "busybox@sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b
6035630c9d7bf92402"
  54s           15s             3       {kubelet origin}        spec.containers{busybox}        Warning         Failed          Failed to pull image "busybox@sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4
392d97b6035630c9d7bf92402": manifest unknown: manifest unknown
  54s           15s             3       {kubelet origin}                                        Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "busybox" with E
rrImagePull: "manifest unknown: manifest unknown"

  54s   3s      3       {kubelet origin}        spec.containers{busybox}        Normal  BackOff         Back-off pulling image "busybox@sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92
402"
  54s   3s      3       {kubelet origin}                                        Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "busybox" with ImagePullBackOff: "Back-o
ff pulling image \"busybox@sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402\""
```

same with attempting to get an ubuntu image. (oc new-app ubuntu, which I know will fail on startup).

**Comment by thaJeztah** [comment]
@ianmiell sounds like an issue that needs to be reported at openshift?

**Comment by ianmiell** [comment]
oops, that's where I thought i'd landed!

**Comment by thaJeztah** [comment]
@ianmiell haha, no problem :smile:

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
