### ISSUE TITLE
Daemon lockup on hairpin nat and veth deletion

### ISSUE THREAD

**Issue by crosbymichael** [moby/moby#17443]
Ok, so I'm using my docker-stress tool found here to stress test the daemon.  You can download and build it here:

https://github.com/crosbymichael/docker-stress

If you run with:

``` bash
docker-stress -c 4 --containers 500
```

Here is the `stress.json`:

``` json
[
    {"name":"busybox", "args": ["true"]},
    {"name":"busybox", "args": ["sleep", "2"]},
    {"name":"busybox", "flags": ["--volumes-from", "redis", "--link", "redis:redis"], "args": ["true"]},
    {"name":"busybox", "flags": ["-v", "/data"], "args": ["true"]},
    {"name":"busybox", "flags": ["--link" , "redis:redis"], "args": ["ping", "-c", "5", "google.com"]}
]
```

More repeatable if you change `-c 4` to `-c 6`

Anyways we will hit a kernel bug on unregister net device.

```
[62903.496161] unregister_netdevice: waiting for vetha59dbae to become free. Usage count = 1
[62913.736257] unregister_netdevice: waiting for vetha59dbae to become free. Usage count = 1
[62923.976168] unregister_netdevice: waiting for vetha59dbae to become free. Usage count = 1
[62934.220242] unregister_netdevice: waiting for vetha59dbae to become free. Usage count = 1
[62944.460258] unregister_netdevice: waiting for vetha59dbae to become free. Usage count = 1
```

We cannot do much about that, however, it locks up the entire daemon, which should not happen.  You have to restart to get it to a usable state.

Here is the stack of the stuck goroutine:

```
goroutine 24645 [syscall, 92 minutes, locked to thread]:
syscall.Syscall6(0x2c, 0xc, 0xc208784ec0, 0x20, 0x0, 0xc2087
Oct 27 16:31:47 michael-stress-test docker[2798]: 84d34, 0xc, 0x1, 0x1, 0xc208784ec0)

/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.sendto(0xc, 0xc208784ec0, 0x20, 0x20, 0x0, 0xc208784d34, 0xc20000000c, 0x0, 0x0)

/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1923 +0x9a
syscall.Sendto(0xc, 0xc208784ec0, 0x20, 0x20, 0x0, 0x7fcbf96f3660, 0xc208784d28, 0x0, 0x0)

/usr/local/go/src/syscall/syscall_unix.go:234 +0xb6
github.com/vishvanandanetlinknl.(*NetlinkSocket).Send(0xc208784d20, 0xc209062300, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/vishvanandanetlinknlnl_linux.go:327 +0xdd
github.com/vishvanandanetlinknl.(*NetlinkRequest).Execute(0xc209062300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/vishvanandanetlinknlnl_linux.go:213 +0x126
github.com/vishvanandanetlink.LinkDel(0x7fcbf9715d28, 0xc2091ca280, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/vishvanandanetlink/link_linux.go:392 +0x251
github.com/docker/libnetwork/drivers/bridge.(*driver).DeleteEndpoint(0xc208556580, 0xc208557040, 0x40, 0xc208c27900, 0x40, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:1039 +0x5c8
github.com/docker/libnetwork.(*endpoint).deleteEndpoint(0xc20856a480, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:595 +0x22d
github.com/docker/libnetwork.(*endpoint).Delete(0xc20856a480, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:574 +0x71b
github.com/docker/libnetwork.(*sandbox).Delete(0xc208ac51e0, 0x0, 0x0)

/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:180 +0x73a
github.com/docker/docker/daemon.(*Container).releaseNetwork(0xc208d50e00)

/go/src/github.com/docker/docker/daemon/container_unix.go:1145 +0x380
github.com/docker/docker/daemon.(*Container).cleanup(0xc208d50e00)

/go/src/github.com/docker/docker/daemon/container.go:342 +0x33
github.co
Oct 27 16:31:47 michael-stress-test docker[2798]: m/docker/docker/daemon.(*containerMonitor).Close(0xc209099650, 0x0, 0x0)
```

Kernel:

`Linux michael-stress-test 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

4 cores

**Comment by tiborvass** [comment]
Ping @mrjana @sanimej

**Comment by thaJeztah** [comment]
also see https://github.com/docker/docker/issues/5618 ?

**Comment by crosbymichael** [comment]
this kernel bug seems to be related when the hairpin nat is enabled, which is not the docker default

**Comment by JonasT** [comment]
This might be a silly question, but is there actually a bug report on bugzilla.kernel.org yet?

I can see various attempts to work around this in docker in the tickets above, but nothing that indicates the kernel developers were informed about a potential bug so they can get a chance to address this issue to fix it properly in the long run..

**Comment by polarathene** [comment]
I am not able to reproduce this, as detailed in related issue: https://github.com/moby/moby/issues/5618#issuecomment-1537076724

No activity on this issue since 2016, and quite a bit has happened since within Docker and Kernel dev since then.

I tried to reproduce with the above example config. Seems some instructions were missing regarding redis, I just ran a redis image with a random volume attached. Not sure if that affects the reproduction. No time or other context was given for when the kernel event message should start appearing by either.

Output after a while from the Go program:

```
INFO[0307] ran 500 containers in 307.49 seconds (1.63 container per sec. or 0.61 sec. per container) 
INFO[0307] failures 0
```

**Comment by akerouanton** [comment]
I believe this is a duplicate of #5618. Kernel devs fixed a number of bugs that would trigger this error in the past 10 years, so I think there's nothing we can do here. Thus, let me close it as stale.
