### ISSUE TITLE
Create container with invalid name fails with 500 instead of 4xx

### ISSUE THREAD

**Issue by exarkun** [moby/moby#18192]
``` py
>>> from docker import Client
>>> c = Client()
>>> c.create_container(name="!!!", image="busybox")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jean-paul/Environments/flocker/local/lib/python2.7/site-packages/docker/api/container.py", line 116, in create_container
    return self.create_container_from_config(config, name)
  File "/home/jean-paul/Environments/flocker/local/lib/python2.7/site-packages/docker/api/container.py", line 127, in create_container_from_config
    return self._result(res, True)
  File "/home/jean-paul/Environments/flocker/local/lib/python2.7/site-packages/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/home/jean-paul/Environments/flocker/local/lib/python2.7/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Invalid container name (!!!), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed")
>>> 
```

This is an error due to bad input.  The server should report it like this, not like an internal problem.

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
