### ISSUE TITLE
External resolution failed, dial udp 172.17.0.1

### ISSUE THREAD

**Issue by byrnedo** [moby/moby#22850]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 48
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 429
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local rexray
 Network: overlay host bridge null
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: aws-prod-node-1
ID: X6WT:ZVAL:SXIO:QBJN:6YUX:BEDL:YKUU:CF64:C4NQ:HMIH:4LEX:7VUO
WARNING: No swap limit support
Labels:
 nodeindex=1
 role.service=true
 role.infra=true
 provider=generic
 ec2.instance.type.t2.small=true
Cluster store: consul://10.0.15.250:8500
Cluster advertise: 10.0.7.95:2376

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, part of 3 node swarm, running consul on 172.17.0.1, no error logs in consul at all, nothing in syslog.

**Describe the results you received:**
In docker logs: 

```
ERRO[1205348] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205350] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205355] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205357] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205359] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205363] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205365] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205926] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205926] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205926] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205927] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205957] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205957] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205959] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205959] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205959] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205960] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
ERRO[1205960] external resolution failed, dial udp 172.17.0.1:53: connect: network is unreachable 
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Ends up affecting db connections about 3 times a day. No problem on consul server or agent which runs on docker node.

**Comment by BSWANG** [comment]
I meet the same issue on docker version 1.12.6:

The Docker Daemon log:

```

Mar  7 11:27:58 iZm5ebfu0qqsrrpetw1qetZ dockerd: time="2017-03-07T11:27:58.869918626+08:00" level=wa
rning msg="Connect failed: dial udp 10.202.72.118:53: connect: network is unreachable"
Mar  7 11:27:58 iZm5ebfu0qqsrrpetw1qetZ dockerd: time="2017-03-07T11:27:58.869973945+08:00" level=wa
rning msg="Connect failed: dial udp 10.202.72.118:53: connect: network is unreachable"

```
 
The `kill -USR1` stack trace:
``` 
Mar  7 14:46:02 iZm5ebfu0qqsrrpetw1qetZ dockerd:     /usr/local/go/src/net/http/server.go:2137 +0x44e
goroutine 750439 [IO wait]:
net.runtime_pollWait(0x7f4b6815f9e8, 0x72, 0x70)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82263cc30, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82263cc30, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readMsg(0xc82263cbd0, 0xc820f47e00, 0x200, 0x200, 0xc8217ef4a0, 0x28, 0x28, 0xffffffffffffffff, 0x0, 0x0, ...)
    /usr/local/go/src/net/fd_unix.go:304 +0x33d
net.(*UDPConn).ReadMsgUDP(0xc821bef4c8, 0xc820f47e00, 0x200, 0x200, 0xc8217ef4a0, 0x28, 0x28, 0x200, 0x17172a0, 0x1, ...)
    /usr/local/go/src/net/udpsock_posix.go:96 +0x171
github.com/miekg/dns.ReadFromSessionUDP(0xc821bef4c8, 0xc820f47e00, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/udp.go:47 +0xc1
github.com/miekg/dns.(*Server).readUDP(0xc821cba000, 0xc821bef4c8, 0x77359400, 0x0, 0x0, 0x0, 0xc82156ae28, 0x0, 0x0)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:605 +0x190
github.com/miekg/dns.(*defaultReader).ReadUDP(0xc8226932d0, 0xc821bef4c8, 0x77359400, 0x0, 0x0, 0x0, 0xc8219248c0, 0x0, 0x0)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:230 +0x5f
github.com/miekg/dns.(*Server).serveUDP(0xc821cba000, 0xc821bef4c8, 0x0, 0x0)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:478 +0x1fe
github.com/miekg/dns.(*Server).ActivateAndServe(0xc821cba000, 0x0, 0x0)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:354 +0x23c
github.com/docker/libnetwork.(*resolver).Start.func2(0xc821cba000)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:127 +0x21
created by github.com/docker/libnetwork.(*resolver).Start
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:128 +0x32e

```

**Comment by fabio-barile** [comment]
Hi  
We are experimenting the same issue on 1 worker of a  production SWARM cluster (3 managers - 14 workers - Ubuntu 16.04.3 )

docker version is 18.03.1

everything works fine excepted these entries in logs : 

> May 29 15:31:56 prod-worker-5-1 dockerd[23665]: time="2018-05-29T15:31:56.985216645Z" level=warning msg="[resolver] connect failed: dial udp 10.180.0.3:53: connect: network is unreachable"
> May 29 15:31:56 prod-worker-5-1 dockerd[23665]: time="2018-05-29T15:31:56.985283921Z" level=warning msg="[resolver] connect failed: dial udp 10.180.0.3:53: connect: network is unreachable"
> May 29 15:31:56 prod-worker-5-1 dockerd[23665]: time="2018-05-29T15:31:56.985327140Z" level=warning msg="[resolver] connect failed: dial udp 10.180.0.2:53: connect: network is unreachable"
> May 29 15:31:56 prod-worker-5-1 dockerd[23665]: time="2018-05-29T15:31:56.985385702Z" level=warning msg="[resolver] connect failed: dial udp 10.180.0.2:53: connect: network is unreachable"
> May 29 15:31:56 prod-worker-5-1 dockerd[23665]: time="2018-05-29T15:31:56.985461767Z" level=warning msg="[resolver] connect failed: dial udp 10.180.0.3:53: connect: network is unreachable"
> May 29 15:31:56 prod-worker-5-1 dockerd[23665]: time="2018-05-29T15:31:56.985521216Z" level=warning msg="[resolver] connect failed: dial udp 10.180.0.2:53: connect: network is unreachable"
> 
I have try to reach the dns using netcat (nc -vz  10.180.0.3 53 ) : it works fine
This issue occurred suddenly during the night last friday.

How can we fix it without restarting the service  ? As I said this is a production system

FYI : @thaJeztah

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
