### ISSUE TITLE
Panic in encoding/json.(*decodeState).literalStore

### ISSUE THREAD

**Issue by ibuildthecloud** [moby/moby#23158]
I opened my laptop and got this.  This is not the first time I've seen this, but this is the first time I've seen this when I was sure I was running 1.11.1.  There was a similar issue to this before that was caused by concurrent access to a json data structure that was still being Unmarshaled

```
docker version && docker info
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 6169
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.5
Operating System: Ubuntu 15.10 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.4 GiB
Name: inotmac
ID: HMGD:MCSR:XSNO:I7OW:2H7X:KE3J:XIUK:FEOU:SR4J:PVBZ:B3KW:2C6V
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 31
 System Time: 2016-05-31T21:45:39.367158906-07:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: 
 Docker Root Dir: /var/lib/docker
Username: ibuildthecloud
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

```
fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x68e6be]

goroutine 103 [running]:
runtime.throw(0x17b1cb8, 0x5)
    /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc82ee6fa40 sp=0xc82ee6fa28
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc82ee6fa90 sp=0xc82ee6fa40
encoding/json.(*decodeState).literalStore(0xc82bbdf770, 0xc82bf2f93c, 0x1f, 0x836, 0x12b5360, 0xc830a464d8, 0xd8, 0x0)
    /usr/local/go/src/encoding/json/decode.go:738 +0xb4e fp=0xc82ee6ff38 sp=0xc82ee6fa90
encoding/json.(*decodeState).literal(0xc82bbdf770, 0x12b5360, 0xc830a464d8, 0xd8)
    /usr/local/go/src/encoding/json/decode.go:646 +0xe9 fp=0xc82ee6ffa0 sp=0xc82ee6ff38
encoding/json.(*decodeState).value(0xc82bbdf770, 0x12b5360, 0xc830a464d8, 0xd8)
    /usr/local/go/src/encoding/json/decode.go:299 +0x397 fp=0xc82ee70078 sp=0xc82ee6ffa0
encoding/json.(*decodeState).object(0xc82bbdf770, 0x1639320, 0xc830a464b0, 0xd9)
    /usr/local/go/src/encoding/json/decode.go:613 +0x1179 fp=0xc82ee70420 sp=0xc82ee70078
encoding/json.(*decodeState).value(0xc82bbdf770, 0x1639320, 0xc830a464b0, 0xd9)
    /usr/local/go/src/encoding/json/decode.go:296 +0x3bd fp=0xc82ee704f8 sp=0xc82ee70420
encoding/json.(*decodeState).array(0xc82bbdf770, 0x127a0c0, 0xc838097858, 0xd7)
    /usr/local/go/src/encoding/json/decode.go:447 +0xa6b fp=0xc82ee70700 sp=0xc82ee704f8
encoding/json.(*decodeState).value(0xc82bbdf770, 0x127a0c0, 0xc838097858, 0xd7)
    /usr/local/go/src/encoding/json/decode.go:293 +0x3dd fp=0xc82ee707d8 sp=0xc82ee70700
encoding/json.(*decodeState).object(0xc82bbdf770, 0x165b620, 0xc838097680, 0xd9)
    /usr/local/go/src/encoding/json/decode.go:613 +0x1179 fp=0xc82ee70b80 sp=0xc82ee707d8
encoding/json.(*decodeState).value(0xc82bbdf770, 0x164cda0, 0xc838097680, 0x16)
    /usr/local/go/src/encoding/json/decode.go:296 +0x3bd fp=0xc82ee70c58 sp=0xc82ee70b80
encoding/json.(*decodeState).unmarshal(0xc82bbdf770, 0x164cda0, 0xc838097680, 0x0, 0x0)
    /usr/local/go/src/encoding/json/decode.go:157 +0x196 fp=0xc82ee70d30 sp=0xc82ee70c58
encoding/json.Unmarshal(0xc82bf2e800, 0x1772, 0x1972, 0x164cda0, 0xc838097680, 0x0, 0x0)
    /usr/local/go/src/encoding/json/decode.go:85 +0x12b fp=0xc82ee70da0 sp=0xc82ee70d30
github.com/docker/docker/image.NewFromJSON(0xc82bf2e800, 0x1772, 0x1972, 0xc82bf2e800, 0x0, 0x0)
    /go/src/github.com/docker/docker/image/image.go:128 +0xaf fp=0xc82ee70e30 sp=0xc82ee70da0
github.com/docker/docker/image.(*store).Get(0xc82028bac0, 0xc82086f270, 0x47, 0xc82ee70f00, 0x0, 0x0)
    /go/src/github.com/docker/docker/image/store.go:189 +0xee fp=0xc82ee70ec8 sp=0xc82ee70e30
github.com/docker/docker/image.(*store).imagesMap(0xc82028bac0, 0x1, 0x0)
    /go/src/github.com/docker/docker/image/store.go:287 +0x1f6 fp=0xc82ee70fe8 sp=0xc82ee70ec8
github.com/docker/docker/image.(*store).Map(0xc82028bac0, 0xc82f882a40)
    /go/src/github.com/docker/docker/image/store.go:274 +0x26 fp=0xc82ee71008 sp=0xc82ee70fe8
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc820066f00, 0xc82fecaf60, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/info.go:76 +0x636 fp=0xc82ee712d8 sp=0xc82ee71008
github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo(0xc8206531d0, 0x7fcfe0240140, 0xc82fecaf60, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0, 0xc82fecac00, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/router/system/system_routes.go:30 +0x53 fp=0xc82ee71348 sp=0xc82ee712d8
github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm(0x7fcfe0240140, 0xc82fecaf60, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0, 0xc82fecac00, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/router/system/system.go:22 +0x74 fp=0xc82ee71398 sp=0xc82ee71348
github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fcfe0240140, 0xc82fecaf60, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0, 0xc82fecac00, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43 fp=0xc82ee71548 sp=0xc82ee71398
github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fcfe0240140, 0xc82fecaf30, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0, 0xc82fecac00, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6b8 fp=0xc82ee716d8 sp=0xc82ee71548
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7fcfe0a85200, 0xc82000f040, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0, 0xc82fecac00, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware/debug.go:21 +0xd57 fp=0xc82ee71970 sp=0xc82ee716d8
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0)
    /go/src/github.com/docker/docker/api/server/server.go:132 +0x138 fp=0xc82ee71a68 sp=0xc82ee71970
net/http.HandlerFunc.ServeHTTP(0xc820cda340, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0)
    /usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc82ee71a88 sp=0xc82ee71a68
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820ec2140, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0)
    /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e fp=0xc82ee71ba0 sp=0xc82ee71a88
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820fb3d20, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0)
    /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72 fp=0xc82ee71bd0 sp=0xc82ee71ba0
net/http.serverHandler.ServeHTTP(0xc820303560, 0x7fcfe0a99dc8, 0xc835d52a50, 0xc82c260fc0)
    /usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc82ee71c30 sp=0xc82ee71bd0
net/http.(*conn).serve(0xc821fda840)
    /usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc82ee71f88 sp=0xc82ee71c30
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82ee71f90 sp=0xc82ee71f88
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by LK4D4** [comment]
![darren](https://media.giphy.com/media/ozmcaOBoLSY2k/giphy.gif)
It's weird, data structure created right before `Unmarshal` call. But we saw the similar cryptic error when I occasionally removed an important variable from struct used in cgo; random goroutine was killed by sigpanic.
@ibuildthecloud is there other goroutines in trace?

**Comment by tonistiigi** [comment]
. @ibuildthecloud managed to get it in `1.12` as well: https://github.com/docker/docker/issues/26619

**Comment by LK4D4** [comment]
Now I think maybe it's map race. It's not always reported like map race, but still kills daemon.

**Comment by thaJeztah** [comment]
@LK4D4 is this something to look into for a patch release?

**Comment by thaJeztah** [comment]
I see https://github.com/moby/moby/issues/26666 (marked as possible dup of https://github.com/moby/moby/issues/26619) linked to various changes in locking that were made after this. I haven't seen this issue reproduce recently, so let me close this one
