### ISSUE TITLE
Strange behavior handling overlay network

### ISSUE THREAD

**Issue by uggla** [moby/moby#23167]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
cloud@dockerdc1:~/docker/env$ docker --version
Docker version 1.10.3-cs3, build 6df5588
```

**Output of `docker info`:**

```
cloud@dockerdc1:~/docker/env$ docker info
Containers: 43
 Running: 39
 Paused: 0
 Stopped: 4
Images: 120
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 dockerdc1: 10.3.81.106:12376
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 8.187 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-27-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-01T16:01:25Z
 dockerdc2: 10.3.81.107:12376
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 8.187 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-27-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-01T16:00:42Z
 dockerdc3: 10.3.81.108:12376
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 8.187 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-27-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-01T16:00:52Z
 dockereng1: 10.3.81.112:12376
  └ Status: Healthy
  └ Containers: 12
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 8.187 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-27-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-01T16:00:47Z
Cluster Managers: 3
 10.3.81.106: Healthy
  └ Orca Controller: https://10.3.81.106:443
  └ Swarm Manager: tcp://10.3.81.106:2376
  └ KV: etcd://10.3.81.106:12379
 10.3.81.107: Healthy
  └ Orca Controller: https://10.3.81.107:443
  └ Swarm Manager: tcp://10.3.81.107:2376
  └ KV: etcd://10.3.81.107:12379
 10.3.81.108: Healthy
  └ Orca Controller: https://10.3.81.108:443
  └ Swarm Manager: tcp://10.3.81.108:2376
  └ KV: etcd://10.3.81.108:12379
Plugins: 
 Volume: 
 Network: 
Kernel Version: 4.2.0-27-generic
Operating System: linux
Architecture: amd64
CPUs: 8
Total Memory: 32.75 GiB
Name: ucp-controller-dockerdc1
ID: H7RB:RTPV:2RWV:SZ36:MHFT:7PUG:5XDE:GSSQ:4TEL:HXWN:EBFK:QEFM
Labels:
 com.docker.ucp.license_key=6yuiEY9Y7g1r0XuxTrR37ZYdYqRSjvFE3dBll54fMWfs
 com.docker.ucp.license_max_engines=1
 com.docker.ucp.license_expires=2016-06-09 13:38:37 +0000 UTC

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Docker datacenter (UCP / DTR) is build on top of vmware vcenter. (6 ESX nodes)
- All nodes are healthy from UCP node dashboard.
- Same for etcd services on all nodes

**Steps to reproduce the issue:**
1. Create an overlay network
2. Delete overlay network
3. Try to recreate

**Describe the results you received:**

```
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
e2eef120be4af200f1964e687a3f7052657191f8c05d091cfeb00fcb41fe79d4
cloud@dockerdc1:~/docker/env$ docker network rm mynetwork
Error response from daemon: network e2eef120be4af200f1964e687a3f7052657191f8c05d091cfeb00fcb41fe79d4 not found
cloud@dockerdc1:~/docker/env$ docker network rm mynetwork
Error response from daemon: network e2eef120be4af200f1964e687a3f7052657191f8c05d091cfeb00fcb41fe79d4 not found
cloud@dockerdc1:~/docker/env$ docker network rm mynetwork
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
cloud@dockerdc1:~/docker/env$ docker network create mynetwork
318f731dae10f35fa1040b2e009e30e7a251924c4aea8b2701b015e9e4a68c6f
```

I think this is related to the above issue, but it impacts docker-compose :

```
cloud@dockerdc1:~/orchestration-workshop/dockercoins$ docker-compose -f docker-compose.yml-v2 up -d
Creating network "dockercoins_default" with the default driver
ERROR: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
```

However sometimes it works after several attempts, but services fail to attach to the overlay network at bit later :

```
cloud@dockerdc1:~/orchestration-workshop/dockercoins$ docker-compose -f docker-compose.yml-v2 up -d
Creating network "dockercoins_default" with the default driver
Creating dockercoins_redis_1
Creating dockercoins_webui_1
Creating dockercoins_worker_1
Creating dockercoins_rng_1
Creating dockercoins_hasher_1

ERROR: for worker  network dockercoins_default not found

ERROR: for redis  network dockercoins_default not found
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

**Describe the results you expected:**
- Clean behavior, no more ERROR: 500.
- Hoping it will allow docker-compose to work as expected.

**Comment by cpuguy83** [comment]
It sounds like one of your nodes is not configured to read the K/V store.

**Comment by uggla** [comment]
Hello @cpuguy83,

Maybe a bit more info,
I try to look at the troubleshooting page.

I have a etcd container on each container controller.
```
cloud@dockerdc1:~/orchestration-workshop/dockercoins$ docker ps -a | grep etcd
446629c8b224        sha256:205bc764d14b5c6980ef5812bc0587c30aa22e8c233280d36701e2f347bf4043   "/etcd"                  2 weeks ago         Up 2 weeks               2379-2380/tcp, 4001/tcp, 7001/tcp                                                         dockereng1/dtr-etcd-d2545afda9f6
f9c37f34dc48        docker/ucp-etcd:1.1.0                                                     "/bin/etcd --data-dir"   3 weeks ago         Up 3 weeks               2380/tcp, 4001/tcp, 7001/tcp, 10.3.81.108:12380->12380/tcp, 10.3.81.108:12379->2379/tcp   dockerdc3/ucp-kv
8c00bedf391f        docker/ucp-etcd:1.1.0                                                     "/bin/etcd --data-dir"   3 weeks ago         Up 3 weeks               2380/tcp, 4001/tcp, 7001/tcp, 10.3.81.107:12380->12380/tcp, 10.3.81.107:12379->2379/tcp   dockerdc2/ucp-kv
31e6a76bac3b        docker/ucp-etcd:1.1.0                                                     "/bin/etcd --data-dir"   3 weeks ago         Up 3 weeks               2380/tcp, 4001/tcp, 7001/tcp, 10.3.81.106:12380->12380/tcp, 10.3.81.106:12379->2379/tcp   dockerdc1/ucp-kv

cloud@dockerdc1:~/orchestration-workshop/dockercoins$ docker exec -it f9c37f34dc48 etcdctl         --endpoint https://127.0.0.1:2379         --ca-file /etc/docker/ssl/ca.pem         --cert-file /etc/docker/ssl/cert.pem         --key-file /etc/docker/ssl/key.pem         cluster-health
member 680fd9b6a037823f is healthy: got healthy result from https://10.3.81.106:12379
member b8373701e4383d4d is healthy: got healthy result from https://10.3.81.108:12379
member ec9d1538c514a855 is healthy: got healthy result from https://10.3.81.107:12379
cluster is healthy
```
Regarding configuration that sounds etcd is refered on all node configuration file.
```
[uggla@ugglalaptop dockercoins]$ ssh cloud@10.3.81.106 "sudo sh -c 'cat /etc/docker/daemon.json'"
{
	"cluster-advertise": "10.3.81.106:12376",
	"cluster-store": "etcd://10.3.81.106:12379",
	"cluster-store-opts": {
		"kv.cacertfile": "/var/lib/docker/discovery_certs/ca.pem",
		"kv.certfile": "/var/lib/docker/discovery_certs/cert.pem",
		"kv.keyfile": "/var/lib/docker/discovery_certs/key.pem"
	}
}[uggla@ugglalaptop dockercoins]$ ssh cloud@10.3.81.107 "sudo sh -c 'cat /etc/docker/daemon.json'"
{
	"cluster-advertise": "10.3.81.107:12376",
	"cluster-store": "etcd://10.3.81.107:12379",
	"cluster-store-opts": {
		"kv.cacertfile": "/var/lib/docker/discovery_certs/ca.pem",
		"kv.certfile": "/var/lib/docker/discovery_certs/cert.pem",
		"kv.keyfile": "/var/lib/docker/discovery_certs/key.pem"
	}
}[uggla@ugglalaptop dockercoins]$ ssh cloud@10.3.81.108 "sudo sh -c 'cat /etc/docker/daemon.json'"
{
	"cluster-advertise": "10.3.81.108:12376",
	"cluster-store": "etcd://10.3.81.108:12379",
	"cluster-store-opts": {
		"kv.cacertfile": "/var/lib/docker/discovery_certs/ca.pem",
		"kv.certfile": "/var/lib/docker/discovery_certs/cert.pem",
		"kv.keyfile": "/var/lib/docker/discovery_certs/key.pem"
	}
}[uggla@ugglalaptop dockercoins]$ ssh cloud@10.3.81.112 "sudo sh -c 'cat /etc/docker/daemon.json'"
{
	"cluster-advertise": "10.3.81.112:12376",
	"cluster-store": "etcd://10.3.81.106:12379,10.3.81.107:12379,10.3.81.108:12379",
	"cluster-store-opts": {
		"kv.cacertfile": "/var/lib/docker/discovery_certs/ca.pem",
		"kv.certfile": "/var/lib/docker/discovery_certs/cert.pem",
		"kv.keyfile": "/var/lib/docker/discovery_certs/key.pem"
	}

[uggla@ugglalaptop dockercoins]$ !1027
ssh cloud@10.3.81.112 "sudo sh -c 'ps -ef | grep docker' | grep swarm"
root     17311 17214  0 May11 ?        00:01:03 /swarm join --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.112:12376 --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes etcd://10.3.81.106:12379
cloud    19597 19596  0 19:25 ?        00:00:00 bash -c sudo sh -c 'ps -ef | grep docker' | grep swarm
[uggla@ugglalaptop dockercoins]$ !1028
ssh cloud@10.3.81.106 "sudo sh -c 'ps -ef | grep docker' | grep swarm"
cloud    12885 12884  0 19:25 ?        00:00:00 bash -c sudo sh -c 'ps -ef | grep docker' | grep swarm
root     18533 16872  0 May11 ?        00:00:58 /swarm join --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.106:12376 etcd://10.3.81.106:12379
root     18574 16872  0 May11 ?        00:29:59 /swarm manage --tlsverify --tlscacert /etc/docker/ssl/ca.pem --tlscert /etc/docker/ssl/cert.pem --tlskey /etc/docker/ssl/key.pem --replication --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.106:2376 --strategy spread etcd://10.3.81.106:12379
root     19034 16872  0 May11 ?        00:53:09 /bin/controller server --discovery etcd://10.3.81.106:12379 --docker tcp://10.3.81.106:2376 --orca-tls-ca-cert /etc/docker/ssl/orca/ca.pem --orca-tls-cert /etc/docker/ssl/orca/cert.pem --orca-tls-key /etc/docker/ssl/orca/key.pem --tls-ca-cert /etc/docker/ssl/swarm/ca.pem --tls-cert /etc/docker/ssl/swarm/cert.pem --tls-key /etc/docker/ssl/swarm/key.pem --discovery-tls-ca-cert /etc/docker/ssl/swarm/ca.pem --discovery-tls-cert /etc/docker/ssl/swarm/cert.pem --discovery-tls-key /etc/docker/ssl/swarm/key.pem
[uggla@ugglalaptop dockercoins]$ ssh cloud@10.3.81.112 "sudo sh -c 'ps -ef | grep docker' | grep swarm"^C
[uggla@ugglalaptop dockercoins]$ !1029
ssh cloud@10.3.81.107 "sudo sh -c 'ps -ef | grep docker' | grep swarm"
root      1497   691  0 May11 ?        00:01:55 /swarm join --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.107:12376 --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes etcd://10.3.81.106:12379
root      1641   691  0 May11 ?        00:51:47 /swarm manage --tlsverify --tlscacert /etc/docker/ssl/ca.pem --tlscert /etc/docker/ssl/cert.pem --tlskey /etc/docker/ssl/key.pem --replication --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.107:2376 --strategy spread etcd://10.3.81.107:12379
root      2879   691  0 May11 ?        01:20:25 /bin/controller server --discovery etcd://10.3.81.107:12379 --docker tcp://10.3.81.107:2376 --orca-tls-ca-cert /etc/docker/ssl/orca/ca.pem --orca-tls-cert /etc/docker/ssl/orca/cert.pem --orca-tls-key /etc/docker/ssl/orca/key.pem --tls-ca-cert /etc/docker/ssl/swarm/ca.pem --tls-cert /etc/docker/ssl/swarm/cert.pem --tls-key /etc/docker/ssl/swarm/key.pem --discovery-tls-ca-cert /etc/docker/ssl/swarm/ca.pem --discovery-tls-cert /etc/docker/ssl/swarm/cert.pem --discovery-tls-key /etc/docker/ssl/swarm/key.pem
cloud    14863 14862  0 19:26 ?        00:00:00 bash -c sudo sh -c 'ps -ef | grep docker' | grep swarm
[uggla@ugglalaptop dockercoins]$ !1030
ssh cloud@10.3.81.108 "sudo sh -c 'ps -ef | grep docker' | grep swarm"
cloud     6679  6678  0 19:26 ?        00:00:00 bash -c sudo sh -c 'ps -ef | grep docker' | grep swarm
root     19213 19120  0 May11 ?        00:01:59 /swarm join --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.108:12376 --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes etcd://10.3.81.106:12379
root     19522 19120  0 May11 ?        01:36:49 /bin/controller server --discovery etcd://10.3.81.108:12379 --docker tcp://10.3.81.108:2376 --orca-tls-ca-cert /etc/docker/ssl/orca/ca.pem --orca-tls-cert /etc/docker/ssl/orca/cert.pem --orca-tls-key /etc/docker/ssl/orca/key.pem --tls-ca-cert /etc/docker/ssl/swarm/ca.pem --tls-cert /etc/docker/ssl/swarm/cert.pem --tls-key /etc/docker/ssl/swarm/key.pem --discovery-tls-ca-cert /etc/docker/ssl/swarm/ca.pem --discovery-tls-cert /etc/docker/ssl/swarm/cert.pem --discovery-tls-key /etc/docker/ssl/swarm/key.pem
root     19548 19120  0 May11 ?        00:55:16 /swarm manage --tlsverify --tlscacert /etc/docker/ssl/ca.pem --tlscert /etc/docker/ssl/cert.pem --tlskey /etc/docker/ssl/key.pem --replication --discovery-opt kv.cacertfile=/etc/docker/ssl/ca.pem --discovery-opt kv.certfile=/etc/docker/ssl/cert.pem --discovery-opt kv.keyfile=/etc/docker/ssl/key.pem --discovery-opt kv.path=/docker/nodes --advertise 10.3.81.108:2376 --strategy spread etcd://10.3.81.108:12379

```

**Comment by sam-thibault** [comment]
This is an old issue and overlay networks with an external K/V store has been deprecated.  I will close it.
