### ISSUE TITLE
panic when starting dockerd (v1.12.0)

### ISSUE THREAD

**Issue by chenpengdev** [moby/moby#25356]
docker version

```
[root@cpcentos6 docker.service.d]# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64
```

docker swarm mode

```
[root@cpcentos6 docker.service.d]# /usr/bin/dockerd  -H=tcp://0.0.0.0:2376 --registry-mirror=http://mirror.ghostcloud.cn --insecure-registry=192.168.6.2:5001
WARN[0000] [!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!] 
INFO[0000] libcontainerd: new containerd process, pid: 41122 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
WARN[0001] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
WARN[0001] devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored. 
INFO[0001] [graphdriver] using prior storage driver "devicemapper" 
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
WARN[0001] mountpoint for pids not found                
INFO[0001] Loading containers: start.                   
INFO[0001] Firewalld running: true                      
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 

INFO[0001] Loading containers: done.                    
INFO[0002] Listening for connections                     addr=[::]:2377 proto=tcp
INFO[0002] Listening for local connections               addr=/var/lib/docker/swarm/control.sock proto=unix
WARN[0002] ignoring request to join cluster, because raft state already exists 
INFO[0002] 63b069b31f4ee3d0 became follower at term 5   
INFO[0002] newRaft 63b069b31f4ee3d0 [peers: [], term: 5, commit: 0, applied: 0, lastindex: 0, lastterm: 0] 
PANI[0003] tocommit(3425) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? 
panic: (*logrus.Entry) (0x1cfe940,0xc820ad9a40)

goroutine 87 [running]:
panic(0x1cfe940, 0xc820ad9a40)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/Sirupsen/logrus.Entry.log(0xc82000a2c0, 0xc82036c090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820ab0000, ...)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/Sirupsen/logrus/entry.go:113 +0x62c
github.com/Sirupsen/logrus.(*Entry).Panic(0xc820305a40, 0xc8210b63b8, 0x1, 0x1)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc820305a40, 0x20a6700, 0x5d, 0xc820cbb9c0, 0x2, 0x2)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/Sirupsen/logrus/entry.go:206 +0x139
github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8203afd50, 0xd61)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc820d36780, 0x8, 0xbcffd7d37c9266f, 0x4e922094287f5a30, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
github.com/coreos/etcd/raft.stepFollower(0xc820d36780, 0x8, 0xbcffd7d37c9266f, 0x4e922094287f5a30, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
github.com/coreos/etcd/raft.(*raft).Step(0xc820d36780, 0x8, 0xbcffd7d37c9266f, 0x4e922094287f5a30, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
github.com/coreos/etcd/raft.(*node).run(0xc820cddbd0, 0xc820d36780)
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
created by github.com/coreos/etcd/raft.RestartNode
    /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
```

**Comment by thaJeztah** [comment]
Was this after a restart of the host? Did docker shut down cleanly, or a hard reboot?

I see there's a message in the logs that the raft log is corrupted, so wondering why that happened; what platform/distro and version are you running on?

**Comment by thaJeztah** [comment]
closing because of no activity

**Comment by guenhter** [comment]
Same issue here

```
/usr/bin/dockerd --version
Docker version 1.12.2, build bb80604
```

```
INFO[0000] libcontainerd: new containerd process, pid: 19832
ERRO[0001] devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/daemon/#daemon-storage-driver-option
INFO[0001] Graph migration to content-addressability took 0.00 seconds
WARN[0001] Your kernel does not support swap memory limit.
INFO[0001] Loading containers: start.
INFO[0001] Firewalld running: false
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address

INFO[0001] Loading containers: done.
INFO[0001] Listening for local connections               addr=/var/lib/docker/swarm/control.sock proto=unix
INFO[0001] Listening for connections                     addr=138.201.138.165:2377 proto=tcp
WARN[0001] ignoring request to join cluster, because raft state already exists
INFO[0001] 5f0069e03eac2b0b became follower at term 2
INFO[0001] newRaft 5f0069e03eac2b0b [peers: [], term: 2, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
PANI[0001] tocommit(341) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
panic: (*logrus.Entry) (0x1dc0660,0xc8203fb340)

goroutine 192 [running]:
panic(0x1dc0660, 0xc8203fb340)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/Sirupsen/logrus.Entry.log(0xc820074180, 0xc82039e090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820a3ccc0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:113 +0x62c
github.com/Sirupsen/logrus.(*Entry).Panic(0xc820335900, 0xc8209083b8, 0x1, 0x1)
	/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc820335900, 0x216ae60, 0x5d, 0xc820b395a0, 0x2, 0x2)
	/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:206 +0x139
github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc820370380, 0x155)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc820c540c0, 0x8, 0x7d4f0a20dabaa028, 0x459060784fac68e5, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
github.com/coreos/etcd/raft.stepFollower(0xc820c540c0, 0x8, 0x7d4f0a20dabaa028, 0x459060784fac68e5, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
github.com/coreos/etcd/raft.(*raft).Step(0xc820c540c0, 0x8, 0x7d4f0a20dabaa028, 0x459060784fac68e5, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
github.com/coreos/etcd/raft.(*node).run(0xc820aaa690, 0xc820c540c0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
created by github.com/coreos/etcd/raft.RestartNode
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
```

**Comment by thaJeztah** [comment]
@guenhter could you also provide some additional information? e.g., was this after a clean restart, a reboot? What platform/distro etc

**Comment by guenhter** [comment]
The situation was the following:

- 3 Nodes within a swarm (A, B, C)
- All three are also managers
- Node C (logs above) ran out of disk
- The docker service on that Node crashed

Before I noticed that the disk was full, I just restarted the daemon.
It crashed again. Than I noticed the full disk and just deleted the whole `/var/lib/docker` folder (not the smartest idea).
I started docker again and tried to add it to the swarm. 

After that it crashed again and that error occurred.

**Comment by aboch** [comment]
I am reopening this issue, because I am hitting it in latest master (to be 1.14) + some changes in libnetwork code which should not be related (I will try to reproduce with a clean image and update this).

In my case I run a 3 mgrs cluster. 
I `docker swarm leave --force` one of them.
Then I have the node join the cluster again and I hit the panic.
Only way to be able to restart the daemon is to wipe out the swarm directory.

I can always reproduce.

```
DEBU[0480] Calling GET /_ping                           
DEBU[0480] Calling POST /v1.26/swarm/join               
DEBU[0480] form data: {"AdvertiseAddr":"","JoinToken":"*****","ListenAddr":"0.0.0.0:2377","RemoteAddrs":["192.168.201.119:2377"]} 
DEBU[0480] retrieved remote CA certificate: /var/lib/docker/swarm/certificates/swarm-root-ca.crt  module=node
DEBU[0480] downloaded CA certificate                     module=node
DEBU[0480] no node credentials found in: /var/lib/docker/swarm/certificates/swarm-node.crt  error="open /var/lib/docker/swarm/certificates/swarm-node.key: no such file or directory" module=node
DEBU[0480] new node credentials generated: /var/lib/docker/swarm/certificates/swarm-node.crt  module="node/tls" node.id=j2k1mj9rgy0pdvk46wmx9qx2k node.role=swarm-manager
DEBU[0480] (*Agent).run                                  module="node/agent"
DEBU[0480] next certificate renewal scheduled            module="node/tls" node.id=j2k1mj9rgy0pdvk46wmx9qx2k node.role=swarm-manager time=2017-01-21 14:10:00.000000089 -0800 PST
INFO[0480] Listening for local connections               addr="/var/run/docker/swarm/control.sock" proto=unix
INFO[0480] Listening for connections                     addr="[::]:2377" proto=tcp
INFO[0480] 8e4e8f39877c45 became follower at term 0     
INFO[0480] newRaft 8e4e8f39877c45 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0] 
INFO[0480] 8e4e8f39877c45 became follower at term 1     
INFO[0480] 8e4e8f39877c45 [term: 1] received a MsgHeartbeat message with higher term from 3a87d1d5ec35797c [term: 39] 
INFO[0480] 8e4e8f39877c45 became follower at term 39    
INFO[0480] raft.node: 8e4e8f39877c45 elected leader 3a87d1d5ec35797c at term 39 
DEBU[0480] 8e4e8f39877c45 [logterm: 0, index: 3083] rejected msgApp [logterm: 39, index: 3083] from 3a87d1d5ec35797c 
DEBU[0480] (*session).start                              module="node/agent"
DEBU[0481] 8e4e8f39877c45 [logterm: 0, index: 3075] rejected msgApp [logterm: 39, index: 3075] from 3a87d1d5ec35797c 
PANI[0481] tocommit(3075) is out of range [lastIndex(135)]. Was the raft log corrupted, truncated, or lost? 
panic: (*logrus.Entry) (0x19317a0,0xc4208646e0)

goroutine 2141 [running]:
panic(0x19317a0, 0xc4208646e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/docker/vendor/github.com/Sirupsen/logrus.Entry.log(0xc42009e140, 0xc420430c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc422015d00, ...)
	/go/src/github.com/docker/docker/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/docker/docker/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc4203c8cd0, 0xc422015e00, 0x1, 0x1)
	/go/src/github.com/docker/docker/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/docker/docker/vendor/github.com/Sirupsen/logrus.(*Entry).Panicf(0xc4203c8cd0, 0x19cea6d, 0x5d, 0xc424604b40, 0x2, 0x2)
	/go/src/github.com/docker/docker/vendor/github.com/Sirupsen/logrus/entry.go:217 +0x101
github.com/docker/docker/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc4229d27e0, 0xc03)
	/go/src/github.com/docker/docker/vendor/github.com/coreos/etcd/raft/log.go:191 +0x166
github.com/docker/docker/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc421db5a40, 0x8, 0x2e5ad15b981d93b1, 0x3a87d1d5ec35797c, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/coreos/etcd/raft/raft.go:916 +0x54
github.com/docker/docker/vendor/github.com/coreos/etcd/raft.stepFollower(0xc421db5a40, 0x8, 0x2e5ad15b981d93b1, 0x3a87d1d5ec35797c, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/coreos/etcd/raft/raft.go:855 +0x1109
github.com/docker/docker/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc421db5a40, 0x8, 0x2e5ad15b981d93b1, 0x3a87d1d5ec35797c, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/coreos/etcd/raft/raft.go:633 +0x6a0
github.com/docker/docker/vendor/github.com/coreos/etcd/raft.(*node).run(0xc4237777a0, 0xc421db5a40)
	/go/src/github.com/docker/docker/vendor/github.com/coreos/etcd/raft/node.go:324 +0x67f
created by github.com/docker/docker/vendor/github.com/coreos/etcd/raft.StartNode
	/go/src/github.com/docker/docker/vendor/github.com/coreos/etcd/raft/node.go:211 +0x6bb
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/swarm/join: EOF
```

**Comment by thaJeztah** [comment]
@aboch could this be related to https://github.com/docker/swarmkit/pull/1758 ? (just based on the `docker swarm leave --force`)

**Comment by aboch** [comment]
No idea, I will let @aaronlehmann take a look at logs once I reproduce.

**Comment by aaronlehmann** [comment]
Is it possible that you ran out of disk space? That's one known cause of this issue.

**Comment by aboch** [comment]
@aaronlehmann No, not in my case, had plenty of disk space, running on my laptop.

**Comment by kinghuang** [comment]
I just encountered this on a Docker 1.12.5 swarm. One of the controller nodes was restarted by operations (not sure if clean or hard restart). The node is a RHEL 7.3 VM.

```
systemd[1]: Starting Docker Application Container Engine...
dockerd[7202]: time="2017-01-02T16:02:29-07:00" level=warning msg="Running experimental build"
dockerd[7202]: time="2017-01-02T16:02:29.983081806-07:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
dockerd[7202]: time="2017-01-02T16:02:30.009739524-07:00" level=info msg="libcontainerd: new containerd process, pid: 7205"
dockerd[7202]: time="2017-01-02T16:02:30.258690283-07:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
dockerd[7202]: time="2017-01-02T16:02:30.295829069-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
dockerd[7202]: time="2017-01-02T16:02:30.296951566-07:00" level=warning msg="mountpoint for pids not found"
dockerd[7202]: time="2017-01-02T16:02:30.298991100-07:00" level=info msg="Loading containers: start."
dockerd[7202]: ..time="2017-01-02T16:02:30.329481679-07:00" level=info msg="Firewalld running: true"
dockerd[7202]: time="2017-01-02T16:02:31.010189125-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
dockerd[7202]: time="2017-01-02T16:02:31.213678456-07:00" level=info msg="Loading containers: done."
dockerd[7202]: time="2017-01-02T16:02:31.589498656-07:00" level=info msg="Listening for connections" addr="[::]:2377" proto=tcp
dockerd[7202]: time="2017-01-02T16:02:31.589621338-07:00" level=info msg="Listening for local connections" addr="/var/lib/docker/swarm/control.sock" proto=unix
dockerd[7202]: time="2017-01-02T16:02:31.760283789-07:00" level=warning msg="ignoring request to join cluster, because raft state already exists"
dockerd[7202]: time="2017-01-02T16:02:31.760446057-07:00" level=info msg="5d921f995e3d7277 became follower at term 292206"
dockerd[7202]: time="2017-01-02T16:02:31.760499672-07:00" level=info msg="newRaft 5d921f995e3d7277 [peers: [9d0d6ce7e6a0efe,19b024e95907e3a3,2f1878422dd2c808,46cc52daa4aeb214,5552ae599bd52dba,5d921f995e3d7277,6e68bfc75868f564], term: 292206, commit: 360837, applied: 360044, lastindex: 360838, lastterm: 292206]"
dockerd[7202]: time="2017-01-02T16:02:33.323913823-07:00" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=10.45.32.22 Adv-addr=10.45.32.22 Remote-addr =10.45.32.24"
dockerd[7202]: time="2017-01-02T16:02:33.323984618-07:00" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=10.45.32.22 Adv-addr=10.45.32.22 Remote-addr =10.45.32.42"
dockerd[7202]: time="2017-01-02T16:02:33.324082428-07:00" level=info msg="Gossip cluster hostname itpocucp01.ucalgary.ca-985ab937b54e"
dockerd[7202]: time="2017-01-02T16:02:33.355004753-07:00" level=info msg="Daemon has completed initialization"
dockerd[7202]: time="2017-01-02T16:02:33.355065028-07:00" level=info msg="Docker daemon" commit=7392c3b graphdriver=devicemapper version=1.12.5
systemd[1]: Started Docker Application Container Engine.
dockerd[7202]: time="2017-01-02T16:02:33.442584493-07:00" level=info msg="API listen on [::]:2375"
dockerd[7202]: time="2017-01-02T16:02:33.455883669-07:00" level=info msg="raft.node: 5d921f995e3d7277 elected leader 2f1878422dd2c808 at term 292206"
dockerd[7202]: time="2017-01-02T16:02:33.475505009-07:00" level=info msg="API listen on /var/run/docker.sock"
dockerd[7202]: time="2017-01-02T16:02:33.475992052-07:00" level=panic msg="tocommit(360842) is out of range [lastIndex(360838)]. Was the raft log corrupted, truncated, or lost?"
dockerd[7202]: panic: (*logrus.Entry) (0x1d60b60,0xc820bf85c0)
dockerd[7202]: goroutine 111 [running]:
dockerd[7202]: panic(0x1d60b60, 0xc820bf85c0)
dockerd[7202]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
dockerd[7202]: github.com/Sirupsen/logrus.Entry.log(0xc82000e200, 0xc82036a120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820043730, ...)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/Sirupsen/logrus/entry.go:113 +0x62c
dockerd[7202]: github.com/Sirupsen/logrus.(*Entry).Panic(0xc8203038c0, 0xc8211303b8, 0x1, 0x1)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
dockerd[7202]: github.com/Sirupsen/logrus.(*Entry).Panicf(0xc8203038c0, 0x2111d00, 0x5d, 0xc820a7f460, 0x2, 0x2)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/Sirupsen/logrus/entry.go:206 +0x139
dockerd[7202]: github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8203a6770, 0x5818a)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
dockerd[7202]: github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc8209300c0, 0x8, 0x5d921f995e3d7277, 0x2f1878422dd2c808, 0x4756e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
dockerd[7202]: github.com/coreos/etcd/raft.stepFollower(0xc8209300c0, 0x8, 0x5d921f995e3d7277, 0x2f1878422dd2c808, 0x4756e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
dockerd[7202]: github.com/coreos/etcd/raft.(*raft).Step(0xc8209300c0, 0x8, 0x5d921f995e3d7277, 0x2f1878422dd2c808, 0x4756e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
dockerd[7202]: github.com/coreos/etcd/raft.(*node).run(0xc820a48780, 0xc8209300c0)
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
dockerd[7202]: created by github.com/coreos/etcd/raft.RestartNode
dockerd[7202]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: Unit docker.service entered failed state.
systemd[1]: docker.service failed.
```

**Comment by aaronlehmann** [comment]
Cross-post from #26487, which is about the same panic:

There has been some recent progress on understanding this panic. https://github.com/docker/swarmkit/pull/1815#issuecomment-267703760 explains three cases which are thought to cause it. That PR fixes one of the cases, and https://github.com/docker/swarmkit/pull/1820 fixes another. The third case is downgrading from 1.13 to an earlier version, and that will be supported through a reverse migration tool.
