### ISSUE TITLE
Cannot create a Kafka service and publish ports due to rout mesh network

### ISSUE THREAD

**Issue by Richard-Mathie** [moby/moby#26594]
**Description**

Using docker 1.12.1 or the latest master 1.13.0.

I want to set up a kafka service, and be able to attache to it from location external to the docker swarm cluster. However the rout mesh networking gets in the way of communicating to the nodes. In kafka the broker state is stored in zookeeper and connections are bootstraped from that information. So I might have 2 nodes, and 2 instances of kafka (one on each node, replication mode global) so zookeeper will store
1. Broker 1001  192.168.99.100
2. Broker 1002  192.168.99.101

When I try and connect I get all kinds of errors as kafka is trying to talk to broker 1001 and getting 1002 doe to the rout mesh network. Ideally I would like to use `--endpoint-mode dnsrr` however that is disabled for services with published ports. This might be related to https://github.com/docker/docker/issues/25016. Basically I think i should be able to enable `--endpoint-mode dnsrr` when the service is using a global replication factor.

**Steps to reproduce the issue:**
1. set up nodes

```
docker run --rm ricmathie/boot2docker_1_13_0_dev > boot2docker.iso
docker_image_url="./boot2docker.iso"
virtualbox_options="-d virtualbox  --virtualbox-boot2docker-url=$docker_image_url"
docker-machine create $virtualbox_options master
docker-machine create $virtualbox_options slave
# get config
master_config=$(docker-machine config master  | tr -d '")
master_ip=$(docker-machine ip master)
slave_config=$(docker-machine config slave | tr -d '")
# init swarm
docker $master_config swarm init --advertise-addr $master_ip:2377
worker_token=$(docker $master_config swarm join-token worker -q)
docker $slave_config swarm join --token $worker_token  $master_ip:2377
eval $(docker-machine env master)
# create network
docker network create -d overlay --attachable mynet
```
1. run a flask app or similar on the local host so that we can discover the host ips of the docker engines of the host machines which the containers are running on (similar to aws metadata service...)

```
from flask import Flask
from flask import request

app = Flask(__name__)

@app.route('/')
def hello_world():
    return request.remote_addr
```
1. Set up services

```
eval $(docker-machine master)
docker service create --name zookeeper  --network mynet  -p 2181:2181  wurstmeister/zookeeper
docker service create --name kafka \
  --mode global \
  --network mynet \
  -e 'KAFKA_PORT=9092' \
  -e 'KAFKA_ADVERTISED_PORT=9092'  \
  -e 'KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092' \
  -e 'KAFKA_ZOOKEEPER_CONNECT=tasks.zookeeper:2181' \
  -e "HOSTNAME_COMMAND=curl 192.168.99.1:5000" \
  wurstmeister/kafka
```
1. try to connect to the kafka service

```
eval $(docker-machine env -u)
```

a consumer

```
docker run --rm -it wurstmeister/kafka bash -c "\$KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper 192.168.99.100:2181 --topic test --from-beginning"
```

a producer in another shell

```
docker run --rm -it wurstmeister/kafka bash -c "\$KAFKA_HOME/bin/kafka-console-producer.sh --broker-list 192.168.99.100:9092 --topic test"
```

**Describe the results you received:**

Lots of errors everywhere

producer >> 

```
a[2016-09-15 10:53:08,225] ERROR Error when sending message to topic test with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
[2016-09-15 10:54:08,227] ERROR Error when sending message to topic test with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

**Describe the results you expected:**

messages to pass from the producer to the consumer

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   3ae023c
 Built:        Wed Sep 14 04:52:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   3ae023c
 Built:        Wed Sep 14 04:52:02 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

``````
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.59 GiB
Name: zbook
ID: ZIUX:AEW5:6FRW:K2SW:24X2:QHIA:BVCS:QILL:VNCN:ZLHD:ZBGW:ROXW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ricmathie
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```
``````

**Comment by Richard-Mathie** [comment]
additionally truing to do this from within the overlay network (on a cluster machine) gives this error

```
eval $(docker-machine env master)
$ docker run --rm -it --net mynet wurstmeister/kafka bash -c "\$KAFKA_HOME/bin/kafka-console-producer.sh --broker-list tasks.kafka:9092 --topic test"
t
[2016-09-15 10:57:34,770] WARN Error while fetching metadata with correlation id 0 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-15 10:57:35,023] WARN Error while fetching metadata with correlation id 1 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-15 10:57:35,167] WARN Error while fetching metadata with correlation id 2 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-15 10:57:35,336] WARN Error while fetching metadata with correlation id 3 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-15 10:57:35,475] WARN Error while fetching metadata with correlation id 4 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-15 10:57:35,590] WARN Error while fetching metadata with correlation id 5 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-15 10:57:35,728] WARN Error while fetching metadata with correlation id 6 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

```

consumer
```
$ docker run --rm -it --net mynet  wurstmeister/kafka bash -c "\$KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper 192.168.99.100:2181 --topic test --from-beginning"
[2016-09-15 10:59:02,370] WARN Fetching topic metadata with correlation id 408 for topics [Set(test)] from broker [BrokerEndPoint(1001,192.168.99.101,9092)] failed (kafka.client.ClientUtils$)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:80)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:79)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:124)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:59)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:94)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
[2016-09-15 10:59:02,372] WARN Fetching topic metadata with correlation id 408 for topics [Set(test)] from broker [BrokerEndPoint(1002,192.168.99.100,9092)] failed (kafka.client.ClientUtils$)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:80)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:79)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:124)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:59)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:94)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
[2016-09-15 10:59:02,373] WARN [console-consumer-72912_438eea72c322-1473936997422-42b3bfaf-leader-finder-thread], Failed to find leader for Set([test,0]) (kafka.consumer.ConsumerFetcherManager$LeaderFinderThread)
kafka.common.KafkaException: fetching topic metadata for topics [Set(test)] from broker [ArrayBuffer(BrokerEndPoint(1001,192.168.99.101,9092), BrokerEndPoint(1002,192.168.99.100,9092))] failed
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:73)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:94)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:80)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:79)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:124)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:59)
	... 3 more
[2016-09-15 10:59:02,578] WARN Fetching topic metadata with correlation id 409 for topics [Set(test)] from broker [BrokerEndPoint(1002,192.168.99.100,9092)] failed (kafka.client.ClientUtils$)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:80)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:79)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:124)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:59)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:94)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
[2016-09-15 10:59:02,580] WARN Fetching topic metadata with correlation id 409 for topics [Set(test)] from broker [BrokerEndPoint(1001,192.168.99.101,9092)] failed (kafka.client.ClientUtils$)
```


having kafka purely internal to the mynet network works ok, but I cant get external access to it easily. I am considering setting up a vpn into mynet.

**Comment by aaronlehmann** [comment]
ping @stevvooe @dperny

**Comment by mostolog** [comment]
Hi.

I don't know if its close-related enough to be commented here, but here I go.
> docker service zookeeper create --name my_zoo...
> docker service kafka create --name my_kafka...

logstash.conf
> bootstrap_servers => [ "my_kafka:9092" ]

on logstash start, kafka complains with:
>11:41:02.175 [[main]<kafka] WARN  org.apache.kafka.clients.ClientUtils - Removing server from bootstrap.servers as DNS resolution failed: my_kafka:9092

Seems this could be somehow fixed with advertised.listeners, but haven't figured out how yet.
At the same time, reason why I'm asking here, host output is quite intriguing for me:
> $host my_kafka
>
> my_kafka has address 10.0.0.7
> Host my_kafka not found: 3(NXDOMAIN)

**Comment by stevvooe** [comment]
I'd recommend either trying the DNSRR publish mode or host port networking. Another option is to run a service per identity.

Admittedly, the routing mesh isn't great for applications with smart clients or strong service identity.

Let me know if you have trouble hunting down those options.

**Comment by dperny** [comment]
This issue should be solved with host port networking mode, and I think it can probably be closed @thaJeztah

**Comment by mostolog** [comment]
FYI: I was able to create a kafka cluster with an init script and all nodes answer properly (and listen on same ports) as a service.

The main problem was "grouping the ensemble", as each node should know each other node address/port.
IMHO it would be easier to have a unicast system, but that's a kafka feature.

```
Something like:

sed -i "s|^#broker.id=0|broker.id="$id"|" /kafka/config/kafka.properties
sed -i "s|^#listeners=PLAINTEXT://localhost:9092|listeners=PLAINTEXT://"$ip":9092|" /kafka/config/kafka.properties
sed -i "s|^#zookeeper.connect=localhost:2181|zookeeper.connect=myzookeeper:2181|" /kafka/config/kafka.properties
```

**Comment by Richard-Mathie** [comment]
This is solved with the latest updates to kafka and using swarm overlay networks see: https://github.com/wurstmeister/kafka-docker#listener-configuration

> Kafka added `listener.security.protocol.map` to their config. This allows you to set different listener addresses and protocols depending on whether you are inside or outside the cluster, and stops Kafka getting confused by any load balancing or ip translation which occurs in docker. Wurstmeister has a working docker image and example compose file here. I tried this a while back with a few docker machine nodes set up as a swarm and it seems to work.

This issue should be closed
