### ISSUE TITLE
docker 1.11.2 hung on docker ps

### ISSUE THREAD

**Issue by devnev** [moby/moby#27827]
**Description**

in a gce cluster, on a coreos machine running as kubernetes master with ~23 hours uptime, docker got stuck: `docker ps` and `docker stop` would hang. existing containers continued running. system was not under load and cpu usage was minimal.

**Steps to reproduce the issue:**

unclear how to trigger the condition.

**Describe the results you received:**

`docker ps` did not terminate even after waiting even a few minutes. stopping the docker systemd unit did not complete even after waiting a few minutes.

In the end, we killed the docker daemon with SIGABRT to get the goroutine dump. After starting the docker daemon again, kubernetes operations resumed as normal.

The goroutine dump had many goroutines stuck on a semaphore at `0xc820354f54`. Most of these were `Lock` calls from `(*Daemon).reducePsContainer`. The only exceptions are listed below:

```
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: goroutine 82255 [semacquire, 5 minutes]:
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: sync.runtime_Semacquire(0xc820354f54)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/runtime/sema.go:47 +0x26
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: sync.(*Mutex).Lock(0xc820354f50)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/sync/mutex.go:83 +0x1c4
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/daemon.(*Daemon).killWithSignal(0xc820414000, 0xc822378700, 0xf, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/kill.go:59 +0x1d8
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/daemon.(*Daemon).ContainerKill(0xc820414000, 0xc822f64197, 0x40, 0xf, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/kill.go:49 +0x291
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersKill(0xc8207a04b0, 0x7f5cb51e4ff0, 0xc8229b41e0, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000, 0xc8229b4090, 0
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:202 +0x20a
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersKill)-fm(0x7f5cb51e4ff0, 0xc8229b41e0, 0x7f5cb5251348,
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:43 +0x74
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7f5cb51e4ff0, 0xc8229b41e0, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000, 0xc8229b4090, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7f5cb51e4ff0, 0xc8229b4150, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000, 0xc8229b4090, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6a9
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5cb5251348, 0xc822d880d0, 0xc822746000)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: net/http.HandlerFunc.ServeHTTP(0xc8207d7680, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:1618 +0x3a
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc82079bcc0, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820926e10, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: net/http.serverHandler.ServeHTTP(0xc82030d180, 0x7f5cb5251348, 0xc822d880d0, 0xc822746000)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:2081 +0x19e
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: net/http.(*conn).serve(0xc822f64100)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:1472 +0xf2e
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: created by net/http.(*Server).Serve
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:2137 +0x44e
```

```
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: goroutine 82274 [semacquire, 5 minutes]:
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: sync.runtime_Semacquire(0xc820354f54)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/runtime/sema.go:47 +0x26
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: sync.(*Mutex).Lock(0xc820354f50)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/sync/mutex.go:83 +0x1c4
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/container.(*State).SetRemovalInProgress(0xc820354f50, 0xc82125aa00)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/container/state.go:262 +0x35
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820414000, 0xc82125aac9, 0xc, 0xc822d9ecb0, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/delete.go:28 +0xb3
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc8207a04b0, 0x7f5cb51e4ff0, 0xc82125ad50, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0, 0xc82125ab70, 0x0
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:386 +0x1de
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5cb51e4ff0, 0xc82125ad50, 0x7f5cb5251348, 0
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:61 +0x74
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7f5cb51e4ff0, 0xc82125ad50, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0, 0xc82125ab70, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7f5cb51e4ff0, 0xc82125ac60, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0, 0xc82125ab70, 0x0, 0x0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6a9
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: net/http.HandlerFunc.ServeHTTP(0xc82085d420, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:1618 +0x3a
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc82079bcc0, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820926e10, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: net/http.serverHandler.ServeHTTP(0xc82030d180, 0x7f5cb5251348, 0xc820cc8ea0, 0xc822747ea0)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:2081 +0x19e
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: net/http.(*conn).serve(0xc82309e500)
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:1472 +0xf2e
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]: created by net/http.(*Server).Serve
Oct 27 15:20:23 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:2137 +0x44e
```

```
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: goroutine 82238 [semacquire, 19 minutes]:
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: sync.runtime_Semacquire(0xc820354f54)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/runtime/sema.go:47 +0x26
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: sync.(*Mutex).Lock(0xc820354f50)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/sync/mutex.go:83 +0x1c4
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/container.(*State).IsRunning(0xc820354f50, 0xc821841817)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/container/state.go:159 +0x28
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc820414000, 0xc821841817, 0xc, 0x2d, 0x0, 0x0)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/stop.go:24 +0xa8
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop(0xc8207a04b0, 0x7f5cb51e4ff0, 0xc821ed0b10, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40, 0xc821ed09c0, 0
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:174 +0x18b
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm(0x7f5cb51e4ff0, 0xc821ed0b10, 0x7f5cb5251348,
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:48 +0x74
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7f5cb51e4ff0, 0xc821ed0b10, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40, 0xc821ed09c0, 0x0, 0x0)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7f5cb51e4ff0, 0xc821ed0a80, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40, 0xc821ed09c0, 0x0, 0x0)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6a9
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5cb5251348, 0xc82073c680, 0xc8234fda40)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: net/http.HandlerFunc.ServeHTTP(0xc8207f93e0, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:1618 +0x3a
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc82079bcc0, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820926e10, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: net/http.serverHandler.ServeHTTP(0xc82030d180, 0x7f5cb5251348, 0xc82073c680, 0xc8234fda40)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:2081 +0x19e
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: net/http.(*conn).serve(0xc8234bec80)
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:1472 +0xf2e
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]: created by net/http.(*Server).Serve
Oct 27 15:20:24 h-stg-core-1 dockerd[1748]:         /usr/lib/go1.6/src/net/http/server.go:2137 +0x44e
```

**Describe the results you expected:**
Expected `docker ps` to list containers as usual after at most a few seconds.

**Additional information you deem important (e.g. issue happens only occasionally):**
Only seen machines deadlock on docker twice so far, and didn't dig in the first time. Both happened fairly recently (last few days).

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 10
 Paused: 0
 Stopped: 11
Images: 21
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.7.3-coreos-r2
Operating System: CoreOS 1185.2.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.309 GiB
Name: h-stg-core-1
ID: ZIKY:SLQ7:KFNM:BQPE:66GP:3HWY:GDXF:SFE5:H2MI:7ZY2:36XP:M4YM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a GCE instance.
contents of `/etc/os-release`:

```
NAME=CoreOS
ID=coreos
VERSION=1185.2.0
VERSION_ID=1185.2.0
BUILD_ID=2016-10-20-2326
PRETTY_NAME="CoreOS 1185.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by cpuguy83** [comment]
Can you provide the full stack trace?

**Comment by devnev** [comment]
I still have the full dump from the logs. The stack trace is *very* long (lots of `docker ps` or equivalent from kubernetes). Are you looking for anything? Should I try and strip it a bit?

**Comment by cpuguy83** [comment]
Need to be able to see what might be holding the container lock.

**Comment by thaJeztah** [comment]
@devnev GitHub now allows attachments to comments, which helps for longer logs

**Comment by devnev** [comment]
output from docker daemon via journalctl:
[docker-log.txt](https://github.com/docker/docker/files/558468/docker-log.txt)

**Comment by SirAlvarex** [comment]
We are seeing a similar issue with Docker PS hanging on CoreOS machines.  After awhile docker ps and docker stop just hang indefinitely.

GIST of stacktrace: https://gist.github.com/SirAlvarex/02412e86ce833a4ea12d000471aecdad

It seems there are an extremely large amount of goroutines on app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/vishvananda/netlink/link_linux.go:898

If this belongs in it's own issue, or if there is another issue I should attach it to let me know.

**/etc/os-release**:
```
NAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**docker info**:
```
Containers: 5481
 Running: 7
 Paused: 0
 Stopped: 5474
Images: 17
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.3-coreos-r2
Operating System: CoreOS 1185.3.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 110.2 GiB
Name: stage-east-1-agents-4-1
ID: V6CL:KDMY:JARU:2KYJ:YPKW:TGNQ:L5AX:DCHZ:NFR5:EKHY:4Q2K:6WAS
Docker Root Dir: /mnt/resource/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**docker version**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64
```

**Comment by jsravn** [comment]
I'm also experiencing this. I'm using `docker ps` as a health check, it times out after a minute, then tries to do `docker stop` which also times out. Eventually it seems to recover on its own.

**Comment by thaJeztah** [comment]
> I'm using docker ps as a health check

Just out of interest; could you add some more information about how you're using `docker ps` for that?  Would restart policies (`--restart`), or listening to `docker events` be a better alternative?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
