### ISSUE TITLE
Service Discovery doesn't work on Windows 10 if dockerd is stored at c:\program files\docker\dockerd.exe

### ISSUE THREAD

**Issue by PatrickLang** [moby/moby#28452]
**Description**
Service discovery is not working between containers on Windows 10 from Docker Compose. This doesn't reproduce on the Azure image "Windows Server 2016 with Containers"

**Steps to reproduce the issue:**
1. Set up a Windows 10 machine using Docker v1.13-dev per the [Quick Start Guide](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)
2. Clone @friism's repo for MusicStore, and deploy the instructions in the [MultiContainerApp](https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md) lab
 - docker-compose -f .\docker-compose.windows.yml build
 - docker-compose -f .\docker-compose.windows.yml up

**Describe the results you received:**
The web container failed DNS lookup for the db container:

```none
PS C:\demo\MusicStore> docker-compose -f .\docker-compose.windows.yml up
Starting musicstore_db_1
Starting musicstore_web_1
Attaching to musicstore_db_1, musicstore_web_1
db_1   | VERBOSE: Starting SQL Server
db_1   | VERBOSE: Changing SA login credentials
db_1   | VERBOSE: Started SQL Server.
web_1  | Project MusicStore.Standalone (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
web_1  |
web_1  | Unhandled Exception: System.AggregateException: One or more errors occurred. (A network-related or instance-specific error occurred while establishing a conne
ction to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connect
ions. (provider: TCP Provider, error: 0 - No such host is known.)) ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while
 establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to
 allow remote connections. (provider: TCP Provider, error: 0 - No such host is known.) ---> System.ComponentModel.Win32Exception: No such host is known
web_1  |    --- End of inner exception stack trace ---
web_1  |    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Bool
ean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
web_1  |    at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbCo
nnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
web_1  |    at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbCon
nectionPoolKey poolKey, DbConnectionOptions userOptions)
web_1  |    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
web_1  |    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnecti
on)
web_1  |    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean
 onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
web_1  |    at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__31.MoveNext()
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass13_0.<<ExistsAsync>b__0>d.MoveNext()
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass13_0.<<ExistsAsync>b__0>d.MoveNext()
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__32.MoveNext()
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
web_1  |    at MusicStore.Models.SampleData.<InitializeMusicStoreDatabaseAsync>d__3.MoveNext()
web_1  |    --- End of inner exception stack trace ---
web_1  |    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
web_1  |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
web_1  |    at System.Threading.Tasks.Task.Wait()
web_1  |    at MusicStore.Startup.Configure(IApplicationBuilder app)
web_1  |    at MusicStore.Startup.ConfigureProduction(IApplicationBuilder app, ILoggerFactory loggerFactory)
web_1  | --- End of stack trace from previous location where exception was thrown ---
web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1  |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
web_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
web_1  |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
web_1  |    at MusicStore.Standalone.Program.Main(String[] args)
```

Also, the dockerd logs don't show any DNS queries at all.

**Describe the results you expected:**
- Both containers should start successfully
- dockerd should show a DNS lookup

**Additional information you deem important (e.g. issue happens only occasionally):**

If you move dockerd.exe to another location and run it from there, the issue doesn't reproduce.

**Output of `docker version`:**

```
PS C:\WINDOWS\system32> docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   c5ceb0f
 Built:        Sat Nov  5 03:24:43 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   c5ceb0f
 Built:        Sat Nov  5 03:24:43 2016
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 75
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88 GiB
Name: roaster
ID: VOST:SYNK:ZVS2:Q7X5:IAJL:XAAA:MMCA:HSS3:2ME5:S6DO:RZXW:IRGJ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 Anniversary Edition (Pro)
WindowsBuildLabEx : 14393.447.amd64fre.rs1_release_inmarket.161102-0100

**Comment by friism** [comment]
It'd be nice to see if you can repro with smaller app. When I debugged the DNS issue that we discussed offline, I used this:

Dockerfile

```
FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord
# RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ScreenDefaultServers -Value 0 -Type DWord
# RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ScreenUnreachableServers -Value 0 -Type DWord

# RUN $log = New-Object System.Diagnostics.Eventing.Reader.EventLogConfiguration 'Microsoft-Windows-DNS-Client/Operational' ; \
# 	$log.IsEnabled=$true ; \
# 	$log.SaveChanges() ;

# CMD Get-WinEvent -LogName 'Microsoft-Windows-DNS-Client/Operational' | where { $_.ID -gt 1010 }
```

docker-compose.yml

```
version: '2'
services:
  db:
    image: microsoft/windowsservercore
    command: powershell /c sleep 3600

  web:
    # image: microsoft/windowsservercore
    build: .
    command: ping db
    depends_on:
      - "db"

networks:
  default:
    external:
      name: nat
```

**Comment by johnstep** [comment]
I tried with the smaller app above. It did fail the first time, but succeeded on retrying. It also fails sometimes with dockerd.exe running from a different location. There might be a synchronization issue where `docker-compose` is starting `web` before `db` is ready. I am looking into it.

**Comment by PatrickLang** [comment]
Any updates on this? Anything I can do to help?

**Comment by StefanScherer** [comment]
Using Docker 4 Windows Beta 31 it works:

```yaml
version: '2.1'
services:
  db:
    image: microsoft/nanoserver
    command: powershell /c sleep 3600

  web:
    image: microsoft/nanoserver
    command: ping db
    depends_on:
      - "db"

networks:
  default:
    external:
      name: nat
```

```
PS C:\issue28452> docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             windows/amd64
 Experimental:        false
PS C:\issue28452> docker-compose up
Pulling db (microsoft/nanoserver:latest)...
5496abde368a: Pull complete
482ab31872a2: Pull complete
Digest: sha256:31b905198137b957b2218e7f6f85d5e478de9f53e1da06b02a6637c1c24549c8
Status: Downloaded newer image for microsoft/nanoserver:latest
Recreating issue28452_db_1
Creating issue28452_web_1
Attaching to issue28452_db_1, issue28452_web_1
web_1  |
web_1  | Pinging db [172.20.254.159] with 32 bytes of data:
web_1  | Reply from 172.20.254.159: bytes=32 time=9ms TTL=128
web_1  | Reply from 172.20.254.159: bytes=32 time=1ms TTL=128
web_1  | Reply from 172.20.254.159: bytes=32 time=1ms TTL=128
web_1  | Reply from 172.20.254.159: bytes=32 time=1ms TTL=128
web_1  |
web_1  | Ping statistics for 172.20.254.159:
web_1  |     Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
web_1  | Approximate round trip times in milli-seconds:
web_1  |     Minimum = 1ms, Maximum = 9ms, Average = 3ms
issue28452_web_1 exited with code 0
```

**Comment by mdubbs** [comment]
Using Docker 4 Windows Beta 31 fails on Windows 10, I have been trying to figure this out for a while as well.

version: '2.1'
services:
  db:
    image: microsoft/nanoserver
    command: powershell /c sleep 3600

  web:
    image: microsoft/nanoserver
    command: ping db
    depends_on:
      - "db"

networks:
  default:
    external:
      name: nat

---

Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             windows/amd64
 Experimental:        false

--
PS C:\Dev\Docker\sdt> docker-compose up
Creating sdt_db_1
Creating sdt_web_1
Attaching to sdt_db_1, sdt_web_1
web_1  | Ping request could not find host db. Please check the name and try again.
sdt_web_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping sdt_db_1 ... done

**Comment by johnstep** [comment]
@mdubbs I will try to reproduce it again, with Docker for Windows.

**Comment by mdubbs** [comment]
@johnstep Cool, it's entirely possible that there is something else causing it to fail on my work laptop, I will try and reproduce on my personal desktop as well.

**Comment by johnstep** [comment]
@mdubbs That would be great; I have been unable to reproduce it so far.

**Comment by mdubbs** [comment]
@johnstep It works on my personal desktop so it's definitely something with my work laptop, probably a firewall issue. Thanks for taking another look!

**Comment by johnstep** [comment]
@mdubbs Okay, thanks for the update! If you have a chance to experiment on your work laptop, please let me know if you find a solution. It might be helpful to understand.

**Comment by mdubbs** [comment]
@johnstep Will do!

**Comment by rjarl** [comment]
I have the same issue as @PatrickLang
Did anyone finds how to fix this?

The example provided by @StefanScherer works well for me, but that doesn't fix the main issue.

Cheers

**Comment by olljanat** [comment]
Solution is create group policy which contains settings like these:
1. Computer Configuration -> Windows Settings -> Security Settings -> Network List Manager Policies -> Unidentified Networks
	Location Type: Public
	User permissions: User can change location

2. Disabling firewall from Private zone

When these are applied you can use this PowerShell command to change Docker interface to private zone:
```powershell
Set-NetConnectionProfile -InterfaceAlias "vEthernet (HNS Internal NIC)" -NetworkCategory "Private"
```

**Comment by PatrickLang** [comment]
I haven't had this problem using Docker for Windows on Windows 10 recently, so closing as stale.
