### ISSUE TITLE
[1.13-rc4] docker stats --format panic

### ISSUE THREAD

**Issue by djeeg** [moby/moby#29969]
Hi

**Description**

One a single node swarm
Run this command:
`sudo docker stats --format="table {{.Container}}\t{{.Name}}\t{{.CPUPerc}}\t{{.MemPerc}}\t{{.MemUsage}}"`

Sometimes it works
Sometimes I get a panic

 ```
    panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0xb1fce0, 0xc420010120)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
text/template.errRecover(0xc42020d3f0)
        /usr/local/go/src/text/template/exec.go:140 +0x2ad
panic(0xb1fce0, 0xc420010120)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/docker/docker/cli/command/formatter.(*containerStatsContext).Name(0xc42009b1e0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/command/formatter/stats.go:148 +0x86
reflect.Value.call(0xb99020, 0xc42009b1e0, 0x2213, 0xbe1f72, 0x4, 0x11ba8f8, 0x0, 0x0, 0x4d7643, 0x1196860, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xb99020, 0xc42009b1e0, 0x2213, 0x11ba8f8, 0x0, 0x0, 0xc42014dbf8, 0xb, 0xb)
        /usr/local/go/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0xb99020, 0xc42009b1e0, 0x2213, 0x1176ea0, 0xc4203b1200, 0xc4203d5b12, ...)
        /usr/local/go/src/text/template/exec.go:658 +0x530
text/template.(*state).evalField(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0xc4203d5b12, 0x4, 0x1176ea0, 0xc4203b1200, 0xc420144be0, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:549 +0xdb6
text/template.(*state).evalFieldChain(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0xb99020, 0xc42009b1e0, 0x16, 0x1176ea0, 0xc4203b1200, 0xc420144bd0, ...)
        /usr/local/go/src/text/template/exec.go:520 +0x22f
text/template.(*state).evalFieldNode(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0xc4203b1200, 0xc420144be0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/text/template/exec.go:484 +0x114
text/template.(*state).evalCommand(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0xc4203b11d0, 0x0, 0x0, 0x0, 0xc42020d1c0, 0x525b3f, ...)
        /usr/local/go/src/text/template/exec.go:422 +0x866
text/template.(*state).evalPipeline(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0xc4201cf3b0, 0x0, 0x0, 0x98)
        /usr/local/go/src/text/template/exec.go:400 +0xee
text/template.(*state).walk(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0x1176c60, 0xc4203b1230)
        /usr/local/go/src/text/template/exec.go:226 +0x423
text/template.(*state).walk(0xc42020d370, 0xb99020, 0xc42009b1e0, 0x16, 0x1176fc0, 0xc4203b10e0)
        /usr/local/go/src/text/template/exec.go:234 +0x13d
text/template.(*Template).execute(0xc4203d5b40, 0x116bae0, 0xc4203d6700, 0xb99020, 0xc42009b1e0, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:189 +0x204
text/template.(*Template).Execute(0xc4203d5b40, 0x116bae0, 0xc4203d6700, 0xb99020, 0xc42009b1e0, 0x7f44bb856000, 0x0)
        /usr/local/go/src/text/template/exec.go:175 +0x53
github.com/docker/docker/cli/command/formatter.(*Context).contextFormat(0xc4201cf180, 0xc4203d5b40, 0x1171860, 0xc42009b1e0, 0x1, 0xc42009b1e0)
        /go/src/github.com/docker/docker/cli/command/formatter/formatter.go:91 +0x75
github.com/docker/docker/cli/command/formatter.(*Context).Write.func1(0x1171860, 0xc42009b1e0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/command/formatter/formatter.go:115 +0x47
github.com/docker/docker/cli/command/formatter.ContainerStatsWrite.func1(0xc4201a58e0, 0xc4201a58e0, 0x0)
        /go/src/github.com/docker/docker/cli/command/formatter/stats.go:127 +0x143
github.com/docker/docker/cli/command/formatter.(*Context).Write(0xc4201cf180, 0x1171860, 0xc420393ef0, 0xc4201a5820, 0x7e070d, 0xc4202bfd90)
        /go/src/github.com/docker/docker/cli/command/formatter/formatter.go:117 +0x17d
github.com/docker/docker/cli/command/formatter.ContainerStatsWrite(0x116c120, 0xc4203071d0, 0x7ffe03753e17, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/cli/command/formatter/stats.go:133 +0x120
github.com/docker/docker/cli/command/container.runStats(0xc4201bf440, 0xc4203b0060, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/command/container/stats.go:217 +0xbac
github.com/docker/docker/cli/command/container.NewStatsCommand.func1(0xc4203ae6c0, 0xc4203a2af0, 0x0, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/command/container/stats.go:38 +0x6a
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203ae6c0, 0xc42000c110, 0x1, 0x1, 0xc4203ae6c0, 0xc42000c110)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x26d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42007f8c0, 0xc42007fd40, 0xc42032aeb0, 0xc420024438)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x377
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42007f8c0, 0xc42007f8c0, 0x116d9e0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:104 +0xcb

```

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 54
 Running: 22
 Paused: 0
 Stopped: 32
Images: 87
Server Version: 1.13.0-rc4
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 333
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: txp90wco6y9fhkz242tp790x2
 Is Manager: true
 ClusterID: bqbzj0dvlf3tn8mcggbp34blr
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.137.146
 Manager Addresses:
  192.168.137.146:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.39-boot2docker
Operating System: Boot2Docker 1.13.0-rc4 (TCL 7.2); HEAD : 5567e9b - Mon Dec 19 16:12:00 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.711 GiB
Name: dockernode1
ID: U5A2:MV7M:6LW7:VWAF:FQJQ:DZAZ:GPYH:4OEX:R6LX:WO4F:X3PT:LSNG
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 694
 Goroutines: 1246
 System Time: 2017-01-07T15:22:36.019045657Z
 EventsListeners: 22
Registry: https://index.docker.io/v1/
Labels:
 provider=hyperv
Experimental: false
Insecure Registries:
 192.168.137.128:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by justincormack** [comment]
Can you check on 1.13.0-rc5?

**Comment by vdemeester** [comment]
I think this should be fixed by https://github.com/docker/docker/pull/29702 😅

**Comment by ripcurld0** [comment]
@thaJeztah this ticket can be closed, I believe.

**Comment by thaJeztah** [comment]
Thanks! Yes, I'll close :)
