### ISSUE TITLE
unstable overlay network in swarm mode

### ISSUE THREAD

**Issue by thinkhard-j-park** [moby/moby#31048]
**Description**

**Steps to reproduce the issue:**
1. create overlay network from swarm manager in swarm mode
2. start zookeeper ensembles(3 nodes) with overlay network. 
e.g.  
docker service create  --name zoo01 \
                       --hostname zoo01 \
                       --env ZOO_MY_ID=1 \
                       --env ZOO_SERVERS="$SERVERS" \
                       --network cluster-network \
                       --replicas 1 \
                       localhost:5000/zookeeper

3.  zookeeper are not able to resolve hostname many times.
e.g.
....
2017-02-15 15:37:44,609 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumPeer$QuorumServer@155] - Failed to resolve address: zoo03
java.net.UnknownHostException: zoo03: Name does not resolve
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:148)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:407)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
	at java.lang.Thread.run(Thread.java:745)
....

**Describe the results you received:**
I have encountered similar issues  when I trying to run zookeeper, hadoop nodes in swarm mode.
It looks overlay network is not stable.

**Describe the results you expected:**
Stable overlay network

**Additional information you deem important (e.g. issue happens only occasionally):**
Frequently it occurred. I have investigated reasons. Many of them is related to unreachable hosts.

**Output of `docker version`:**
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 43
 Running: 8
 Paused: 0
 Stopped: 35
Images: 14
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 181
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: mvimcgosd3ajnul07i7s23puw
 Is Manager: false
 Node Address: 192.168.0.29
 Manager Addresses:
  192.168.0.27:2377
  192.168.0.32:2377
  192.168.0.33:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: worker01
ID: 3BUL:LI3A:ZTCA:RKJE:VGDN:FNVG:5ROB:ZPFV:UYIN:W5AU:HMLK:VOA2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have used vmware vshpere to build ubuntu docker host(16.04)

**Comment by thaJeztah** [comment]
Could you tell if;

- the `--advertise-addr` option was used when initialising the swarm (`docker swarm init`)?
- are you using the `--encrypted` option when creating the overlay network?
- how / where are the nodes deployed? bare metal, local VM's, in the cloud?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
