### ISSUE TITLE
Docker version 17.03.1-ce SWARM Cluster Routing Mess over EC2 AWS not working

### ISSUE THREAD

**Issue by fkoner** [moby/moby#32426]
**Docker SWARM Routing Mess over AWS not working**

**Steps to reproduce the issue:**
1. Two EC2 Instance in AWS both with docker
2. Node Manager: 
```
docker swarm init --advertise-addr 10.10.70.219 --listen-addr 10.10.70.219:2377
```
```
Swarm initialized: current node (xfchgy6pqdsnwo2fy0pu2qncq) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-1uzey7j66fkah98xo9t2nbz7ynvtk9x98pex6nzrz9sgjkl3vq-d20nlo7s8s2yeoqs9tpf3uknh \
    10.10.70.219:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
```
3. Node Worker: 
```
docker swarm join  --token SWMTKN-1-1uzey7j66fkah98xo9t2nbz7ynvtk9x98pex6nzrz9sgjkl3vq-d20nlo7s8s2yeoqs9tpf3uknh 10.10.70.219:2377 
This node joined a swarm as a worker.
```
4. 
```
docker network create -d overlay skynet
```
5. 
```
docker volume create consul
```
6. 
```
docker service create --name consul --network skynet --replicas 1 \
	-p 8400:8400 -p 8500:8500/tcp -p 8600:53/udp \
	-e 'CONSUL_LOCAL_CONFIG={"bootstrap_expect":1,"datacenter":"dc1","data_dir":"/usr/local/bin/consul.d/data","server":true}' \
	--mount src=consul,dst=/usr/local/bin/consul.d/data \
	--constraint 'node.role == manager' \
	consul agent -server -bind=127.0.0.1 -client=0.0.0.0 -ui
```
7. 
```
docker service create --name vault --network skynet --replicas 1 \
	-p 8200:8200 \
	-e SKIP_SETCAP=true \
	--mount type=bind,source=$PWD/vault/config,destination=/vault/config \
	--constraint 'node.role == manager' \
	vault server
```
8. 
```
docker service create --name vault-ui --network skynet --replicas 1 \
	-p 9000:8000 \
	-e VAULT_URL_DEFAULT=http://vault:8200 \
	--constraint 'node.role == manager' \
	djenriquez/vault-ui
```
9. 
```
docker service create --name rabbitmq --network skynet --replicas 1 \
	-p 5672:5672 -p 15672:15672 \
	-e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password \
	--constraint 'node.role == manager' \
	rabbitmq:3-management
```
10. 
```
cat $ROOT_TOKEN_FILE | docker secret create spring.cloud.config.token - && \
echo "http://config:8888" | docker secret create spring.cloud.config.uri - && \
echo "user" | docker secret create spring.rabbitmq.username - && \
echo "password" | docker secret create spring.rabbitmq.password -
```
11. 
```
docker service create --name config \
	--network skynet --replicas 2 \
	-p 8888:8888 \
	--secret source=spring.cloud.config.token,target=spring.cloud.config.token \
	--secret source=spring.rabbitmq.username,target=spring.rabbitmq.username \
	--secret source=spring.rabbitmq.password,target=spring.rabbitmq.password \
	-e SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST=vault \
	-e SPRING_CLOUD_CONFIG_SERVER_VAULT_PORT=8200 \
	-e SPRING_CLOUD_CONFIG_SERVER_VAULT_SCHEME=http \
	-e SPRING_CLOUD_CONFIG_SERVER_VAULT_AUTHENTICATION=TOKEN \
	-e SPRING_CLOUD_CONFIG_SERVER_VAULT_TOKEN_FILE="/run/secrets/spring.cloud.config.token" \
	-e SPRING_RABBITMQ_HOST=rabbitmq \
	-e SPRING_RABBITMQ_PORT=5672 \
	-e SPRING_RABBITMQ_USERNAME_FILE="/run/secrets/spring.rabbitmq.username" \
	-e SPRING_RABBITMQ_PASSWORD_FILE="/run/secrets/spring.rabbitmq.password" \
	--with-registry-auth \
	microsip/ms-configuration-service:0.0.1 
```
**Describe the results you received:**
Service config can connect to services rabbitmq and service vault. For both replicas.

**Describe the results you expected:**
The second replica can´t connect to services rabbitmq and service vault.

docker logs config.2.0ums8cxquj4rll0duestr1zdr
```
2017-04-06 21:19:44.846  INFO 8 --- [           main] c.m.c.MsConfigurationServiceApplication  : The following profiles are active: vault,config-monitor
2017-04-06 21:19:44.851  INFO 8 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@14bae047: startup date [Thu Apr 06 21:19:44 CDT 2017]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@553a3d88
2017-04-06 21:19:45.032  INFO 8 --- [           main] o.s.c.support.GenericApplicationContext  : Refreshing org.springframework.context.support.GenericApplicationContext@3028e50e: startup date [Thu Apr 06 21:19:45 CDT 2017]; root of context hierarchy
2017-04-06 21:19:45.121  INFO 8 --- [           main] c.m.c.MsConfigurationServiceApplication  : Started MsConfigurationServiceApplication in 0.442 seconds (JVM running for 15.426)
2017-04-06 21:19:45.300  INFO 8 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: SimpleConnection@127f9161 [delegate=amqp://user@10.0.0.8:5672/, localPort= 52358]
2017-04-06 21:19:45.373  INFO 8 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'ms-configuration-service:vault,config-monitor:8888.springCloudBusOutput' has 1 subscriber(s).
2017-04-06 21:19:45.374  INFO 8 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2017-04-06 21:19:45.409  INFO 8 --- [           main] o.s.c.c.m.FileMonitorConfiguration       : Not monitoring for local config changes
2017-04-06 21:19:45.409  INFO 8 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2017-04-06 21:19:45.410  INFO 8 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'ms-configuration-service:vault,config-monitor:8888.errorChannel' has 1 subscriber(s).
2017-04-06 21:19:45.410  INFO 8 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2017-04-06 21:19:45.411  INFO 8 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2017-04-06 21:19:45.439  INFO 8 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: springCloudBus.anonymous.qfQm4dwaQrS096wROqOQ9w, bound to: springCloudBus
2017-04-06 21:19:45.544  INFO 8 --- [           main] o.s.i.a.i.AmqpInboundChannelAdapter      : started inbound.springCloudBus.anonymous.qfQm4dwaQrS096wROqOQ9w
2017-04-06 21:19:45.545  INFO 8 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {message-handler:inbound.springCloudBus.default} as a subscriber to the 'bridge.springCloudBus' channel
2017-04-06 21:19:45.545  INFO 8 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started inbound.springCloudBus.default
2017-04-06 21:19:45.546  INFO 8 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2017-04-06 21:19:45.668  INFO 8 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8888 (http)
2017-04-06 21:19:45.675  INFO 8 --- [           main] c.m.c.MsConfigurationServiceApplication  : Started MsConfigurationServiceApplication in 14.695 seconds (JVM running for 15.98)
```

docker logs config.1.t3gyd91wwlhq36mzzv4p6dut0

```
org.springframework.amqp.AmqpIOException: java.net.UnknownHostException: rabbitmq
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:367) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:565) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:90) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:140) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:76) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:505) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1382) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: java.net.UnknownHostException: rabbitmq
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_112]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_112]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_112]
	at com.rabbitmq.client.DnsRecordIpAddressResolver.resolveIpAddresses(DnsRecordIpAddressResolver.java:83) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.DnsRecordIpAddressResolver.getAddresses(DnsRecordIpAddressResolver.java:73) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:903) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:799) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:351) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	... 7 common frames omitted

2017-04-06 21:25:45.441  INFO 8 --- [OJM2rduIlvtg-72] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@66b3dea2: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
2017-04-06 21:25:50.515  WARN 8 --- [OJM2rduIlvtg-73] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it

org.springframework.amqp.AmqpIOException: java.net.UnknownHostException: rabbitmq: Name or service not known
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:367) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:565) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:90) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:140) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:76) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:505) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1382) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: java.net.UnknownHostException: rabbitmq: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_112]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_112]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_112]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_112]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_112]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_112]
	at com.rabbitmq.client.DnsRecordIpAddressResolver.resolveIpAddresses(DnsRecordIpAddressResolver.java:83) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.DnsRecordIpAddressResolver.getAddresses(DnsRecordIpAddressResolver.java:73) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:903) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:799) ~[amqp-client-4.0.2.jar!/:4.0.2]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:351) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
	... 7 common frames omitted

2017-04-06 21:25:50.515  INFO 8 --- [OJM2rduIlvtg-73] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@74a3a1f3: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
```

**Additional information you deem important (e.g. issue happens only occasionally):**
docker service ls
```
ID            NAME      MODE        REPLICAS  IMAGE
1ngq7n3cytys  config    replicated  2/2      microsip/ms-configuration-service:0.0.1
addtzcz81wsv  vault     replicated  1/1       vault:latest
iaq36m8p60lp  vault-ui  replicated  1/1       djenriquez/vault-ui:latest
j4q7gu0djhpu  consul    replicated  1/1       consul:latest
x3zuh4zxlr2v  rabbitmq  replicated  1/1       rabbitmq:3-management
```
*Node Manager*
docker network inspect skynet 
```
[
    {
        "Name": "skynet",
        "Id": "l8d09gk41nt2gl5wtc95w88py",
        "Created": "2017-04-07T02:14:13.218532809Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "15725ccfa2b1020198651bbb56425a2710ea7cb1c7d1344ec8ffaea346424614": {
                "Name": "config.2.0ums8cxquj4rll0duestr1zdr",
                "EndpointID": "88f67b9904565f2651c17ef51acb3808796760b76034d36de7ead40469239e29",
                "MacAddress": "02:42:0a:00:00:0c",
                "IPv4Address": "10.0.0.12/24",
                "IPv6Address": ""
            },
            "687f60965098064b0a738f1b9523ff4ef3df64c65185a84b0d88e275e4bbee5e": {
                "Name": "rabbitmq.1.n578pgytdfnybeabcaalhil22",
                "EndpointID": "e173c0b2e8a8f6e7af568934c31dcfbf81cfe2f3db223fa1d0d35dd69d2ffcc8",
                "MacAddress": "02:42:0a:00:00:09",
                "IPv4Address": "10.0.0.9/24",
                "IPv6Address": ""
            },
            "bfcba7b1a5a65c29006b47b7a67c182f4f8692ac33fb4959df3fe82ab8a4ee6d": {
                "Name": "vault.1.coyornosxd4a1qb3os7poqn03",
                "EndpointID": "879f67d246779923b7376992b5b3c51018170ea9b6e0a9f0249091c3e7781050",
                "MacAddress": "02:42:0a:00:00:05",
                "IPv4Address": "10.0.0.5/24",
                "IPv6Address": ""
            },
            "c06eda2d173a100691b40f5bf3220a52e5ee35b242024f4337a66f8ead6e8a09": {
                "Name": "vault-ui.1.bv9yfwyjb5w8qim4etaiao97k",
                "EndpointID": "3ef3495144ec8af4389cd77035e064ed3b2d59817dc2a2ab6cce148990c34f96",
                "MacAddress": "02:42:0a:00:00:07",
                "IPv4Address": "10.0.0.7/24",
                "IPv6Address": ""
            },
            "e82405c04a9cdd64846860804732c9546c311e23979f216e804939a74c5ab071": {
                "Name": "consul.1.aii1lwldlpo233dpz84txaztf",
                "EndpointID": "3a1434c2c2ac10a4d3b16bf177152a1f6f42cdf417a3828dc3871e3df5caa571",
                "MacAddress": "02:42:0a:00:00:03",
                "IPv4Address": "10.0.0.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "ip-10-10-70-219-e6ceb4657576",
                "IP": "10.10.70.219"
            }
        ]
    }
]
```

*Node Worker*
docker network inspect skynet
```
[
    {
        "Name": "skynet",
        "Id": "l8d09gk41nt2gl5wtc95w88py",
        "Created": "2017-04-07T02:19:29.102121806Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "a7d471629c3fa03eb68990a93054a46641fb427506c8f854eb59bc784794fd3f": {
                "Name": "config.1.t3gyd91wwlhq36mzzv4p6dut0",
                "EndpointID": "ea1315f29d08dad947b5936bab061f08f25aabc135270c5379ddc08f40f0c3f4",
                "MacAddress": "02:42:0a:00:00:0b",
                "IPv4Address": "10.0.0.11/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "ip-10-10-129-189-cbbcd5d165c6",
                "IP": "10.10.129.189"
            }
        ]
    }
]
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: xfchgy6pqdsnwo2fy0pu2qncq
 Is Manager: true
 ClusterID: bvjlfp1wcczraj1mccdtx1ceb
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.70.219
 Manager Addresses:
  10.10.70.219:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.6 MiB
Name: ip-10-10-70-219
ID: Y4IL:5YST:YOS5:VKWJ:2XOQ:KXPN:D4XE:2OVJ:NZR3:PM6F:ZZKR:PUYY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Two AWS EC2 instances same vpc, subnet, group, owner, permissions, etc.

lsb_release  -a
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
