### ISSUE TITLE
docker build fails with "unexpected EOF" when using multiple built-in build args

### ISSUE THREAD

**Issue by djs55** [moby/moby#32744]
This was reported by @shomron on https://github.com/docker/for-mac/issues/1550 on Docker for Mac, but it reproduces inside the Linux VM too.

**Description**

Passing multiple builtin build-args (e.g. `http_proxy` + `https_proxy`) causes the build to fail as follows:

**Steps to reproduce the issue:**

```
$ cat > Dockerfile   <<EOT
FROM alpine:3.4
RUN touch /tmp/foobar
EOT
$ docker build --build-arg http_proxy=foo --build-arg https_proxy=foo .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine:3.4
 ---> 245f7a86c576
Step 2/2 : RUN touch /tmp/foobar
 ---> Running in 3974cb96fb50
unexpected EOF
```

@shomrom reports that the bug only manifests if
- multiple *built-in* build-args are provided (there must be some special handling for those)
- the `RUN` command is provided

**Describe the results you received:**

Rather than complete the build it will print
```
unexpected EOF
```

**Describe the results you expected:**

A successful build will say
```
 ---> f7194379edfe
Removing intermediate container 2fdaa9a16682
Successfully built f7194379edfe
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue reproduces on `17.05.0-ce-rc1` but @dave-tucker reports that the build works correctly on `17.04.0-ce`

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 25
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 7JD3:P3CR:QIQY:33FR:HALA:OMXK:QXD7:IBRU:B6O2:7CBQ:WPTT:7IGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 42
 System Time: 2017-04-20T16:04:51.884882696Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It reproduces on Docker for Mac edge both inside and outside the VM. Although when run outside the VM the error message "unexpected EOF" disappears somewhere in the plumbing.

**Comment by AkihiroSuda** [comment]
`journalctl -u docker` (on Linux VM) please?

**Comment by dave-tucker** [comment]
```
Apr 21 10:56:03 moby root: 2017-04-21 10:56:03.482436 I | http: panic serving @: runtime error: slice bounds out of range
Apr 21 10:56:03 moby root: goroutine 377 [running]:
Apr 21 10:56:03 moby root: net/http.(*conn).serve.func1(0xc420fa1600)
Apr 21 10:56:03 moby root: /usr/local/go/src/net/http/server.go:1491 +0x12a
Apr 21 10:56:03 moby root: panic(0x1712e80, 0xc4200120f0)
Apr 21 10:56:03 moby root: /usr/local/go/src/runtime/panic.go:458 +0x243
Apr 21 10:56:03 moby root: github.com/docker/docker/builder/dockerfile.run(0xc420e53200, 0xc420aa2040, 0x1, 0x1, 0x0, 0xc42126fbc0, 0xe, 0x0, 0x0)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/builder/dockerfile/dispatchers.go:426 +0x989
Apr 21 10:56:03 moby root: github.com/docker/docker/builder/dockerfile.(*Builder).dispatch(0xc420e53200, 0x1, 0x2, 0xc420302a10, 0xc42165d1b8, 0x1)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/builder/dockerfile/evaluator.go:183 +0xd07
Apr 21 10:56:03 moby root: github.com/docker/docker/builder/dockerfile.(*Builder).build(0xc420e53200, 0x24ed840, 0xc4212bed20, 0x24ed800, 0xc4212bed40, 0x24eccc0, 0xc4212bed00, 0x0, 0x0, 0xc420e53200, ...)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/builder/dockerfile/builder.go:278 +0x290
Apr 21 10:56:03 moby root: github.com/docker/docker/builder/dockerfile.(*BuildManager).BuildFromContext(0xc420f481a0, 0x7f4715bd0fc0, 0xc420fb5640, 0x24fa780, 0xc420fb5580, 0x0, 0x0, 0xc421571e40, 0x24eccc0, 0xc4212bed00, ...)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/builder/dockerfile/builder.go:122 +0x323
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0xc420efda40, 0x7f4715bd0fc0, 0xc420fb5640, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0x0, 0x0)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/router/build/build_routes.go:213 +0x87f
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server/router/build.(*buildRouter).(github.com/docker/docker/api/server/router/build.postBuild)-fm(0x7f4715bd0fc0, 0xc420fb5640, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0xc42126f3a0, 0x1)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/router/build/build.go:27 +0x69
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server/router.cancellableHandler.func1(0x7f471641e0a8, 0xc4212e2c90, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0x0, 0x0)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/router/local.go:84 +0x104
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f471641e0a8, 0xc4212e2c90, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0x7f471641e0a8, 0xc4212e2c90)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f471641e0a8, 0xc4212e2c30, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0xc420e4e790, 0x8)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x5b4
Apr 21 10:56:03 moby root: github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f471641e0a8, 0xc4212e2c30, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0x756ea1671c9778, 0xc420abf998)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x83f
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f471641e0a8, 0xc4212e2c30, 0x25048c0, 0xc421085ee0, 0xc4200d12c0, 0xc4212e2ba0, 0x7f471641e0a8, 0xc4212e2c30)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x9bf
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x25048c0, 0xc421085ee0, 0xc4200d12c0)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/server.go:140 +0x232
Apr 21 10:56:03 moby root: net/http.HandlerFunc.ServeHTTP(0xc420235fc0, 0x25048c0, 0xc421085ee0, 0xc4200d12c0)
Apr 21 10:56:03 moby root: /usr/local/go/src/net/http/server.go:1726 +0x44
Apr 21 10:56:03 moby root: github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420f4c000, 0x25048c0, 0xc421085ee0, 0xc4200d12c0)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
Apr 21 10:56:03 moby root: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420e4a2d0, 0x25048c0, 0xc421085ee0, 0xc4200d12c0)
Apr 21 10:56:03 moby root: /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
Apr 21 10:56:03 moby root: net/http.serverHandler.ServeHTTP(0xc420214100, 0x25048c0, 0xc421085ee0, 0xc4200d12c0)
Apr 21 10:56:03 moby root: /usr/local/go/src/net/http/server.go:2202 +0x7d
Apr 21 10:56:03 moby root: net/http.(*conn).serve(0xc420fa1600, 0x2506580, 0xc420fb5440)
Apr 21 10:56:03 moby root: /usr/local/go/src/net/http/server.go:1579 +0x4b7
Apr 21 10:56:03 moby root: created by net/http.(*Server).Serve
Apr 21 10:56:03 moby root: /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by dave-tucker** [comment]
wait that's from my branch... let me get one from the version that repro's.
I think this is related to my `build-arg` change so will try and fix it

**Comment by dave-tucker** [comment]
```
Apr 21 11:04:17 moby root: 2017-04-21 11:04:17.382169 I | http: panic serving @: runtime error: slice bounds out of range
Apr 21 11:04:17 moby root: goroutine 228 [running]:
Apr 21 11:04:17 moby root: net/http.(*conn).serve.func1(0xc421821080)
Apr 21 11:04:17 moby root: /usr/local/go/src/net/http/server.go:1491 +0x12a
Apr 21 11:04:17 moby root: panic(0x17cb5e0, 0xc4200120f0)
Apr 21 11:04:17 moby root: /usr/local/go/src/runtime/panic.go:458 +0x243
Apr 21 11:04:17 moby root: github.com/docker/docker/builder/dockerfile.run(0xc42095b680, 0xc42151c280, 0x1, 0x1, 0x0, 0xc421328e90, 0x7, 0x0, 0x0)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/builder/dockerfile/dispatchers.go:457 +0x98b
Apr 21 11:04:17 moby root: github.com/docker/docker/builder/dockerfile.(*Builder).dispatch(0xc42095b680, 0x1, 0x2, 0xc420951ab0, 0xc42202b180, 0x1)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/builder/dockerfile/evaluator.go:154 +0x9e0
Apr 21 11:04:17 moby root: github.com/docker/docker/builder/dockerfile.(*Builder).build(0xc42095b680, 0x260cca0, 0xc4212be080, 0x260cc60, 0xc4212be0c0, 0x260c0a0, 0xc4212be060, 0x0, 0x0, 0x0, ...)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/builder/dockerfile/builder.go:241 +0x33c
Apr 21 11:04:17 moby root: github.com/docker/docker/builder/dockerfile.(*BuildManager).BuildFromContext(0xc420190780, 0x7fc3d9c67600, 0xc4208f60c0, 0x261a5e0, 0xc420a15c80, 0x0, 0x0, 0xc420779e00, 0x260c0a0, 0xc4212be060, ...)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/builder/dockerfile/builder.go:110 +0x308
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0xc4207bf1a0, 0x7fc3d9c67600, 0xc4208f60c0, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0x0, 0x0)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/router/build/build_routes.go:214 +0x87f
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server/router/build.(*buildRouter).(github.com/docker/docker/api/server/router/build.postBuild)-fm(0x7fc3d9c67600, 0xc4208f60c0, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0xc421291dc0, 0x1)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/router/build/build.go:27 +0x69
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server/router.cancellableHandler.func1(0x7fc3da64a028, 0xc4204c1b00, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0x0, 0x0)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/router/local.go:84 +0x104
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7fc3da64a028, 0xc4204c1b00, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0x7fc3da64a028, 0xc4204c1b00)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fc3da64a028, 0xc4204c1aa0, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0xc4212b5ea0, 0xc42042c9a0)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x5b4
Apr 21 11:04:17 moby root: github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7fc3da64a028, 0xc4204c1aa0, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0x756ea164e74266, 0xc420ec19a8)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x923
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7fc3da64a028, 0xc4204c1aa0, 0x2625860, 0xc4226285b0, 0xc422626690, 0xc4204c1a40, 0x7fc3da64a028, 0xc4204c1aa0)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x9bf
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2625860, 0xc4226285b0, 0xc422626690)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/server.go:140 +0x247
Apr 21 11:04:17 moby root: net/http.HandlerFunc.ServeHTTP(0xc42091fa40, 0x2625860, 0xc4226285b0, 0xc422626690)
Apr 21 11:04:17 moby root: /usr/local/go/src/net/http/server.go:1726 +0x44
Apr 21 11:04:17 moby root: github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42026c690, 0x2625860, 0xc4226285b0, 0xc422626690)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
Apr 21 11:04:17 moby root: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420a713f0, 0x2625860, 0xc4226285b0, 0xc422626690)
Apr 21 11:04:17 moby root: /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
Apr 21 11:04:17 moby root: net/http.serverHandler.ServeHTTP(0xc420127480, 0x2625860, 0xc4226285b0, 0xc422626690)
Apr 21 11:04:17 moby root: /usr/local/go/src/net/http/server.go:2202 +0x7d
Apr 21 11:04:17 moby root: net/http.(*conn).serve(0xc421821080, 0x2627520, 0xc420a15980)
Apr 21 11:04:17 moby root: /usr/local/go/src/net/http/server.go:1579 +0x4b7
Apr 21 11:04:17 moby root: created by net/http.(*Server).Serve
Apr 21 11:04:17 moby root: /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by dave-tucker** [comment]
I've found the bug...
It's in the logic I added for pruning the built-in build args from the `saveCmd`
As I'm iterating over the slice I'm mutating, deleting an item from it causes the indexes to be off by one. This will have no effect for a single build arg but will cause issues when pruning mutliple args. PR inbound

**Comment by alexellis** [comment]
@thaJeztah this is an important change for enterprise users behind proxies who cannot use Docker without multiple --build-args. This breaks mid-build with no warning and is very confusing. I think it's essential that this regression doesn't make it into a stable release.

**Comment by Bharathkumarraju** [comment]
```


[ansible] # docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Jul 20 00:06:39 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Jul 20 00:06:39 2017
 OS/Arch:         linux/amd64
[ansible] # cd elastic/edmi-wm-platform-v9/provisioning/
[provisioning] # cat Dockerfile
FROM wm95isbase:0.0.1
MAINTAINER EDMIDevops@sc.com

RUN curl -s http://XXXXXXXX:8888/develop/paas-default,$DC,$ENV,$DMN,$DC$DMN,$DMN$ENV.yml > /tmp/vars.yml


[provisioning] # docker build  --build-arg "DC=HK" --build-arg  "ENV=T2" --build-arg  "DMN=DT0" -t config:1.0.0 .
Sending build context to Docker daemon 697.9 kB
Step 1 : FROM wm95isbase:0.0.1
 ---> 39cafd038cec
Step 2 : MAINTAINER EDMIDevops@sc.com
 ---> Using cache
 ---> 7f13059bc128
Step 3 : RUN curl -s http://xxxxxxx:8888/develop/paas-default,$DC,$ENV,$DMN,$DC$DMN,$DMN$ENV.yml > /tmp/vars.yml
 ---> Using cache
 ---> 9baddac40e5c
One or more build-args [DC DMN ENV] were not consumed, failing build.
[provisioning] #

```

**Comment by Bharathkumarraju** [comment]
I am getting above error can anyone help me on this

**Comment by cpuguy83** [comment]
You have to declare args in the Dockerfile with "ARG foo"

**Comment by thaJeztah** [comment]
@kkaung if you have details, and steps to reproduce please open a new ticket instead of commenting on this ticket, because this one was resolved

**Comment by kkaung** [comment]
Got it resolved with `.dockerignore`,.  Thanks

**Comment by aleemnazer** [comment]
@kkaung  how did you resolved it?
