### ISSUE TITLE
docker fails to start with SIGSEGV

### ISSUE THREAD

**Issue by piontec** [moby/moby#32808]
**Description**
Docker daemon fails to start when restarted with `systemctl restart docker`

**Steps to reproduce the issue:**
1. Restart docker with systemctl
2. Check syslog

**Describe the results you received:**
Systemd is restarting docker:
```
Apr 24 13:47:37 localhost systemd[1]: Stopping Docker Application Container Engine...
Apr 24 13:47:53 localhost systemd[1]: Stopped Docker Application Container Engine.
Apr 24 13:47:53 localhost systemd[1]: Closed Docker Socket for the API.
Apr 24 13:47:53 localhost systemd[1]: Stopping Docker Socket for the API.
Apr 24 13:47:53 localhost systemd[1]: Starting Docker Socket for the API.
Apr 24 13:47:53 localhost systemd[1]: Listening on Docker Socket for the API.
Apr 24 13:47:53 localhost systemd[1]: Starting Docker Application Container Engine...
Apr 24 13:48:05 localhost systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 13:48:05 localhost systemd[1]: Failed to start Docker Application Container Engine.
```

But dockerd fails:
```
3657126 Apr 24 13:59:27 localhost dockerd[17816]: time="2017-04-24T13:59:27.061012296Z" level=warning msg="libcontainerd: client is out of sync, restore was called on a fully synced container (386eb7812980        fe22ac7e2f32d3cfee52686ba5aef116b67ea2a1cd10e5a01b5f)."
3657127 Apr 24 13:59:27 localhost dockerd[17816]: time="2017-04-24T13:59:27.061623954Z" level=debug msg="libcontainerd: restore container 386eb7812980fe22ac7e2f32d3cfee52686ba5aef116b67ea2a1cd10e5a01b5f st        ate running"
3657128 Apr 24 13:59:27 localhost dockerd[17816]: panic: runtime error: invalid memory address or nil pointer dereference
3657129 Apr 24 13:59:27 localhost dockerd[17816]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x59add1]
3657130 Apr 24 13:59:27 localhost dockerd[17816]: goroutine 6155 [running]:
3657131 Apr 24 13:59:27 localhost dockerd[17816]: panic(0x16dc2a0, 0xc42000c080)
3657132 Apr 24 13:59:27 localhost dockerd[17816]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
3657133 Apr 24 13:59:27 localhost dockerd[17816]: github.com/docker/docker/daemon.(*Daemon).createSpec(0xc4203e2200, 0xc4214c7000, 0x0, 0x0, 0xc4203e2200)
3657134 Apr 24 13:59:27 localhost dockerd[17816]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/oci_linux.go:729 +0xe11
3657135 Apr 24 13:59:27 localhost dockerd[17816]: github.com/docker/docker/daemon.(*Daemon).containerStart(0xc4203e2200, 0xc4214c7000, 0x0, 0x0, 0x0, 0x0, 0xc42349b400, 0x0, 0x0)
3657136 Apr 24 13:59:27 localhost dockerd[17816]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:149 +0x290
3657137 Apr 24 13:59:27 localhost dockerd[17816]: github.com/docker/docker/daemon.(*Daemon).StateChanged.func2(0xc42349ade0, 0xc4203e2200, 0xc4214c7000, 0xc421a3b104, 0x4, 0x100000000, 0x0, 0x0, 0x0, 0xc42        3496680)
3657138 Apr 24 13:59:27 localhost dockerd[17816]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:65 +0x267
3657139 Apr 24 13:59:27 localhost dockerd[17816]: created by github.com/docker/docker/daemon.(*Daemon).StateChanged
3657140 Apr 24 13:59:27 localhost dockerd[17816]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:76 +0x6de
3657141 Apr 24 13:59:27 localhost systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
3657142 Apr 24 13:59:27 localhost systemd[1]: Failed to start Docker Application Container Engine.
3657143 Apr 24 13:59:27 localhost systemd[1]: Dependency failed for daemon for configuring additional routing and iptables rules for additional IPs.
3657144 Apr 24 13:59:27 localhost systemd[1]: docker_routing_rules.service: Job docker_routing_rules.service/start failed with result 'dependency'.
3657145 Apr 24 13:59:27 localhost systemd[1]: docker.service: Unit entered failed state.
3657146 Apr 24 13:59:27 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Additional information you deem important (e.g. issue happens only occasionally):**
It's not repeatable; eventually, some restart will be successful and docker will start

**Output of `docker version`:**
Please note: we confirmed this on 17.03.0 EE also
```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 20:06:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 20:06:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 393
 Running: 316
 Paused: 0
 Stopped: 77
Images: 1886
Server Version: 17.03.1-ee-3
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4506
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 960.7 GiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 2962
 Goroutines: 1968
 System Time: 2017-04-25T10:12:51.915536168Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* running on AWS x16.xlarge

**Comment by cpuguy83** [comment]
Are you able to get the full trace for this panic?

@mlaventure Looks like this is happening here: https://github.com/moby/moby/blob/v17.03.1-ce/daemon/oci_linux.go#L729
So looks like the net controller is nil.
It seems like this would only ever get called when a `StateExit` event is received.

So I'm guessing that the container was running when docker was stopped, then the container died, and then docker was brought back up, which subsequently tried to auto-restart the container on the exit event.
Does that make sense to you?

**Comment by cpuguy83** [comment]
Working on a branch right now for another bug but will try to repro this today.

**Comment by piontec** [comment]
@cpuguy83 No, I don't have the full trace and it might be hard to guess the moment when you should send SIGUSR1 to the process. Do you have any other ideas about catching the trace?

**Comment by mlaventure** [comment]
@cpuguy83 yes, I agree with your assessment, the container must have died while the daemon was still going through the restore process.

I'd say we need to avoid starting the main loop before the restore process is done. This may cause some duplicated event (and some error on containers) early on when the daemon process the exit event twice, but that's already the case in a lesser amount.

**Comment by cpuguy83** [comment]
@piontec It seems like the trace in the logs is just a little bit cut off, but maybe not. Don't need the full stack. But maybe not needed anyway.

**Comment by cpuguy83** [comment]
Ok, I've got a reproducer for this. Definitely a race condition for that netcontroller to be set.

**Comment by cpuguy83** [comment]
```go
func (s *DockerDaemonSuite) TestDaemonLiveRestoreRestartWithFailedContainers(c *check.C) {
	testRequires(c, DaemonIsLinux, SameHostDaemon)

	s.d.StartWithBusybox(c, "--live-restore")
	out, err := s.d.Cmd("run", "-d", "--name=test", "--restart=always", "busybox", "top")
	c.Assert(err, checker.IsNil, check.Commentf(out))

	hostArgs := []string{"--host", s.d.Sock()}
	err = waitInspectWithArgs("test", "{{.State.Running}} {{.State.Restarting}}", "true false", 10*time.Second, hostArgs...)
	c.Assert(err, checker.IsNil)

	out, err = s.d.Cmd("inspect", "--format={{.State.Pid}}", "test")
	c.Assert(err, checker.IsNil, check.Commentf(out))
	pid := strings.TrimSpace(out)

	err = s.d.Kill()
	c.Assert(err, checker.IsNil)

	result := icmd.RunCommand("kill", "-9", pid)
	c.Assert(result.ExitCode, checker.Equals, 0, check.Commentf(result.Combined()))

	// start daemon again and wait for container to be in running state
	s.d.StartWithBusybox(c, "--live-restore")
	err = waitInspectWithArgs("test", "{{.State.Running}} {{.State.Restarting}}", "true false", 10*time.Second, hostArgs...)
	c.Assert(err, checker.IsNil)
}
```

Can repro 100% of the time if I put a 30s sleep in before https://github.com/moby/moby/blob/master/daemon/daemon.go#L271

**Comment by piontec** [comment]
@cpuguy83 Great! Can you already tell in which 17.03 EE update it will be included? This is a serious problem for us

**Comment by cpuguy83** [comment]
@piontec Still working on a fix.

Can you explain how this is critical? From what I can tell this is a race condition when the daemon is restarted with live-restore where a container that was running exited while the daemon was offline.
Seems pretty difficult to trigger without specifically adding the sleep.

**Comment by cpuguy83** [comment]
Opened #32845

**Comment by piontec** [comment]
@cpuguy83 HOw's that critical? Very simple: with high load we got on the server, dockerd fails sometimes and needs to be restarted (see #32809 ). This bug happens like 2 out of 3 or even 3 out of 4 times we try to restart dockerd!

**Comment by AkihiroSuda** [comment]
Seems already resolved?
