### ISSUE TITLE
dnf install -y docker-ce fails due to vim-common

### ISSUE THREAD

**Issue by belooussov** [moby/moby#33189]
Description:
The rpm installer on Fedora Core 25 fails to install docker-ce due to vim-common being present on the system.

```
[root@monolith ~]# dnf reinstall docker-ce
Last metadata expiration check: 0:21:33 ago on Sun May 14 21:21:46 2017.
Dependencies resolved.
================================================================================
 Package        Arch        Version                   Repository           Size
================================================================================
Reinstalling:
 docker-ce      x86_64      17.05.0.ce-1.fc25         docker-ce-edge       20 M

Transaction Summary
================================================================================

Total size: 20 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] docker-ce-17.05.0.ce-1.fc25.x86_64.rpm: Already downloaded           
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Reinstalling: docker-ce-17.05.0.ce-1.fc25.x86_64                          1/2 
  Erasing     : docker-ce-17.05.0.ce-1.fc25.x86_64                          2/2 
warning: %triggerin(vim-common-2:8.0.586-1.fc25.x86_64) scriptlet failed, exit status 127
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py", line 427, in callback
    self._scriptError(bytes, total, h)
  File "/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py", line 557, in _scriptError
    pkg, _, _ = self._extract_cbkey(h)
  File "/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py", line 229, in _extract_cbkey
    return self._extract_str_cbkey(cbkey)
  File "/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py", line 237, in _extract_str_cbkey
    assert(isinstance(name, basestring))
AssertionError
FATAL ERROR: python callback ??? failed, aborting!
[root@monolith ~]# docker search vim-common
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[root@monolith ~]# dnf search vim-common
Last metadata expiration check: 0:22:20 ago on Sun May 14 21:21:46 2017.
=========================== N/S Matched: vim-common ============================
vim-common.x86_64 : The common files needed by any version of the VIM editor
[root@monolith ~]# dnf -y remove vim-common
Dependencies resolved.
================================================================================
 Package          Arch         Version                     Repository      Size
================================================================================
Removing:
 golint           x86_64       0-0.2.gitc7bacac.fc25       @fedora        3.4 M
 vim-common       x86_64       2:8.0.586-1.fc25            @updates        28 M
 vim-golint       x86_64       0-0.2.gitc7bacac.fc25       @fedora        651  
 vim-latex        noarch       1.9.0-1.fc25                @System        806 k

Transaction Summary
================================================================================
Remove  4 Packages

Installed size: 32 M
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Erasing     : vim-golint-0-0.2.gitc7bacac.fc25.x86_64                     1/4 
  Erasing     : vim-latex-1.9.0-1.fc25.noarch                               2/4 
  Erasing     : golint-0-0.2.gitc7bacac.fc25.x86_64                         3/4 
  Erasing     : vim-common-2:8.0.586-1.fc25.x86_64                          4/4 
  Verifying   : vim-common-2:8.0.586-1.fc25.x86_64                          1/4 
  Verifying   : vim-golint-0-0.2.gitc7bacac.fc25.x86_64                     2/4 
  Verifying   : vim-latex-1.9.0-1.fc25.noarch                               3/4 
  Verifying   : golint-0-0.2.gitc7bacac.fc25.x86_64                         4/4 

Removed:
  golint.x86_64 0-0.2.gitc7bacac.fc25       vim-common.x86_64 2:8.0.586-1.fc25  
  vim-golint.x86_64 0-0.2.gitc7bacac.fc25   vim-latex.noarch 1.9.0-1.fc25       

Complete!
[root@monolith ~]# dnf reinstall docker-ce
Last metadata expiration check: 0:22:40 ago on Sun May 14 21:21:46 2017.
Dependencies resolved.
================================================================================
 Package        Arch        Version                   Repository           Size
================================================================================
Reinstalling:
 docker-ce      x86_64      17.05.0.ce-1.fc25         docker-ce-edge       20 M

Transaction Summary
================================================================================

Total size: 20 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] docker-ce-17.05.0.ce-1.fc25.x86_64.rpm: Already downloaded           
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Reinstalling: docker-ce-17.05.0.ce-1.fc25.x86_64                          1/2 
  Erasing     : docker-ce-17.05.0.ce-1.fc25.x86_64                          2/2 
  Verifying   : docker-ce-17.05.0.ce-1.fc25.x86_64                          1/2 
  Verifying   : docker-ce-17.05.0.ce-1.fc25.x86_64                          2/2 

Reinstalled:
  docker-ce.x86_64 17.05.0.ce-1.fc25                                            

Complete!
[root@monolith ~]# 
```

Steps to reproduce on FC25:
1. dnf -y install vim-common
2. dnf -y install docker-ce

Received:
Failure on install.

Expected:
The dnf installer works around vim-common being present.

**Output of `docker version`:**

```
[root@monolith ~]# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:18:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:18:37 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@monolith ~]# 
```

**Output of `docker info`:**

```
[root@monolith ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 168
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-527467-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.77GB
 Data Space Total: 107.4GB
 Data Space Available: 21.65GB
 Metadata Space Used: 14.39MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.133GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.14-200.fc25.x86_64
Operating System: Fedora 25 (Twenty Five)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.787GiB
Name: monolith.home.lan
ID: FY6B:3KDG:B5S7:4FJ5:7M2X:JYAX:NNFC:T3L5:FMTW:OKGJ:CRUU:BBCX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
[root@monolith ~]# 
```

Running on FC25, 64 bit, IBM Thinkpad X300.

**Comment by runcom** [comment]
How come vim-common is a runtime dep of docker?! In the fedora pkg we don't have it as a runtime dep, it's just a BuildRequires :confused:

**Comment by thaJeztah** [comment]
I don't believe it is; it's only used in the build Dockerfiles. The packages only install the syntax files for vim https://github.com/moby/moby/blob/c307f4521edc58df347897c84159f25606cae597/hack/make/.build-rpm/docker-engine.spec#L177

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
