### ISSUE TITLE
Service Logs fails on scale down

### ISSUE THREAD

**Issue by dperny** [moby/moby#33203]
**Description**

Scaling down a service and then immediately calling `service logs` causes the logs call to fail.

99% sure this is present in master. 50% sure this is a regression. 

**Steps to reproduce the issue:**

1. `docker service create --name test flyinprogrammer/logtester`
2. `docker service scale test=3`
3. `docker service scale test=1 && docker service logs test`

**Describe the results you received:**

```
test scaled to 1
Error: No such task: k182o2jt30jn3p8ojdi5n9pv8
```

**Describe the results you expected:**

1 task worth of logs

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
 
```

**Comment by JonasKs** [comment]
I struggle with the same.

**Steps to reproduce the issue:**
1) `docker service create  --name my-web --publish 9091:80 --replicas 2 nginx`
2) Generate some log and traffic: `httperf --server <server ip> --port <nginx port> --num-conns 1000 --rate 10 --hog`
3) Scale up and down. I used a simple bash script resulting in this with 5 second delays between each:
```
my-web scaled to 8
my-web scaled to 17
my-web scaled to 7
```
4) Get log-lines while doing this.  `docker service logs my-web | wc -l`

**Describe the results you received:**
```
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
589
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
623
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
error from daemon in stream: Error grabbing logs: rpc error: code = 2 desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = 13 desc = grpc: failed to unmarshal the received message proto: illegal wireType 7

661
ubuntu@manager-project2:~$ docker service logs my-web | wc -l
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0xd45620, 0xc4203bd300)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
strings.Repeat(0xe44138, 0x1, 0xffffffffffffffff, 0xc4203bd2f0, 0xd)
	/usr/local/go/src/strings/strings.go:420 +0x49
github.com/docker/docker/cli/command/service.(*taskFormatter).format(0xc420451260, 0x7fe81f680028, 0xc420012258, 0xc42046a019, 0x19, 0xc42046a04f, 0x19, 0xc42046a082, 0x19, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:204 +0x4d5
github.com/docker/docker/cli/command/service.(*logWriter).Write(0xc420451290, 0xc42045e008, 0xf9, 0x8001, 0x404, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:243 +0x392
github.com/docker/docker/pkg/stdcopy.StdCopy(0x15158e0, 0xc420451290, 0x15158e0, 0xc4204512c0, 0x1516ca0, 0xc42045c080, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/stdcopy/stdcopy.go:174 +0x36f
github.com/docker/docker/cli/command/service.runLogs(0xc4203b37a0, 0xc42037b340, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:147 +0x70e
github.com/docker/docker/cli/command/service.newLogsCommand.func1(0xc4203fb680, 0xc420436280, 0x1, 0x1, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/command/service/logs.go:50 +0x6d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203fb680, 0xc42000c1f0, 0x1, 0x1, 0xc4203fb680, 0xc42000c1f0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x26d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42007fd40, 0xc4203b6240, 0xc42035bef0, 0xc4200264c8)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x377
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42007fd40, 0xc42007fd40, 0x1517260)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/usr/src/docker/.gopath/src/github.com/docker/docker/cmd/docker/docker.go:169 +0xcb

```

**Describe the results you expected:**
The log to just increase, and not bug up. Doing the same without scaling down has no issues.

Output of `docker version`:
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Comment by dperny** [comment]
Hi, @JonasKs. You're in the right place. The problem you are having is real and may be related to. However, could you open a new issue with the contents of that report, so I can track your problem separately from this one? Also, when you open your issue, can you include the contents of `docker info` as well?

**Comment by JonasKs** [comment]
Hi, @dperny. Glad to hear! 
I will do that tomorrow morning and tag you in it. Thanks!

**Comment by aaronlehmann** [comment]
Should we target a fix for 17.06?

**Comment by thaJeztah** [comment]
Looks like this is duplicated now by https://github.com/moby/moby/issues/33222 - which one do you prefer to close @dperny ?

**Comment by thaJeztah** [comment]
@aaronlehmann looks like this one can be closed as well?

**Comment by aaronlehmann** [comment]
@dperny told me it's still outstanding.

**Comment by dgaikwad** [comment]
I was also facing the same issue but my issue is resolved after restarting the swarm.
