### ISSUE TITLE
Joining a cluster with wrong certificate hides error

### ISSUE THREAD

**Issue by aaronlehmann** [moby/moby#33380]
I tried prepopulating self-signed certificates in `/var/lib/docker/swarm` and then trying to join a different swarm cluster. The `join` command waited for awhile, and I saw the agent trying to reconnect over and over in the daemon logs:

```
DEBU[0020] loaded node credentials                       module="node/tls" node.id=ly2go2wiow3bgab5ebs2wb62v node.role=swarm-manager
DEBU[0020] next certificate renewal scheduled for 1421h23m36.546149707s from now  module="node/tls" node.id=ly2go2wiow3bgab5ebs2wb62v node.role=swarm-manager time=2017-07-22 22:59:00.00000025 +0000 UTC
INFO[0020] Listening for connections                     addr="[::]:2377" module=node node.id=ly2go2wiow3bgab5ebs2wb62v proto=tcp
INFO[0020] Listening for local connections               addr="/var/run/docker/swarm/control.sock" module=node node.id=ly2go2wiow3bgab5ebs2wb62v proto=unix
DEBU[0020] (*Agent).run                                  module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
INFO[0020] Stopping manager                              module=node node.id=ly2go2wiow3bgab5ebs2wb62v
DEBU[0020] (*session).start                              module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
ERRO[0020] agent: session failed                         error="rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"x509: ECDSA verification failure\\\" while trying to verify candidate authority certificate \\\"swarm-ca\\\")\"" module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
DEBU[0020] agent: rebuild session                        module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
DEBU[0020] (*session).start                              module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
ERRO[0020] agent: session failed                         error="rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"x509: ECDSA verification failure\\\" while trying to verify candidate authority certificate \\\"swarm-ca\\\")\"" module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
DEBU[0020] agent: rebuild session                        module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
DEBU[0021] (*session).start                              module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
ERRO[0021] agent: session failed                         error="rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"x509: ECDSA verification failure\\\" while trying to verify candidate authority certificate \\\"swarm-ca\\\")\"" module="node/agent" node.id=ly2go2wiow3bgab5ebs2wb62v
```

The join command eventually returned:

```
Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.
```

I would expect the join to fail right away, and expose the certificate error, instead of continuing to retry in the background. I believe we're propagating the error for expired certificates, but apparently not for certificate verification failures.

However, this might be tricky to get right, because we don't necessarily want to shutdown the node that was already part of a cluster if the agent gets a certificate verification failure. We might need to add something to the `join` process that verifies the certificate before setting up a `Node`.

Also, when I shut down the joining daemon while it was in this state, it gave me a stack trace:

```
goroutine 1 [running]:
github.com/docker/docker/pkg/signal.DumpStacks(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/signal/trap.go:82 +0xd9
github.com/docker/docker/daemon/cluster.(*Cluster).Cleanup(0xc4207be7e0)
        /go/src/github.com/docker/docker/daemon/cluster/cluster.go:378 +0x1c0
main.(*DaemonCli).start(0xc420428c00, 0x0, 0x1ab79d5, 0x17, 0xc42035f200, 0xc4204170c0, 0xc4200d1290, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:290 +0x1bed
main.runDaemon(0x0, 0x1ab79d5, 0x17, 0xc42035f200, 0xc4204170c0, 0xc4200d1290, 0x1, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:91 +0x8c
main.newDaemonCommand.func1(0xc420325d40, 0xc420423050, 0x0, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6f
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc420325d40, 0xc42000c1b0, 0x1, 0x1, 0xc420325d40, 0xc42000c1b0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420325d40, 0x18646a0, 0x1, 0xc420422fe0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420325d40, 0xc420422fe0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:118 +0xe6

...

goroutine 189 [chan receive, 1 minutes]:
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).Stop(0xc4202e6480, 0x7f2897a33128, 0xc420772f60, 0xc42004dc00)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:570 +0x125
github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).runManager.func2(0xc4201c2e10, 0xc4202e6480, 0x7f2897a33128, 0xc420772f60, 0xc42004dccf, 0xc4201dd740)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:856 +0x8f
github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).runManager(0xc4201c2e10, 0x7f2897a33128, 0xc420772f60, 0xc42036d4a0, 0xc42084f140, 0x34, 0xc42084f180, 0x34, 0xc42036d6e0, 0xc42036db60, ...)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:873 +0x921
github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).superviseManager(0xc4201c2e10, 0x7f2897a33128, 0xc420772f60, 0xc42036d4a0, 0xc42084f140, 0x34, 0xc42084f180, 0x34, 0xc42036d6e0, 0xc420772ed0, ...)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:900 +0x1a3
github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).run.func5(0xc420751990, 0xc4201c2e10, 0x7f2897a33128, 0xc420772f60, 0xc42036d4a0, 0xc42084f1c0, 0xc42036d6e0, 0xc420772ed0, 0xc420751910, 0xc4207c2d60)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:404 +0x9c
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).run
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:407 +0x951
```

It appears to be blocked on trying to shut down a `Manager` that was never started. Looks like the manager's `Run` returned an error before closing `started` (probably propagating an error from `JoinAndStart`).

cc @cyli

**Comment by aaronlehmann** [comment]
https://github.com/docker/swarmkit/pull/2203 is a fix for the hang shown in the stack trace. I think this will fix the case where a node with a manager certificate tries to join a cluster with a certificate it can't verify - the manager will error out, and this error causes the whole `Node` to shut down. However, I think if it starts with a worker certificate, it would still have the same problem described above, as the agent would keep retrying.

**Comment by cyli** [comment]
https://github.com/docker/swarmkit/pull/2206 is an attempt to make the join fail early if there is an x509 error.

**Comment by aaronlehmann** [comment]
Closing because docker/swarmkit#2206 has been merged and vendored.
