### ISSUE TITLE
test_prune_images failing with recent docker-py

### ISSUE THREAD

**Issue by alfred-landrum** [moby/moby#33407]
Here are a few PR's that want to update to a recent docker-py commit, but are blocked because the experimental jenkins test is failing in test_prune_images:
https://github.com/moby/moby/pull/33005
https://github.com/moby/moby/pull/32122

Here's an example console log of a test failure:
https://jenkins.dockerproject.org/job/Docker-PRs-experimental/34249/console

I've been able to reproduce the issue locally, but am still determining how to pull the relevant logs, will post them soon.

**Comment by alfred-landrum** [comment]
Running the experimental tests with just `hack/make.sh` will repro, but doing something more specific, like `hack/make.sh binary-daemon test-docker-py` will not.

Here's the exact command I use to repro:
```docker run --rm -t --privileged -v `pwd`/bundles:/go/src/github.com/docker/docker/bundles -e DOCKER_EXPERIMENTAL=y --name docker-pr-exp1 -e DOCKER_GITCOMMIT=92ff2ca49ca93412e280613da2708fe4d4d95bd1 -e DOCKER_GRAPHDRIVER=vfs -e DOCKER_EXECDRIVER=native docker:92ff2ca49ca93412e280613da2708fe4d4d95bd1-exp hack/make.sh```

which unfortunately takes a bit of time.

**Comment by thaJeztah** [comment]
ping @shin- @vdemeester

**Comment by shin-** [comment]
This test runs regularly in the `docker-py` CI against recent (edge) releases without any issue, which to me suggests this is potentially a regression.

**Comment by alfred-landrum** [comment]
I can repro this via:
```docker run [... as above] hack/make.sh binary-daemon .integration-daemon-start  .integration-daemon-setup .integration-daemon-stop test-docker-py```

`.integration-daemon-setup` runs  `.ensure-emptyfs`, which manually creates an image, which seems to be causing the problem.

**Comment by alfred-landrum** [comment]
```
May 26 19:30:44 vagrant dockerd[11416]: http: panic serving @: runtime error: invalid memory address or nil pointer dereference
                                        goroutine 31738 [running]:
                                        net/http.(*conn).serve.func1(0xc420efc500)
                                                /usr/local/go/src/net/http/server.go:1721 +0xd0
                                        panic(0x183ca80, 0x26bb150)
                                                /usr/local/go/src/runtime/panic.go:489 +0x2cf
                                        github.com/docker/docker/daemon.(*Daemon).ImagesPrune(0xc42007e480, 0x7f4e874be980, 0xc420fa2080, 0xc4214041b0, 0x0, 0x0, 0x0)
                                                /go/src/github.com/docker/docker/daemon/prune.go:219 +0x509
                                        github.com/docker/docker/api/server/router/image.(*imageRouter).postImagesPrune(0xc420d88140, 0x7f4e874be980, 0xc420fa2080, 0x26fbce0, 0xc420d94460, 0xc4202e1800, 0xc421404030, 0xc420148700, 0xab7a4e)
                                                /go/src/github.com/docker/docker/api/server/router/image/image_routes.go:336 +0xb0
                                        github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/docker/docker/api/server/router/image.postImagesPrune)-fm(0x7f4e874be980, 0xc420fa2080, 0x26fbce0, 0xc420d94460, 0xc4202e1800, 0xc421404030, 0x13, 0xc420148770)
                                                /go/src/github.com/docker/docker/api/server/router/image/image.go:46 +0x69
                                        github.com/docker/docker/api/server/router.cancellableHandler.func1(0x7f4e88667128, 0xc4214040f0, 0x26fbce0, 0xc420d94460, 0xc4202e1800, 0xc421404030, 0x0, 0x0)
                                                /go/src/github.com/docker/docker/api/server/router/local.go:92 +0xda
                                        github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f4e88667128, 0xc4214040f0, 0x26fbce0, 0xc420d94460, 0xc4202e1800, 0xc421404030, 0x7f4e88667128, 0xc4214040f0)
                                                /go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
                                        github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f4e88667128, 0xc4214040c0, 0x26fbce0, 0xc420d94460, 0xc4202e1800, 0xc421404030, 0xc420fa2040, 0xc420148a00)
                                                /go/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d
                                        github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f4e88667128, 0xc4214040c0, 0x26fbce0, 0xc420d94460, 0xc4202e1800, 0xc421404030, 0x7f4e88667128, 0xc4214040c0)
                                                /go/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x871
                                        github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x26fbce0, 0xc420d94460, 0xc4202e1800)
                                                /go/src/github.com/docker/docker/api/server/server.go:139 +0x21a
                                        net/http.HandlerFunc.ServeHTTP(0xc420ed2420, 0x26fbce0, 0xc420d94460, 0xc4202e1800)
                                                /usr/local/go/src/net/http/server.go:1942 +0x44
                                        github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420d86280, 0x26fbce0, 0xc420d94460, 0xc4202e1800)
                                                /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
                                        github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4209c88f0, 0x26fbce0, 0xc420d94460, 0xc4202e1800)
                                                /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
                                        net/http.serverHandler.ServeHTTP(0xc4200902c0, 0x26fbce0, 0xc420d94460, 0xc4202e1800)
                                                /usr/local/go/src/net/http/server.go:2568 +0x92
                                        net/http.(*conn).serve(0xc420efc500, 0x26fd860, 0xc4214e1d80)
                                                /usr/local/go/src/net/http/server.go:1825 +0x612
                                        created by net/http.(*Server).Serve
                                                /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by AkihiroSuda** [comment]
merged #33409

can we close this?

**Comment by vdemeester** [comment]
I think we can, right @alfred-landrum ?

**Comment by alfred-landrum** [comment]
yes, thanks everyone!
