### ISSUE TITLE
flaky tests: docker-py: ServiceTest.test_create_service_with_secret

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#33863]
Seen failing frequently;

```
09:33:46 =================================== FAILURES ===================================
09:33:46 _________________ ServiceTest.test_create_service_with_secret __________________
09:33:46 /docker-py/tests/integration/api_service_test.py:429: in test_create_service_with_secret
09:33:46     container = self.get_service_container(name)
09:33:46 /docker-py/tests/integration/api_service_test.py:41: in get_service_container
09:33:46     all=include_stopped
09:33:46 /docker-py/docker/api/container.py:189: in containers
09:33:46     res = self._result(self._get(u, params=params), True)
09:33:46 /docker-py/docker/utils/decorators.py:46: in inner
09:33:46     return f(self, *args, **kwargs)
09:33:46 /docker-py/docker/api/client.py:183: in _get
09:33:46     return self.get(url, **self._set_request_timeout(kwargs))
09:33:46 /usr/lib/python2.7/dist-packages/requests/sessions.py:469: in get
09:33:46     return self.request('GET', url, **kwargs)
09:33:46 /usr/lib/python2.7/dist-packages/requests/sessions.py:457: in request
09:33:46     resp = self.send(prep, **send_kwargs)
09:33:46 /usr/lib/python2.7/dist-packages/requests/sessions.py:569: in send
09:33:46     r = adapter.send(request, **kwargs)
09:33:46 /usr/lib/python2.7/dist-packages/requests/adapters.py:407: in send
09:33:46     raise ConnectionError(err, request=request)
09:33:46 E   ConnectionError: ('Connection aborted.', BadStatusLine("''",))
09:33:46 ========= 1 failed, 243 passed, 9 skipped, 3 xfailed in 391.56 seconds =========
```

e.g., https://jenkins.dockerproject.org/job/Docker-PRs/43957/console (https://github.com/moby/moby/pull/33860)

**Comment by aaronlehmann** [comment]
```
DEBU[0768] Calling GET /v1.26/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22name%22%3A+%5B%22dockerpytest_994d0616ded4c31c%22%5D%7D&size=0
2017-06-29 21:42:40.847283 I | http: panic serving @: interface conversion: interface {} is nil, not *container.Container
goroutine 9936 [running]:
net/http.(*conn).serve.func1(0xc420fc4280)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x18ca1a0, 0xc4208e0700)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/docker/docker/container.(*memdbView).Get(0xc421561eb0, 0xc420343d40, 0x40, 0xc420418a80, 0x0, 0x1)
	/go/src/github.com/docker/docker/container/view.go:137 +0x176
github.com/docker/docker/daemon.(*Daemon).filterByNameIDMatches(0xc4203301e0, 0x27c00c0, 0xc421561eb0, 0xc4209671f0, 0xc4209671f0, 0x0, 0x0, 0x4784d3, 0xc42103e2f8)
	/go/src/github.com/docker/docker/daemon/list.go:164 +0x490
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc4203301e0, 0xc4208e05c0, 0xc421b77510, 0x40, 0xffffffffffffffff, 0x0, 0x0, 0xffffffffffffffff)
	/go/src/github.com/docker/docker/daemon/list.go:195 +0x102
github.com/docker/docker/daemon.(*Daemon).Containers(0xc4203301e0, 0xc4208e05c0, 0xffffffffffffffff, 0x0, 0x0, 0xc421b77588, 0x412108)
	/go/src/github.com/docker/docker/daemon/list.go:114 +0x5d
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc42020b200, 0x7f178859c000, 0xc420852a50, 0x27cfe80, 0xc4201470a0, 0xc420068700, 0xc4208529c0, 0x1b1fccf, 0x5)
	/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x20f
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f178859c000, 0xc420852a50, 0x27cfe80, 0xc4201470a0, 0xc420068700, 0xc4208529c0, 0x7f178859c000, 0xc420852a50)
	/go/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f178859c000, 0xc420852a50, 0x27cfe80, 0xc4201470a0, 0xc420068700, 0xc4208529c0, 0x7f178859c000, 0xc420852a50)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f178859c000, 0xc420852a20, 0x27cfe80, 0xc4201470a0, 0xc420068700, 0xc4208529c0, 0x8a, 0xc42103e3f0)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f178859c000, 0xc420852a20, 0x27cfe80, 0xc4201470a0, 0xc420068700, 0xc4208529c0, 0xc421b77ab0, 0x756ea10f7c4020)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x871
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f178859c000, 0xc420852a20, 0x27cfe80, 0xc4201470a0, 0xc420068700, 0xc4208529c0, 0x7f178859c000, 0xc420852a20)
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:22 +0x180
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x27cfe80, 0xc4201470a0, 0xc420068700)
	/go/src/github.com/docker/docker/api/server/server.go:139 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc42088adc0, 0x27cfe80, 0xc4201470a0, 0xc420068700)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4204c7ef0, 0x27cfe80, 0xc4201470a0, 0xc420068700)
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420826270, 0x27cfe80, 0xc4201470a0, 0xc420068700)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420137550, 0x27cfe80, 0xc4201470a0, 0xc420068700)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420fc4280, 0x27d1a40, 0xc421ca8e00)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by aaronlehmann** [comment]
ping @fabiokung

**Comment by aaronlehmann** [comment]
I think the problem is that `(*memDB).Get` expects `v.txn.First` to return an error if an entry with that ID doesn't exist in the database, but instead it just returns `nil`.

**Comment by aaronlehmann** [comment]
#33882 avoids the panic and causes the test to fail in this way instead:

```
/docker-py/tests/integration/api_service_test.py:454: in test_create_service_with_unicode_secret
    container = self.get_service_container(name)
/docker-py/tests/integration/api_service_test.py:41: in get_service_container
    all=include_stopped
/docker-py/docker/api/container.py:189: in containers
    res = self._result(self._get(u, params=params), True)
/docker-py/docker/api/client.py:220: in _result
    self._raise_for_status(response)
/docker-py/docker/api/client.py:216: in _raise_for_status
    raise create_api_error_from_http_exception(e)
/docker-py/docker/errors.py:31: in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
E   NotFound: 404 Client Error: Not Found ("no such container 050224bd46a04143132fac672514ae4f4c4b2e7147c6a8a4757ecc271c427f9f")
```

Not a complete solution, since the test is still failing, but hopefully this will help track down the actual problem.

**Comment by aaronlehmann** [comment]
Looks like the issue is that `(*Daemon).foldFilter` calls `daemon.nameIndex.GetAll()` to get a map from IDs to names, and this data can be out of sync with the `view`. So when we try to look up one of these IDs in the `view`, it may not exist there, and this raises an error that gets propagated back to the user.

**Comment by aaronlehmann** [comment]
The code before #31273 handled this situation by ignoring containers that couldn't be looked up. I'll submit a PR to restore this behavior.

**Comment by fabiokung** [comment]
@aaronlehmann good catch! I wonder if there's a way to force the same `nameIndex` that has been snapshotted in `(*Daemon).foldFilter`, or delay the snapshot to that point, and avoid the out-of-sync issue.

**Comment by fabiokung** [comment]
e.g.: `(*Daemon).foldFilter` could call `view.Names()`, instead of `daemon.nameIndex.GetAll()`.

**Comment by aaronlehmann** [comment]
I think adding a name index to the memdb would be doable (this is what you're suggesting, right)? It's probably the best solution from a design perspective. On the other hand, this only affects listing containers, and I'm not sure that really needs atomicity. If a container is removed during while the listing is running, it seems reasonable not to include that container in the output. I'm not sure if I'm missing something though.

**Comment by fabiokung** [comment]
It already has one! PR incoming.

**Comment by fabiokung** [comment]
@aaronlehmann after brief discussion on #33885, I think I agree with you that not including missing containers in the result is a simpler fix.

That together with at least not calling `daemon.nameIndex.GetAll()` again in `foldFilter` LGTM.

A followup of properly snapshotting the Registrar would be nice, but it shouldn't be a blocker IMO.
