### ISSUE TITLE
panic: slice bounds out of range in 1.12.6 logging(?)

### ISSUE THREAD

**Issue by matthiasr** [moby/moby#33961]
**Description**

A docker daemon at version 1.12.6 (the last version supported by Kubernetes) panicked during normal operations.

**Steps to reproduce the issue:**
1. run docker daemon
2. ???
3. panic

**Describe the results you received:**

```
Jul 05 13:52:13 <redacted> docker[545]: time="2017-07-05T13:52:13.56427084Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:31af647586ebc1509c7d4a9a8eea2b545aee8db2699b866f8b91cd52baa9610b (pid 5624) has become an orphan, killing it"
Jul 05 13:52:43 <redacted> docker[545]: time="2017-07-05T13:52:43.510397Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:0fe701d0ab9cae3d8568d6814ee32958a776c6f7e420db6f7c92a1d83802e564 starttime: open /proc/7042/stat: no such file or directory"
Jul 05 13:52:43 <redacted> docker[545]: time="2017-07-05T13:52:43.510798083Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:0fe701d0ab9cae3d8568d6814ee32958a776c6f7e420db6f7c92a1d83802e564 (pid 7042) has become an orphan, killing it"
Jul 05 13:53:23 <redacted> docker[545]: time="2017-07-05T13:53:23.51094142Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:7070a9a1b224892025f0503850d30203162d152a174bea27f0adb08d80326533 starttime: open /proc/8698/stat: no such file or directory"
Jul 05 13:53:23 <redacted> docker[545]: time="2017-07-05T13:53:23.511277159Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:7070a9a1b224892025f0503850d30203162d152a174bea27f0adb08d80326533 (pid 8698) has become an orphan, killing it"
Jul 05 13:54:33 <redacted> docker[545]: time="2017-07-05T13:54:33.50999283Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:2acdce4ae32f334b6bf48adf6002192e63128eb2c205225103d4c4531f044968 starttime: open /proc/12051/stat: no such file or directory"
Jul 05 13:54:33 <redacted> docker[545]: time="2017-07-05T13:54:33.510364004Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:2acdce4ae32f334b6bf48adf6002192e63128eb2c205225103d4c4531f044968 (pid 12051) has become an orphan, killing it"
Jul 05 13:55:23 <redacted> docker[545]: time="2017-07-05T13:55:23.513343626Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:362ec9e16d79523bd1308d67961147178f23627049018f2920bd1c8605c4b636 starttime: open /proc/13869/stat: no such file or directory"
Jul 05 13:55:23 <redacted> docker[545]: time="2017-07-05T13:55:23.513670055Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:362ec9e16d79523bd1308d67961147178f23627049018f2920bd1c8605c4b636 (pid 13869) has become an orphan, killing it"
Jul 05 13:56:13 <redacted> docker[545]: time="2017-07-05T13:56:13.509352511Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:f64053abcda1396c952e9c7a72f2ad0552990632e658d65597e9e4fbff1c0916 starttime: open /proc/15916/stat: no such file or directory"
Jul 05 13:56:13 <redacted> docker[545]: time="2017-07-05T13:56:13.509685436Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:f64053abcda1396c952e9c7a72f2ad0552990632e658d65597e9e4fbff1c0916 (pid 15916) has become an orphan, killing it"
Jul 05 13:56:33 <redacted> docker[545]: time="2017-07-05T13:56:33.511141408Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:fe3646c8308d886a3344f0a0064a2d452823a0b40862c3686c907443208bc64f starttime: open /proc/16692/stat: no such file or directory"
Jul 05 13:56:33 <redacted> docker[545]: time="2017-07-05T13:56:33.511468477Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:fe3646c8308d886a3344f0a0064a2d452823a0b40862c3686c907443208bc64f (pid 16692) has become an orphan, killing it"
Jul 05 13:56:53 <redacted> docker[545]: time="2017-07-05T13:56:53.509433093Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:bb466d1463052e10442efd9d4759ea24a6294f927559e532a25dc05f3ef80b63 starttime: open /proc/17547/stat: no such file or directory"
Jul 05 13:56:53 <redacted> docker[545]: time="2017-07-05T13:56:53.50975292Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:bb466d1463052e10442efd9d4759ea24a6294f927559e532a25dc05f3ef80b63 (pid 17547) has become an orphan, killing it"
Jul 05 13:57:03 <redacted> docker[545]: time="2017-07-05T13:57:03.509870747Z" level=warning msg="containerd: unable to save a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:f55f64379c9eb4421b749074b65cc64b2e641e896544bc7b5db76b091148f712 starttime: open /proc/17898/stat: no such file or directory"
Jul 05 13:57:03 <redacted> docker[545]: time="2017-07-05T13:57:03.510218422Z" level=info msg="containerd: a112360b27e0044d692e096558ae43506a863d58b87b9f21ef6f3f72d88d8c28:f55f64379c9eb4421b749074b65cc64b2e641e896544bc7b5db76b091148f712 (pid 17898) has become an orphan, killing it"
Jul 05 13:57:10 <redacted> docker[545]: panic: runtime error: slice bounds out of range
Jul 05 13:57:10 <redacted> docker[545]: goroutine 943 [running]:
Jul 05 13:57:10 <redacted> docker[545]: panic(0x1a7ca00, 0xc82000e050)
Jul 05 13:57:10 <redacted> docker[545]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Jul 05 13:57:10 <redacted> docker[545]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc821615d00, 0xc82162a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Jul 05 13:57:10 <redacted> docker[545]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:144 +0x459
Jul 05 13:57:10 <redacted> docker[545]: bufio.(*Reader).fill(0xc820053ed0)
Jul 05 13:57:10 <redacted> docker[545]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Jul 05 13:57:10 <redacted> docker[545]: bufio.(*Reader).ReadSlice(0xc820053ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 05 13:57:10 <redacted> docker[545]: /usr/local/go/src/bufio/bufio.go:328 +0x21a
Jul 05 13:57:10 <redacted> docker[545]: bufio.(*Reader).ReadBytes(0xc820053ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 05 13:57:10 <redacted> docker[545]: /usr/local/go/src/bufio/bufio.go:406 +0xa9
Jul 05 13:57:10 <redacted> docker[545]: github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc821615dc0, 0x1d64a18, 0x6, 0x7fa8dcf77988, 0xc821615d00)
Jul 05 13:57:10 <redacted> docker[545]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:50 +0x14a
Jul 05 13:57:10 <redacted> docker[545]: created by github.com/docker/docker/daemon/logger.(*Copier).Run
Jul 05 13:57:10 <redacted> docker[545]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:37 +0x12b
Jul 05 13:57:10 <redacted> systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 05 13:57:10 <redacted> systemd[1]: Unit docker.service entered failed state.
Jul 05 14:15:45 <redacted> systemd[1]: Starting Docker Application Container Engine...
Jul 05 14:15:45 <redacted> docker[2731]: time="2017-07-05T14:15:45.570224178Z" level=info msg="libcontainerd: new containerd process, pid: 2742"
Jul 05 14:15:45 <redacted> docker[2731]: time="2017-07-05T14:15:45.595899044Z" level=error msg="containerd: notify OOM events" error="open /proc/31869/cgroup: no such file or directory"
Jul 05 14:15:45 <redacted> docker[2731]: time="2017-07-05T14:15:45.601151945Z" level=error msg="containerd: notify OOM events" error="open /proc/30746/cgroup: no such file or directory"
Jul 05 14:15:45 <redacted> docker[2731]: time="2017-07-05T14:15:45.624970452Z" level=error msg="containerd: notify OOM events" error="open /proc/32527/cgroup: no such file or directory"
Jul 05 14:15:45 <redacted> docker[2731]: time="2017-07-05T14:15:45.639604541Z" level=error msg="containerd: notify OOM events" error="open /proc/4563/cgroup: no such file or directory"
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.574944793Z" level=warning msg="libcontainerd: unknown container 2a2af449bdd3e1681d6e1ec66c97d038a30b08bacabead1532a5eea630aee915"
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.574998451Z" level=warning msg="libcontainerd: unknown container 4e87503249cd5b04497d767555b28c63006edd8526dffa7255518f995f57a610"
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.575025822Z" level=warning msg="libcontainerd: unknown container abc7cc22e5e0df2f7650d4c01ed1f152b369242afcefdf1eefde802c4966cb77"
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.575049307Z" level=warning msg="libcontainerd: unknown container d180a004c5a1e265656a5743a73882026bea80b6cdbc38293d15f910c3b6ba43"
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.583677223Z" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.624568662Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 05 14:15:46 <redacted> docker[2731]: time="2017-07-05T14:15:46.625380122Z" level=info msg="Loading containers: start."
```

**Describe the results you expected:**

no crash

**Additional information you deem important (e.g. issue happens only occasionally):**

can't say anything about how often this happens yet. it occurred within 24h of starting a wide range of upgrades from 1.10 (via full reinstall, so not carrying over old container state). this is while using Docker as a runtime for Kubernetes 1.5.5, so "try the latest version" is not an option I'm afraid.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64```

**Output of `docker info`:**

```
Containers: 76
 Running: 62
 Paused: 0
 Stopped: 14
Images: 49
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 328
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.10.15+soundcloud
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.88 GiB
Name: <redacted>
ID: AUQY:Z5TN:T6V7:5JPS:RQCJ:ZESD:L4UU:5X5N:VS67:RTB6:2I3J:CVI4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical, Kubernetes bridge networking (pod networks natively routed)

**Comment by thaJeztah** [comment]
Docker 1.12 reached end of life in March, and is no longer maintained. Note that it's actually the _API version_ that would be relevant for kubernetes; every Docker release supports older API versions, so even a (e.g.) Docker 17.09 daemon supports the API version that's in use by Docker 1.12 (API version 1.24; https://docs.docker.com/develop/sdk/#api-version-matrix)

I'm closing this issue because of the above, but feel free to discuss
