### ISSUE TITLE
Running any container causes [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x457888]

### ISSUE THREAD

**Issue by anydoby** [moby/moby#33975]
**Description**

I am on a virtual machine with RedHat Enterprise 7.3 installed. After docker installation everything worked fine until a certain moment when the following started to happen.

Running any container will fail with the following stack trace:

```
docker run hello-world
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x457888]

goroutine 1 [running]:
github.com/docker/cli/cli/command/container.runContainer(0xc4201db9e0, 0xc4203c4120, 0xc420399900, 0xc42043a180, 0x1583760, 0xc4200f40e0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:171 +0xa62
github.com/docker/cli/cli/command/container.runRun(0xc4201db9e0, 0xc4200894d0, 0xc4203c4120, 0xc420399900, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:94 +0x141
github.com/docker/cli/cli/command/container.NewRunCommand.func1(0xc4203b5d40, 0xc420426410, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/run.go:48 +0x109
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203b5d40, 0xc4200101d0, 0x1, 0x1, 0xc4203b5d40, 0xc4200101d0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420368480, 0xc420368900, 0xc42033fff0, 0xc42000e4b8)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420368480, 0xc420368480, 0x1585760)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:168 +0xc3
```

**Steps to reproduce the issue:**
1. docker run &lt;anything&gt;

Building containers works though

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 84
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:6-583008320-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.666GB
 Data Space Total: 107.4GB
 Data Space Available: 97.71GB
 Metadata Space Used: 10.76MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.137GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: dev
ID: 6YKT:JELN:YKSV:EK3Q:KB4V:S2X4:B2SO:4EF2:YXBG:M4N5:RZEK:2R57
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: localhost:3128
No Proxy: localhost,127.0.0.1,*.ing.net
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The docker service runs in the private cloud (vRealize).

**Comment by AkihiroSuda** [comment]
https://github.com/docker/docker-ce/blob/17.06/components/cli/cli/command/container/run.go#L169

This `defer close()` should be called only when `close != nil`. Anyone interested in opening PR? (to https://github.com/docker/cli)

**Comment by yastij** [comment]
@AkihiroSuda - I'll take care of it

**Comment by AkihiroSuda** [comment]
@anydoby 
Please try latest docker/cli (just checkout https://github.com/docker/cli and do `make`)?
It would print some error instead of panic.

**Comment by anydoby** [comment]
Sure, will try it in a couple of hours.

**Comment by anydoby** [comment]
I cannot build it on the machine in question, for obvious reasons. So I did it on a mac (built linux binaries). 

How and what do I transfer to the linux machine to test it?

**Comment by AkihiroSuda** [comment]
`build/docker-linux-amd64` (via SSH or whatever else)
