### ISSUE TITLE
docker daemon 1.13.1 hung: docker ps not responding.

### ISSUE THREAD

**Issue by shishir-a412ed** [moby/moby#33994]
Hi,

We are running `docker 1.13.1` in our production environment, where we containerize deep learning (DL) jobs using docker containers. Those jobs run on GPUs.

Recently we have been running into an issue, where docker daemon stop responding i.e. it gets hung.
`docker info` or `docker images` still respond back with the output. It's `docker ps` which goes into a hung state and never comes back. This leads me to believe (or a hunch) that something fishy is going on with `docker-containerd` 

This is not 100% reproducible and only occurs on rare occasions.
To give a brief summary of what I found:

1) `docker ps` not responding, however `docker info` or `docker images` still responding.
2) I did: `kill -SIGUSR1 $(pid of dockerd)
3) Populated the stack trace `goroutine-stacks-2017-07-06T130351-0700.log`
4) There is a `SemAcquire` call in stack trace where docker is probably acquiring a semaphore and not releasing it in `daemon/list.go`. On another node where docker daemon is running, and `docker ps` is responding, I don't see this in stack trace when I send `SIGUSR1` to docker daemon PID. I am guessing the semaphore is getting released properly on the other node.

Sem Acquire call in stack trace: https://pastebin.com/xQYupPHM
Complete Stack trace:
[goroutine-stacks-2017-07-06T130351-0700.txt](https://github.com/moby/moby/files/1129182/goroutine-stacks-2017-07-06T130351-0700.txt)

output of `docker info`

````
root@sc-sdgx-190:/tmp/stack_dump# docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 26
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 622
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: nvidia-docker ceph local nfs
 Network: bridge host macvlan null overlay
 Authorization: authz-broker
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 80
Total Memory: 503.8 GiB
Name: sc-sdgx-190
ID: LUCQ:5GZE:I3IM:V4I7:ERW6:KQJQ:LB37:Q64J:STBW:VNLV:4JZ7:D5R6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 1852
 Goroutines: 2020
 System Time: 2017-07-06T13:27:53.328526846-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
````

Output of `docker version`
````
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
````root@sc-sdgx-190:/tmp/stack_dump# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"


Linux OS:
````
root@sc-sdgx-190:/tmp/stack_dump# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
````

**Comment by shishir-a412ed** [comment]
Just to add `pstree -aps $(pid_of_docker)` displays a lot of `dockerd` instances running under `dockerd` itself.

````
init,1
  └─dockerd,3993 --raw-logs
      ├─docker-containe,4030 -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim ...
      │   ├─{docker-containe},4031
      │   ├─{docker-containe},4032
      │   ├─{docker-containe},4033
      │   ├─{docker-containe},4034
      │   ├─{docker-containe},4035
      │   ├─{docker-containe},4036
      │   ├─{docker-containe},4037
      │   ├─{docker-containe},4038
      │   ├─{docker-containe},4624
      │   ├─{docker-containe},4629
      │   ├─{docker-containe},7135
      │   ├─{docker-containe},7136
      │   ├─{docker-containe},7137
      │   ├─{docker-containe},7138
      │   ├─{docker-containe},7139
      │   ├─{docker-containe},8731
      │   ├─{docker-containe},8732
      │   ├─{docker-containe},10323
      │   ├─{docker-containe},10324
      │   ├─{docker-containe},11933
      │   ├─{docker-containe},11934
      │   ├─{docker-containe},13491
      │   ├─{docker-containe},13492
      │   ├─{docker-containe},15083
      │   ├─{docker-containe},15084
      │   ├─{docker-containe},16671
      │   ├─{docker-containe},16672
      │   ├─{docker-containe},18276
      │   ├─{docker-containe},18277
      │   ├─{docker-containe},19864
      │   ├─{docker-containe},19866
      │   ├─{docker-containe},21486
      │   ├─{docker-containe},21487
      │   ├─{docker-containe},23057
      │   ├─{docker-containe},23058
      │   ├─{docker-containe},24647
      │   ├─{docker-containe},24648
      │   ├─{docker-containe},80600
      │   ├─{docker-containe},80601
      │   ├─{docker-containe},11669
      │   ├─{docker-containe},16019
      │   ├─{docker-containe},16020
      │   ├─{docker-containe},19020
      │   ├─{docker-containe},19022
      │   ├─{docker-containe},25872
      │   └─{docker-containe},73505
      ├─{dockerd},4000
      ├─{dockerd},4001
      ├─{dockerd},4003
      ├─{dockerd},4004
      ├─{dockerd},4012
      ├─{dockerd},4022
      ├─{dockerd},4023
      ├─{dockerd},4024
      ├─{dockerd},4025
      ├─{dockerd},4026
      ├─{dockerd},4027
      ├─{dockerd},4028
      ├─{dockerd},4029
      ├─{dockerd},4043
      ├─{dockerd},4044
      ├─{dockerd},4045
      ├─{dockerd},4046
      ├─{dockerd},4051
      ├─{dockerd},4052
      ├─{dockerd},4053
      ├─{dockerd},4109
      ├─{dockerd},4110
      ├─{dockerd},4111
      ├─{dockerd},4112
      ├─{dockerd},4113
      ├─{dockerd},4114
      ├─{dockerd},4115
      ├─{dockerd},4129
      ├─{dockerd},4131
      ├─{dockerd},4132
      ├─{dockerd},4134
      ├─{dockerd},4135
      ├─{dockerd},4136
      ├─{dockerd},4137
      ├─{dockerd},4139
      ├─{dockerd},4382
      ├─{dockerd},4383
      ├─{dockerd},4384
      ├─{dockerd},4385
      ├─{dockerd},4386
      ├─{dockerd},4387
      ├─{dockerd},4388
      ├─{dockerd},4389
      ├─{dockerd},4390
      ├─{dockerd},38058
      ├─{dockerd},79920
      ├─{dockerd},79921
      ├─{dockerd},79922
      ├─{dockerd},79923
      ├─{dockerd},79924
      ├─{dockerd},79925
      ├─{dockerd},80001
      ├─{dockerd},80008
      ├─{dockerd},80812
      ├─{dockerd},1403
      ├─{dockerd},1404
      ├─{dockerd},1405
      ├─{dockerd},1406
      ├─{dockerd},1975
      ├─{dockerd},1976
      ├─{dockerd},2081
      ├─{dockerd},2082
      ├─{dockerd},2083
      ├─{dockerd},54738
      ├─{dockerd},60759
      ├─{dockerd},62039
      ├─{dockerd},68284
      ├─{dockerd},73967
      └─{dockerd},5076
````

**Comment by flx42** [comment]
I looked at the legacy plugin code recently, and I think there is no proper HTTP timeout in calls like `Activate` or `Create`. Therefore, I think this part of the stack trace could be the culprit:
```
goroutine 508479 [select, 5775 minutes]:
net/http.(*persistConn).roundTrip(0xc422bb6200, 0xc4229e4360, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc4201485a0, 0xc4217b3590, 0x2, 0x7f4d2add34b0, 0x0)
	/usr/local/go/src/net/http/transport.go:380 +0x4fa
github.com/docker/docker/pkg/plugins/transport.(*httpTransport).RoundTrip(0xc4202f6000, 0xc4217b3590, 0xc4202f6000, 0x0, 0xc400000000)
	<autogenerated>:3 +0x53
net/http.send(0xc4217b3590, 0x7f4d243f3b48, 0xc4202f6000, 0x0, 0x0, 0x0, 0x8, 0xc4203722f8, 0x423178)
	/usr/local/go/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc4202f6030, 0xc4217b3590, 0x0, 0x0, 0x0, 0xc4203722f8, 0x0, 0x1)
	/usr/local/go/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc4202f6030, 0xc4217b3590, 0x1a04960, 0x4, 0x59594e01, 0x35eb88a8)
	/usr/local/go/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc4202f6030, 0xc4217b3590, 0x2452ac0, 0x2411400, 0xc422d53dc0)
	/usr/local/go/src/net/http/client.go:187 +0x11d
github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0xc4203b4240, 0x18f2a2d, 0x10, 0x2411400, 0xc422d53dc0, 0x422901, 0xc423552700, 0x10, 0x10, 0x17185a0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/client.go:141 +0x10e
github.com/docker/docker/pkg/plugins.(*Client).Call(0xc4203b4240, 0x18f2a2d, 0x10, 0x17185a0, 0xc423552700, 0x15d3e60, 0xc4229e42e0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/client.go:94 +0x13d
github.com/docker/docker/volume/drivers.(*volumeDriverProxy).Get(0xc4203b69b0, 0xc423552220, 0xf, 0x4dcc2f, 0xc42000e280, 0x19393b9)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/drivers/proxy.go:204 +0x10c
github.com/docker/docker/volume/drivers.(*volumeDriverAdapter).Get(0xc420364090, 0xc423552220, 0xf, 0x2, 0x2, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/drivers/adapter.go:70 +0x47
github.com/docker/docker/volume/store.(*VolumeStore).create(0xc4202fb4a0, 0xc423552220, 0xf, 0xc4235521b8, 0x3, 0xc4223d0c90, 0xc4223d0d50, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/store.go:383 +0x371
github.com/docker/docker/volume/store.(*VolumeStore).CreateWithRef(0xc4202fb4a0, 0xc423552220, 0xf, 0xc4235521b8, 0x3, 0x0, 0x0, 0xc4223d0c90, 0xc4223d0d50, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/store.go:257 +0x136
github.com/docker/docker/volume/store.(*VolumeStore).Create(0xc4202fb4a0, 0xc423552220, 0xf, 0xc4235521b8, 0x3, 0xc4223d0c90, 0xc4223d0d50, 0xc4227cb4b8, 0x15bd920, 0xc4223d0c30, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/store.go:269 +0x8f
github.com/docker/docker/daemon.(*Daemon).VolumeCreate(0xc42048e800, 0xc423552220, 0xf, 0xc4235521b8, 0x3, 0xc4223d0c90, 0xc4223d0d50, 0xca51ba, 0x178e180, 0xc4223d0330)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:230 +0xae
github.com/docker/docker/api/server/router/volume.(*volumeRouter).postVolumesCreate(0xc420901f20, 0x242b4c0, 0xc4223d0600, 0x7f4d2ad91c50, 0xc4212cd200, 0xc421238870, 0xc42352f080, 0x18e044e, 0x5)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/volume/volume_routes.go:51 +0x1bc
github.com/docker/docker/api/server/router/volume.(*volumeRouter).(github.com/docker/docker/api/server/router/volume.postVolumesCreate)-fm(0x242b4c0, 0xc4223d0600, 0x7f4d2ad91c50, 0xc4212cd200, 0xc421238870, 0xc42352f080, 0x423178, 0x30)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/volume/volume.go:31 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x242b4c0, 0xc4223d0600, 0x7f4d2ad91c50, 0xc4212cd200, 0xc421238870, 0xc42352f080, 0x15, 0x40)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x242b4c0, 0xc42352f140, 0x7f4d2ad91c50, 0xc4212cd200, 0xc421238870, 0xc42352f080, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5ca
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x242b4c0, 0xc42352f140, 0x2427c00, 0xc4218c0000, 0xc421238870, 0xc42352f080, 0x0, 0xc4227cb998)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:69 +0x458
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x242b4c0, 0xc42352f140, 0x2427c00, 0xc4218c0000, 0xc421238870, 0xc42352f080, 0xc400000000, 0xc4214fb7a0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/debug.go:53 +0x5bb
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2427c00, 0xc4218c0000, 0xc421238870)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420bc7540, 0x2427c00, 0xc4218c0000, 0xc421238870)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202de6e0, 0x2427c00, 0xc4218c0000, 0xc421238870)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420d1f400, 0x2427c00, 0xc4218c0000, 0xc421238870)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420081880, 0x2427c00, 0xc4218c0000, 0xc421238870)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4235fa600, 0x2429840, 0xc421806540)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```
As a result of an unresponsive legacy volume plugin, the daemon could hang.

You can see that `NewClient` is used instead of `NewClientWithTimeout` in legacy plugins:
https://github.com/moby/moby/blob/v1.13.1/pkg/plugins/plugins.go#L155

On the contrary, it looks like the new plugin API is correctly using `NewClientWithTimeout`:
https://github.com/moby/moby/blob/v17.03.2-ce/plugin/manager_linux.go#L80

Maybe @anusha-ragunathan can help, but then maybe this stack trace is a red herring too.

**Comment by shishir-a412ed** [comment]
@flx42 Why would an unresponsive volume plugin result into `docker ps` not responding?
May be I am missing something :) but I don't see the connection.

Shishir

**Comment by flx42** [comment]
Because it has happened multiple times from my experience. For instance, the docker daemon can become very slow even after a volume plugin is removed, if said plugin still has an entry in `volumes/metadata.db` cache.

**Comment by flx42** [comment]
I did a quick test. When removing a container that mounted a volume from a legacy volume plugin, the docker daemon will call entrypoint `/VolumeDriver.Unmount` of this volume plugin. If the plugin hangs during this call, the docker daemon will be blocked too, because there is no timeout on the plugin calls.
Calls such as `docker rm` or `docker ps` will therefore hang.

**Comment by mlaventure** [comment]
@flx42 is correct, this is due to an unresponsive volume plugin.

The daemon is stuck waiting for a volume plugin to unmount a volume attached to a container:

```
goroutine 509921 [select, 4409 minutes]:
net/http.(*persistConn).roundTrip(0xc422bb7200, 0xc42285fc00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc4201485a0, 0xc42335e780, 0x2, 0x7f4d2add34b0, 0x0)
	/usr/local/go/src/net/http/transport.go:380 +0x4fa
github.com/docker/docker/pkg/plugins/transport.(*httpTransport).RoundTrip(0xc4202f6000, 0xc42335e780, 0xc4202f6000, 0x0, 0xc400000000)
	<autogenerated>:3 +0x53
net/http.send(0xc42335e780, 0x7f4d243f3b48, 0xc4202f6000, 0x0, 0x0, 0x0, 0x8, 0xc420372bd0, 0x423178)
	/usr/local/go/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc4202f6030, 0xc42335e780, 0x0, 0x0, 0x0, 0xc420372bd0, 0x0, 0x1)
	/usr/local/go/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc4202f6030, 0xc42335e780, 0x1a04960, 0x4, 0x595a8e01, 0x87e6b7c)
	/usr/local/go/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc4202f6030, 0xc42335e780, 0x2452ac0, 0x2411400, 0xc4230e9570)
	/usr/local/go/src/net/http/client.go:187 +0x11d
github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0xc4203b4240, 0x18fbf0b, 0x14, 0x2411400, 0xc4230e9570, 0x422901, 0xc42285fb60, 0x20, 0x20, 0x1756f00)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/client.go:141 +0x10e
github.com/docker/docker/pkg/plugins.(*Client).Call(0xc4203b4240, 0x18fbf0b, 0x14, 0x1756f00, 0xc42285fb60, 0x15d40e0, 0xc4216ea270, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/client.go:94 +0x13d
github.com/docker/docker/volume/drivers.(*volumeDriverProxy).Unmount(0xc4203b69b0, 0xc423465a70, 0xf, 0xc42124a600, 0x40, 0x10, 0xc4227ea8b0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/drivers/proxy.go:150 +0x121
github.com/docker/docker/volume/drivers.(*volumeAdapter).Unmount(0xc42351a320, 0xc42124a600, 0x40, 0xc4227ea820, 0x2400ed0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/drivers/adapter.go:164 +0x54
github.com/docker/docker/volume/store.(*volumeWrapper).Unmount(0xc422b0f740, 0xc42124a600, 0x40, 0x7, 0xc421508360)
	<autogenerated>:6 +0x5d
github.com/docker/docker/container.(*Container).UnmountVolumes(0xc420b05800, 0xc422cb9b90, 0xc422cb9be0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:575 +0x123
github.com/docker/docker/daemon.(*Daemon).Cleanup(0xc42048e800, 0xc420b05800)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:225 +0x32b
github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc42048e800, 0xc42268b640, 0x40, 0xc42211cd40, 0x4, 0x8900000000, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:59 +0x573
github.com/docker/docker/libcontainerd.(*container).handleEvent.func1()
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_unix.go:217 +0x82
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc421a83d00, 0x0, 0xc42308aa50, 0xc42172fc80)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_unix.go:28 +0x30
created by github.com/docker/docker/libcontainerd.(*queue).append
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_unix.go:30 +0x170
```

It seems that the plugin accepted the connection but is stuck on something and not answering.

I think we need to use `Request.WithContext()` [there](https://github.com/moby/moby/blob/master/pkg/plugins/client.go#L141) so the timeout is also taken in account at this point. Actually, 1.13 is using go1.7.x so `Timeout` simply need to be set. This could cause partial body to be received though.

/cc @cpuguy83

**Comment by cpuguy83** [comment]
Having a timeout on the request here could be fairly dangerous since it may actually take more the specified timeout to unmount for some reason.

From a pure reporting perspective, starting in 17.07 this would not block `docker ps` anymore, however the actual issue is still present.

Since there's not much that can be done from docker's perspective, we could do these unmount calls async and not block the container.

**Comment by shishir-a412ed** [comment]
@cpuguy83 Are you talking about lockless containers in #30225 ?
I agree, having a timeout on the request would allow it to timeout before the `unmount` happens, and can leave the container with the volume still mounted. A user would run into other issues when running operations like `docker rm`.

**Comment by cpuguy83** [comment]
@shishir-a412ed More specifically #31273

**Comment by shishir-a412ed** [comment]
@cpuguy83 
Right that the implementation PR. First off hats off for this effort ! I personally saw a fair amount of `docker ps` issues upstream.
So with lockless containers, daemon won't hold a lock on the container while doing operations e.g. walking the container rootfs tree to compute the size for example. 
Same for our problem, plugin becoming unresponsive on `/VolumeDriver.Unmount` call won't block `docker ps` . Although it doesn't solve the actual problem on why the plugin went into an unresponsive state in the first place, but then that is not a daemon problem.

**Comment by shishir-a412ed** [comment]
We were able to dig deeper, and the problem was in `fscache`.
The plug-in `Unmount` call which unmounts the NFS Share was hung:

`umount.nfs` for one of the volumes was in D state.
root@sc-sdgx-226:~# ps aux | grep umount | grep D
root     59984  0.0  0.0  26292  3076 ?        D    Jul03   1:14 /sbin/umount.nfs /var/lib/docker-volumes/netshare/nfs/volume-305591-0

as it is waiting on fscache, so the unmount never completed.

root@sc-sdgx-226:~# cat /proc/59984/stack
[<ffffffffc034f1bf>] __fscache_wait_on_page_write+0x5f/0xa0 [fscache]
[<ffffffffc04104dc>] __nfs_fscache_invalidate_page+0x2c/0x80 [nfs]
[<ffffffffc03fb543>] nfs_invalidate_page+0x63/0x90 [nfs]
[<ffffffff811925c0>] truncate_inode_page+0x80/0x90
[<ffffffff811927a3>] truncate_inode_pages_range+0x193/0x6d0
[<ffffffff81192d4c>] truncate_inode_pages_final+0x4c/0x60
[<ffffffffc03fe4f9>] nfs_evict_inode+0x19/0x30 [nfs]
[<ffffffff8121820e>] evict+0xbe/0x1a0
[<ffffffff81218326>] dispose_list+0x36/0x50

Closing this one, since it is not a daemon issue.

**Comment by thaJeztah** [comment]
Thanks for the update @shishir-a412ed

**Comment by denis-ramani-hs** [comment]
We are also facing same issue in production and want to know what's solutions for it? Do we have to update the docker version from 1.12.1? Or just restarting service will solve the problem.

**Comment by thaJeztah** [comment]
> Do we have to update the docker version from 1.12.1

Docker 1.12.1 is really, really old. Docker 1.12.x reached EOL in January 2017, and has not received updates since, and has known, _critical_ vulnerabilities (including container escapes). I'd definitely not recommend still running it. Updating from a version that old to a current version should be done very carefully though (at least, upgrade 1 version at a time, don't skip major versions, and test the steps on a testing environment)

**Comment by denis-ramani-hs** [comment]
Thanks for the quick update. We will plan the activity of upgrading the Docker soon. Is there any way we know the correct version path to upgrade or what to keep in mind to update this really old version. We running this Docker 1.12.1 on Debian GNU/Linux 8 (Jessie).

**Comment by thaJeztah** [comment]
Hmm. Jessie is no longer a supported distro for docker (we support the "stable" (Buster) and "old stable" (Stretch) debian releases), so you may want to include updating the distro itself as well 😅, see https://docs.docker.com/install/linux/docker-ce/debian/. I realise that may add some work, and definitely be sure to test the upgrade scenario.

(I see the docs still list "stretch" as being the stable release; I'll open a PR to amend that 😅 )
