### ISSUE TITLE
`update_service` method doesn't work

### ISSUE THREAD

**Issue by KernelPryanic** [moby/moby#34116]
**Description**

When I'm trying to update service via python service API I'm getting
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal object into Go struct field EndpointSpec.Mode of type swarm.ResolutionMode")
```

Full stack trace
```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    client.update_service(client.services()[0]["ID"], version=client.services()[0]["Version"]["Index"], task_template=task_template, name=client.services()[0]["Spec"]["Name"], labels=client.services()[0]["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/api/service.py", line 350, in update_service
    self._raise_for_status(resp)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal object into Go struct field EndpointSpec.Mode of type swarm.ResolutionMode")
```

**Code snippet:**
```
import docker
from docker import types

client = docker.APIClient()

task_template = types.TaskTemplate(client.services()[0]["Spec"]["TaskTemplate"])
update_config = types.UpdateConfig(client.services()[0]["Spec"]["UpdateConfig"])
networks = client.services()[0]["Spec"]["TaskTemplate"]["Networks"]
endpoint_spec = types.EndpointSpec(client.services()[0]["Spec"]["EndpointSpec"])
mode = {u'Global': {}}

client.update_service(client.services()[0]["ID"], version=client.services()[0]["Version"]["Index"], task_template=task_template, name=client.services()[0]["Spec"]["Name"], labels=client.services()[0]["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.06.0-ce
Storage Driver: aufs
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: wvon1592uxpsff4gtdgl1jkjo
 Is Manager: true
 ClusterID: boycq9qlg9p27sk5b6k605wvh
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.56.102
 Manager Addresses:
  192.168.56.102:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: null
ID: ZJG4:FEOU:XZEX:JTN7:PGSZ:GFQH:UMTI:6JQR:5Q74:FGFL:GJYF:IEP3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
docker==2.4.2
docker-compose==1.13.0
docker-pycreds==0.2.1
docker-registry-client==0.5.1
dockerpty==0.4.1
Python 2.7.12
```

I'm inside of VirtualBox `5.1.14 r112924`

**Comment by shin-** [comment]
Hi @FromZeus ,

Reading through the issue again, I realize I misunderstood the root cause of the issue. Your `mode` param is invalid. You should create a `docker.types.ServiceMode` instance instead, like such:
```python
import docker
from docker import types

client = docker.APIClient()

task_template = types.TaskTemplate(client.services()[0]["Spec"]["TaskTemplate"])
update_config = types.UpdateConfig(client.services()[0]["Spec"]["UpdateConfig"])
networks = client.services()[0]["Spec"]["TaskTemplate"]["Networks"]
endpoint_spec = types.EndpointSpec(client.services()[0]["Spec"]["EndpointSpec"])
mode = types.ServiceMode(mode='global')

client.update_service(client.services()[0]["ID"], version=client.services()[0]["Version"]["Index"], task_template=task_template, name=client.services()[0]["Spec"]["Name"], labels=client.services()[0]["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
```

Note: You should probably store the result of `client.services()` in a variable instead of calling the method repeatedly.

**Comment by FromZeus** [comment]
I've simply copied my snippet from bpython :) So I've made that changes and run `.py` file with that
```
import docker
from docker import types

client = docker.APIClient()

s = client.services()[0]

task_template = types.TaskTemplate(s["Spec"]["TaskTemplate"])
update_config = types.UpdateConfig(s["Spec"]["UpdateConfig"])
networks = s["Spec"]["TaskTemplate"]["Networks"]
endpoint_spec = types.EndpointSpec(s["Spec"]["EndpointSpec"])
mode = types.ServiceMode(mode='global')

client.update_service(s["ID"], version=s["Version"]["Index"], task_template=task_template, name=s["Spec"]["Name"], labels=s["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
```
nothing has changed
`docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal object into Go struct field EndpointSpec.Mode of type swarm.ResolutionMode")`

**Comment by shin-** [comment]
OK, let's follow up on https://github.com/docker/docker-py/issues/1684

**Comment by shin-** [comment]
@FromZeus If you `print(s['Spec']['EndpointSpec'])`, what do you see?

**Comment by FromZeus** [comment]
@shin- I see `{u'Mode': u'vip'}`

**Comment by shin-** [comment]
Ah! The issue is that you're trying to re-cast the data from the API, and the SDK is a bit too permissive and lets you do it, but that's not actually how that works. I should have seen that from the start, sorry!

so:
```python
import docker
from docker import types

client = docker.APIClient()

s = client.services()[0]

task_template = s["Spec"]["TaskTemplate"]
update_config = s["Spec"]["UpdateConfig"]
networks = s["Spec"]["TaskTemplate"]["Networks"]
endpoint_spec = s["Spec"]["EndpointSpec"]
mode = types.ServiceMode(mode='global')

client.update_service(s["ID"], version=s["Version"]["Index"], task_template=task_template, name=s["Spec"]["Name"], labels=s["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
```

should get you past that hurdle, and is a good reminder to enforce types more strictly on the SDK side.

**Comment by FromZeus** [comment]
@shin- Ok, that's lead to another error :(
`docker.errors.InvalidVersion: Placement.platforms is not supported in API version < 1.30`
And this far I have another question: when I check `client._version` I get `1.26`, but when I check it with `client.version()` I get
```
{u'KernelVersion': u'4.4.0-78-generic', u'Arch': u'amd64', u'BuildTime': u'2017-06-23T21:19:04.990631145+00:00', u'ApiVersion': u'1.30', u'Version': u'17.06.0-ce', u'MinAPIVersion': u'1.12', u'GitCommit': u'02c1d87', u'Os': u'linux
', u'GoVersion': u'go1.8.3'}
```
 where the version is `1.30`. What's the difference?

**Comment by shin-** [comment]
use `docker.APIClient(version='1.30')` or `docker.APIClient(version='auto')`. It's just the SDK's default that hasn't been bumped in a while :)

**Comment by FromZeus** [comment]
Yep, that worked, and the last trouble I hope :)
Now I have this:
`AttributeError: 'dict' object has no attribute 'container_spec'`
It's about https://github.com/docker/docker-py/blob/2.4.2-release/docker/api/service.py#L41

**Comment by shin-** [comment]
Hmm, that one is a SDK bug. You might be able to work around it by reconstructing the `TaskTemplate` object.

**Comment by FromZeus** [comment]
Isn't that class outdated? I found that there is missed `Networks` property from `["Spec"]["TaskTemplate"]["ContainerSpec"]["Networks"]`

Example output of all service properties:
```
{u'Endpoint': {u'VirtualIPs': [{u'NetworkID': u'hxlbemfhk6z0josp9n8z0jak6', u'Addr': u'172.16.239.3/24'}], u'Spec': {u'Mode': u'vip'}}, u'ID': u'sd4ygo8nzj6569im8aotrxxg0', u'Version': {u'Index': 318}, u'UpdatedAt': u'2017-07-15T00
:30:54.55365137Z', u'Spec': {u'Name': u'test-stack_nginx', u'EndpointSpec': {u'Mode': u'vip'}, u'Labels': {u'com.docker.stack.namespace': u'test-stack', u'com.docker.stack.image': u'nginx:1.13.3-alpine'}, u'UpdateConfig': {u'Delay'
: 10000000000, u'MaxFailureRatio': 0, u'Order': u'stop-first', u'Parallelism': 1, u'FailureAction': u'pause'}, u'Mode': {u'Global': {}}, u'TaskTemplate': {u'Placement': {u'Platforms': [{u'OS': u'linux', u'Architecture': u'amd64'}]}
, u'ContainerSpec': {u'Image': u'nginx:1.13.3-alpine@sha256:24a27241f0450b465f9e9deb30628c524aa81a1aa6936daa41ef7c4345515272', u'Labels': {u'com.docker.stack.namespace': u'test-stack'}, u'Privileges': {u'CredentialSpec': None, u'SE
LinuxContext': None}}, u'Networks': [{u'Target': u'hxlbemfhk6z0josp9n8z0jak6', u'Aliases': [u'nginx']}], u'RestartPolicy': {u'MaxAttempts': 0, u'Condition': u'none'}, u'Runtime': u'container', u'ForceUpdate': 0, u'Resources': {}}},
 u'CreatedAt': u'2017-07-15T00:30:54.539854278Z'}
```

I've tested with new snippet:
```
import docker
from docker import types

client = docker.APIClient(version='auto')

s = client.services()[0]

container_spec = s["Spec"]["TaskTemplate"]["ContainerSpec"]
container_spec["Image"] = "nginx:1.12-alpine"
restart_policy = s["Spec"]["TaskTemplate"]["RestartPolicy"]
placement = s["Spec"]["TaskTemplate"]["Placement"]
task_template = types.TaskTemplate(container_spec=container_spec, restart_policy=restart_policy, placement=placement)
update_config = s["Spec"]["UpdateConfig"]
networks = s["Spec"]["TaskTemplate"]["Networks"]
endpoint_spec = s["Spec"]["EndpointSpec"]
mode = types.ServiceMode(mode='global')

client.update_service(s["ID"], version=s["Version"]["Index"], task_template=task_template, name=s["Spec"]["Name"], labels=s["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
```

So after update I got crashed container with improperly configured network.
Inspect of source container:
```
[
    {
        "Id": "a8739ec80f54780efb522b1fe99dcf022a16ba5bf7387e7a0fffca3d8fc6b64f",
        "Created": "2017-07-15T00:31:11.601110471Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-15T00:31:14.718922887Z",
            "FinishedAt": "2017-07-15T00:31:33.185617472Z"
        },
        "Image": "sha256:2d13ad575b6fc91d3b242f344f5d08d65fda5a43d18a26d51b1174543c217735",
        "ResolvConfPath": "/var/lib/docker/containers/a8739ec80f54780efb522b1fe99dcf022a16ba5bf7387e7a0fffca3d8fc6b64f/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a8739ec80f54780efb522b1fe99dcf022a16ba5bf7387e7a0fffca3d8fc6b64f/hostname",
        "HostsPath": "/var/lib/docker/containers/a8739ec80f54780efb522b1fe99dcf022a16ba5bf7387e7a0fffca3d8fc6b64f/hosts",
        "LogPath": "/var/lib/docker/containers/a8739ec80f54780efb522b1fe99dcf022a16ba5bf7387e7a0fffca3d8fc6b64f/a8739ec80f54780efb522b1fe99dcf022a16ba5bf7387e7a0fffca3d8fc6b64f-json.log",
        "Name": "/test-stack_nginx.hys5b3pxkjzsu8uyqurb93gu8.ivt9p39xv21r28dtsybq5phpl",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "a8739ec80f54",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.12.1"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "ArgsEscaped": true,
            "Image": "nginx:1.12-alpine",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.stack.namespace": "test-stack",
                "com.docker.swarm.node.id": "hys5b3pxkjzsu8uyqurb93gu8",
                "com.docker.swarm.service.id": "sd4ygo8nzj6569im8aotrxxg0",
                "com.docker.swarm.service.name": "test-stack_nginx",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "ivt9p39xv21r28dtsybq5phpl",
                "com.docker.swarm.task.name": "test-stack_nginx.hys5b3pxkjzsu8uyqurb93gu8.ivt9p39xv21r28dtsybq5phpl"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b0303c7601aa4d6eea5a3d0d22b99e04c2307d1a9a895f33a42dbbca43866272",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/b0303c7601aa",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "test-stack_test-stack": {
                    "IPAMConfig": {
                        "IPv4Address": "172.16.239.5"
                    },
                    "Links": null,
                    "Aliases": [
                        "a8739ec80f54"
                    ],
                    "NetworkID": "hxlbemfhk6z0josp9n8z0jak6",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```
Inspect of updated container:
```
[
    {
        "Id": "8b80e991cb0e3e132f6649d4338ae74f64083c528a4e8b1fb4f60e7ad4b8d765",
        "Created": "2017-07-15T00:36:40.591163847Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 8358,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-15T00:36:41.779484276Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:ba60b24dbad5e955219159f0a283e5c6d46d43b52d486152cbf6aab3b4ac6bb8",
        "ResolvConfPath": "/var/lib/docker/containers/8b80e991cb0e3e132f6649d4338ae74f64083c528a4e8b1fb4f60e7ad4b8d765/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/8b80e991cb0e3e132f6649d4338ae74f64083c528a4e8b1fb4f60e7ad4b8d765/hostname",
        "HostsPath": "/var/lib/docker/containers/8b80e991cb0e3e132f6649d4338ae74f64083c528a4e8b1fb4f60e7ad4b8d765/hosts",
        "LogPath": "/var/lib/docker/containers/8b80e991cb0e3e132f6649d4338ae74f64083c528a4e8b1fb4f60e7ad4b8d765/8b80e991cb0e3e132f6649d4338ae74f64083c528a4e8b1fb4f60e7ad4b8d765-json.log",
        "Name": "/test-stack_nginx.hys5b3pxkjzsu8uyqurb93gu8.dgc4uv331hsuq36gjg9n8vweq",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "8b80e991cb0e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.13.3"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "ArgsEscaped": true,
            "Image": "nginx:1.13.3-alpine@sha256:24a27241f0450b465f9e9deb30628c524aa81a1aa6936daa41ef7c4345515272",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.stack.namespace": "test-stack",
                "com.docker.swarm.node.id": "hys5b3pxkjzsu8uyqurb93gu8",
                "com.docker.swarm.service.id": "b6q4cednk9ze0br8kgfuq23ex",
                "com.docker.swarm.service.name": "test-stack_nginx",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "dgc4uv331hsuq36gjg9n8vweq",
                "com.docker.swarm.task.name": "test-stack_nginx.hys5b3pxkjzsu8uyqurb93gu8.dgc4uv331hsuq36gjg9n8vweq"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e1b8d539d9da6488347b1e78c1e5b761ebde48c7983e0cb3c68b36dec35e9a32",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/e1b8d539d9da",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "test-stack_test-stack": {
                    "IPAMConfig": {
                        "IPv4Address": "172.16.239.4"
                    },
                    "Links": null,
                    "Aliases": [
                        "8b80e991cb0e"
                    ],
                    "NetworkID": "b336pzqnvd4llzzno8dlkg05y",
                    "EndpointID": "5d4ed18b7b435f3acd4ac6044cb0b1bd771d48867836a0aa66ac0514ab3745a4",
                    "Gateway": "",
                    "IPAddress": "172.16.239.4",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:10:ef:04",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by FromZeus** [comment]
Any news about the last one?

**Comment by swaroopkundeti** [comment]
With `s = client.services()[0]`  it fetches first service in cluster. How about fetching service with name in case of multiple services?

@shin-

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
