### ISSUE TITLE
dockerd stopped responding to API requests; no installed keys could decrypt message

### ISSUE THREAD

**Issue by kinghuang** [moby/moby#34141]
**Description**

I have a 10 node Docker swarm running Docker CE 17.06.0. One of the controllers stopped responding to API commands, and all ten nodes started logging messages about ```memberlist: failed to receive: No installed keys could decrypt the message from=…```. The swarm was in a broken state until the node that stopped responding was restarted.

**Steps to reproduce the issue:**

Not sure how to reproduce the issue. This is on a 10-node Docker swarm that is heavily used for development.

**Describe the results you received:**

On the node that stopped responding, the daemon outputted log lines that it could not decrypt messages from the other 9 nodes.

```
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.003807997-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.137:56134"
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.013832761-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.147:39506"
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.036012506-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.148:40842"
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.275404103-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.84:49264"
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.644752645-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.87:35600"
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.691320840-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.149:44430"
Jul 16 10:02:56 itrmsdev02.ucalgary.ca dockerd[1142]: time="2017-07-16T10:02:56.811744743-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.152:37456"
```

On the other 9 nodes, they all outputted log lines that they could not decrypt messages from the misbehaving node.

```
Jul 16 10:04:41 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:04:41.417179382-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59514"
Jul 16 10:04:45 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:04:45.417459159-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59522"
Jul 16 10:04:47 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:04:47.417319707-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59526"
Jul 16 10:04:48 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:04:48.417226763-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59528"
Jul 16 10:05:16 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:05:16.417069436-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59586"
Jul 16 10:05:18 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:05:18.417402441-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59590"
Jul 16 10:05:35 itrmsdev04.ucalgary.ca dockerd[1105]: time="2017-07-16T10:05:35.417190950-06:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=10.41.149.139:59624"
```

Docker would not respond to any API calls on the failed node. I sent a `SIGUSR` signal to get a stack dump, and restarted dockerd. I'm not sure how to interpret the dump. It's attached as a zip file because the attachment size limit is 10 MB.

[goroutine-stacks-2017-07-17T094958-0600.log.zip](https://github.com/moby/moby/files/1153270/goroutine-stacks-2017-07-17T094958-0600.log.zip)

**Describe the results you expected:**

The swarm should operate normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

This output is from the failed node after it was restarted.

```
-bash-4.2$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
-bash-4.2$ docker info
Containers: 63
 Running: 12
 Paused: 0
 Stopped: 51
Images: 488
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: nj1kr88iu2ai9947u8neoskdw
 Is Manager: true
 ClusterID: m0gz05zqgmhx67noqdvko2npr
 Managers: 3
 Nodes: 10
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.41.149.139
 Manager Addresses:
  10.41.149.137:2377
  10.41.149.138:2377
  10.41.149.139:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: itrmsdev02.ucalgary.ca
ID: VPME:AFML:SQU3:5WR5:UPXE:B5YZ:BBFP:JAEU:A5R4:UYGT:IFO5:AEKF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All 10 nodes are on VMs running RHEL 7.3.

docker/swarmkit#1954 introduced a fix to avoid encryption key rotation on leader change, incorporated into 1.13.x. I don't know if that's the situation I ran into. This is the first time I've ever had a problem about decryption messages in any of my swarms.

**Comment by thaJeztah** [comment]
ping @cyli @aaronlehmann

**Comment by cyli** [comment]
cc-ing @sanimej also

**Comment by kinghuang** [comment]
The exact same thing is happening again, and to the exact same node as before. Docker on `itrmsdev02` stopped responding to API requests, and I'm seeing the same pattern of messages about problems decrypting messages. Restarting the stuck node returns things to normal.

New stack dump attached.

[goroutine-stacks-2017-07-24T100837-0600.log.zip](https://github.com/moby/moby/files/1170434/goroutine-stacks-2017-07-24T100837-0600.log.zip)

**Comment by aaronlehmann** [comment]
Seems like another deadlock between libnetwork and cluster (cc @fcrisciani):

```
goroutine 275 [semacquire, 1377 minutes]:
sync.runtime_Semacquire(0xc4219c01cc)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).RLock(0xc4219c01c0)
	/usr/local/go/src/sync/rwmutex.go:43 +0x49
github.com/docker/docker/daemon/cluster.(*Cluster).IsManager(0xc4219c01c0, 0x1a8a000)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/cluster.go:247 +0x4a
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).isManager(0xc42018aa00, 0xc424dd7f00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:657 +0xa9
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).isDistributedControl(0xc42018aa00, 0xc428c2fd40)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:670 +0x2b
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).processEndpointDelete(0xc42018aa00, 0xc420842030, 0xc424dd7e40)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:419 +0x50
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).watchLoop(0xc42018aa00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:455 +0x138
created by github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).startWatch
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:468 +0x109
```

Something is holding the mutex in `github.com/docker/docker/daemon/cluster`, and a bunch of libnetwork functions get blocked trying to call into this package.

I didn't see an obvious root cause of this mutex being held for so long, but I wonder if it's this goroutine:

```
goroutine 1362 [semacquire, 1377 minutes]:
sync.runtime_Semacquire(0xc4219c01cc)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).RLock(0xc4219c01c0)
	/usr/local/go/src/sync/rwmutex.go:43 +0x49
github.com/docker/docker/daemon/cluster.(*Cluster).lockedManagerAction(0xc4219c01c0, 0xc421378290, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/cluster.go:417 +0x5d
github.com/docker/docker/daemon/cluster.(*Cluster).GetService(0xc4219c01c0, 0xc425ff9540, 0x19, 0xc424353900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/services.go:109 +0x114
github.com/docker/docker/daemon/cluster.(*Cluster).GetTasks.func1(0xc4228e37a0, 0xc4228e3830, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/tasks.go:26 +0x5c1
github.com/docker/docker/daemon/cluster.newListTasksFilters(0xc4228e37a0, 0xc424353930, 0xc42186d440, 0x2638620, 0xc423b00000)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/filters.go:65 +0x780
github.com/docker/docker/daemon/cluster.(*Cluster).GetTasks(0xc4219c01c0, 0xc4228e37a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/tasks.go:48 +0x17a
github.com/docker/docker/api/server/router/swarm.(*swarmRouter).getTasks(0xc4219d95f0, 0x7f20e6e1f070, 0xc4228e3710, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200, 0xc4228e35f0, 0x19fa222, 0x4)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/swarm/cluster_routes.go:333 +0xa8
github.com/docker/docker/api/server/router/swarm.(*swarmRouter).(github.com/docker/docker/api/server/router/swarm.getTasks)-fm(0x7f20e6e1f070, 0xc4228e3710, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200, 0xc4228e35f0, 0x7f20e6e1f070, 0xc4228e3710)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/swarm/cluster.go:47 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f20e6e1f070, 0xc4228e3710, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200, 0xc4228e35f0, 0x7f20e6e1f070, 0xc4228e3710)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f20e6e1f070, 0xc4228e36e0, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200, 0xc4228e35f0, 0xc421585440, 0xc421379a00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f20e6e1f070, 0xc4228e36e0, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200, 0xc4228e35f0, 0x7f20e6e1f070, 0xc4228e36e0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x871
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2627cc0, 0xc422ac40e0, 0xc4296ba200)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc421bd8f60, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4219da730, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc421cc6c30, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4201311e0, 0x2627cc0, 0xc422ac40e0, 0xc4296ba200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4218601e0, 0x2629840, 0xc4215d0440)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

It first aquires the `RLock` in `GetTasks`, then calls into `lockedManagerAction`, which tries to call `RLock` again. According to the `sync` documentation, this is not safe:

> If a goroutine holds a RWMutex for reading, it must not expect this or any other goroutine to be able to also take the read lock until the first read lock is released. In particular, this prohibits recursive read locking. This is to ensure that the lock eventually becomes available; a blocked Lock call excludes new readers from acquiring the lock.

I suspect this is the root cause. `GetServices` needs to be fixed not to recursively take a read lock.

**Comment by fcrisciani** [comment]
@aaronlehmann 
grepping the stacktrace I arrived to your same conclusion:
```
grep semacquire -A 10 goroutine-stacks-2017-07-24T100837-0600.log  | grep controller.go | sort | uniq -c
   1 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:1008 +0x4c
   1 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:300 +0x46
   1 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:606 +0x9c
   1 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:618 +0x49c
5102 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:652 +0x42
   1 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:657 +0xa9
5103 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:670 +0x2b
   5 	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:957 +0x40
```

The suspicious one of course is that difference of 1 between 5103 and 5102, this points to one go routine to have successfully acquired the lock on the controller:
```
goroutine 275 [semacquire, 1377 minutes]:
sync.runtime_Semacquire(0xc4219c01cc)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).RLock(0xc4219c01c0)
	/usr/local/go/src/sync/rwmutex.go:43 +0x49
github.com/docker/docker/daemon/cluster.(*Cluster).IsManager(0xc4219c01c0, 0x1a8a000)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/cluster/cluster.go:247 +0x4a
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).isManager(0xc42018aa00, 0xc424dd7f00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:657 +0xa9
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).isDistributedControl(0xc42018aa00, 0xc428c2fd40)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:670 +0x2b
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).processEndpointDelete(0xc42018aa00, 0xc420842030, 0xc424dd7e40)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:419 +0x50
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).watchLoop(0xc42018aa00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:455 +0x138
created by github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).startWatch
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:468 +0x109
```

And now is stuck on: 
```
return c.currentNodeState().IsActiveManager()
```

**Comment by alfonsodg** [comment]
Hi,

Today (6/3/19) my cluster down because this bug,
Docker engine version: 18.09.6
Nodes: 8 / 3(Master) and 5(workers)

The fail apparently starts when one master node have a hardware problem

**Comment by kjkuan** [comment]
This also just happened to me two days ago... I'm using 18.09.3.
