### ISSUE TITLE
Panic initializing network controller after deleting stale bridge endpoint

### ISSUE THREAD

**Issue by dsheets** [moby/moby#34256]
**Description**

Engine fails to start with panic during network controller initialization after a stale bridge endpoint is deleted from the store. The initial panic is distinct from subsequent panics and occurred coincident with a regular minor upgrade from 17.06.0-ce-mac18 to 17.06.0-ce-mac19.

The initial panic:

```
Jul 26 03:43:13 moby root: time="2017-07-26T03:43:13.682740662Z" level=debug msg="Network (fc2ed73) not found for restored bridge endpoint (7add587)"  
Jul 26 03:43:13 moby root: time="2017-07-26T03:43:13.682772392Z" level=debug msg="Deleting stale bridge endpoint (7add587) from store"  
Jul 26 03:43:13 moby root: panic: assertion failed: write: circular dependency occurred 
Jul 26 03:43:13 moby root: goroutine 1 [running]: 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt._assert(0xc420394000, 0x1adbbee, 0x23, 0x0, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:1026 +0xf6 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).write(0xc420147420, 0xc420394000) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:226 +0x3ad 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).spill(0xc420147420, 0xc4201ef340, 0x27087a0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:378 +0x28f 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).spill(0xc420147340, 0xc4202483c0, 0xc420519f28) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:350 +0xb4 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc420489cc0, 0xc420248300, 0xc42051a198) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:571 +0x17b 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc4200127f8, 0x28b37459, 0x27582e0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:538 +0x8f8 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4200127e0, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/tx.go:163 +0x125 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4203e85a0, 0xc42051a3f0, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:602 +0xf7 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicDelete(0xc420221cc0, 0xc4201471f0, 0x65, 0xc420248120, 0x0, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:345 +0x19c 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).DeleteObjectAtomic(0xc420489880, 0x27123a0, 0xc420213680, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:623 +0x25c 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).storeDelete(0xc420478190, 0x27123a0, 0xc420213680, 0x1, 0x1) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:120 +0x65 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).populateEndpoints(0xc420478190, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:87 +0x426 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0xc420478190, 0xc420202120, 0x0, 0xc420202660) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:40 +0x245 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0xc420478190, 0xc420202120, 0xc420202180, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:417 +0x1ce 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.Init(0x26f9e20, 0xc4203c4340, 0xc420202120, 0x0, 0xffffffffffffffff) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:151 +0xe2 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(0xc4203c4340, 0x1a9fba1, 0x6, 0x1b29978, 0xc420202120, 0xc42045a2c0, 0xc42051aad0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72 +0x46 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc420488c40, 0x8, 0x8, 0xc420063350, 0xc4201da5d0, 0xc420488c40, 0x8) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:208 +0x570 
Jul 26 03:43:13 moby root: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc420083680, 0xc420088900, 0xc4201da5d0, 0xc420083680, 0xc420101b10, 0xc4201da5d0, 0xc4201da5a0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon_unix.go:736 +0xa7 
Jul 26 03:43:13 moby root: github.com/docker/docker/daemon.(*Daemon).restore(0xc420083680, 0x26ee320, 0xc420083680) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon.go:288 +0x777 
Jul 26 03:43:13 moby root: github.com/docker/docker/daemon.NewDaemon(0xc420088900, 0x2713020, 0xc4200145e0, 0x26ff520, 0xc4203ad110, 0xc420063350, 0x0, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon.go:747 +0x2116 
Jul 26 03:43:13 moby root: main.(*DaemonCli).start(0xc420368c60, 0x0, 0x1ac1337, 0x17, 0xc420088000, 0xc4203c4180, 0xc4201dc510, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:214 +0x1223 
Jul 26 03:43:13 moby root: main.runDaemon(0x0, 0x1ac1337, 0x17, 0xc420088000, 0xc4203c4180, 0xc4201dc510, 0x8, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:91 +0x8c 
Jul 26 03:43:13 moby root: main.newDaemonCommand.func1(0xc420082480, 0xc42027a280, 0x0, 0x8, 0x0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6f 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc420082480, 0xc4200100a0, 0x8, 0x8, 0xc420082480, 0xc4200100a0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420082480, 0x186de40, 0x1, 0xc420324ee0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349 
Jul 26 03:43:13 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420082480, 0xc420324ee0, 0x0) 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b 
Jul 26 03:43:13 moby root: main.main() 
Jul 26 03:43:13 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:118 +0xe6 
```

The subsequent start-up panics:

```
Jul 26 06:22:20 moby root: time="2017-07-26T06:22:20.584912527Z" level=debug msg="Network (fc2ed73) not found for restored bridge endpoint (764d3a4)"  
Jul 26 06:22:20 moby root: time="2017-07-26T06:22:20.585005023Z" level=debug msg="Deleting stale bridge endpoint (764d3a4) from store"  
Jul 26 06:22:20 moby root: panic: invalid childAt(1) on a leaf node 
Jul 26 06:22:20 moby root: goroutine 1 [running]: 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).childAt(0xc4202f5ab0, 0x1, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:75 +0x142 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).nextSibling(0xc4202f5ab0, 0xc4202f5ab0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:100 +0x7c 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).rebalance(0xc4202f5ab0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:466 +0x16a 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).rebalance(0xc4202f5ab0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:507 +0x3f2 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).rebalance(0xc420431bc0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:636 +0x97 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).rebalance(0xc4200127f8) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:639 +0x114 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4200127e0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/tx.go:156 +0xd9 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4202db680, 0xc4204ea3f0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:602 +0xf7 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicDelete(0xc420257090, 0xc4202f5880, 0x65, 0xc420232f30, 0x0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:345 +0x19c 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).DeleteObjectAtomic(0xc4204317c0, 0x27123a0, 0xc420266aa0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:623 +0x25c 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).storeDelete(0xc420100dc0, 0x27123a0, 0xc420266aa0, 0x1, 0x1) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:120 +0x65 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).populateEndpoints(0xc420100dc0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:87 +0x426 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0xc420100dc0, 0xc420103cb0, 0x0, 0xc4202a9350) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:40 +0x245 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0xc420100dc0, 0xc420103cb0, 0xc420103d10, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:417 +0x1ce 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.Init(0x26f9e20, 0xc420118600, 0xc420103cb0, 0x0, 0xffffffffffffffff) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:151 +0xe2 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(0xc420118600, 0x1a9fba1, 0x6, 0x1b29978, 0xc420103cb0, 0xc4201095e0, 0xc4204eaad0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72 +0x46 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc420118500, 0x8, 0x8, 0xc42043f020, 0xc4202956e0, 0xc420118500, 0x8) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:208 +0x570 
Jul 26 06:22:20 moby root: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc4204bc000, 0xc420375680, 0xc4202956e0, 0xc4204bc000, 0xc420272a00, 0xc4202956e0, 0xc4202956b0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon_unix.go:736 +0xa7 
Jul 26 06:22:20 moby root: github.com/docker/docker/daemon.(*Daemon).restore(0xc4204bc000, 0x26ee320, 0xc4204bc000) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon.go:288 +0x777 
Jul 26 06:22:20 moby root: github.com/docker/docker/daemon.NewDaemon(0xc420375680, 0x2713020, 0xc420439d90, 0x26ff520, 0xc42043ba00, 0xc42043f020, 0x0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon.go:747 +0x2116 
Jul 26 06:22:20 moby root: main.(*DaemonCli).start(0xc42043e450, 0x0, 0x1ac1337, 0x17, 0xc420375200, 0xc420430e40, 0xc4200113b0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:214 +0x1223 
Jul 26 06:22:20 moby root: main.runDaemon(0x0, 0x1ac1337, 0x17, 0xc420375200, 0xc420430e40, 0xc4200113b0, 0x8, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:91 +0x8c 
Jul 26 06:22:20 moby root: main.newDaemonCommand.func1(0xc42033dd40, 0xc4203a1900, 0x0, 0x8, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6f 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc42033dd40, 0xc4200100a0, 0x8, 0x8, 0xc42033dd40, 0xc4200100a0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42033dd40, 0x186de40, 0x1, 0xc420438cb0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42033dd40, 0xc420438cb0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b 
Jul 26 06:22:20 moby root: main.main() 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:118 +0xe6 
```

Escalated from docker/for-mac#1902.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)

**Comment by thaJeztah** [comment]
ping @fcrisciani PTAL

**Comment by AmirMustafa** [comment]
Team, did we receive for docker not starting issue (Mac Catalina 10.156)? Stuck with with docker desktop not starting error

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
