### ISSUE TITLE
Create duplicated network expect 409 response but get 500

### ISSUE THREAD

**Issue by tossmilestone** [moby/moby#34459]
**Description**

When create a network with name already existed using docker-py, and set arg `check_duplicated=True`, the error should be `409 Conflict`, but `500 Internal Server Error` returns.

**Steps to reproduce the issue:**
In python console
```
>>> import docker
>>> c = docker.from_env()
>>> c.networks.create('net1')
<Network: 4c7d2d08e3>
>>> c.networks.create('net1', check_duplicate=True)
```

**Describe the results you received:**

```
>>> c.networks.create('net1', check_duplicate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/models/networks.py", line 144, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 134, in create_network
    return self._result(res, json=True)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/networks/create ("network with name net1 already exists")
>>> 
```

**Describe the results you expected:**

```
>>> c.networks.create('net1', check_duplicate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/models/networks.py", line 144, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 134, in create_network
    return self._result(res, json=True)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict for url: http+docker://localunixsocket/v1.24/networks/create ("network with name net1 already exists")
>>> 
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 7ty93f9vgo9gb2nmwk4km10hb
 Is Manager: true
 ClusterID: fofqp1rgom60nftnc5fwkz1st
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.249.129
 Manager Addresses:
  192.168.249.129:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 472.5MiB
Name: swarm_manager
ID: YRD2:DTIW:AKEF:RXJY:RKXM:OJU2:N7B6:K7JK:XDOG:4E5S:NWFU:SGWY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 40
 Goroutines: 184
 System Time: 2017-08-08T14:20:57.288514678+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.27.37.40:5000
 10.37.210.125:5001
 127.0.0.0/8
Registry Mirrors:
 https://2h3po24q.mirror.aliyuncs.com/
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
docker-py version 2.1.0
```

**Comment by ripcurld0** [comment]
According to the [docs](https://docs.docker.com/engine/api/v1.30/#operation/NetworkCreate) doesn't mention any thing about status code `409`. Although, it might be better than `500`.

@thaJeztah WDYT?

**Comment by thaJeztah** [comment]
Yes should be a 4xx error code; the server detected the problem and handled it; it's a problem with the request not a server error 

Could possible also be a generic 400 error; depends on what we do for other similar cases I guess

**Comment by tossmilestone** [comment]
The [service create](https://docs.docker.com/engine/api/v1.30/#operation/ServiceCreate) with existed name returns `409`.

**Comment by thaJeztah** [comment]
Perfect! in that case I agree this should use the same

**Comment by ripcurld0** [comment]
@yastij would you like to work on that?

**Comment by yastij** [comment]
Yea sure, thanks for the ping @ripcurld0 !

**Comment by liketic** [comment]
@yastij Can I continue to work on this?

**Comment by yastij** [comment]
Oh forgot about this one, i'll finish it once home, sorry again guys for the delay

**Comment by yastij** [comment]
@liketic - I think i won't have time to complete this one, due to some issues I'm working on, can you complete the initial PR ? if not I'll get to this as soon as I can

**Comment by liketic** [comment]
@yastij I'm happy to. Thanks.

**Comment by tossmilestone** [comment]
@liketic Hi, I have create a PR to fix this, thanks for your help. @yastij PTAL.
