### ISSUE TITLE
Docker 17.06.0-ce crash with http: panic serving @: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lox** [moby/moby#34515]
We are encountering this issue when using Docker 17.05.0-ce on Amazon Linux, as described in https://github.com/moby/moby/issues/25663. 

We are running docker in an autoscaling group that runs CI jobs in fairly large volumes. Around 10% of runs will fail on new docker hosts during the creation of the first network with `docker-compose run`:

```
017-08-15T01:39:57.809Z 2017-08-15 01:39:57.811935 I | http: panic serving @: runtime error: invalid memory address or nil pointer dereference
2017-08-15T01:39:57.809Z goroutine 212 [running]:
2017-08-15T01:39:57.809Z net/http.(*conn).serve.func1(0xc4203da280)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
2017-08-15T01:39:57.809Z panic(0x1845f60, 0x26c7940)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
2017-08-15T01:39:57.809Z github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).conflictsWithNetworks(0xc420eba0b0, 0xc420cd63c0, 0x40, 0xc4201ecf20, 0x3, 0x3, 0x0, 0x4124a8)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:349 +0xf0
2017-08-15T01:39:57.809Z github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).createNetwork(0xc420476c30, 0xc420eba0b0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:686 +0x9b6
2017-08-15T01:39:57.809Z github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).CreateNetwork(0xc420476c30, 0xc420cd63c0, 0x40, 0xc420e7c5d0, 0x26ef760, 0xc420eaa000, 0xc420e7c990, 0x1, 0x1, 0x27801b0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:610 +0x21c
2017-08-15T01:39:57.809Z github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).addNetwork(0xc4202b8b00, 0xc420eaa000, 0xc420e97080, 0xc420eaa000)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:945 +0x157
2017-08-15T01:39:57.809Z github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).NewNetwork(0xc4202b8b00, 0x1a9fba1, 0x6, 0xc420a28940, 0x31, 0xc420cd63c0, 0x40, 0xc420e7c540, 0x6, 0x6, ...)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:807 +0xb00
2017-08-15T01:39:57.809Z github.com/docker/docker/daemon.(*Daemon).createNetwork(0xc420380000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/network.go:349 +0x5c0
2017-08-15T01:39:57.809Z github.com/docker/docker/daemon.(*Daemon).CreateNetwork(0xc420380000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/network.go:280 +0x87
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server/router/network.(*networkRouter).postNetworkCreate(0xc4200fd140, 0x7f1df0643000, 0xc4204cf8f0, 0x2707fe0, 0xc4201042a0, 0xc420480800, 0xc4204cf770, 0x1a9e63d, 0x5)
	/go/src/github.com/docker/docker/api/server/router/network/network_routes.go:195 +0x1ed
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server/router/network.(*networkRouter).(github.com/docker/docker/api/server/router/network.postNetworkCreate)-fm(0x7f1df0643000, 0xc4204cf8f0, 0x2707fe0, 0xc4201042a0, 0xc420480800, 0xc4204cf770, 0x7f1df0643000, 0xc4204cf8f0)
	/go/src/github.com/docker/docker/api/server/router/network/network.go:37 +0x69
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f1df0643000, 0xc4204cf8f0, 0x2707fe0, 0xc4201042a0, 0xc420480800, 0xc4204cf770, 0x7f1df0643000, 0xc4204cf8f0)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f1df0643000, 0xc4204cf7d0, 0x2707fe0, 0xc4201042a0, 0xc420480800, 0xc4204cf770, 0x47, 0xc420483220)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d
2017-08-15T01:39:57.809Z github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f1df0643000, 0xc4204cf7d0, 0x2707fe0, 0xc4201042a0, 0xc420480800, 0xc4204cf770, 0x0, 0x756ea11b601fbb)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x871
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f1df0643000, 0xc4204cf7d0, 0x2707fe0, 0xc4201042a0, 0xc420480800, 0xc4204cf770, 0x7f1df0643000, 0xc4204cf7d0)
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:53 +0x527
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2707fe0, 0xc4201042a0, 0xc420480800)
	/go/src/github.com/docker/docker/api/server/server.go:139 +0x21a
2017-08-15T01:39:57.809Z net/http.HandlerFunc.ServeHTTP(0xc42046c900, 0x2707fe0, 0xc4201042a0, 0xc420480800)
	/usr/local/go/src/net/http/server.go:1942 +0x44
2017-08-15T01:39:57.809Z github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203f2640, 0x2707fe0, 0xc4201042a0, 0xc420480800)
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
2017-08-15T01:39:57.809Z github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420108b80, 0x2707fe0, 0xc4201042a0, 0xc420480800)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
2017-08-15T01:39:57.809Z net/http.serverHandler.ServeHTTP(0xc420095970, 0x2707fe0, 0xc4201042a0, 0xc420480800)
	/usr/local/go/src/net/http/server.go:2568 +0x92
2017-08-15T01:39:57.809Z net/http.(*conn).serve(0xc4203da280, 0x2709b60, 0xc420a28640)
	/usr/local/go/src/net/http/server.go:1825 +0x612
2017-08-15T01:39:57.809Z created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

The full docker.log is here https://gist.github.com/lox/7669bd18a80a48a5c83f4cb96ff40d95.

**Comment by thaJeztah** [comment]
ping @fcrisciani

**Comment by lox** [comment]
What's really strange is that only some customers see this. I was wondering if it's something to do with the private address range that gets chosen.

**Comment by fcrisciani** [comment]
@lox looks like it's mainly due to the creation in parallel of networks. I put some more details on the patch itself. maybe a workaround can be to create the networks serially outside of the compose and then define them in the compose as external

**Comment by lox** [comment]
Thanks @fcrisciani, will that patch fix the issue when it eventually makes its way into docker?

**Comment by fcrisciani** [comment]
yep  the process is to merge it on libnetwork and then has to be revendored in moby. At that point the next release that will come up from moby will pick it up.

**Comment by thaJeztah** [comment]
Reopening, because https://github.com/docker/libnetwork/pull/1918 was not vendored yet

**Comment by fcrisciani** [comment]
@lox this fix will be in 17.12

**Comment by lox** [comment]
That is great news! Thanks all!

**Comment by thaJeztah** [comment]
Changes from https://github.com/docker/libnetwork/pull/1918 were brought in through https://github.com/moby/moby/pull/35677, so closing this one
