### ISSUE TITLE
 fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by allencloud** [moby/moby#34540]
**Description**

Currently in one docker daemon in our cluster, we met one issue when running dockerd. And it seems to be a panic of concurrent read and write to a map.

Here are some fatal error log:

```
Aug 10 09:54:11 service-prd98-13 dockerd: time="2017-08-10T09:54:11.196551928+08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Aug 10 09:54:11 service-prd98-13 dockerd: time="2017-08-10T09:54:11.196592321+08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Aug 10 09:54:11 service-prd98-13 dockerd: time="2017-08-10T09:54:11+08:00" level=info msg="Firewalld running: false"
Aug 10 09:54:12 service-prd98-13 dockerd: time="2017-08-10T09:54:12.432262996+08:00" level=warning msg="Error getting v2 registry: Get https://daocloud.io/v2/: dial tcp: lookup daocloud.io on 127.0.0.1:53: read udp 127.0.0.1:49424->127.0.0.1:53: read: connection refused"
Aug 10 09:54:12 service-prd98-13 dockerd: time="2017-08-10T09:54:12.432322303+08:00" level=error msg="Attempting next endpoint for pull after error: Get https://daocloud.io/v2/: dial tcp: lookup daocloud.io on 127.0.0.1:53: read udp 127.0.0.1:49424->127.0.0.1:53: read: connection refused"
Aug 10 09:54:12 service-prd98-13 dockerd: time="2017-08-10T09:54:12.433207007+08:00" level=error msg="Attempting next endpoint for pull after error: Get https://daocloud.io/v1/_ping: dial tcp: lookup daocloud.io on 127.0.0.1:53: read udp 127.0.0.1:43166->127.0.0.1:53: read: connection refused"
Aug 10 09:54:12 service-prd98-13 dockerd: time="2017-08-10T09:54:12.433305305+08:00" level=error msg="Handler for POST /v1.24/images/create returned error: Get https://daocloud.io/v1/_ping: dial tcp: lookup daocloud.io on 127.0.0.1:53: read udp 127.0.0.1:43166->127.0.0.1:53: read: connection refused"
Aug 10 09:54:13 service-prd98-13 dockerd: time="2017-08-10T09:54:13.068096424+08:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module="node/agent/taskmanager" task.id=dujojh6h9fyecq2gln8sczt3u
Aug 10 09:54:13 service-prd98-13 dockerd: time="2017-08-10T09:54:13.761097740+08:00" level=warning msg="failed to deactivate service binding for container dce_base.06y1h3s2qasjdmsarnbaa45l5.98pbjky3etwcr0sq1t018mt1i" error="network sandbox does not exist for container dce_base.06y1h3s2qasjdmsarnbaa45l5.98pbjky3etwcr0sq1t018mt1i" module="node/agent"
Aug 10 09:54:18 service-prd98-13 dockerd: time="2017-08-10T09:54:18.411837354+08:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Aug 10 09:54:18 service-prd98-13 dockerd: time="2017-08-10T09:54:18.411896156+08:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Aug 10 09:54:19 service-prd98-13 dockerd: fatal error: concurrent map read and map write
Aug 10 09:54:19 service-prd98-13 dockerd: goroutine 64201215 [running]:
Aug 10 09:54:19 service-prd98-13 dockerd: runtime.throw(0x1921176, 0x21)
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4363ad368 sp=0xc4363ad348
Aug 10 09:54:19 service-prd98-13 dockerd: runtime.mapaccess2_faststr(0x16bebe0, 0xc425978c30, 0x18ed7a7, 0x6, 0xc425979440, 0x0)
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4363ad3c8 sp=0xc4363ad368
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/daemon.(*Daemon).ContainerInspectCurrent(0xc4203cc200, 0xc42b344086, 0x40, 0x0, 0x0, 0x0, 0x0)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/inspect.go:65 +0x29a fp=0xc4363ad608 sp=0xc4363ad3c8
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/daemon.(*Daemon).ContainerInspect(0xc4203cc200, 0xc42b344086, 0x40, 0x0, 0xc42b344076, 0x4, 0xcaccea, 0x1799a60, 0xc425979260, 0xc4223446c0)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/inspect.go:26 +0x176 fp=0xc4363ad650 sp=0xc4363ad608
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersByName(0xc4209ba100, 0x24445e0, 0xc425979350, 0x2440d20, 0xc42dff1450, 0xc4255c4d20, 0xc425979290, 0x18ec285, 0x5)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/container/inspect.go:15 +0xfd fp=0xc4363ad6c8 sp=0xc4363ad650
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersByName)-fm(0x24445e0, 0xc425979350, 0x2440d20, 0xc42dff1450, 0xc4255c4d20, 0xc425979290, 0x4241e8, 0x30)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:47 +0x69 fp=0xc4363ad720 sp=0xc4363ad6c8
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x24445e0, 0xc425979350, 0x2440d20, 0xc42dff1450, 0xc4255c4d20, 0xc425979290, 0x19, 0x1c)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8 fp=0xc4363ad788 sp=0xc4363ad720
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x24445e0, 0xc425979320, 0x2440d20, 0xc42dff1450, 0xc4255c4d20, 0xc425979290, 0x1a09156, 0x4150d5)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5ca fp=0xc4363ad8d8 sp=0xc4363ad788
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x24445e0, 0xc425979320, 0x2440d20, 0xc42dff1450, 0xc4255c4d20, 0xc425979290, 0xc400000000, 0xc423149e60)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x83f fp=0xc4363ada88 sp=0xc4363ad8d8
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2440d20, 0xc42dff1450, 0xc4255c4d20)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x233 fp=0xc4363adb90 sp=0xc4363ada88
Aug 10 09:54:19 service-prd98-13 dockerd: net/http.HandlerFunc.ServeHTTP(0xc420bfe900, 0x2440d20, 0xc42dff1450, 0xc4255c4d20)
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xc4363adbb8 sp=0xc4363adb90
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420e92500, 0x2440d20, 0xc42dff1450, 0xc4255c4d20)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255 fp=0xc4363adca8 sp=0xc4363adbb8
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420d1bd40, 0x2440d20, 0xc42dff1450, 0xc4255c4d20)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70 fp=0xc4363adce0 sp=0xc4363adca8
Aug 10 09:54:19 service-prd98-13 dockerd: net/http.serverHandler.ServeHTTP(0xc420358180, 0x2440d20, 0xc42dff1450, 0xc4255c4d20)
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/net/http/server.go:2202 +0x7d fp=0xc4363add28 sp=0xc4363adce0
Aug 10 09:54:19 service-prd98-13 dockerd: net/http.(*conn).serve(0xc42f561f00, 0x2442960, 0xc43675b880)
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/net/http/server.go:1579 +0x4b7 fp=0xc4363adf88 sp=0xc4363add28
Aug 10 09:54:19 service-prd98-13 dockerd: runtime.goexit()
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4363adf90 sp=0xc4363adf88
Aug 10 09:54:19 service-prd98-13 dockerd: created by net/http.(*Server).Serve
Aug 10 09:54:19 service-prd98-13 dockerd: /usr/local/go/src/net/http/server.go:2293 +0x44d
Aug 10 09:54:19 service-prd98-13 dockerd: goroutine 1 [chan receive, 19821 minutes]:
Aug 10 09:54:19 service-prd98-13 dockerd: main.(*DaemonCli).start(0xc42039ccc0, 0x0, 0x190d6a5, 0x17, 0xc42045e000, 0xc420372640, 0xc42025a3f0, 0x0, 0x0)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:326 +0x183e
Aug 10 09:54:19 service-prd98-13 dockerd: main.runDaemon(0x0, 0x190d6a5, 0x17, 0xc42045e000, 0xc420372640, 0xc42025a3f0, 0x0, 0x0)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:86 +0xb2
Aug 10 09:54:19 service-prd98-13 dockerd: main.newDaemonCommand.func1(0xc42036c000, 0x248cb18, 0x0, 0x0, 0x0, 0x0)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x71
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc42036c000, 0xc42000c260, 0x0, 0x0, 0xc42036c000, 0xc42000c260)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x26d
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42036c000, 0x16fa960, 0xc420372601, 0xc42039a660)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x377
Aug 10 09:54:19 service-prd98-13 dockerd: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42036c000, 0xc42039a660, 0xc42008e058)
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
Aug 10 09:54:19 service-prd98-13 dockerd: main.main()
Aug 10 09:54:19 service-prd98-13 dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:106 +0xe2
```

**Steps to reproduce the issue:**
Actually I cannot reproduce this, since this log file is delivered to me via my colleague

**Describe the results you received:**
docker daemon crashed.

**Describe the results you expected:**
docker daemon runs as usual without crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker 17.03.1-ce
```

**Output of `docker info`:**
I have no these info
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Thanks this should be fixed by https://github.com/moby/moby/pull/33456 which will be in 17.06.1 which is due soon.
