### ISSUE TITLE
`docker ps ` hang with non-blocking mode log

### ISSUE THREAD

**Issue by sqleejan** [moby/moby#34582]
**`docker ps ` hang with non-blocking mode log**

**Steps to reproduce the issue:**
1.set the config of docker daemon with 'mode: non-blocking'&'address:"tcp://..."'
2.pause log server
3.start a container generate lots of logs
4.stop the container
5."docker ps"

**Describe the results you received:**
"docker ps" hang ,no results return 

**Describe the results you expected:**
docker daemon should not be influenced by log server and return the container list

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
17.06.0-ce
```

**Comment by sqleejan** [comment]
TCP receive buffer for storing data is full,causing TCP sends Window=0 message

**Comment by cpuguy83** [comment]
What's the real logger that you are using?
Can you send `SIGUSR1` to the dockerd process and collect the stack trace from the file shown in the dockerd logs?

**Comment by sqleejan** [comment]
I use syslog driver
 
stackdump ->log:
```
goroutine 25448 [IO wait, 33 minutes]:
net.runtime_pollWait(0x7f5436f6dc68, 0x77, 0xc4)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc423055648, 0x77, 0x2617940, 0x260b440)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitWrite(0xc423055648, 0xc42355334a, 0x196)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x34
net.(*netFD).Write(0xc4230555e0, 0xc423553200, 0x2e0, 0x300, 0x14a, 0x2617940, 0x260b440)
	/usr/local/go/src/net/fd_unix.go:340 +0x34d
net.(*conn).Write(0xc421016c78, 0xc423553200, 0x2e0, 0x300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:193 +0x70
github.com/docker/docker/vendor/github.com/RackSec/srslog.(*netConn).writeString(0xc422209270, 0x1a85ef0, 0x1a85998, 0x1e, 0xc422209200, 0x10, 0xc42237a900, 0xb3, 0xc421bbea20, 0x11a, ...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/RackSec/srslog/net_conn.go:23 +0x110
github.com/docker/docker/vendor/github.com/RackSec/srslog.(*Writer).write(0xc4209ba7e0, 0x26191c0, 0xc422209270, 0x1e, 0xc421bbe7e0, 0x11a, 0xc421bbe7e0, 0x119, 0x119)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/RackSec/srslog/writer.go:177 +0xe6
github.com/docker/docker/vendor/github.com/RackSec/srslog.(*Writer).writeAndRetry(0xc4209ba7e0, 0x6, 0xc421bbe7e0, 0x119, 0x25ebea0, 0x17a7f00, 0xc42421fc20)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/RackSec/srslog/writer.go:157 +0x151
github.com/docker/docker/vendor/github.com/RackSec/srslog.(*Writer).Info(0xc4209ba7e0, 0xc421bbe7e0, 0x119, 0x200, 0xc421bbe7e0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/RackSec/srslog/writer.go:141 +0x48
github.com/docker/docker/daemon/logger/syslog.(*syslogger).Log(0xc421016c80, 0xc42421fc20, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/logger/syslog/syslog.go:154 +0xdb
github.com/docker/docker/daemon/logger.(*RingLogger).Close(0xc424a21680, 0xc424f238c0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/logger/ring.go:95 +0xd7
github.com/docker/docker/container.(*Container).Reset(0xc421b91440, 0xc422111400)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/container/monitor.go:42 +0x190
github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc42036a000, 0xc422111400, 0x40, 0xc423f258c0, 0x4, 0x8900000000, 0x0, 0x0, 0x0, 0x0, ...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/monitor.go:47 +0x271
github.com/docker/docker/libcontainerd.(*container).handleEvent.func1()
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/container_unix.go:217 +0x78
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc42204fe00, 0x0, 0xc4211fc820, 0xc424f23860)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/queue_unix.go:28 +0x30
created by github.com/docker/docker/libcontainerd.(*queue).append
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/queue_unix.go:30 +0x16c

```

```
goroutine 26169 [semacquire, 33 minutes]:
sync.runtime_SemacquireMutex(0xc42179b484)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0xc42179b480)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc42036a000, 0xc421b91440, 0xc423678e70, 0xc423303670, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/list.go:210 +0x35
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc42036a000, 0xc422ae1c00, 0xc423303670, 0xc421b9c680, 0xc421b9c680, 0x415338, 0x40, 0x1928360)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/list.go:192 +0x112
github.com/docker/docker/daemon.(*Daemon).Containers(0xc42036a000, 0xc422ae1c00, 0x19fb807, 0x5, 0x2699f40, 0xc421b9c6e8, 0x415338)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/list.go:115 +0x5d
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc420ebc300, 0x7f5436f42128, 0xc4226a4510, 0x2627cc0, 0xc423793c00, 0xc4237a7600, 0xc4226a4450, 0x19fb55a, 0x5)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x20f
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f5436f42128, 0xc4226a4510, 0x2627cc0, 0xc423793c00, 0xc4237a7600, 0xc4226a4450, 0x7f5436f42128, 0xc4226a4510)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f5436f42128, 0xc4226a4510, 0x2627cc0, 0xc423793c00, 0xc4237a7600, 0xc4226a4450, 0x7f5436f42128, 0xc4226a4510)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f5436f42128, 0xc4226a44e0, 0x2627cc0, 0xc423793c00, 0xc4237a7600, 0xc4226a4450, 0xc422ae1bc0, 0xc421b9ca00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f5436f42128, 0xc4226a44e0, 0x2627cc0, 0xc423793c00, 0xc4237a7600, 0xc4226a4450, 0x7f5436f42128, 0xc4226a44e0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x871
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2627cc0, 0xc423793c00, 0xc4237a7600)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc421293a60, 0x2627cc0, 0xc423793c00, 0xc4237a7600)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420fd0550, 0x2627cc0, 0xc423793c00, 0xc4237a7600)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc421a3efb0, 0x2627cc0, 0xc423793c00, 0xc4237a7600)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4200c2d10, 0x2627cc0, 0xc423793c00, 0xc4237a7600)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4219e3720, 0x2629840, 0xc42269a4c0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 25450 [semacquire, 40 minutes]:
sync.runtime_SemacquireMutex(0xc42179b484)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0xc42179b480)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
github.com/docker/docker/container.(*State).IsPaused(0xc42179b480, 0xc422c51607)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/container/state.go:323 +0x2d
github.com/docker/docker/daemon.(*Daemon).ContainerAttach(0xc42036a000, 0xc422c51607, 0x40, 0xc421d9c9f0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/attach.go:33 +0xe7
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersAttach(0xc420ebc300, 0x7f5436f42128, 0xc421d9c930, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00, 0xc421d9c870, 0x19fb55a, 0x5)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:519 +0x36a
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersAttach)-fm(0x7f5436f42128, 0xc421d9c930, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00, 0xc421d9c870, 0x7f5436f42128, 0xc421d9c930)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f5436f42128, 0xc421d9c930, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00, 0xc421d9c870, 0x7f5436f42128, 0xc421d9c930)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f5436f42128, 0xc421d9c900, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00, 0xc421d9c870, 0xc422111740, 0xc423fc8a00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f5436f42128, 0xc421d9c900, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00, 0xc421d9c870, 0x7f5436f42128, 0xc421d9c900)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x871
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2627cc0, 0xc420e68e00, 0xc4244c2c00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc4214d1e60, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420fd0550, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc421a3efb0, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4200c2d10, 0x2627cc0, 0xc420e68e00, 0xc4244c2c00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42283b680, 0x2629840, 0xc422111600)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by sqleejan** [comment]
think "daemon/logger/ring.go" cause the problem

```
func (r *RingLogger) Close(){
    ...
    for _, msg := range r.buffer.Drain() {
       ...
       if err := r.l.Log(msg); err != nil { //r.l.Log(msg) hang up lead to the container'locker can't be released
           ...
       }
       ...
   }
   ...
}
```

**Comment by cpuguy83** [comment]
So ideally this should timeout. We'll need to look at what the syslog logger is doing.

**Comment by cpuguy83** [comment]
@sqleejan Does this ever return (like after a few minutes)?

**Comment by sqleejan** [comment]
@cpuguy83  this will continue ; only when closed log server  can make it return

**Comment by thaJeztah** [comment]
@cpuguy83 did you look into this; is this still an issue with the "no locking" changes in recent versions?

**Comment by cpuguy83** [comment]
This is a little tricky since ideally the socket write would have a timeout on it but it does not, but this happens at such a low level the options to configure the timeout aren't really there.
This will require changes to some of our dependencies.

To fix the immediate issue, we could just drop everything in the log buffer rather than trying to send it.

**Comment by sam-thibault** [comment]
related issue:
- https://github.com/moby/moby/issues/40024
