### ISSUE TITLE
Docker 17.06-ce crash with memory address or nil pointer dereference on libnetwork networkdb.(*NetworkDB).purgeSameNode(

### ISSUE THREAD

**Issue by jetgeng** [moby/moby#34591]
**BUG REPORT INFORMATION**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```

Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: i0yeddylzskjngac1d15obfnz
 Is Manager: true
 ClusterID: hxe9l5dhkjg5uz9nvbpzqdk3p
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.0.25
 Manager Addresses:
  192.168.0.25:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.76GiB
Name: localhost
ID: PLVD:VDG5:KEG2:WLIZ:N3CD:7Z77:4UZQ:LS2L:HBUJ:YM2C:N2YS:2R4F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.0.22:5000
 127.0.0.0/8
Registry Mirrors:
 https://qkgqg5da.mirror.aliyuncs.com/
Live Restore Enabled: false


```

the server was working , someday the server is crash at early morning. and no some special action on the server. the log as follow:

```

Aug 21 00:37:48 localhost dockerd: panic: runtime error: invalid memory address or nil pointer dereference
Aug 21 00:37:48 localhost dockerd: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcacee0]
Aug 21 00:37:48 localhost dockerd: goroutine 340 [running]:
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).purgeSameNode(0xc420bec9c0, 0x0)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/delegate.go:65 +0x90
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).handleNodeEvent(0xc420bec9c0, 0xc420cedb70, 0x100)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/delegate.go:108 +0x184
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*delegate).MergeRemoteState(0xc4202e2868, 0xc4214f4400, 0xfc, 0xfc, 0x0)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/delegate.go:499 +0x27f
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).mergeRemoteState(0xc4201e72c0, 0xc421c08000, 0xc4212581c0, 0x2, 0x2, 0xc4214f4400, 0xfc, 0xfc, 0xfc, 0xfc)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/net.go:989 +0x495
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).pushPullNode(0xc4201e72c0, 0xc421c08000, 0x11, 0x0, 0x0, 0x0)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/state.go:560 +0x1a8
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).pushPull(0xc4201e72c0)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/state.go:545 +0x119
Aug 21 00:37:48 localhost dockerd: github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).pushPullTrigger(0xc4201e72c0, 0xc421577bc0)
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/state.go:157 +0x1a0
Aug 21 00:37:48 localhost dockerd: created by github.com/docker/docker/vendor/github.com/hashicorp/memberlist.(*Memberlist).schedule
Aug 21 00:37:48 localhost dockerd: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/hashicorp/memberlist/state.go:100 +0x347
Aug 21 00:37:48 localhost systemd: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 21 00:37:48 localhost systemd: Unit docker.service entered failed state.
Aug 21 00:37:48 localhost systemd: docker.service failed.
Aug 21 00:37:49 localhost systemd: docker.service holdoff time over, scheduling restart.
```

**Comment by thaJeztah** [comment]
can you update to the latest patch-release for 17.06 (17.06.2)? I believe there was a fix for this in 17.06.1 or 17.06.2

**Comment by thaJeztah** [comment]
ping @jetgeng any update? did upgrading to 17.06.2 resolve your issue?

**Comment by thaJeztah** [comment]
ping @fcrisciani to double check if this is indeed resolved (related to https://github.com/docker/docker-ce/pull/157 ?)

**Comment by fcrisciani** [comment]
This PR definitely avoids that condition: https://github.com/docker/libnetwork/pull/1936
That method does not exists anymore, this will probably will be part of the next 17.10 RC, but up to now just got merged

**Comment by jetgeng** [comment]
@thaJeztah thank you， i have updated to 17.06.2. i am testing!

**Comment by fcrisciani** [comment]
@jetgeng 17.06.2 does not contain that fix :)

**Comment by jetgeng** [comment]
@fcrisciani 17.06.2 has fix this! thanks a lot

**Comment by thaJeztah** [comment]
Let me close this then; thanks!

**Comment by orenye** [comment]
It is not clear in which version the issue was fixed.
@fcrisciani, does it exist in 17.06.2? Does it exist in 17.10?

**Comment by fcrisciani** [comment]
@orenye 17.10 onward has the fix

**Comment by orenye** [comment]
Great, thanks @fcrisciani
