### ISSUE TITLE
The --ipv6 flag won't pass, V6 still False

### ISSUE THREAD

**Issue by ntk148v** [moby/moby#34902]
**Description**

If I run docker network create with a remote network driver and the --ipv6 flag, I expect my remote plugin to be passed the "V6" flag. The expected "V6" must be True with --ipv6 as its description "Enable IPv6 networking", but it isn't.

**Steps to reproduce the issue:**
I use docker libnetwork driver [kuryr-libnetwork](https://github.com/openstack/kuryr-libnetwork). 
> NOTE: All bellow commands require OpenStack installation.
1.  Create neutron network
> $ openstack network create testnet
2.  Create neutron subnet
> $ openstack subnet create --name testsubnetv6 testnet 2001:db8:a0b:12f0::/64
3.  Create neutron subnetpool
> $ openstack subnet pool create --pool-prefix 2001:db8:a0b:12f0::/64 testsubnetpoolv6
4.  Run docker network create:
> $ docker -D network create --ipv6=true -d kuryr --ipam-driver=kuryr --subnet 2001:db8:a0b:12f0::/64 --gateway 2001:db8:a0b:12f0::1 -o neutron.pool.v6.name=testpoolv6 --ipam-opt neutron.pool.v6.name=testpoolv6  foo2

**Describe the results you received:**

```
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]: Traceback (most recent call last):
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:     rv = self.dispatch_request()
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:   File "/opt/stack/kuryr-libnetwork/kuryr_libnetwork/controllers.py", line 1479, in ipam_request_pool
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:     subnet_cidr, pool_id = _get_cidr_from_subnetpool(name=pool_name)
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:   File "/opt/stack/kuryr-libnetwork/kuryr_libnetwork/controllers.py", line 475, in _get_cidr_from_subnetpool
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]:     .format(kwargs))
Sep 20 13:52:17 devstack-zun-1 kuryr-server[29606]: NoResourceException: No subnetpools with {'name': 'kuryr'} is found.
```
- It happens because "V6" is False and the "Pool": "" (empty).
- Do the same with v4 subnet works perfectly.

**Describe the results you expected:**

"V6" : True and "Pool" != Empty.

**Additional information you deem important (e.g. issue happens only occasionally):**

1. Some related issues (almost --ipv6 without --subnet):
- https://github.com/moby/moby/issues/28055
- https://github.com/docker/libnetwork/pull/1538

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 9
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host kuryr macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 6.32GiB
Name: devstack-zun-1
ID: WIX4:F5F2:R6EU:5YDF:65RU:QVOZ:V6NK:NBG3:CHE4:DCU7:CKY3:QB3R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.164.177.170:8080/
Https Proxy: http://10.164.177.170:8080/
No Proxy: localhost,10.164.180.83,10.164.178.123,stack-team3-pc1,10.164.178.166,duonghq,192.168.122,30,192.168.100.30,192.168.100.31,192.168.122.31,127.0.0.1,10.164.180.0/24,10.0.0.0/24,10.164.180.104,10.0.0.1,::1,[::1],172.24.0.0/16,10.164.180.111
Registry: https://index.docker.io/v1/
Experimental: false
Cluster Store: etcd://192.168.100.30:2379
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details:**

Virtual Machine in KVM.

**Comment by thaJeztah** [comment]
Isn't this forwarded to the driver through the `"com.docker.network.enable_ipv6"` option?

**Comment by ntk148v** [comment]
@thaJeztah: Yes, it is not, AFAIK.

**Comment by andrewbonney** [comment]
We've been encountering this issue and I took a further look into it. It's perhaps worth noting that when creating a dual stack network we don't see the same issue, however we have exactly the same problem for IPv6 only.

When running the above example command:
```
$ docker -D network create --ipv6=true -d kuryr --ipam-driver=kuryr --subnet 2001:db8:a0b:12f0::/64 --gateway 2001:db8:a0b:12f0::1 -o neutron.pool.v6.name=testpoolv6 --ipam-opt neutron.pool.v6.name=testpoolv6 foo2
```

With debug logs turned up, we get the following:
```
dockerd[58324]: time="2021-03-18T14:14:50.188856739Z" level=debug msg="Calling POST /v1.40/networks/create"
dockerd[58324]: time="2021-03-18T14:14:50.188968609Z" level=debug msg="form data: {\"Attachable\":false,\"CheckDuplicate\":true,\"ConfigFrom\":null,\"ConfigOnly\":false,\"Driver\":\"kuryr\",\"EnableIPv6\":true,\"IPAM\":{\"Config\":[{\"Gateway\":\"2001:db8:a0b:12f0::1\",\"Subnet\":\"2001:db8:a0b:12f0::/64\"}],\"Driver\":\"kuryr\",\"Options\":{\"neutron.pool.v6.name\":\"testpoolv6\"}},\"Ingress\":false,\"Internal\":false,\"Labels\":{},\"Name\":\"foo2\",\"Options\":{\"neutron.pool.v6.name\":\"testpoolv6\"},\"Scope\":\"\"}"
dockerd[58324]: time="2021-03-18T14:14:50.197916014Z" level=debug msg="Allocating IPv4 pools for network foo2 (6da15c8601001184cc706faf0655d76ed71aacf35c9c43b86f517fd6195eb042)"
dockerd[58324]: time="2021-03-18T14:14:50.282712722Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: IpamDriver.RequestPool: No subnetpools with {'name': 'kuryr'} is found." error_type="*plugins.statusError" module=api
dockerd[58324]: time="2021-03-18T14:14:50.282731817Z" level=error msg="Handler for POST /v1.40/networks/create returned error: IpamDriver.RequestPool: No subnetpools with {'name': 'kuryr'} is found."
dockerd[58324]: time="2021-03-18T14:14:50.282744536Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: IpamDriver.RequestPool: No subnetpools with {'name': 'kuryr'} is found." error_type="*plugins.statusError" module=api
```

Note the debug message regarding creating an **IPv4** network. Looking at https://github.com/moby/libnetwork/blob/d0951081b35fa4216fc4f0064bf065beeb55a74b/network.go#L1542, IPv4 networks always seem to be created first, whether or not they're necessary. This explains why dual stack networks are fine as the v4 allocation will proceed, followed by v6. For pure IPv6 networks however there's a requirement that `ipamAllocateVersion` returns `nil` for things to proceed. Unfortunately (and I'd note I have very little Go knowledge), it appears that https://github.com/moby/libnetwork/blob/d0951081b35fa4216fc4f0064bf065beeb55a74b/network.go#L1620 results in the loop always proceeding, which is what causes the underlying plugin to be called with many missing parameters, and the 'V6' set to false.
