### ISSUE TITLE
Removed services in Docker Swarm Mode (1.17.07) - something continues to write to volumes

### ISSUE THREAD

**Issue by svscorp** [moby/moby#35019]
I am having a very strange behavior on my Docker cluster in Swarm Mode.

When I remove a service that I provisioned with `docker stack deploy` and clean-up volume physical locations I am still getting log files (or other files) appeared in that volume. Somehow.

Setup:

Docker 1.17.07 (Swarm Mode), RHEL 7.3, Kernel 4.13.3 (have second setup with 3.10), "behind the corporate proxy", vxlan, multi-host env.

docker info (swarm master)
````
root@master # docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.07.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local (*using volume driver=local, type=nfs*)
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: aw5r20gz2pr18m9yglk4qwjh4
 Is Manager: true
 ClusterID: b5gds92q3otj9ego2en95qm34
 Managers: 1
 Nodes: 5 (*I drained rest of the nodes*)
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: <manager-ip>
 Manager Addresses:
<manager-ip>:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.3-1.el7.elrepo.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Name: master
ID: DMJT:S6EF:LUAF:PQKX:I5R6:TU2W:JZRH:MVMM:YJC5:MC2K:SGSQ:PXKM
Docker Root Dir: <unique_nfs_mount_folder_for_this_master>/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://<proxy>
Https Proxy: http://<proxy>
No Proxy: <nodes-ips>,<master-ip>,<proxy-ip>,127.0.0.1,localhost,sonar,jenkins
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

````

docker info (swarm node)
````
root@node1 # docker info
Containers: 35
 Running: 17
 Paused: 0
 Stopped: 18
Images: 19
Server Version: 17.07.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local (*use volume driver=local type=nfs*)
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ph3qqr9ti750cc3m741rs1dsm
 Is Manager: false
 Node Address:  <node-ip>
 Manager Addresses:
  <manager-ip>:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp 
  Profile: default
Kernel Version: 4.13.3-1.el7.elrepo.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Name: node1
ID: KR3X:353P:3XHC:Z7M3:ZXU3:W4NI:7N4O:VYMI:MTYR:D47M:UMT4:LKH5
Docker Root Dir: <unique_nfs_mount_folder_for_this_node>/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://<proxy>
Https Proxy: http://<proxy>
No Proxy: <nodes-ips>,<master-ip>,<proxy-ip>,127.0.0.1,localhost,sonar,jenkins
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
````

Steps to reproduce (will be tricky considering whole setup, assuming you have Docker Swarm latest version, latest kernel, volumes are stored on NFS):
1. Provision stack with few services `docker stack deploy stname`
2. Remove a service which has volumes exposed and mounted. `docker service rm stname_sonar`
3. Remove volumes and physical space  `docker volume rm stname_sonar_logs`, `rm -rf <path-to-nfs>/stname_sonar_logs/*`
4. Check the volume folder `ls -la <path-to-nfs>/stname_sonar_logs/*`

**Expected Result:**
Nothing should be inside of the cleaned volume folder

**Actual Result**
Log files appear. And get updated every second. Like something is restarting the app, while it is not.

````
017.09.28 12:59:09 INFO  web[o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2017.09.28 12:59:09 WARN  web[o.s.p.ProcessEntryPoint] Fail to start web
java.lang.IllegalStateException: Webapp did not start
        at org.sonar.server.app.EmbeddedTomcat.isUp(EmbeddedTomcat.java:84) ~[sonar-server-5.6.3.jar:na]
        at org.sonar.server.app.WebServer.isUp(WebServer.java:47) [sonar-server-5.6.3.jar:na]
        at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:105) ~[sonar-process-5.6.3.jar:na]
        at org.sonar.server.app.WebServer.main(WebServer.java:68) [sonar-server-5.6.3.jar:na]
2017.09.28 12:59:09 INFO  web[o.a.c.h.Http11NioProtocol] Pausing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2017.09.28 12:59:10 INFO  web[o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2017.09.28 12:59:10 INFO  web[o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2017.09.28 12:59:10 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
````

How can it be if `docker ps -a` on all nodes, `docker volume ls` doesn't show anything to do with sonar anymore.

I got that yesterday and was fighting it for few days with another application - something was overriding volume files, even though containers and services were removed.

Thank you in advance.

**Comment by svscorp** [comment]
It looks like it's another swarm with the same name that is pointed to the same named NFS volumes. I'll be checking this additionally. If so, issue can be closed.

**Comment by thaJeztah** [comment]
Thanks for the update, that sounds like a plausible explanation. I'll go ahead and close this issue for housekeeping, but feel free to comment if you still suspect there's a bug

**Comment by svscorp** [comment]
@thaJeztah looks like it was the problem. Sorry. When working too much on an issue - hard to spot some obvious things.

Now I am back to my core issue with a running services (Nginx in particular) suddenly stop authenticating themselves with LDAP (running on another node). Container restart helps. I am thinking, maybe it is related to one of the "network/overlay" issues in Swarm.

````
2017/09/28 14:17:42 [error] 214#0: *20 http_auth_ldap: Authentication timed out, client: 10.255.0.2, server: ~^[0-9]*, request: "GET / HTTP/1.1", host: "127.0.0.1"
2017/09/28 14:17:48 [info] 214#0: *21 client closed connection while waiting for request, client: 10.255.0.2, server: 0.0.0.0:443
````
