### ISSUE TITLE
libnetwork panic on master

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#35308]
Libnetwork paniced on a CI run: https://jenkins.dockerproject.org/job/Docker-PRs/46197/console

ping @fcrisciani 

```
time="2017-10-25T21:09:55.252549097Z" level=debug msg="Did not find any interface with name br-n3lapw5yeouc: Link not found"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x122a050]

goroutine 350 [running]:
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).conflictsWithNetworks(0xc4202cd8c0, 0xc42048f280, 0x19, 0xc42080b010, 0x2, 0x2, 0x0, 0x410bc8)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:349 +0xf0
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).createNetwork(0xc4203b11d0, 0xc4202cd8c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:686 +0x9b3
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).CreateNetwork(0xc4203b11d0, 0xc42048f280, 0x19, 0xc42129fd40, 0x2b78d80, 0xc420825d40, 0xc4212dac90, 0x1, 0x1, 0x2c13940, ...)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:610 +0x21c
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).addNetwork(0xc42047a800, 0xc420825d40, 0xc4211a95a0, 0xc420825d40)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:945 +0x157
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).NewNetwork(0xc42047a800, 0xc420833820, 0x6, 0xc420833800, 0xd, 0xc42048f280, 0x19, 0xc420e141e0, 0x9, 0xc, ...)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:807 +0xb00
github.com/docker/docker/daemon.(*Daemon).createNetwork(0xc4202eea00, 0x1, 0xc420833820, 0x6, 0x1da01eb, 0x5, 0x0, 0xc421267560, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/network.go:361 +0x5c0
github.com/docker/docker/daemon.(*Daemon).CreateManagedNetwork(0xc4202eea00, 0xc42048f280, 0x19, 0x1, 0xc420833820, 0x6, 0x1da01eb, 0x5, 0x0, 0xc421267560, ...)
	/go/src/github.com/docker/docker/daemon/network.go:258 +0x8f
github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).createNetworks(0xc4212663c0, 0x7f06e0eca390, 0xc420fd1f00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:152 +0x126
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Prepare(0xc4211c5220, 0x7f06e0eca390, 0xc420fd1f00, 0xc4212d4718, 0x2ba0980)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:102 +0x85
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec.Do(0x7f06e0eca390, 0xc420fd1f00, 0xc421380b40, 0x2ba0980, 0xc4211c5220, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec/controller.go:308 +0x9a0
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run.func2(0x7f06e1f0c0f0, 0xc421237b90, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:134 +0xe1
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.runctx(0x7f06e1f0c0f0, 0xc421237b90, 0xc4203a4a20, 0xc4201f5bc0, 0xc420fe20c0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/helpers.go:9 +0x55
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:150 +0x5cd
```

**Comment by mountkin** [comment]
This was fixed by https://github.com/docker/libnetwork/pull/1918 , which was merged to moby in https://github.com/moby/moby/commit/c1e1fb6fa5204bb7014ca9ebab9fe1804c1eb957

**Comment by thaJeztah** [comment]
Thanks @mountkin - closing 👍
