### ISSUE TITLE
dockerd panic when running LCOW container on 1709

### ISSUE THREAD

**Issue by peterschen** [moby/moby#35302]
**Description**
When trying running a linux container on Windows Server 1709 dockerd arrives at a panic.

**Steps to reproduce the issue:**
1. Setup LCOW/LinuxKit as per https://blog.docker.com/2017/09/preview-linux-containers-on-windows/ and https://gist.github.com/rn/6bfade1ba98e22691cb287cc8c23609b
2. ```.\dockerd.exe -D --experimental -H 0.0.0.0:12375 --data-root "C:\lcow"```
3. ```docker run -H localhost:12375 tomcat```

**Describe the results you received:**
CLI output:
```
error during connect: Post http://app1:12375/v1.34/containers/3a6eeaa74074db85672d44bfa35b6acdb245dd2f6a8e11c1024cc201b573c880/start: EOF.
```
dockerd output:
```
2017-10-26 09:50:18.095017 I | http: panic serving 10.4.0.253:50557: runtime error: invalid memory address or nil
pointer dereference
goroutine 228 [running]:
net/http.(*conn).serve.func1(0xc0423da500)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0x1809ac0, 0x24d2ed0)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/docker/docker/daemon.(*Daemon).createSpec(0xc042446400, 0xc042106480, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/oci_windows.go:220 +0x1208
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc042446400, 0xc042106480, 0x0, 0x0, 0x0, 0x0, 0x2520801,
0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/start.go:156 +0x279
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc042446400, 0xc042418407, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0,
0x176e060, 0xc043181601)
        /go/src/github.com/docker/docker/daemon/start.go:94 +0x1c3
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc0423709c0, 0x480c8e8,
0xc042752060, 0x2485940, 0xc0421081c0, 0xc0423f2a00, 0xc04272fec0, 0x1a636f1, 0x4)
        /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:163 +0x26f
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/con
tainer.postContainersStart)-fm(0x480c8e8, 0xc042752060, 0x2485940, 0xc0421081c0, 0xc0423f2a00, 0xc04272fec0,
0x480c8e8, 0xc042752060)
        /go/src/github.com/docker/docker/api/server/router/container/container.go:66 +0x70
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x480c8e8, 0xc042752060,
0x2485940, 0xc0421081c0, 0xc0423f2a00, 0xc04272fec0, 0x480c8e8, 0xc042752060)
        /go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xdf
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x480c8e8, 0xc04272ff50, 0x2485940,
0xc0421081c0, 0xc0423f2a00, 0xc04272fec0, 0x10, 0x10)
        /go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x4b2
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x480c8e8, 0xc04272ff50, 0x2485940,
0xc0421081c0, 0xc0423f2a00, 0xc04272fec0, 0xc042af5ab0, 0x756ea152ce6e8f)
        /go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x878
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x480c8e8, 0xc04272ff50, 0x2485940,
0xc0421081c0, 0xc0423f2a00, 0xc04272fec0, 0x480c8e8, 0xc04272ff50)
        /go/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x9b9
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2485940, 0xc0421081c0, 0xc0423f2a00)
        /go/src/github.com/docker/docker/api/server/server.go:137 +0x221
net/http.HandlerFunc.ServeHTTP(0xc0427c8240, 0x2485940, 0xc0421081c0, 0xc0423f2a00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc04245e0f0, 0x2485940, 0xc0421081c0,
0xc0423f2a00)
        /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x25c
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc042a42210, 0x2485940, 0xc0421081c0, 0xc0423f2a00)
        /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x77
net/http.serverHandler.ServeHTTP(0xc0423c2f20, 0x2485940, 0xc0421081c0, 0xc0423f2a00)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0423da500, 0x2487480, 0xc042371a40)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
```
**Describe the results you expected:**
Running container

**Output of `docker version`:**

```
Client:
 Version:      master-dockerproject-2017-10-25
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   9b7656c
 Built:        Thu Oct 26 00:05:37 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-10-25
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.4
 Git commit:   074b1fc
 Built:        Thu Oct 26 00:09:38 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: master-dockerproject-2017-10-25
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 9.999GiB
Name: APP1
ID: WIFB:YLX2:BFTR:4UDU:DENY:YKWJ:ZL7D:MDAS:Q3MR:URDS:GMZU:GUKO
Docker Root Dir: C:\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 30
 System Time: 2017-10-26T09:55:41.3030541+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The docker host running Windows Server 1709 is nested within a Windows 10 1709. I'm not sure if this is relevant to this issue.

**Comment by thaJeztah** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
Looks like a regression introduced by https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-a1f5051ce84e711a2ee688ab9ded5e74L73 in https://github.com/moby/moby/pull/34895

I'll submit a fix shortly.

**Comment by jhowardmsft** [comment]
@mlaventure ^^ FYI

**Comment by mlaventure** [comment]
Indeed, missing an init. I wonder why CI didn't catch it, may need to add a test.

**Comment by jhowardmsft** [comment]
There's no RS3 CI yet, and no LCOW CI at all. 

Should root be init for LCOL as well? I've fixed it for LCOW, but not submitted a PR as there's a further break in the containerd integration which causes LCOW container start to fail - am investigating currently and will submit a PR for both fixes together.

**Comment by mlaventure** [comment]
I don't think there's any penalty at having it initialized in all cases
