### ISSUE TITLE
Error grabbing logs: EOF when tailing container logs

### ISSUE THREAD

**Issue by jamesongithub** [moby/moby#35370]
**Description**
Seem to be having issues tailing logs after upgrading to 17.09.0-ce. Was working on 17.06.0-ce

**Steps to reproduce the issue:**
1. Create container
2. Start container
3. Tail logs

**Describe the results you received:**
```
20:34:13 Error grabbing logs: EOF
20:34:13 [localhost] local: git checkout ./.dockerignore
20:34:13 Traceback (most recent call last):
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
20:34:13     *args, **kwargs
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
20:34:13     results['<local-only>'] = task.run(*args, **new_kwargs)
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
20:34:13     return self.wrapped(*args, **kwargs)
20:34:13   File "$PATH@2/fabfile/__init__.py", line 142, in run_e2e_tests
20:34:13     e2e_tests.run(specs)
20:34:13   File "$PATH@2/fabfile/e2e_tests.py", line 69, in run
20:34:13     docker_build.copy_from(build_tag, '/blend/e2e/artifacts/.', 'artifacts')
20:34:13   File "$PATH@2/fabfile/docker_build.py", line 240, in copy_from
20:34:13     with tarfile.open(mode='r|*', fileobj=container.get_archive(source)[0]) as tarball:
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/docker/models/containers.py", line 194, in get_archive
20:34:13     return self.client.api.get_archive(self.id, path)
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
20:34:13     return f(self, resource_id, *args, **kwargs)
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 34, in wrapper
20:34:13     return f(self, *args, **kwargs)
20:34:13   File "/mnt/jenkins-slave/workspace/blend-test-e2e-multitenant@2/venv/local/lib/python2.7/site-packages/docker/api/container.py", line 732, in get_archive
20:34:13     self._raise_for_status(res)
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
20:34:13     raise create_api_error_from_http_exception(e)
20:34:13   File "$PATH@2/venv/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
20:34:13     raise cls(e, response=response, explanation=explanation)
```

**Describe the results you expected:**
```
No exception.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 19
 Running: 7
 Paused: 0
 Stopped: 12
Images: 40
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: REDACT
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69GiB
Name: REDACT
ID: 4NVG:MGS6:QUMP:GA7Z:5CPC:UVA2:AA2Q:XIL4:PSCM:QMX4:SULJ:Y4XQ
Docker Root Dir: REDACT
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 118
 Goroutines: 131
 System Time: 2017-11-01T21:28:08.293959958Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Executed using docker-py python library.

```
container.logs(
        follow=True,
        stdout=True,
        stderr=True,
        stream=True,
        tail=2
    )
```

**Comment by jamesongithub** [comment]
@shin- don't know if this is docker-py related.

**Comment by shin-** [comment]
There's more info on this issue here: https://github.com/docker/for-win/issues/1235

I don't believe it's related to what we do in the python SDK or Compose, as reports indicate the same error occurs while using the docker CLI as well (e.g. https://github.com/dokku/dokku/issues/2898#issuecomment-327059061, https://github.com/docker/for-win/issues/1235#issuecomment-341221030)

It looks like the error occurs here in the Engine code: https://github.com/moby/moby/blob/147443a42665419d8b3c2047a7d345440bfb63c0/api/server/httputils/write_log_stream.go#L43

**Comment by jamesongithub** [comment]
ok thanks.

**Comment by jamesongithub** [comment]
Looks like affects 17.06.2-ce also.

**Comment by thaJeztah** [comment]
Are you using log-rotation? Is this for every container or a specific one? And do you see the same problem if you use the docker CLI to read the logs for the same container?

**Comment by jamesongithub** [comment]
Not using log-rotation. Happened for every occurence in our test builds. I haven't been able to replicate with CLI yet since we reverted everything back to 12.06.0. I remember `docker logs` worked, however it didn't occur to me to try to use tail at that time.

**Comment by omidahangari** [comment]
any update?

**Comment by gesellix** [comment]
I also stumbled on that error from a Java remote engine api client which first runs a container and then tries to fetch the logs. More specifically it would look like this if I would use the official Docker client:

```
docker run -P --name my-tomcat --net my-net --env foo=bar --env bar=baz tomcat
docker logs -f my-tomcat
```

When I add a `sleep(5 seconds)` between `docker run` and `docker logs`, then the error disappears. Not sure if relevant, but there are also some other containers starting (e.g. `mongodb`) just before the `my-tomcat` container.

My setup is like follows:

```
$ docker info
Containers: 8
 Running: 2
 Paused: 0
 Stopped: 6
Images: 475
Server Version: 17.12.0-ce-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: P33I:5Y3R:WMDQ:PUHA:5PSW:2B2L:XWG6:TOO6:VGME:BLFB:KMBV:74DH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 53
 System Time: 2017-12-29T23:10:12.992176421Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
$ docker version
Client:
 Version:	17.12.0-ce-rc4
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	6a2c058
 Built:	Wed Dec 20 15:53:52 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce-rc4
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	6a2c058
  Built:	Wed Dec 20 15:59:49 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Comment by vblazhnov** [comment]
Having the same issue with accessing logs via API using https://github.com/fsouza/go-dockerclient/ 

``` #docker info
Containers: 9
 Running: 8
 Paused: 0
 Stopped: 1
Images: 579
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.617GiB
Name: dev
ID: RFLQ:FVJN:B4RH:MRW3:722I:EFEF:FJ5M:LSAY:NDVA:Y6A6:NTEF:CWNM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

# docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by cpuguy83** [comment]
#36305 fixes this.
