### ISSUE TITLE
Docker swarm service logs error

### ISSUE THREAD

**Issue by masonb81** [moby/moby#35489]
When running docker service logs service_name, we get the following error:

vnext-backend-demo.1.xs4et82l5v7om3ec7av0d0566@moby    | [18:49:30 INF] Request finished in 5.896ms 200
vnext-backend-demo.1.xov7hvc52nshl4uy3ord1dk7k@moby    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
vnext-backend-demo.1.xov7hvc52nshl4uy3ord1dk7k@moby    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
**error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: illegal wireType 7**

We are running docker windows with swarm using 1 node. Here is the docker version output

$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

The host machine is Windows Server 2016.

**Comment by thaJeztah** [comment]
ping @dperny PTAL

**Comment by smyrman** [comment]
We got the same error on Linux, using a locak client
```
 docker -H REMOTE_HOST version
Client:
 Version:      17.09.0-ce
 API version:  1.31 (downgraded from 1.32)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:46:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by smyrman** [comment]
As an FYI: I tried to `ssh` to the manger to find out if the problem was the same when using the swarm server docker client, but by the time the problem seams to have resolved itself...

**Comment by smyrman** [comment]
As another FYI, without concluding on anything, we at least have a theory that the issue our side is caused by low disk-space on the Swarm nodes.

**Comment by thaJeztah** [comment]
I'll close this issue as it looks to have gone stale, and we don't have a reproducer.
