### ISSUE TITLE
docker daemon panics on serving HTTP request

### ISSUE THREAD

**Issue by 3van** [moby/moby#35581]
**Description**
`dockerd` panics whenever I try to issue commands over an HTTP/HTTPS connection. Commands issued to the local unix domain socket work fine.

**Steps to reproduce the issue:**
1. Configure systemd with a socket activation-based unit listening on the HTTP/HTTPS ports for dockerd
2. Issue a command to the socket

**Describe the results you received:**
`Nov 22 15:55:20 cetuximab dockerd-current[1089]: http: panic serving 192.168.69.101:61061: reflect: call of reflect.Value.Elem on zero Value`

**Describe the results you expected:**
Not panicking.

**Additional information you deem important (e.g. issue happens only occasionally):**
Full stacktrace:
```
http: panic serving 192.168.69.101:61062: reflect: call of reflect.Value.Elem on zero Value
         goroutine 136 [running]:
         net/http.(*conn).serve.func1(0xc4204761e0)
                 /usr/lib/golang/src/net/http/server.go:1721 +0xd0
         panic(0x17966e0, 0xc420270ca0)
                 /usr/lib/golang/src/runtime/panic.go:489 +0x2cf
         reflect.Value.Elem(0x0, 0x0, 0x0, 0x1a05f51, 0x2, 0x0)
                 /usr/lib/golang/src/reflect/value.go:752 +0x123
         github.com/docker/docker/api/server/middleware.getFdFromWriter(0x25ed2c0, 0xc4204ff340, 0xc420ba0706)
                 /builddir/build/BUILD/docker-877b6df065ba431384723ef496a2d5240ae96a94/_build/src/github.com/docker/docker/api/server/middleware/audit_linux.go:78 +0x303
         github.com/docker/docker/api/server/middleware.logAction(0x25ed2c0, 0xc4204ff340, 0xc42000ad00, 0xc42008c600, 0x17102e0, 0xc420d81a98)
                 /builddir/build/BUILD/docker-877b6df065ba431384723ef496a2d5240ae96a94/_build/src/github.com/docker/docker/api/server/middleware/audit_linux.go:221 +0x107
         github.com/docker/docker/api/server/middleware.AuditMiddleware.WrapHandler.func1(0x25f0c40, 0xc420ba0870, 0x25ed2c0, 0xc4204ff340, 0xc42000ad00, 0xc420ba0810, 0xc4208d5cb8, 0x46aed3)
                 /builddir/build/BUILD/docker-877b6df065ba431384723ef496a2d5240ae96a94/_build/src/github.com/docker/docker/api/server/middleware/audit_linux.go:26 +0x55
         github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x25ed2c0, 0xc4204ff340, 0xc42000ad00)
                 /builddir/build/BUILD/docker-877b6df065ba431384723ef496a2d5240ae96a94/_build/src/github.com/docker/docker/api/server/server.go:146 +0x230
         net/http.HandlerFunc.ServeHTTP(0xc420400dc0, 0x25ed2c0, 0xc4204ff340, 0xc42000ad00)
                 /usr/lib/golang/src/net/http/server.go:1942 +0x44
         github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420044c80, 0x25ed2c0, 0xc4204ff340, 0xc42000ad00)
                 /builddir/build/BUILD/docker-877b6df065ba431384723ef496a2d5240ae96a94/_build/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
         github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420b81710, 0x25ed2c0, 0xc4204ff340, 0xc42000ad00)
                 /builddir/build/BUILD/docker-877b6df065ba431384723ef496a2d5240ae96a94/_build/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
         net/http.serverHandler.ServeHTTP(0xc4201922c0, 0x25ed2c0, 0xc4204ff340, 0xc42000ad00)
                 /usr/lib/golang/src/net/http/server.go:2568 +0x92
         net/http.(*conn).serve(0xc4204761e0, 0x25eef80, 0xc4204cd380)
                 /usr/lib/golang/src/net/http/server.go:1825 +0x612
         created by net/http.(*Server).Serve
                 /usr/lib/golang/src/net/http/server.go:2668 +0x2ce
```
I have an `override.conf` in `/etc/systemd/system/docker.service.d` that adds my two sockets to the `Requires` for the service unit, and added `-H fd://` to the CLI options in `/etc/sysconfig/docker`

Socket unit in question:
```
[Unit]
Description=secured TCP socket for docker
PartOf=docker.service

[Socket]
ListenStream=2376
BindIPv6Only=both
Service=docker.service

[Install]
WantedBy=sockets.target
```

**Output of `docker version`:**
```
[evan.kinney@cetuximab ~]$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.4
 Git commit:      877b6df/1.13.1
 Built:           Fri Nov  3 18:36:10 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.4
 Git commit:      877b6df/1.13.1
 Built:           Fri Nov  3 18:36:10 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `docker info`:**
```
[evan.kinney@cetuximab ~]$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.13.1
Storage Driver: btrfs
 Build Version: Btrfs v4.9.1
 Library Version: 102
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: runc oci
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 4.13.14-200.fc26.x86_64
Operating System: Fedora 26 (Twenty Six)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 3.856 GiB
Name: cetuximab
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure), registry.fedoraproject.org (secure), registry.access.redhat.com (secure), docker.io (secure), hub.ol.epicgames.net (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Shouldn't matter, but this is in a VirtualBox VM on Fedora 26, using the latest docker package in the Fedora repos (`docker-1.13.1-40.git877b6df.fc26.x86_64`).

**Comment by 3van** [comment]
There was some [refactoring done to the netFD struct](https://github.com/golang/go/commit/3792db518327c685da17ca6c6faa4e1d2da4c33c#diff-2bd4b6db4c434f0fc104d159813965e9L24), but that didn't land until go 1.9.2 and I don't see any backported patches for this in the go package in the F26 repo.

**Comment by thaJeztah** [comment]
It looks like you're running the Red Hat fork of Docker, not the official packages. That fork is not maintained here's, contains a lot of modifications, and we can't provide support for those packages.

Are you able to reproduce this on an official build of Docker (https://docs.docker.com/engine/installation/linux/docker-ce/fedora/)?

Also note that Docker 1.13 has reached EOL last April, and is no longer maintained

**Comment by 3van** [comment]
Oops. I didn't realize the Fedora package was using Red Hat's fork.

Works fine on latest stable from the docker-ce repo. I'll go stick this in their Bugzilla.

Thanks - I'll see myself out. :sunglasses:

**Comment by thaJeztah** [comment]
No problem! Good to hear it works using `docker-ce` 👍
