### ISSUE TITLE
Manager nodes failing after update to Docker 17.11.0

### ISSUE THREAD

**Issue by kinghuang** [moby/moby#35657]
**Description**

I updated a 10-node swarm from Docker CE 17.09.0 to 17.11.0. 3 of the nodes are managers. The Docker engine keeps crashing on the manager nodes.

**Steps to reproduce the issue:**

1. Upgrade an existing swarm from Docker CE 17.09.0 to 17.11.0.

**Describe the results you received:**

The Docker Engines on the three manager nodes keep crashing. Logs show a big Go stack trace. Here's the first few lines. Full log file attached.

```
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: fatal error: bad map state
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: goroutine 67607 [running]:
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: runtime.throw(0x2a6e1af, 0xd)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42748b6c0 sp=0xc42748b6a0
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: runtime.evacuate(0x2796a40, 0xc42028cde0, 0x13)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /usr/local/go/src/runtime/hashmap.go:997 +0x932 fp=0xc42748b7b0 sp=0xc42748b6c0
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: runtime.growWork(0x2796a40, 0xc42028cde0, 0x1a)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /usr/local/go/src/runtime/hashmap.go:957 +0x9f fp=0xc42748b7d8 sp=0xc42748b7b0
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: runtime.mapassign(0x2796a40, 0xc42028cde0, 0xc42748b8b8, 0x40)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /usr/local/go/src/runtime/hashmap.go:513 +0x5d5 fp=0xc42748b878 sp=0xc42748b7d8
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: github.com/docker/docker/daemon.(*Daemon).registerExecPidUnlocked(0xc42040ea00, 0xc4261acb40, 0xc427a04000)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/exec.go:39 +0x218 fp=0xc42748b918 sp=0xc42748b878
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: github.com/docker/docker/daemon.(*Daemon).ContainerExecStart(0xc42040ea00, 0x7f375eafefc8, 0xc4242e75c0, 0xc424e455c0, 0x40, 0x0, 0x0, 0x381ea80, 0xc42012d700, 0x381ea80, ...)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/exec.go:256 +0xa64 fp=0xc42748bd70 sp=0xc42748b918
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: github.com/docker/docker/daemon.(*cmdProbe).run(0xc42551e821, 0x7f375eafefc8, 0xc4242e75c0, 0xc42040ea00, 0xc4261acb40, 0x11670c5, 0xc42001ff00, 0x21a9f62)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/health.go:94 +0x5a7 fp=0xc42748bea8 sp=0xc42748bd70
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: github.com/docker/docker/daemon.monitor.func1(0x381ea00, 0xc42551e821, 0x7f375eafefc8, 0xc4242e75c0, 0xc42040ea00, 0xc4261acb40, 0xc4242e7620, 0xed1b2df1f, 0xc422819abf, 0x3894ec0)
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/health.go:198 +0xb0 fp=0xc42748bf90 sp=0xc42748bea8
Nov 30 22:26:55 itrmsdev02.ucalgary.ca dockerd[1196]: runtime.goexit()
```

[docker.log](https://github.com/moby/moby/files/1520537/docker.log)

**Describe the results you expected:**

The manager nodes should work normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

If the managers are re-added to the swarm (after unlocking), service tasks start scaling up unexpectedly (i.e., services with a scale of 1 starting rising to 2/1 or 3/1 tasks).

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:06 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 32
 Running: 14
 Paused: 0
 Stopped: 18
Images: 40
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: sy4tk0fkmicikubo4nw9bvfap
 Is Manager: true
 ClusterID: rybcwsnikz7kvb1lpslbwyjeu
 Managers: 3
 Nodes: 10
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: true
 Root Rotation In Progress: false
 Node Address: 10.41.149.137
 Manager Addresses:
  10.41.149.137:2377
  10.41.149.138:2377
  10.41.149.139:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26GiB
Name: itrmsdev01.ucalgary.ca
ID: MYIJ:6PFS:CZR5:QGU6:2ZBA:S3T7:3ER5:3QRM:5QYB:ZM22:SH6N:S2JP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

10-node swarm on RHEL 7.4 VMs.

**Comment by kinghuang** [comment]
Closing this old issue. The cluster was rolled back to 17.09.0, and later upgraded to 18.03.0. Both of those did not exhibit the problem.
