### ISSUE TITLE
Flaky Test: DockerSwarmSuite.TestAPISwarmServicesUpdateStartFirst

### ISSUE THREAD

**Issue by tophj-ibm** [moby/moby#35775]
Seen across multiple platforms
```
08:38:00 FAIL: check_test.go:366: DockerSwarmSuite.TearDownTest
08:38:00 
08:38:00 check_test.go:371:
08:38:00     d.Stop(c)
08:38:00 daemon/daemon.go:395:
08:38:00     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
08:38:00 ... Error: Error while stopping the daemon d5cbb4a3e9c35 : exit status 130
08:38:00 
08:38:00 
08:38:00 ----------------------------------------------------------------------
08:38:00 PANIC: docker_api_swarm_service_test.go:201: DockerSwarmSuite.TestAPISwarmServicesUpdateStartFirst
08:38:00 
08:38:00 [d5cbb4a3e9c35] waiting for daemon to start
08:38:00 [d5cbb4a3e9c35] daemon started
08:38:00 
08:38:00 [d5cbb4a3e9c35] daemon started
08:38:00 Attempt #2: daemon is still running with pid 9137
08:38:00 Attempt #3: daemon is still running with pid 9137
08:38:00 Attempt #4: daemon is still running with pid 9137
08:38:00 [d5cbb4a3e9c35] exiting daemon
08:38:00 ... Panic: Fixture has panicked (see related PANIC)
08:38:00 
08:38:00 ----------------------------------------------------------------------
```

log from https://jenkins.dockerproject.org/job/Docker-PRs-experimental/38353/consoleFull

failing daemon log here:
https://gist.githubusercontent.com/tophj-ibm/a6dc27c599b6fc1117314c2afcad7b0e/raw/fdf7d079e58f7e320c446d6c43bc3dfc52e969ec/gistfile1.txt

**Comment by seemethere** [comment]
Seeing this a lot as well but on ppc64le

**Comment by cpuguy83** [comment]
`IsRunning()` check blocked here:
```
goroutine 3544 [semacquire]:
sync.runtime_SemacquireMutex(0xc421b20b04, 0xc421932000)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc421b20b00)
	/usr/local/go/src/sync/mutex.go:134 +0xee
github.com/docker/docker/container.(*State).IsRunning(0xc421b20b00, 0xc421a16cc0)
	/go/src/github.com/docker/docker/container/state.go:250 +0x2d
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc420408000, 0xc421a16cc0, 0x26, 0x0, 0x14cbf78, 0x0)
	/go/src/github.com/docker/docker/daemon/stop.go:23 +0x84
github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).shutdown(0xc421bf7290, 0x7fe898c190b0, 0xc4212dd740, 0x2, 0xc4202d7690)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:356 +0x9d
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Shutdown(0xc4216334a0, 0x7fe898c190b0, 0xc4212dd740, 0xc420e42400, 0xc4202d7730)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:348 +0xa2
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Remove(0xc4216334a0, 0x7fe898c190b0, 0xc4212dd740, 0x7fe898c190b0, 0xc4212dd740)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:391 +0x77
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.reconcileTaskState.func1(0xc421b14c60)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/worker.go:267 +0xa7
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.reconcileTaskState
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/worker.go:295 +0x1105
```

Which is being blocked by:
```
goroutine 3068 [select]:
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc4216ff440, 0x1de0978, 0xc421c790e0, 0x2bc33a0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:256 +0x146
github.com/docker/docker/vendor/google.golang.org/grpc.recvResponse(0x7fe898c190b0, 0xc4217012c0, 0xc4200d3d20, 0xc4200d3d40, 0x2bb9b60, 0x2c409c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:64 +0xac
github.com/docker/docker/vendor/google.golang.org/grpc.invoke(0x7fe898c190b0, 0xc4217012c0, 0x1d8b18a, 0x28, 0x1bf64e0, 0xc421701200, 0x1c580a0, 0x2c409c0, 0xc420419ba0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:279 +0xcfe
github.com/docker/docker/vendor/github.com/containerd/containerd.namespaceInterceptor.unary(0x1d4609e, 0x4, 0x7fe898c15030, 0xc420018028, 0x1d8b18a, 0x28, 0x1bf64e0, 0xc421701200, 0x1c580a0, 0x2c409c0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:18 +0xf4
github.com/docker/docker/vendor/github.com/containerd/containerd.(namespaceInterceptor).(github.com/docker/docker/vendor/github.com/containerd/containerd.unary)-fm(0x7fe898c15030, 0xc420018028, 0x1d8b18a, 0x28, 0x1bf64e0, 0xc421701200, 0x1c580a0, 0x2c409c0, 0xc420419ba0, 0x1de0950, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:34 +0xf4
github.com/docker/docker/vendor/google.golang.org/grpc.Invoke(0x7fe898c15030, 0xc420018028, 0x1d8b18a, 0x28, 0x1bf64e0, 0xc421701200, 0x1c580a0, 0x2c409c0, 0xc420419ba0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:141 +0xdd
github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1.(*tasksClient).Kill(0xc420f0b970, 0x7fe898c15030, 0xc420018028, 0xc421701200, 0x0, 0x0, 0x0, 0xc421857470, 0xc42162e870, 0x10)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:468 +0xd2
github.com/docker/docker/vendor/github.com/containerd/containerd.(*task).Kill(0xc421857470, 0x2bba360, 0xc420018028, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/task.go:180 +0x206
github.com/docker/docker/libcontainerd.(*client).SignalProcess(0xc420142380, 0x2bba360, 0xc420018028, 0xc42158d100, 0x40, 0x1d45f8e, 0x4, 0xf, 0xc421cd6120, 0xc420e66f00)
	/go/src/github.com/docker/docker/libcontainerd/client_daemon.go:361 +0xd6
github.com/docker/docker/daemon.(*Daemon).kill(0xc420408000, 0xc421c0b8c0, 0xf, 0x2, 0x2)
	/go/src/github.com/docker/docker/daemon/kill.go:179 +0x8c
github.com/docker/docker/daemon.(*Daemon).killWithSignal(0xc420408000, 0xc421c0b8c0, 0xf, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/kill.go:99 +0x243
github.com/docker/docker/daemon.(*Daemon).killPossiblyDeadProcess(0xc420408000, 0xc421c0b8c0, 0xf, 0x27, 0xc42158d100)
	/go/src/github.com/docker/docker/daemon/kill.go:169 +0x4c
github.com/docker/docker/daemon.(*Daemon).containerStop(0xc420408000, 0xc421c0b8c0, 0xa, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/stop.go:48 +0xaa
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc420408000, 0xc421a16e70, 0x26, 0x0, 0x14cbf78, 0x0)
	/go/src/github.com/docker/docker/daemon/stop.go:30 +0xc5
github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).shutdown(0xc421bf7290, 0x7fe898c191e0, 0xc4212bbc80, 0x7fe89a46f000, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:356 +0x9d
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Shutdown(0xc4216334a0, 0x7fe898c191e0, 0xc4212bbc80, 0xc420f0b960, 0x2bc2980)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:348 +0xa2
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec.Do(0x7fe898c191e0, 0xc4212bbc80, 0xc421bf9c20, 0x2bc2980, 0xc4216334a0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec/controller.go:298 +0x34f
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run.func2(0x7fe898c190b0, 0xc421c0cf30, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:134 +0xe1
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.runctx(0x7fe898c190b0, 0xc421c0cf30, 0xc421631380, 0xc420ec5e00, 0xc4212bbd80)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/helpers.go:9 +0x55
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:122 +0xf9d
```

**Comment by cpuguy83** [comment]
Here's another one, these are all deadlocks waiting on containerd streams... could be a race in moby code or in containerd.

```
goroutine 3081 [select]:
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc420ef1d40, 0x1de2e68, 0xc421129030, 0x2bc63a0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:256 +0x146
github.com/docker/docker/vendor/google.golang.org/grpc.recvResponse(0x7f50dae400b0, 0xc420ec2660, 0xc420116240, 0xc420116260, 0x2bbcb60, 0x2c439c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:64 +0xac
github.com/docker/docker/vendor/google.golang.org/grpc.invoke(0x7f50dae400b0, 0xc420ec2660, 0x1d8b178, 0x27, 0x1bf8420, 0xc4218115c0, 0x1bf8500, 0xc4215a3c90, 0xc420074680, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:279 +0xcfe
github.com/docker/docker/vendor/github.com/containerd/containerd.namespaceInterceptor.unary(0x1d482fe, 0x4, 0x7f50dae3c030, 0xc420018028, 0x1d8b178, 0x27, 0x1bf8420, 0xc4218115c0, 0x1bf8500, 0xc4215a3c90, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:18 +0xf4
github.com/docker/docker/vendor/github.com/containerd/containerd.(namespaceInterceptor).(github.com/docker/docker/vendor/github.com/containerd/containerd.unary)-fm(0x7f50dae3c030, 0xc420018028, 0x1d8b178, 0x27, 0x1bf8420, 0xc4218115c0, 0x1bf8500, 0xc4215a3c90, 0xc420074680, 0x1de2e40, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:34 +0xf4
github.com/docker/docker/vendor/google.golang.org/grpc.Invoke(0x7f50dae3c030, 0xc420018028, 0x1d8b178, 0x27, 0x1bf8420, 0xc4218115c0, 0x1bf8500, 0xc4215a3c90, 0xc420074680, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:141 +0xdd
github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1.(*tasksClient).Get(0xc4215a3c88, 0x7f50dae3c030, 0xc420018028, 0xc4218115c0, 0x0, 0x0, 0x0, 0xc4211296e8, 0x64ebf7, 0x1ba5780)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:450 +0xd2
github.com/docker/docker/vendor/github.com/containerd/containerd.(*process).Status(0xc420ec2450, 0x2bbd360, 0xc420018028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4218115a0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/process.go:201 +0x16d
github.com/docker/docker/vendor/github.com/containerd/containerd.(*process).Delete(0xc420ec2450, 0x2bbd360, 0xc420018028, 0x0, 0x0, 0x0, 0xc421d369c0, 0x2bc69a0, 0xc420ec2450)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/process.go:178 +0x131
github.com/docker/docker/libcontainerd.(*client).Exec(0xc4201447e0, 0x2bbd3a0, 0xc421d5b020, 0xc421fdb280, 0x40, 0xc4214b2140, 0x40, 0xc4217f80d0, 0x0, 0xc4219e5160, ...)
	/go/src/github.com/docker/docker/libcontainerd/client_daemon.go:348 +0x5fa
github.com/docker/docker/daemon.(*Daemon).ContainerExecStart(0xc4203ba200, 0x7f50da5f7940, 0xc421d5b020, 0xc4214b2140, 0x40, 0x0, 0x0, 0x2b9bfa0, 0xc421c35e00, 0x2b9bfa0, ...)
	/go/src/github.com/docker/docker/daemon/exec.go:245 +0x9ca
github.com/docker/docker/daemon.(*cmdProbe).run(0xc421816031, 0x7f50da5f7940, 0xc421d5b020, 0xc4203ba200, 0xc421e88480, 0xc4212c66f8, 0x4a1f76, 0x5a4fd1b5)
	/go/src/github.com/docker/docker/daemon/health.go:95 +0x5b8
github.com/docker/docker/daemon.monitor.func1(0x2b9bf20, 0xc421816031, 0x7f50da5f7940, 0xc421d5b020, 0xc4203ba200, 0xc421e88480, 0xc421d5b080, 0xbe8c124d5c987e06, 0x43f8b69bf, 0x2c1a280)
	/go/src/github.com/docker/docker/daemon/health.go:200 +0xb0
created by github.com/docker/docker/daemon.monitor
	/go/src/github.com/docker/docker/daemon/health.go:198 +0x336
```

**Comment by cpuguy83** [comment]
Copied dumps into other issue.
Closing this one.
