### ISSUE TITLE
SIGSEGV: segmentation violation (containerd)

### ISSUE THREAD

**Issue by Fank** [moby/moby#36215]
**Description**

Today i loged in on the docker machine, and typed "docker service ls" because some services were not available, but didn't received any output it just stuck and wait. Than i looked in the syslog and found a crash.

**Steps to reproduce the issue:**
N/A happend over night ..

**Describe the results you received:**

Stacktrace in the center:
```
Feb  6 08:12:08 docker0104 dockerd[1601]: time="2018-02-06T08:12:08.155021222+01:00" level=warning msg="Health check for container 8eca74c3ef255d0c96bf49a13300c50a51317f0b5717d3e9c612fa9c8dc1eea3 error: context cancelled"
Feb  6 08:12:08 docker0104 dockerd[1601]: time="2018-02-06T08:12:08.155085944+01:00" level=warning msg="Health check for container 59561e71392b4a43f7c7e21e3ac1511431bd76884cad495ec118a95962bde645 error: context cancelled"
Feb  6 08:12:08 docker0104 dockerd[1601]: time="2018-02-06T08:12:08.837900388+01:00" level=warning msg="Health check for container 973cebc9ba19cacceb5496cac892c22fd2582d81b65c92d053fd67b07f7953f9 error: context cancelled"
Feb  6 08:12:09 docker0104 dockerd[1601]: time="2018-02-06T08:12:09.088110210+01:00" level=warning msg="Ignoring Exit Event, no such exec command found" container=8eca74c3ef255d0c96bf49a13300c50a51317f0b5717d3e9c612fa9c8dc1eea3 exec-id=02bf67035e7eec5935ec5f2d38ad6b1ede7a31761e0263f3126502b80d391956 exec-pid=31930
Feb  6 08:12:10 docker0104 dockerd[1601]: time="2018-02-06T08:12:10.135118421+01:00" level=warning msg="Ignoring Exit Event, no such exec command found" container=59561e71392b4a43f7c7e21e3ac1511431bd76884cad495ec118a95962bde645 exec-id=26a565618e4b4b25eb299dd33b6f99f522623cfdcfae1192a7d4e2c901d65ef5 exec-pid=31929
Feb  6 08:12:15 docker0104 dockerd[1601]: time="2018-02-06T08:12:15.565959041+01:00" level=warning msg="Ignoring Exit Event, no such exec command found" container=973cebc9ba19cacceb5496cac892c22fd2582d81b65c92d053fd67b07f7953f9 exec-id=ef2bf3c52cafd7e9bd6ee12303b343de1a71982ad6340d65eb01aba159586fb6 exec-pid=31972
Feb  6 08:14:08 docker0104 dockerd[1601]: time="2018-02-06T08:14:08.436518314+01:00" level=warning msg="Health check for container 973cebc9ba19cacceb5496cac892c22fd2582d81b65c92d053fd67b07f7953f9 error: context cancelled"
Feb  6 08:14:11 docker0104 dockerd[1601]: time="2018-02-06T08:14:11.123815156+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:11 docker0104 dockerd[1601]: time="2018-02-06T08:14:11.123808979+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:11 docker0104 dockerd[1601]: time="2018-02-06T08:14:11.123809011+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:11 docker0104 dockerd[1601]: time="2018-02-06T08:14:11.123809081+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:17 docker0104 dockerd[1601]: time="2018-02-06T08:14:16.881082312+01:00" level=warning msg="Health check for container 59561e71392b4a43f7c7e21e3ac1511431bd76884cad495ec118a95962bde645 error: context cancelled"
Feb  6 08:14:17 docker0104 dockerd[1601]: time="2018-02-06T08:14:17.020975028+01:00" level=warning msg="Health check for container 8eca74c3ef255d0c96bf49a13300c50a51317f0b5717d3e9c612fa9c8dc1eea3 error: context cancelled"
Feb  6 08:14:17 docker0104 dockerd[1601]: time="2018-02-06T08:14:17.849623194+01:00" level=warning msg="Health check for container 007ad739e63dbaba722b0921983047b9c1f1f33f5a2e53097f77b1fdbd49419e error: context cancelled"
Feb  6 08:14:23 docker0104 dockerd[1601]: time="2018-02-06T08:14:23.884214594+01:00" level=warning msg="Ignoring Exit Event, no such exec command found" container=59561e71392b4a43f7c7e21e3ac1511431bd76884cad495ec118a95962bde645 exec-id=1ee95a310a0ac25158bb9ff98183e77a780df29e9bd1e996ea965cb1ac968c32 exec-pid=2575
Feb  6 08:14:23 docker0104 dockerd[1601]: time="2018-02-06T08:14:23.884197831+01:00" level=warning msg="Ignoring Exit Event, no such exec command found" container=8eca74c3ef255d0c96bf49a13300c50a51317f0b5717d3e9c612fa9c8dc1eea3 exec-id=8503ecf6d18493cf3c8ed3eb1b394ef786fe396c001f22f6afa9efc5be44a0f1 exec-pid=2576
Feb  6 08:14:24 docker0104 dockerd[1601]: time="2018-02-06T08:14:24.002480451+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:24 docker0104 dockerd[1601]: time="2018-02-06T08:14:24.002484701+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:34 docker0104 dockerd[1601]: time="2018-02-06T08:14:34.733983207+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:35 docker0104 dockerd[1601]: time="2018-02-06T08:14:34.734030773+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:35 docker0104 dockerd[1601]: time="2018-02-06T08:14:34.734030226+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:35 docker0104 dockerd[1601]: time="2018-02-06T08:14:34.734031828+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:14:36 docker0104 kernel: [59254.874198] CIFS VFS: Server srv-fs002.boeblingen.mcl.local has not responded in 120 seconds. Reconnecting...
Feb  6 08:14:36 docker0104 kernel: [59254.883852] CIFS VFS: Free previous auth_key.response = ffff8a79456d2800
Feb  6 08:14:46 docker0104 dockerd[1601]: time="2018-02-06T08:14:43.922767870+01:00" level=warning msg="Ignoring Exit Event, no such exec command found" container=007ad739e63dbaba722b0921983047b9c1f1f33f5a2e53097f77b1fdbd49419e exec-id=13610d9387c1dd04139b07fba26733d6e67f0c15df36dea214527e866a8b9527 exec-pid=2513
Feb  6 08:14:59 docker0104 dockerd[1601]: time="2018-02-06T08:14:56.361745666+01:00" level=info msg="killing and restarting containerd" module=libcontainerd pid=1874
Feb  6 08:17:16 docker0104 CRON[2750]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Feb  6 08:17:56 docker0104 kernel: [59455.421161] CIFS VFS: Free previous auth_key.response = ffff8a7926615e00
Feb  6 08:17:56 docker0104 kernel: [59455.421741] CIFS VFS: Free previous auth_key.response = ffff8a7f3dfb9300
Feb  6 08:17:56 docker0104 kernel: [59455.422601] CIFS VFS: Free previous auth_key.response = ffff8a7913681800
Feb  6 08:18:14 docker0104 gitlab-runner[1524]: time="2018-02-06T08:17:54+01:00" level=warning msg="Checking for jobs... failed" runner=96809613 status="couldn't execute POST against https://git.mcl.de/api/v4/jobs/request: Post https://git.mcl.de/api/v4/jobs/request: dial tcp: i/o timeout" #012<nil>
Feb  6 08:18:31 docker0104 gitlab-ci-multi-runner[1524]: time="2018-02-06T08:17:54+01:00" level=warning msg="Checking for jobs... failed" runner=96809613 status="couldn't execute POST against https://git.mcl.de/api/v4/jobs/request: Post https://git.mcl.de/api/v4/jobs/request: dial tcp: i/o timeout"
Feb  6 08:19:14 docker0104 kernel: [59532.708869] CIFS VFS: Free previous auth_key.response = ffff8a7af5673000
Feb  6 08:19:14 docker0104 kernel: [59532.709189] CIFS VFS: Free previous auth_key.response = ffff8a7a93b6a900
Feb  6 08:19:40 docker0104 dockerd[1601]: panic: runtime error: invalid memory address or nil pointer dereference
Feb  6 08:19:40 docker0104 dockerd[1601]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1c0a0e9]
Feb  6 08:19:40 docker0104 dockerd[1601]: goroutine 2976627 [running]:
Feb  6 08:19:40 docker0104 dockerd[1601]: github.com/docker/docker/vendor/github.com/containerd/containerd/dialer.Dialer.func2(0xc4259fc180)
Feb  6 08:19:40 docker0104 dockerd[1601]: #011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/dialer/dialer.go:46 +0x59
Feb  6 08:19:40 docker0104 dockerd[1601]: created by github.com/docker/docker/vendor/github.com/containerd/containerd/dialer.Dialer
Feb  6 08:19:40 docker0104 dockerd[1601]: #011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/dialer/dialer.go:43 +0x1c7
Feb  6 08:19:40 docker0104 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb  6 08:19:40 docker0104 systemd[1]: docker.service: Unit entered failed state.
Feb  6 08:19:40 docker0104 systemd[1]: docker.service: Failed with result 'exit-code'.
Feb  6 08:19:41 docker0104 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Feb  6 08:19:41 docker0104 systemd[1]: Stopped Docker Application Container Engine.
Feb  6 08:19:41 docker0104 systemd[1]: Closed Docker Socket for the API.
Feb  6 08:19:41 docker0104 systemd[1]: Stopping Docker Socket for the API.
Feb  6 08:19:41 docker0104 systemd[1]: Starting Docker Socket for the API.
Feb  6 08:19:41 docker0104 systemd[1]: Listening on Docker Socket for the API.
Feb  6 08:19:41 docker0104 systemd[1]: Starting Docker Application Container Engine...
Feb  6 08:19:46 docker0104 dockerd[2809]: time="2018-02-06T08:19:46.970783969+01:00" level=info msg="libcontainerd: started new docker-containerd process" pid=2926
Feb  6 08:19:46 docker0104 dockerd[2809]: time="2018-02-06T08:19:46+01:00" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="setting subreaper..." module=containerd
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="changing OOM score to -500" module=containerd
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." module=containerd type=io.containerd.snapshotter.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." module=containerd type=io.containerd.metadata.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." module=containerd type=io.containerd.differ.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." module=containerd type=io.containerd.gc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." module=containerd type=io.containerd.monitor.v1
Feb  6 08:19:47 docker0104 dockerd[2809]: time="2018-02-06T08:19:47+01:00" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1
Feb  6 08:19:48 docker0104 dockerd[2809]: time="2018-02-06T08:19:48+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:48 docker0104 dockerd[2809]: time="2018-02-06T08:19:48+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:48 docker0104 dockerd[2809]: time="2018-02-06T08:19:48+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1
Feb  6 08:19:48 docker0104 dockerd[2809]: time="2018-02-06T08:19:48+01:00" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
Feb  6 08:19:48 docker0104 dockerd[2809]: time="2018-02-06T08:19:48+01:00" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
Feb  6 08:19:48 docker0104 dockerd[2809]: time="2018-02-06T08:19:48+01:00" level=info msg="containerd successfully booted in 1.307976s" module=containerd
Feb  6 08:20:28 docker0104 dockerd[2809]: time="2018-02-06T08:20:28.707192430+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Feb  6 08:20:28 docker0104 dockerd[2809]: time="2018-02-06T08:20:28.708151181+01:00" level=warning msg="Your kernel does not support swap memory limit"
Feb  6 08:20:28 docker0104 dockerd[2809]: time="2018-02-06T08:20:28.708222439+01:00" level=warning msg="Your kernel does not support cgroup rt period"
Feb  6 08:20:28 docker0104 dockerd[2809]: time="2018-02-06T08:20:28.708238812+01:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Feb  6 08:20:28 docker0104 dockerd[2809]: time="2018-02-06T08:20:28.709013738+01:00" level=info msg="Loading containers: start."
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.454079181+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.454101420+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37+01:00" level=warning msg="unable to retrieve cgroup on stop" error="cgroup does not exist: not found" module="containerd/io.containerd.monitor.v1.cgroups"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.526503122+01:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.560030756+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.560026611+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37+01:00" level=warning msg="unable to retrieve cgroup on stop" error="cgroup does not exist: not found" module="containerd/io.containerd.monitor.v1.cgroups"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.616211833+01:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.681315029+01:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.697471483+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37.697532925+01:00" level=error msg="stream copy error: reading from a closed fifo"
Feb  6 08:20:37 docker0104 dockerd[2809]: time="2018-02-06T08:20:37+01:00" level=warning msg="unable to retrieve cgroup on stop" error="cgroup does not exist: not found" module="containerd/io.containerd.monitor.v1.cgroups"
```

**Describe the results you expected:**

No crash

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:13:21 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:11:47 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 122
 Running: 17
 Paused: 0
 Stopped: 105
Images: 141
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: odfdzn8rp9qcvblnk39p5lpto
 Is Manager: true
 ClusterID: fqffr81nxyg046kjm2uaniz8g
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.85.104
 Manager Addresses:
  192.168.85.104:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 39.28GiB
Name: docker0104
ID: QRLZ:G6LR:KI4X:JY46:PI4C:3LAU:ES2K:LHQO:FU4I:6RE5:NU4H:VHVQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: fank
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server running latest ubuntu 17.10

**Comment by cpuguy83** [comment]
In think this is fixed in the upcoming containerd 1.0.2 release via https://github.com/containerd/containerd/commit/a03fb1bd137806a5900f24eb385a505ae6842ffa

**Comment by Fank** [comment]
Is there a planned release date which contains the fix for it?

**Comment by cpuguy83** [comment]
We are working on a 17.12 (stable) patch release... Not sure if 1.0.2 will land in time for it.

For edge this would land with 18.03.

Note that we are also working to get containerd packaged separately so that users can upgrade containerd separately from Docker.

**Comment by cpuguy83** [comment]
You can use a custom containerd version with Docker, though.
There is a "--containerd" option on dockerd to point it at the correct socket address.
