### ISSUE TITLE
Docker swarm join fails - 17.12

### ISSUE THREAD

**Issue by instantlinux** [moby/moby#36382]
**Description**

I have a 3-node cluster upgraded twice since 17.06. Not long after the 17.12 update, after a couple of server crashes from which recovery happened OK, I had one go down and I cannot join a new node to the swarm which continues to run on two nodes. Even a freshly-installed Linux cannot join.

**Steps to reproduce the issue:**

I lack the hardware to attempt to reproduce this. 

**Describe the results you received:**
```
# docker swarm join --token SWMTKN-1-37xxxxx 192.168.2.79:2377
Error response from daemon: Timeout was reached before node joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.
# tail /var/log/syslog
Feb 22 08:23:30 sys144b dockerd[17000]: time="2018-02-22T08:23:30.547171772-08:00" level=error msg="Handler for POST /v1.35/swarm/join returned error: Timeout was reached before node joined. The attempt to join the swarm will continue in the background. Use the \"docker info\" command to see the current swarm status of your node."
Feb 22 08:23:45 sys144b dockerd[17000]: time="2018-02-22T08:23:45.634304108-08:00" level=error msg="failed to request and save new certificate" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=node/tls
```

**Describe the results you expected:**

Join OK. 

** Additional Info **

In my attempts to deal with this, I think I have lost manager quorum. This is a very nasty problem if it happens to anyone else; unless I learn of a workaround, my only recourse is to discard my current swarm with all its data and rebuild under an older more-trusted version (17.09).

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

(Fresh node trying to join)
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: data01-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 334MB
 Data Space Total: 2.097GB
 Data Space Available: 1.763GB
 Metadata Space Used: 135.2kB
 Metadata Space Total: 104.9MB
 Metadata Space Available: 104.7MB
 Thin Pool Minimum Free Space: 209.7MB
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: error
 NodeID: 
 Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
 Is Manager: false
 Node Address: 192.168.2.125
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.10-041110-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 2.936GiB
Name: sys144b
ID: TTPJ:JLWV:IZOC:OLAH:O45U:PWX6:XGIM:6MRI:VAKQ:QJLA:AXK5:CZVL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

(One of existing nodes)
```
Containers: 85
 Running: 33
 Paused: 0
 Stopped: 52
Images: 1039
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: data01-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 49.42GB
 Data Space Total: 145GB
 Data Space Available: 95.6GB
 Metadata Space Used: 18.38MB
 Metadata Space Total: 104.9MB
 Metadata Space Available: 86.48MB
 Thin Pool Minimum Free Space: 14.5GB
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: c8kaeqrq2ogb2g34zfuh73hhe
 Is Manager: true
 ClusterID: 48s4nkfptgk54do81dxqz58ny
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.2.79
 Manager Addresses:
  192.168.2.64:2377
  192.168.2.69:2377
  192.168.2.79:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.12-041112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.17GiB
Name: vinson
ID: G7HB:LHJD:ZJKL:G34H:TQSE:WM55:FBGT:U3GR:6SPM:CR25:KHA3:3ACD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare-metal three-node cluster.

**Comment by parminder-flora** [comment]
I'm running 18.03 and have seen the same issue.

**Comment by cpuguy83** [comment]
Can you get a goroutine stack dump on the affected node?
`curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2`

**Comment by nderzhak** [comment]
Happened to us in production cluster. CentOS 7.5 + docker 18.03.1-ce Any ideas ?

**Comment by nderzhak** [comment]
stack dump:
```
goroutine 326 [IO wait]:
internal/poll.runtime_pollWait(0x7f3ea9af6970, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x59
internal/poll.(*pollDesc).wait(0xc420300118, 0x72, 0xffffffffffffff00, 0x555cda44abc0, 0x555cda43bc08)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xb0
internal/poll.(*pollDesc).waitRead(0xc420300118, 0xc420a34400, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
internal/poll.(*FD).Read(0xc420300100, 0xc420a34491, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18c
net.(*netFD).Read(0xc420300100, 0xc420a34491, 0x1, 0x1, 0x0, 0x555cda442e00, 0x555cda4df9c0)
        /usr/local/go/src/net/fd_unix.go:202 +0x54
net.(*conn).Read(0xc42011e290, 0xc420a34491, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6f
github.com/docker/docker/cmd/dockerd/hack.(*MalformedHostHeaderOverrideConn).Read(0xc420b3cf80, 0xc420a34491, 0x1, 0x1, 0xc420e769b0, 0x555cda443101, 0xc420e769b0)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/hack/malformed_host_override.go:110 +0x86
net/http.(*connReader).backgroundRead(0xc420a34480)
        /usr/local/go/src/net/http/server.go:660 +0x64
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:656 +0xda
```

**Comment by Alvise88** [comment]
I have the same issue using Docker 19.03.15. 
if you  demote promote managers many times you loose quorum. 
If you try to force new cluster you are able to add/join only workers.
