### ISSUE TITLE
Daemon panics on container export after a restart

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#36561]
**Description**

Unable to export a container after a daemon restart. The daemon panics.

**Steps to reproduce the issue:**
1. `docker run --name mynginx -d nginx`
2. restart the docker daemon
3. `docker export mynginx > foo.tar

**Describe the results you received:**

```
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/e6891c6c5c89fe91631d252b707563041f5106bef051c801c56cbb5a9c1ad9f9/export: EOF
```

Daemon panics with the following stack

```
2018-03-12 12:37:17.409021 I | http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 7405 [running]:
net/http.(*conn).serve.func1(0xc420c099a0)
	/usr/local/go/src/net/http/server.go:1697 +0xd2
panic(0x21655c0, 0x2e71f70)
	/usr/local/go/src/runtime/panic.go:491 +0x287
github.com/docker/docker/daemon.(*Daemon).containerExport(0xc420448240, 0xc420448480, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/export.go:69 +0x31a
github.com/docker/docker/daemon.(*Daemon).ContainerExport(0xc420448240, 0xc4202480d6, 0xc, 0x2e9e020, 0xc42137e000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/export.go:37 +0x2f4
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersExport(0xc4201343c0, 0x7fcfcd3a53c8, 0xc421b62e40, 0x2eb8be0, 0xc42137e000, 0xc42140e500, 0xc421b62d50, 0x190b3c6, 0x4)
	/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:159 +0xd3
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersExport)-fm(0x7fcfcd3a53c8, 0xc421b62e40, 0x2eb8be0, 0xc42137e000, 0xc42140e500, 0xc421b62d50, 0x7fcfcd3a53c8, 0xc421b62e40)
	/go/src/github.com/docker/docker/api/server/router/container/container.go:37 +0x6b
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7fcfcd3a53c8, 0xc421b62e40, 0x2eb8be0, 0xc42137e000, 0xc42140e500, 0xc421b62d50, 0x7fcfcd3a53c8, 0xc421b62e40)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xda
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fcfcd3a53c8, 0xc421b62db0, 0x2eb8be0, 0xc42137e000, 0xc42140e500, 0xc421b62d50, 0xc420248b00, 0xc422326000)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x425
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7fcfcd3a53c8, 0xc421b62db0, 0x2eb8be0, 0xc42137e000, 0xc42140e500, 0xc421b62d50, 0x10, 0x401557)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x83d
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7fcfcd3a53c8, 0xc421b62db0, 0x2eb8be0, 0xc42137e000, 0xc42140e500, 0xc421b62d50, 0x7fcfcd3a53c8, 0xc421b62db0)
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:22 +0x180
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2eb8be0, 0xc42137e000, 0xc42140e500)
	/go/src/github.com/docker/docker/api/server/server.go:137 +0x1c8
net/http.HandlerFunc.ServeHTTP(0xc420bb9260, 0x2eb8be0, 0xc42137e000, 0xc42140e500)
	/usr/local/go/src/net/http/server.go:1918 +0x46
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420b27e00, 0x2eb8be0, 0xc42137e000, 0xc42140e500)
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x22d
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420db5f00, 0x2eb8be0, 0xc42137e000, 0xc42140e500)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc420335790, 0x2eb8be0, 0xc42137e000, 0xc42140e500)
	/usr/local/go/src/net/http/server.go:2619 +0xb6
net/http.(*conn).serve(0xc420c099a0, 0x2eba8a0, 0xc421258b00)
	/usr/local/go/src/net/http/server.go:1801 +0x71f
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x28a
```

**Describe the results you expected:**

No error :stuck_out_tongue_closed_eyes: 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.3
 Git commit:    486a48d2701493bb65385788a291e36febb44ec1
 Built: Fri Jan 26 03:13:34 2018
 OS/Arch:       linux/amd64
 Experimental:  true

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   486a48d2701493bb65385788a291e36febb44ec1
  Built:        Thu Jan  1 00:00:01 1970
  OS/Arch:      linux/amd64
  Experimental: true
```

But this is also true for version after that (tested on 18.03 RCs)

**Comment by vdemeester** [comment]
This is related to https://github.com/docker/for-mac/issues/2679

**Comment by thaJeztah** [comment]
(copying here)

The only location this value is set is in [daemon/daemon.go#L1066](https://github.com/moby/moby/blob/1790ce52e96fd66621b5d8eb2e203203874a7921/daemon/daemon.go#L1066), and that part of the code won't be reached if the container's RWLayer was not set, or failed to mount [daemon/daemon.go#L1047-L1053](https://github.com/moby/moby/blob/1790ce52e96fd66621b5d8eb2e203203874a7921/daemon/daemon.go#L1047-L1053)

I do see one code path where `daemon.Mount()` can fail, and the error is ignored (only a warning is printed); [daemon/daemon.go#L294-L301](https://github.com/moby/moby/blob/1790ce52e96fd66621b5d8eb2e203203874a7921/daemon/daemon.go#L294-L301)

**Comment by kolyshkin** [comment]
This is caused by commit 7a7357dae1bccc ("LCOW: Implemented support for docker cp + build"), which changed `container.BaseFS` from being a string (that could be empty but can't lead to nil pointer dereference) to an instance of `containerfs.ContainerFS` interface, which could be be `nil`.

I'm afraid we need to audit the code for any use of `container.BaseFS` without a check for non-nil. It seems the only place where it is set is `daemon.Mount()` so either an explicit check is needed, or a call to `daemon.Mount()` with a check it did not return an error.

I will prepare a pr soon

**Comment by vdemeester** [comment]
We should close this one once #36606 is merged :angel: The fix should be available at least in docker-ce 18:03.
