### ISSUE TITLE
 The operation timed out because a response was not received from the Virtual Machine hosting the Container

### ISSUE THREAD

**Issue by danleydmello** [moby/moby#36635]
I am trying to build docker image using microsoft/iis by following steps decribed on https://hub.docker.com/r/microsoft/iis/. and getting this error:

```PowerShell
PS D:\docker\iis> docker build -t iis-site .
Sending build context to Docker daemon 2.048kB
Step 1/5 : FROM microsoft/iis
---> 6d91070fab75
Step 2/5 : RUN mkdir C:\site
---> Running in 38f29bfe9e35
container 38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 encountered an error during Start: failure in
a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the
Container. (0xc0370109)
PS D:\docker\iis>
```

Information
Diagnostic ID from "Diagnose & Feedback" in the menu.
048585C3-B42F-4EE8-8E03-347399801267/2018-03-16_10-52-55

a reproducible case if this is a bug, Dockerfiles FTW
Dockerfile:

```Dockerfile
#Use IIS from microsoft docker registry
FROM microsoft/iis
RUN mkdir C:\site
RUN powershell -NoProfile -Command 
Import-module IISAdministration; 
New-IISSite -Name "Site" -PhysicalPath C:\site -BindingInformation "*:8000:"

EXPOSE 8000

ADD content/ /site
```

host distribution and version (Windows version, build number, etc)

Windows 10 Enterprise
Docker Version 18.03.0-ce-rc4-win57 (16511)
Channel: edge

**Comment by thaJeztah** [comment]
I see you also opened this in the IIS https://github.com/Microsoft/iis-docker/issues/93, and Docker for Windows issue tracker https://github.com/docker/for-win/issues/1846.

Given that this is an issue with Docker for Windows, I'll close the issue here to prevent the conversation from diverging.

**Comment by rn** [comment]
@thaJeztah I had asked the user to open an issue here as this is not an issue with the Docker for Windows app itself but the error comes from the docker daemon trying to create a windows container so I think this is a more appropriate place to track than `docker/for-win`.

**Comment by thaJeztah** [comment]
Oops, apologies, I missed the conversation on the linked issue.

@danleydmello for completeness, could you provide the output of `docker version` and `docker info`?

@rn is there anything in the support dump that could be useful for debugging? We don't have access to those dumps 😊

**Comment by rn** [comment]
@thaJeztah no problem. From the logs:
```
Version: 18.03.0-ce-rc4-win57 (16511)
OS: Windows 10 Enterprise
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
```

and the last bits in the log file:
```
[10:50:16.868][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 16ae528a192639046661b3c427d79b077ab719f992246f01a759fcf64c66fa0b
[10:50:16.870][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 49035cae88fb180bd52f5b90538ed1f12d7a326413b156b4c79cb6330d5879d8
[10:50:16.872][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name a18141825e45df18e62aab7e28ccd7c233a4517d38a1770c79286abc75c1b8ec
[10:50:16.872][WindowsDaemon  ][Info   ] debug: hcsshim::PrepareLayer succeeded flavour=1 layerId=f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.873][WindowsDaemon  ][Info   ] debug: hcsshim::GetLayerMountPath Flavour 1 ID f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.875][WindowsDaemon  ][Info   ] debug: Calling proc (1)
[10:50:16.877][WindowsDaemon  ][Info   ] debug: Calling proc (2)
[10:50:16.877][WindowsDaemon  ][Info   ] debug: hcsshim::GetLayerMountPath succeeded flavour=1 id=f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af path=C:\ProgramData\Docker\windowsfilter\f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.878][WindowsDaemon  ][Info   ] debug: WindowsGraphDriver Put() id f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.880][WindowsDaemon  ][Info   ] debug: hcsshim::UnprepareLayer flavour 1 layerId f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.882][WindowsDaemon  ][Info   ] debug: hcsshim::UnprepareLayer succeeded flavour 1 layerId=f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.882][WindowsDaemon  ][Info   ] debug: hcsshim::DeactivateLayer Flavour 1 ID f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.883][WindowsDaemon  ][Info   ] debug: hcsshim::DeactivateLayer succeeded flavour=1 id=f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.884][WindowsDaemon  ][Info   ] debug: WindowsGraphDriver Get() id 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6 mountLabel
[10:50:16.887][WindowsDaemon  ][Info   ] debug: hcsshim::ActivateLayer Flavour 1 ID 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.889][WindowsDaemon  ][Info   ] debug: hcsshim::ActivateLayer  - succeeded id=5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6 flavour=1
[10:50:16.892][WindowsDaemon  ][Info   ] debug: hcsshim::PrepareLayer flavour 1 layerId 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.892][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.893][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 16ae528a192639046661b3c427d79b077ab719f992246f01a759fcf64c66fa0b
[10:50:16.897][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 49035cae88fb180bd52f5b90538ed1f12d7a326413b156b4c79cb6330d5879d8
[10:50:16.897][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name a18141825e45df18e62aab7e28ccd7c233a4517d38a1770c79286abc75c1b8ec
[10:50:16.898][WindowsDaemon  ][Info   ] debug: hcsshim::PrepareLayer succeeded flavour=1 layerId=5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.898][WindowsDaemon  ][Info   ] debug: hcsshim::GetLayerMountPath Flavour 1 ID 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.899][WindowsDaemon  ][Info   ] debug: Calling proc (1)
[10:50:16.901][WindowsDaemon  ][Info   ] debug: Calling proc (2)
[10:50:16.902][WindowsDaemon  ][Info   ] debug: hcsshim::GetLayerMountPath succeeded flavour=1 id=5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6 path=C:\ProgramData\Docker\windowsfilter\5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.902][WindowsDaemon  ][Info   ] debug: WindowsGraphDriver Put() id 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.904][WindowsDaemon  ][Info   ] debug: hcsshim::UnprepareLayer flavour 1 layerId 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.907][WindowsDaemon  ][Info   ] debug: hcsshim::UnprepareLayer succeeded flavour 1 layerId=5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.907][WindowsDaemon  ][Info   ] debug: hcsshim::DeactivateLayer Flavour 1 ID 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.907][WindowsDaemon  ][Info   ] debug: hcsshim::DeactivateLayer succeeded flavour=1 id=5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.927][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6
[10:50:16.927][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af
[10:50:16.928][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 16ae528a192639046661b3c427d79b077ab719f992246f01a759fcf64c66fa0b
[10:50:16.932][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name 49035cae88fb180bd52f5b90538ed1f12d7a326413b156b4c79cb6330d5879d8
[10:50:16.932][WindowsDaemon  ][Info   ] debug: hcsshim::NameToGuid Name a18141825e45df18e62aab7e28ccd7c233a4517d38a1770c79286abc75c1b8ec
[10:50:16.935][WindowsDaemon  ][Info   ] debug: HCSShim::CreateContainer id=38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 config={"SystemType":"Container","Name":"38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803","Layers":[{"ID":"24a12980-938d-5461-a5e2-d11d6e94c634","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5ef0d114d2a594169aafaa1303386cd9573dfde5d3de9dca0c5ff4cb98d848b6"},{"ID":"cc46b4e9-ea82-5d4a-9df8-01196428f242","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f0e4ee9c1545bd5f7c749d7cc081a507df84a83b22e1f1c279b027cdcca2a7af"},{"ID":"8fcc7d39-5eeb-5740-9cc3-d0e6050a505d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\16ae528a192639046661b3c427d79b077ab719f992246f01a759fcf64c66fa0b"},{"ID":"bb475d3c-8e9d-54b1-906c-40b26e591f80","Path":"C:\\ProgramData\\Docker\\windowsfilter\\49035cae88fb180bd52f5b90538ed1f12d7a326413b156b4c79cb6330d5879d8"},{"ID":"c25bc1e8-f1ed-5262-bc9c-73b902f898fc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a18141825e45df18e62aab7e28ccd7c233a4517d38a1770c79286abc75c1b8ec"}],"HostName":"38f29bfe9e35","HvPartition":true,"EndpointList":["e98aa339-ccc1-4a3c-ab23-2f1a3c111a56"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\49035cae88fb180bd52f5b90538ed1f12d7a326413b156b4c79cb6330d5879d8\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
[10:50:19.776][WindowsDaemon  ][Info   ] debug: HCSShim::CreateContainer succeeded id=38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 handle=106512384
[10:50:19.776][WindowsDaemon  ][Info   ] debug: starting container [namespace=moby module=libcontainerd container=38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803]
[10:50:19.777][WindowsDaemon  ][Info   ] debug: HCSShim::Container::Start id=38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803
[10:50:28.480][LocalhostForwarder][Info   ] Reconciliation succeeded
[10:50:28.483][WindowsDaemon  ][Info   ] debug: Calling GET /v1.37/containers/json?limit=0
[10:50:33.440][WindowsDaemon  ][Warning] svchost (13020) A significant portion of the database buffer cache has been written out to the system paging file. This may result in severe performance degradation.

See help link for complete details of possible causes.

Previous cache residency state: 100 (4362 out of 4362 buffers) (1070 seconds ago)

Current cache residency state:  58 (26953 out of 45915 buffers)

Current cache size vs. target:  99 (181.586 / 181.730 MBs)

Physical Memory / RAM size:     32646.902 MBs
[10:50:48.480][LocalhostForwarder][Info   ] Reconciliation succeeded
[10:50:48.484][WindowsDaemon  ][Info   ] debug: Calling GET /v1.37/containers/json?limit=0
[10:51:08.483][LocalhostForwarder][Info   ] Reconciliation succeeded
[10:51:08.486][WindowsDaemon  ][Info   ] debug: Calling GET /v1.37/containers/json?limit=0
[10:51:27.364][WindowsDaemon  ][Info   ] debug: Result: {"Error":-1070137079,"ErrorMessage":"The operation timed out because a response was not received from the Virtual Machine hosting the Container."}
[10:51:27.365][WindowsDaemon  ][Error  ] failed to start container [error=container 38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109) module=libcontainerd namespace=moby]
[10:51:27.365][WindowsDaemon  ][Info   ] debug: HCSShim::Container::Terminate id=38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803
[10:51:27.367][WindowsDaemon  ][Info   ] debug: cleaned up after failed Start by calling Terminate [module=libcontainerd namespace=moby]
[10:51:27.403][WindowsDaemon  ][Info   ] debug: attach: stdout: end
[10:51:27.403][WindowsDaemon  ][Info   ] debug: attach: stderr: end
[10:51:27.415][WindowsDaemon  ][Info   ] debug: DisableService 38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 START
[10:51:27.416][WindowsDaemon  ][Info   ] debug: DisableService 38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 DONE
[10:51:27.417][WindowsDaemon  ][Info   ] debug: Revoking external connectivity on endpoint adoring_curran (1bea8aaf90c5786f855a66502c0bcf68d96bec4666449fb1c3b138708486305d)
[10:51:27.420][WindowsDaemon  ][Info   ] debug: HCSShim::OpenContainer id=38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803
[10:51:27.456][WindowsDaemon  ][Info   ] debug: [DELETE]=>[/endpoints/e98aa339-ccc1-4a3c-ab23-2f1a3c111a56] Request :
[10:51:27.498][WindowsDaemon  ][Info   ] debug: Releasing addresses for endpoint adoring_curran's interface on network nat
[10:51:27.499][WindowsDaemon  ][Info   ] debug: ReleaseAddress(172.30.240.0/20, 172.30.248.120)
[10:51:27.531][WindowsDaemon  ][Error  ] 38f29bfe9e35ad7bf534e66e0020e0b2f0caa87e51be958b48c6029f2b0e1803 cleanup: failed to delete container from containerd: no such container
```


Don't think i've ever seen:
```
[10:50:33.440][WindowsDaemon  ][Warning] svchost (13020) A significant portion of the database buffer cache has been written out to the system paging file. This may result in severe performance degradation.
```
before

**Comment by danleydmello** [comment]
@thaJeztah , docker version is: 
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true

AND docker info:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.12.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.88GiB
Name: NAOU19230
ID: MBL2:B2SZ:BEDR:I4YO:YC75:45YC:3HD3:2LOK:PYPO:4I2P:DQXM:BS5H
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 63
 System Time: 2018-03-20T08:56:36.5139576-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by danleydmello** [comment]
One thin I will like to mention is that the docker build works once in a blue moon thats why I closed the issue initially in in the IIS Microsoft/iis-docker#93, thining that problem is fixed but then next day it appeared again.

**Comment by thaJeztah** [comment]
Thanks!

That warning seems to be related to insufficient memory being available, according to this document; [A significant portion of the database buffer cache has been written out to the system paging file. This may result in severe performance degradation](https://technet.microsoft.com/en-us/library/hh344030(v=exchg.140).aspx)

> This Warning event indicates that a large portion of the database buffer cache is being written to the system paging file. This issue may indicate that you do not have enough memory installed on the computer. The minimum amount of RAM that is required for a multi-role server is 8 gigabytes (GB).

**Comment by thaJeztah** [comment]
ping @johnstep @jhowardmsft PTAL

**Comment by danleydmello** [comment]
Not sure if this is related but I also get the error when I Switch to Linux container: 
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Diagnostic Id: 048585C3-B42F-4EE8-8E03-347399801267/2018-03-20_14-36-21

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
