### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by dhaavi** [moby/moby#36772]
**Description**

Docker crashed with a fatal error:

```
fatal error: concurrent map iteration and map write

goroutine 71835668 [running]:
runtime.throw(0x561fd25ae7bf, 0x26)
        /usr/lib/go/src/runtime/panic.go:596 +0x97 fp=0xc4272e7110 sp=0xc4272e70f0
runtime.mapiternext(0xc4272e7480)
        /usr/lib/go/src/runtime/hashmap.go:737 +0x7f0 fp=0xc4272e71c0 sp=0xc4272e7110
runtime.mapiterinit(0x561fd2bb2140, 0xc44003ba10, 0xc4272e7480)
        /usr/lib/go/src/runtime/hashmap.go:727 +0x2b5 fp=0xc4272e7218 sp=0xc4272e71c0
github.com/docker/docker/daemon.(*Daemon).transformContainer(0xc420482800, 0xc42033ae00, 0xc45217c540, 0x0, 0x0, 0x0)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/daemon/list.go:592 +0x844 fp=0xc4272e74f0 sp=0xc4272e7218
github.com/docker/docker/daemon.(*Daemon).(github.com/docker/docker/daemon.transformContainer)-fm(0xc42033ae00, 0xc45217c540, 0x0, 0xc420482800, 0x561fd2546700)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/daemon/list.go:115 +0x40 fp=0xc4272e7530 sp=0xc4272e74f0
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc420482800, 0xc42033ae00, 0xc45217c540, 0xc4272e7670, 0x20, 0x0, 0xc42114e650)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/daemon/list.go:224 +0x85 fp=0xc4272e7580 sp=0xc4272e7530
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc420482800, 0xc43fa54ec0, 0xc4272e7670, 0xc42114e680, 0xc42114e680, 0x8, 0x40, 0x561fd2d4b260)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/daemon/list.go:192 +0x114 fp=0xc4272e7630 sp=0xc4272e7580
github.com/docker/docker/daemon.(*Daemon).Containers(0xc420482800, 0xc43fa54ec0, 0x561fd256ea05, 0x5, 0x561fd3743f20, 0xc42114e6e8, 0x561fd14200aa)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/daemon/list.go:115 +0x5f fp=0xc4272e7690 sp=0xc4272e7630
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc421300200, 0x7f72e4f23070, 0xc447e0cab0, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00, 0xc447e0ca20, 0x561fd256db67, 0x4)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x211 fp=0xc4272e7728 sp=0xc4272e7690
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f72e4f23070, 0xc447e0cab0, 0x561fd36d25e0, 0xc420cfc1c0, 0xc4
5e1f0c00, 0xc447e0ca20, 0x7f72e4f23070, 0xc447e0cab0)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x6b fp=0xc4272e7780 sp=0xc4272e7728
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f72e4f23070, 0xc447e0cab0, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00, 0xc447e0ca20, 0x7f72e4f23070, 0xc447e0cab0)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xda fp=0xc4272e77e8 sp=0xc4272e7780
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f72e4f23070, 0xc447e0ca80, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00, 0xc447e0ca20, 0xc43fa54a80, 0xc42114ea00)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55f fp=0xc4272e7910 sp=0xc4272e77e8
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f72e4f23070, 0xc447e0ca80, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00, 0xc447e0ca20, 0x7f72e4f23070, 0xc447e0ca80)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x873 fp=0xc4272e7ac8 sp=0xc4272e7910
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/api/server/server.go:140 +0x21c fp=0xc4272e7bc0 sp=0xc4272e7ac8
net/http.HandlerFunc.ServeHTTP(0xc427a50440, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00)
        /usr/lib/go/src/net/http/server.go:1942 +0x46 fp=0xc4272e7be8 sp=0xc4272e7bc0
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc428636410, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x257 fp=0xc4272e7cd8 sp=0xc4272e7be8
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc427a5fce0, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00)
        /home/buildozer/aports/community/docker/src/moby-17.05.0-ce/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72 fp=0xc4272e7d10 sp=0xc4272e7cd8
net/http.serverHandler.ServeHTTP(0xc42014ce70, 0x561fd36d25e0, 0xc420cfc1c0, 0xc45e1f0c00)
        /usr/lib/go/src/net/http/server.go:2568 +0x94 fp=0xc4272e7d58 sp=0xc4272e7d10
net/http.(*conn).serve(0xc4256735e0, 0x561fd36d4120, 0xc45070ca00)
        /usr/lib/go/src/net/http/server.go:1825 +0x614 fp=0xc4272e7fc8 sp=0xc4272e7d58
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4272e7fd0 sp=0xc4272e7fc8
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2668 +0x2d0
```

**Steps to reproduce the issue:**

not able to reproduce

**Describe the results you received:**

docker crashed

**Describe the results you expected:**

no crashing ;)

**Additional information you deem important (e.g. issue happens only occasionally):**

Single server, swarm mode. Has been running for months with occasional high load. Almost no load when crash happened.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   v17.05.0-ce
 Built:        Tue May 16 10:10:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   v17.05.0-ce
 Built:        Tue May 16 10:10:15 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 42
 Running: 22
 Paused: 0
 Stopped: 20
Images: 17
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 9b86viugse9yh6v2zxemg1cqq
 Is Manager: true
 ClusterID: avuiyle3b90t8usyebc9auosl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.205.1
 Manager Addresses:
  192.168.205.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.9.32-0-virthardened
Operating System: Alpine Linux v3.6
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.83GiB
Name: REDACTED
ID: NMFE:I2XP:2RZD:D7IT:PMTF:ANAA:365S:PQ2G:CPHI:X4X5:P4MK:JAV5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: REDACTED
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

run on an ESXI instance

**Comment by dhaavi** [comment]
Ok, great!
I was confused about the current version, as https://github.com/moby/moby/releases has 17.05 as latest version - at least as far as I scrolled ;)

Full trace: https://gist.github.com/dhaavi/7735ba3e3037325e2a89c4a3299a954a

**Comment by cpuguy83** [comment]
Releases are done in github.com/docker/docker-ce now ;)

**Comment by cpuguy83** [comment]
Yep, the panic was caused by unlocked access while connecting a container to a network, here was that fix: 4d0888e32bc
