### ISSUE TITLE
[1.12.6] runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by heijigaoke** [moby/moby#36980]
@docker  @moby @GordonTheTurtle @ththaJeztah
I have 56 hosts use docker to run my app.
The os and docker info as follow:
**os:** suse12 sp2
**docker:**1.12.6
**Storage Driver:** devicemapper and use thinpool

When we start all  app use rancher it looks very normal.
But run for a period of time some dockers were  not normal.

When i use command `docker exec -it container-name bash` the error info as follow:

    **level=error msg="Error running exec in container: rpc error: code = 2 desc = containerd: container not started"**

When i use command `docker stats|grep container-name` the error info as follow:

```
**dockerd[1836]: time="2018-05-02T09:53:05.079860937+08:00" level=error msg="collecting stats for fe2b391b64d87e76abd1cd6fa2fe145eb9e5b13b0dfcfb44e93965d802ad8d76: rpc error: code = 2 desc = exit status 2: \"runtime/cgo: pthread_create failed: Resource temporarily unavailable\\nSIGABRT: abort\\nPC=0x7f18cc3ab8d7 m=3\\n\\ngoroutine 0 [idle]:\\n\\ngoroutine 1 [chan receive, locked to thread]:\\ntext/template/parse.(*Tree).nextNonSpace(0xc8200862a0, 0x0, 0x0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:102 +0x14c\\ntext/template/parse.(*Tree).action(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:363 +0x47\\ntext/template/parse.(*Tree).textOrAction(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:350 +0x8d\\ntext/template/parse.(*Tree).itemList(0xc8200862a0, 0xc82005b590, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:332 +0x103\\ntext/template/parse.(*Tree).parseControl(0xc8200862a0, 0x7e8900, 0x84a4a0, 0x5, 0x0, 0x6, 0xc820010690, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:457 +0x15c\\ntext/template/parse.(*Tree).rangeControl(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:499 +0x5c\\ntext/template/parse.(*Tree).action(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:373 +0x4fe\\ntext/template/parse.(*Tree).textOrAction(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:350 +0x8d\\ntext/template/parse.(*Tree).parse(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:295 +0x6be\\ntext/template/parse.(*Tree).Parse(0xc8200862a0, 0x906560, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc82005b0e0, 0xc820012e30, 0x2, ...)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:234 +0x299\\ntext/template/parse.Parse(0x8490f0, 0x5, 0x906560, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc820012e30, 0x2, ...)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:55 +0x14c\\ntext/template.(*Template).Parse(0xc82000aa00, 0x906560, 0xf0, 0x8aa300, 0x0, 0x0)\\n\\t/usr/lib64/go/
dockerd[1836]: src/text/template/template.go:190 +0x2ab\\ngithub.com/opencontainers/runc/libcontainer.init()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/libcontainer/generic_error.go:36 +0x17d\\nmain.init()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/utils_linux.go:315 +0x69\\n\\ngoroutine 17 [syscall, locked to thread]:\\nruntime.goexit()\\n\\t/usr/lib64/go/src/runtime/asm_amd64.s:1998 +0x1\\n\\ngoroutine 5 [runnable]:\\ntext/template/parse.lexLeftDelim(0xc82007e380, 0x900ac8)\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:313 +0x25f\\ntext/template/parse.(*lexer).run(0xc82007e380)\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:223 +0x52\\ncreated by text/template/parse.lex\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:216 +0x162\\n\\nrax    0x0\\nrbx    0x7f18cc7156b8\\nrcx    0x7f18cc3ab8d7\\nrdx    0x6\\nrdi    0x19d40\\nrsi    0x19d42\\nrbp    0x90e381\\nrsp    0x7f18cbb74978\\nr8     0xa\\nr9     0x7f18cbb75700\\nr10    0x8\\nr11    0x202\\nr12    0x7f18c40008c0\\nr13    0x8fed94\\nr14    0x0\\nr15    0x8\\nrip    0x7f18cc3ab8d7\\nrflags 0x202\\ncs     0x33\\nfs     0x0\\ngs     0x0\\n\""
dockerd[1836]: time="2018-05-02T09:53:05.081368258+08:00" level=error msg="collecting stats for 8743f1354dc256349cc1f2ae1b82a72743fabd6dbfdca80190a3b095a70f5656: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.082434513+08:00" level=error msg="collecting stats for d590f704d85e0975900c21104ef04e73b4d1da5542a9e5781b674c915741bf21: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.083588746+08:00" level=error msg="collecting stats for 6e99eac2a12ac41c43ca94c31a6b1d1c13dd77204bb7cf64a07766f84e46b318: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.084663486+08:00" level=error msg="collecting stats for 62972425f38c44106a3224a387efce4d77088af7d7ddd42035e3a3f2f154d721: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.085717243+08:00" level=error msg="collecting stats for a74499f7af86a842177d665f97d0bc7b3da36f5881e2106d37192d708c4ca44f: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.104990307+08:00" level=error msg="collecting stats for 52a871f4f2fd1d04007e2454a703f91768a23ad1ea1177392b08a14bdc3d8742: rpc error: code = 2 desc = exit status 2: \"runtime/cgo: pthread_create failed: Resource temporarily unavailable\\nSIGABRT: abort\\nPC=0x7fd45cda98d7 m=4\\n\\ngoroutine 0 [idle]:\\n\\ngoroutine 1 [runnable]:\\nsyscall.Syscall(0x0, 0x5, 0xc82011626e, 0xd92, 0x0, 0xd92, 0x0)\\n\\t/usr/lib64/go/src/syscall/asm_linux_amd64.s:18 +0x5\\nsyscall.read(0x5, 0xc82011626e, 0xd92, 0xd92, 0x30, 0x0, 0x0)\\n\\t/usr/lib64/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f\\nsyscall.Read(0x5, 0xc82011626e, 0xd92, 0xd92, 0xc81fff6dff, 0x0, 0x0)\\n\\t/usr/lib64/go/src/syscall/syscall_unix.go:161 +0x4d\\nos.(*File).read(0xc820024170, 0xc82011626e, 0xd92, 0xd92, 0x42f79f, 0x0, 0x0)\\n\\t/usr/lib64/go/src/os/file_unix.go:228 +0x53\\nos.(*File).Read(0xc820024170, 0xc82011626e, 0xd92, 0xd92, 0xc5a100, 0x0, 0x0)\\n\\t/usr/lib64/go/src/os/file.go:95 +0x8a\\nbufio.(*Scanner).Scan(0xc82009e7e0, 0xc8200de6f0)\\n\\t/usr/lib64/go/src/bufio/scan.go:208 +0x97b\\ngithub.com/opencontainers/runc/libcontainer/cgroups/fs.(*MemoryGroup).GetStats(0xc752c8, 0xc82000ca80, 0x5d, 0xc8200fe000, 0x0, 0x0)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go:200 +0x259\\ngithub.com/opencontainers/runc/libcontainer/cgroups/fs.(*Manager).GetStats(0xc8200e8b40, 0x0, 0x0, 0x0)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go:185 +0x3c1\\ngithub.com/opencontainers/runc/libcontainer.(*linuxContainer).Stats(0xc8200b60c0, 0x84abd8, 0x0, 0x0)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/libcontainer/container_linux.go:157 +0xa5\\nmain.glob.func4(0xc82007aa00, 0x0, 0x0)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/events.go:142 +0x3ba\\nreflect.Value.call(0x74ecc0, 0x900388, 0x13, 0x8468c8, 0x4, 0xc82009f278, 0x1, 0x1, 0x0, 0x0, ...)\\n\\t/usr/lib64/go/src/reflect/value.go:435 +0x120d\\nreflect.Value.Call(0x74ecc0, 0x900388,
dockerd[1836]: 0x13, 0xc82009f278, 0x1, 0x1, 0x0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/reflect/value.go:303 +0xb1\\ngithub.com/urfave/cli.HandleAction(0x74ecc0, 0x900388, 0xc82007aa00, 0x0, 0x0)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee\\ngithub.com/urfave/cli.Command.Run(0x849128, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dff00, 0x58, 0x0, ...)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec\\ngithub.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a180, 0x4, 0x4, 0x0, 0x0)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4\\nmain.main()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/main.go:137 +0xe24\\n\\ngoroutine 17 [syscall, locked to thread]:\\nruntime.goexit()\\n\\t/usr/lib64/go/src/runtime/asm_amd64.s:1998 +0x1\\n\\ngoroutine 6 [syscall]:\\nos/signal.signal_recv(0x0)\\n\\t/usr/lib64/go/src/runtime/sigqueue.go:116 +0x132\\nos/signal.loop()\\n\\t/usr/lib64/go/src/os/signal/signal_unix.go:22 +0x18\\ncreated by os/signal.init.1\\n\\t/usr/lib64/go/src/os/signal/signal_unix.go:28 +0x37\\n\\ngoroutine 7 [runnable]:\\nmain.glob.func4.1(0xc8200f2cd0, 0xc82000cc00)\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/events.go:132\\ncreated by main.glob.func4\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/events.go:140 +0x369\\n\\nrax    0x0\\nrbx    0x7fd45d1136b8\\nrcx    0x7fd45cda98d7\\nrdx    0x6\\nrdi    0x19d4f\\nrsi    0x19d52\\nrbp    0x90e381\\nrsp    0x7fd45bd71968\\nr8     0xa\\nr9     0x7fd45bd72700\\nr10    0x8\\nr11    0x202\\nr12    0x7fd4540008c0\\nr13    0x8fed94\\nr14    0x0\\nr15    0x8\\nrip    0x7fd45cda98d7\\nrflags 0x202\\ncs     0x33\\nfs     0x0\\ngs     0x0\\n\""
dockerd[1836]: time="2018-05-02T09:53:05.111395353+08:00" level=error msg="collecting stats for 6ad214b0da25aa1945dc1b6a36abdd7b5a57af8f48040e67925d4dd47552bf48: rpc error: code = 2 desc = exit status 2: \"runtime/cgo: pthread_create failed: Resource temporarily unavailable\\nSIGABRT: abort\\nPC=0x7f646cea68d7 m=4\\n\\ngoroutine 0 [idle]:\\n\\ngoroutine 1 [chan receive, locked to thread]:\\ntext/template/parse.(*Tree).nextNonSpace(0xc8200862a0, 0x0, 0x0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:102 +0x14c\\ntext/template/parse.(*Tree).expect(0xc8200862a0, 0xe, 0x849058, 0x3, 0x0, 0x0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:171 +0x47\\ntext/template/parse.(*Tree).endControl(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:514 +0x54\\ntext/template/parse.(*Tree).action(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:369 +0xfe\\ntext/template/parse.(*Tree).textOrAction(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:350 +0x8d\\ntext/template/parse.(*Tree).itemList(0xc8200862a0, 0xc82005b350, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:332 +0x103\\ntext/template/parse.(*Tree).parseControl(0xc8200862a0, 0xc82000e601, 0x8496f0, 0x2, 0x0, 0x3, 0xc8200105f0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:457 +0x15c\\ntext/template/parse.(*Tree).ifControl(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:491 +0x5c\\ntext/template/parse.(*Tree).action(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:371 +0x4c9\\ntext/template/parse.(*Tree).textOrAction(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:350 +0x8d\\ntext/template/parse.(*Tree).parse(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:295 +0x6be\\ntext/template/parse.(*Tree).Parse(0xc8200862a0, 0x906560, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc82005b0e0, 0xc820012e30, 0x2, ...)\\n\\t/usr/lib64/go/src/text/template/parse/parse.g
dockerd[1836]: o:234 +0x299\\ntext/template/parse.Parse(0x8490f0, 0x5, 0x906560, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc820012e30, 0x2, ...)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:55 +0x14c\\ntext/template.(*Template).Parse(0xc82000aa00, 0x906560, 0xf0, 0x8aa300, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/template.go:190 +0x2ab\\ngithub.com/opencontainers/runc/libcontainer.init()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/libcontainer/generic_error.go:36 +0x17d\\nmain.init()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/utils_linux.go:315 +0x69\\n\\ngoroutine 17 [syscall, locked to thread]:\\nruntime.goexit()\\n\\t/usr/lib64/go/src/runtime/asm_amd64.s:1998 +0x1\\n\\ngoroutine 5 [runnable]:\\ntext/template/parse.lexIdentifier(0xc82007e380, 0x900ab8)\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:449 +0x322\\ntext/template/parse.(*lexer).run(0xc82007e380)\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:223 +0x52\\ncreated by text/template/parse.lex\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:216 +0x162\\n\\nrax    0x0\\nrbx    0x7f646d2106b8\\nrcx    0x7f646cea68d7\\nrdx    0x6\\nrdi    0x19d54\\nrsi    0x19d57\\nrbp    0x90e381\\nrsp    0x7f646be6e978\\nr8     0xa\\nr9     0x7f646be6f700\\nr10    0x8\\nr11    0x202\\nr12    0x7f64640008c0\\nr13    0x8fed94\\nr14    0x0\\nr15    0x8\\nrip    0x7f646cea68d7\\nrflags 0x202\\ncs     0x33\\nfs     0x0\\ngs     0x0\\n\""
dockerd[1836]: time="2018-05-02T09:53:05.112638174+08:00" level=error msg="collecting stats for 657cf90925efd137cf73362a51d78f656cc0b99c86f8f813b037e63c26285247: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.113664421+08:00" level=error msg="collecting stats for 46db11e42fa8f72c225c6761b5744a044d01b6fc17df827ab1fec6e62f0ddd47: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.114716199+08:00" level=error msg="collecting stats for a8d701ccc7b90b4b2e623eda1af9723c97d41218d48a282a6b2ec206a9940073: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:05.115696298+08:00" level=error msg="collecting stats for ba72a15141cffb0a3924a6a9f90a7b5958768dbd6ee720176591eb40dbfba678: rpc error: code = 2 desc = fork/exec /usr/bin/docker-runc: resource temporarily unavailable: \"\""
dockerd[1836]: time="2018-05-02T09:53:06.078566620+08:00" level=error msg="collecting stats for fe60b88ac356405619f1d0ec4e90cb5875e86cd17bb91240cd0e7ac2fb9e1e1d: rpc error: code = 2 desc = exit status 2: \"runtime/cgo: pthread_create failed: Resource temporarily unavailable\\nSIGABRT: abort\\nPC=0x7f47ae15d8d7 m=4\\n\\ngoroutine 0 [idle]:\\n\\ngoroutine 1 [chan receive, locked to thread]:\\ntext/template/parse.(*Tree).parse(0xc8200862a0, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:282 +0xcaa\\ntext/template/parse.(*Tree).Parse(0xc8200862a0, 0x906560, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc82005b0e0, 0xc820012e30, 0x2, ...)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:234 +0x299\\ntext/template/parse.Parse(0x8490f0, 0x5, 0x906560, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc820012e30, 0x2, ...)\\n\\t/usr/lib64/go/src/text/template/parse/parse.go:55 +0x14c\\ntext/template.(*Template).Parse(0xc82000aa00, 0x906560, 0xf0, 0x8aa300, 0x0, 0x0)\\n\\t/usr/lib64/go/src/text/template/template.go:190 +0x2ab\\ngithub.com/opencontainers/runc/libcontainer.init()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/libcontainer/generic_error.go:36 +0x17d\\nmain.init()\\n\\t/home/abuild/go/src/github.com/opencontainers/runc/utils_linux.go:315 +0x69\\n\\ngoroutine 17 [syscall, locked to thread]:\\nruntime.goexit()\\n\\t/usr/lib64/go/src/runtime/asm_amd64.s:1998 +0x1\\n\\ngoroutine 5 [runnable]:\\ntext/template/parse.lexText(0xc82007e380, 0x900af8)\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:248 +0x233\\ntext/template/parse.(*lexer).run(0xc82007e380)\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:223 +0x52\\ncreated by text/template/parse.lex\\n\\t/usr/lib64/go/src/text/template/parse/lex.go:216 +0x162\\n\\nrax    0x0\\nrbx    0x7f47ae4c76b8\\nrcx    0x7f47ae15d8d7\\nrdx    0x6\\nrdi    0x19d68\\nrsi    0x19d6b\\nrbp    0x90e381\\nrsp    0x7f47ad125978\\nr8     0xa\\nr9     0x7f47ad126700\\nr10    0x8\\nr11    0x202\\nr12    0x7f47a80008c0\\nr13    0x8fed94\\nr14    0x0\\nr15    0x8\\nrip    0x7f47ae15d8d7\\nrflags 0x202\\ncs     0x33
dockerd[1836]: \\nfs     0x0\\ngs     0x0\\n\""**
```
I have no idea for this issue. When i use "server docker restart" command and test the same command and the result is normal.

**Comment by heijigaoke** [comment]
hello,anybody here?

**Comment by thaJeztah** [comment]
You're running a very old version of docker; Docker 1.12 reached End Of Life in January of last year, and hasn't been maintained since. In addition, there are no official Docker CE packages for SUSE (Docker EE (enterprise edition) does [exist for SLES](https://docs.docker.com/install/linux/docker-ee/suse/)); perhaps you're running a version of Docker that was packaged by SUSE? (if so, please report the issue through their issue tracker)

Because of the above, unfortunately there's not much we can help with here, so I'll close this issue, but feel free to continue the conversation
