### ISSUE TITLE
docker daemon not starting on Ubuntu16/WSL

### ISSUE THREAD

**Issue by RodolpheGohard** [moby/moby#37140]
**Description**

I am trying to run docker inside WSL. I tried various workarounds but the daemon won't start. Any docker command will give this output:

```
rodolphe@PHP140:~$ docker pull mongo
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Describe the results you received:**
When looking at /var/log/docker.log, here is what I get:

```

goroutine 35 [running]:
github.com/containerd/containerd/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc420038890, 0x7fd465d6ddae, 0x2, 0x2, 0x4)
        /go/src/github.com/containerd/containerd/vendor/github.com/boltdb/bolt/cursor.go:256 +0x40e
github.com/containerd/containerd/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc420045890, 0x7fd465d6ddae, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/containerd/containerd/vendor/github.com/boltdb/bolt/cursor.go:159 +0xb3
github.com/containerd/containerd/vendor/github.com/boltdb/bolt.(*Bucket).Bucket(0xc420236718, 0x7fd465d6ddae, 0x2, 0x2, 0x0)
        /go/src/github.com/containerd/containerd/vendor/github.com/boltdb/bolt/bucket.go:112 +0xfe
github.com/containerd/containerd/vendor/github.com/boltdb/bolt.(*Tx).Bucket(0xc420236700, 0x7fd465d6ddae, 0x2, 0x2, 0x7fd464eed2be)
        /go/src/github.com/containerd/containerd/vendor/github.com/boltdb/bolt/tx.go:101 +0x51
github.com/containerd/containerd/metadata.scanRoots(0x7fd465d7d4e0, 0xc4203a86c0, 0xc420236700, 0xc4202385a0, 0xc42039df00, 0x1)
        /go/src/github.com/containerd/containerd/metadata/gc.go:34 +0x8f
github.com/containerd/containerd/metadata.(*DB).getMarked.func1(0xc420236700, 0x0, 0x0)
        /go/src/github.com/containerd/containerd/metadata/db.go:328 +0x17b
github.com/containerd/containerd/vendor/github.com/boltdb/bolt.(*DB).View(0xc42022c1e0, 0xc420038bd0, 0x0, 0x0)
        /go/src/github.com/containerd/containerd/vendor/github.com/boltdb/bolt/db.go:629 +0x9c
github.com/containerd/containerd/metadata.(*DB).getMarked(0xc4201ee300, 0x7fd465d7d5a0, 0xc4201ffe60, 0xc420038fa8, 0xc42021a180, 0xc420038f18)
        /go/src/github.com/containerd/containerd/metadata/db.go:311 +0x7a
github.com/containerd/containerd/metadata.(*DB).GarbageCollect(0xc4201ee300, 0x7fd465d7d5a0, 0xc4201ffe60, 0x0, 0xc420020f70, 0xc420020f40, 0x2, 0x2)
        /go/src/github.com/containerd/containerd/metadata/db.go:227 +0xbd
github.com/containerd/containerd/gc/scheduler.(*gcScheduler).run(0xc4201ee3c0, 0x7fd465d7d5a0, 0xc4201ffe60)
        /go/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:289 +0x545
created by github.com/containerd/containerd/gc/scheduler.init.0.func1
        /go/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:111 +0x4bf
time="2018-05-24T00:38:04.535986300+02:00" level=error msg="containerd did not exit successfully" error="exit status 2" module=libcontainerd
time="2018-05-24T00:38:04.536623700+02:00" level=error msg="failed to get event" error="rpc error: code = Internal desc = transport is closing" module=libcontainerd namespace=moby
time="2018-05-24T00:38:04.536757700+02:00" level=error msg="failed to get event" error="rpc error: code = Internal desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2018-05-24T00:38:04.548460800+02:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.4.0-17134-Microsoft`, error: exit status 1"
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
rodolphe@PHP140:~$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm
```

**Output of `docker info`:**

```
rodolphe@PHP140:~$ docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows with ubuntu16 WSL:

```rodolphe@PHP140:~$ uname -a
Linux PHP140 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by AkihiroSuda** [comment]
This is unsupported
