### ISSUE TITLE
Docker ps hung after the 'The requested compute system operation is not valid in the current state' error

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#37395]
**Description**

Several days ago `docker ps` hung on a server. But if use some filter (e.g `docker ps -f name=prod`) then it works. This behavior is similar to the existing issue https://github.com/moby/moby/issues/30605 

After `docker ps` hung we started regularly (several tens times per minute) seeing following messages/errors in the Application docker windows event log:
```
HCSShim::GetContainers query={}
Result: {"Error":-1070137083,"ErrorMessage":"The requested compute system operation is not valid in the current state."}
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I collected goroutine traces and saw such goroutine locked to thread:
```
goroutine 1338176 [syscall, 3243 minutes, locked to thread]:
syscall.Syscall(0x7fffbbf3c680, 0x3, 0x9bf8e10, 0xc046c71170, 0xc0434f68f8, 0x48a170, 0x0, 0x0)
	/usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim._hcsStartComputeSystem(0x9bf8e10, 0xc046c71170, 0xc0434f68f8, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/zhcsshim.go:715 +0xb4
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim.hcsStartComputeSystem(0x9bf8e10, 0x0, 0x0, 0xc0434f68f8, 0x1, 0xc0434f6890)
	/go/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/zhcsshim.go:708 +0x85
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim.(*container).Start(0xc04875a040, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/container.go:317 +0x392
github.com/docker/docker/libcontainerd.(*container).start(0xc049e7ef00, 0xc0483ea030, 0xc0434f6de0, 0x1)
	/go/src/github.com/docker/docker/libcontainerd/container_windows.go:56 +0x19a
github.com/docker/docker/libcontainerd.(*client).Create(0xc0422e7fc0, 0xc04946aec0, 0x40, 0x0, 0x0, 0xc04441fab0, 0x6e, 0xc042063420, 0x9, 0x18231cb, ...)
	/go/src/github.com/docker/docker/libcontainerd/client_windows.go:274 +0x12e6
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc0420b18c0, 0xc0456116c0, 0x0, 0x0, 0xc04441fab0, 0x6e, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:166 +0x425
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc0420b18c0, 0xc048849f27, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x410f1f, 0x10)
	/go/src/github.com/docker/docker/daemon/start.go:86 +0x1ab
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc0426da100, 0x25d8250, 0xc047cafad0, 0x2120600, 0xc04996fea0, 0xc0494caa00, 0xc047caf890, 0x181f2d3, 0x5)
	/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:166 +0x26f
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x25d8250, 0xc047cafad0, 0x2120600, 0xc04996fea0, 0xc0494caa00, 0xc047caf890, 0x25d8250, 0xc047cafad0)
	/go/src/github.com/docker/docker/api/server/router/container/container.go:60 +0x70
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x25d8250, 0xc047cafad0, 0x2120600, 0xc04996fea0, 0xc0494caa00, 0xc047caf890, 0x25d8250, 0xc047cafad0)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xdf
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x25d8250, 0xc047caf980, 0x2120600, 0xc04996fea0, 0xc0494caa00, 0xc047caf890, 0xc048cde9c0, 0xc04983f900)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x564
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x25d8250, 0xc047caf980, 0x2120600, 0xc04996fea0, 0xc0494caa00, 0xc047caf890, 0xc045391ab0, 0x756ea157a02f0c)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:54 +0x878
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x25d8250, 0xc047caf980, 0x2120600, 0xc04996fea0, 0xc0494caa00, 0xc047caf890, 0x25d8250, 0xc047caf980)
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x9b9
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2120600, 0xc04996fea0, 0xc0494caa00)
	/go/src/github.com/docker/docker/api/server/server.go:139 +0x221
net/http.HandlerFunc.ServeHTTP(0xc0421deea0, 0x2120600, 0xc04996fea0, 0xc0494caa00)
	/usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0422ae6e0, 0x2120600, 0xc04996fea0, 0xc0494caa00)
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x25c
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc04297b030, 0x2120600, 0xc04996fea0, 0xc0494caa00)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x77
net/http.serverHandler.ServeHTTP(0xc042142160, 0x2120600, 0xc04996fea0, 0xc0494caa00)
	/usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0473ca320, 0x21220c0, 0xc048cde680)
	/usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2d5
```

If I reboot the host this issue disappear, but last time when i rebooted it again appeared in a few days.

Could you suggest what can be a reason of such behavior and it can be prevented? 

Thanks!

**Output of `docker version`:**

```
Client:
 Version:       17.06.2-ee-11
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    06fc007
 Built: Thu May 17 06:14:39 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-11
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   06fc007
  Built:        Thu May 17 06:17:26 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 47
 Running: 46
 Paused: 0
 Stopped: 1
Images: 32
Server Version: 17.06.2-ee-11
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2273.amd64fre.rs1_release_1.180427-1811)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 40
Total Memory: 160GiB
Name: ...
ID: VZIV:...
Docker Root Dir: E:\docker_storage_1_13
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 9555
 System Time: 2018-07-04T13:59:22.77692-05:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a 40 cores m4.10xl AWS EC2 instance

**Comment by jhowardmsft** [comment]
As you confirmed in the matching hcsshim repo, the hang does not repro on EE 18.03. Docker Inc would be the ones to figure out a fix to Docker EE 17.06, there's nothing that can be done in this repo.

For the second issue here, this has been tracked to a platform issue as per https://github.com/moby/moby/issues/37562#issuecomment-410318946. Hence closing this issue.
