### ISSUE TITLE
Cannot start Linux containers on Windows

### ISSUE THREAD

**Issue by Tealons** [moby/moby#37418]
I have trouble getting the Linux containers to work on my Windows 10. Windows containers is no problem, but trying to start Linux containers gives the following error:

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

I uploaded the logs with the following id: DBB86FDE-2B1F-46B7-B094-AAEFB20F7CEE/2018-07-09_09-12-12

Any ideas how to fix this?

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by rn** [comment]
@Tealons the https://github.com/docker/for-win/issues tracker would be a better place to report issue with Docker Desktop. I had a look at your diagnostics and found the following stack backtrace in the logs:
```
[21:40:08.415][ApiProxy       ][Info   ] Dial Hyper-V socket dec083e5-9d66-420d-b860-8f104b421934:23a432c2-537a-4291-bcb5-d62504644739
[21:40:08.424][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket dec083e5-9d66-420d-b860-8f104b421934:23a432c2-537a-4291-bcb5-d62504644739
[21:40:08.424][ApiProxy       ][Info   ] Exception 0xc0000005 0x0 0x0 0x5cdb32e1
[21:40:08.424][ApiProxy       ][Info   ] PC=0x5cdb32e1
[21:40:08.425][ApiProxy       ][Info   ] syscall.Syscall9(0x7ffbbb6b9900, 0x7, 0x7fc, 0xc0421d7408, 0x1, 0xc0421d73e4, 0xc0421d73e0, 0xc0420956b0, 0x0, 0x0, ...)
[21:40:08.425][ApiProxy       ][Info   ]        C:/go18/src/runtime/syscall_windows.go:185 +0x6b
[21:40:08.425][ApiProxy       ][Info   ] syscall.WSARecv(0x7fc, 0xc0421d7408, 0x1, 0xc0421d73e4, 0xc0421d73e0, 0xc0420956b0, 0x0, 0x0, 0x0)
[21:40:08.426][ApiProxy       ][Info   ]        C:/go18/src/syscall/zsyscall_windows.go:1545 +0x11b
[21:40:08.426][ApiProxy       ][Info   ] github.com/docker/pinata/v1/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).read(0xc04210c000, 0xc04207e1c8, 0x4, 0x4, 0x4, 0x4, 0xc0420d0420)
[21:40:08.426][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/v1/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:158 +0x11d
[21:40:08.426][ApiProxy       ][Info   ] github.com/docker/pinata/v1/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).Read(0xc04210c000, 0xc042204000, 0x1000, 0x1000, 0x40f39c, 0xc042095260, 0x30)
[21:40:08.426][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/v1/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go:305 +0xbd
[21:40:08.426][ApiProxy       ][Info   ] github.com/docker/pinata/v1/docker_proxy.(*withLogging).Read(0xc0420d04c0, 0xc042204000, 0x1000, 0x1000, 0x0, 0xc042381680, 0x40f39c)
[21:40:08.426][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/v1/docker_proxy/passthru.go:258 +0x77
[21:40:08.426][ApiProxy       ][Info   ] bufio.(*Reader).fill(0xc0423b81e0)
[21:40:08.426][ApiProxy       ][Info   ]        C:/go18/src/bufio/bufio.go:97 +0x11e
[21:40:08.426][ApiProxy       ][Info   ] bufio.(*Reader).ReadSlice(0xc0423b81e0, 0x44d40a, 0x9222c0, 0x0, 0xc000074fc0, 0xcb9020, 0x944c00)
[21:40:08.426][ApiProxy       ][Info   ]        C:/go18/src/bufio/bufio.go:338 +0xc2
[21:40:08.426][ApiProxy       ][Info   ] bufio.(*Reader).ReadLine(0xc0423b81e0, 0xc042418360, 0x90, 0x90, 0x9b0940, 0x892250, 0x4)
[21:40:08.426][ApiProxy       ][Info   ]        C:/go18/src/bufio/bufio.go:367 +0x3e
[21:40:08.426][ApiProxy       ][Info   ] net/textproto.(*Reader).readLineSlice(0xc0421d7888, 0x200000089bee0, 0xc0423817c0, 0x40fc0f, 0x90, 0x9b0940)
[21:40:08.426][ApiProxy       ][Info   ]        C:/go18/src/net/textproto/reader.go:55 +0x66
[21:40:08.426][ApiProxy       ][Info   ] net/textproto.(*Reader).ReadLine(0xc042381888, 0xc042418360, 0xc042204000, 0x3033148, 0xc0423b8101)
[21:40:08.426][ApiProxy       ][Info   ]        C:/go18/src/net/textproto/reader.go:36 +0x36
```

This is commonly caused by third part AV software. For example we have seen this with LavaSoft Webcompanion (https://github.com/moby/moby/issues/27423) and a few others.

Do you run any AV software?

**Comment by Tealons** [comment]
@thaJeztah Sorry, I thought I had summitted al the information needed. 

@rn I'm in a corporate environment with lots of AV and similar software. I just disabled some of them and was able to start the linux container! 

Just to be complete: I'm now running 18.05.0-ce-win67 (18263) channel: Edge
Docker version: 
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

Docker info:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155db0010e
ID: MZ73:K6CF:ZSMJ:YQNB:5DSW:ZXZ4:B2LY:6AYV:QHXS:3VSG:63J3:4SGV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 36
 System Time: 2018-07-10T14:27:44.0277159Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
I will find out which AV program is specifically responsible for the problem and post it here.
Thanks for the help!
