### ISSUE TITLE
[build] Panic while building image

### ISSUE THREAD

**Issue by manishtomar** [moby/moby#37603]
**Steps to reproduce the issue:**
1. Build image using below Dockerfile. Build context doesn't matter.
```
FROM golang:1.10-alpine

ADD https://github.com/docker-infra/reefer/releases/download/v0.0.4/reefer.gz /usr/local/bin/reefer.gz
RUN gunzip /usr/local/bin/reefer.gz && chmod a+x /usr/local/bin/reefer

ENV DISTRIBUTION_DIR /go/src/github.com/docker/distribution

RUN set -ex \
    && apk add --no-cache make git

WORKDIR $DISTRIBUTION_DIR
COPY . $DISTRIBUTION_DIR

RUN make PREFIX=/go clean binaries

# These ports correspond to http.addr and http.debug.addr in
# serverconf/config.yml.tmpl.
EXPOSE 5000 5001
CMD [ "reefer", \
      "-t", "serverconf/cloudfront_key.pem.tmpl", \
      "-t", "serverconf/config.cloudflare.yml.tmpl", \
      "-E", \
      "registry", "serve", "serverconf/config.cloudflare.yml" ]
```

**Describe the results you received:**
Got following panic and dockerd stops:
```
2018-08-07T00:23:43Z docker-ce time="2018-08-07T00:23:43.333963900Z" level=debug msg="saved nhiic5ww1mr69igeffvc9q3pr as local.sharedKey:dockerfile:Dockerfile:cf1e395a3ba40baf14193289c3a249f3843edbd4c45a86fc74e708ddefd8455e"
2018-08-07T00:23:44Z docker-ce panic: invalid dispatch: return leaving incoming open
2018-08-07T00:23:44Z docker-ce 
2018-08-07T00:23:44Z docker-ce goroutine 527 [running]:
2018-08-07T00:23:44Z docker-ce github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc42029e2a0, 0xc420036b40)
2018-08-07T00:23:44Z docker-ce 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:173 +0xdd4
2018-08-07T00:23:44Z docker-ce github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).loop(0xc42029e2a0)
2018-08-07T00:23:44Z docker-ce 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:97 +0x163
2018-08-07T00:23:44Z docker-ce created by github.com/docker/docker/vendor/github.com/moby/buildkit/solver.newScheduler
2018-08-07T00:23:44Z docker-ce 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:28 +0x1d7
```
Following is build output after just before it crashed:
```
[+] Building 1.4s (6/11)
 => local://dockerfile (Dockerfile.hub.cloudflare)                                                                                                      0.1s
 => => transferring dockerfile: 769B                                                                                                                    0.0s
 => local://context (.dockerignore)                                                                                                                     0.1s
 => => transferring context: 02B                                                                                                                        0.0s
 => docker-image://docker.io/tonistiigi/copy:v0.1.3@sha256:e57a3b4d6240f55bac26b655d2cfb751f8b9412d6f7bb1f787e946391fb4b21b                             0.0s
 => local://context                                                                                                                                     0.0s
 => docker-image://docker.io/library/golang:1.10-alpine                                                                                                 0.0s
 => https://github.com/docker-infra/reefer/releases/download/v0.0.4/reefer.gz                                                                           1.2s
```

**Describe the results you expected:**
Expected to build the image.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens every-time.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      true

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 760
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: ULIQ:IUQA:2PYJ:ABG5:ZTWQ:VPBA:7U2H:O5C7:4XT6:LV4G:PBAS:J2R6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2018-08-07T17:40:45.26815886Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 18.236.198.155:5000
 54.202.63.156
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is with Docker for Mac.

**Comment by manishtomar** [comment]
This may be same to #37473. Please feel free to mark it as duplicate.

**Comment by manishtomar** [comment]
cc @tonistiigi

**Comment by tonistiigi** [comment]
@manishtomar Unfortunately could not reproduce. Just get

```
 => ERROR /bin/sh -c make PREFIX=/go clean binaries                                                                                                                                                                                      0.2s
------
 > /bin/sh -c make PREFIX=/go clean binaries:
#11 0.080 make: *** No rule to make target 'clean'.  Stop.
```

You say it happens every time. Is there any commands you run before that? Or maybe it depends on the cache state? If it really happens every time could I send you a binary with extra debugging? Could you also post the full panic trace please.

**Comment by manishtomar** [comment]
> Is there any commands you run before that?

Not really.

> Or maybe it depends on the cache state? If it really happens every time could I send you a binary with extra debugging?

Could be due to cache state. Please feel free to send the binary with extra debug.

> Could you also post the full panic trace please.

Sure. Do you know where I can get that in D4M?

**Comment by thaJeztah** [comment]
> Do you know where I can get that in D4M?

You can bind mount `/var/log` in a container, eg;

```
docker run -it --rm -v /var/log:/var/log alpine sh
```

Daemon logs should be in there

**Comment by manishtomar** [comment]
@tonistiigi I got logs by following steps in https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs: https://gist.github.com/manishtomar/cacc2cb1e103a7e821e49382b661cc9e

**Comment by tiborvass** [comment]
@tonistiigi debug logs https://gist.github.com/tiborvass/2f7e471588924002521a4c7a9c8d7b0f

**Comment by tiborvass** [comment]
FWIW, as an additional datapoint, I just hit the same bug separately, on another project. I'm using master (merge of cancel bugfix f1ef16c736 into master 4122eb1a43)... Unfortunately my state is gigantic (87G, it's my dev machine).

**Comment by tiborvass** [comment]
Here I used the buildkit-debug dockerd: https://gist.github.com/tiborvass/e98d87e697ecd0fbdffe07e6e767dc8b

**Comment by tonistiigi** [comment]
Leaving this open until vendor is updated
