### ISSUE TITLE
docker container gets hung

### ISSUE THREAD

**Issue by krishnaghatti** [moby/moby#37606]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
We deploy docker containers on Mesos/Marathon setup. When we re-deploy an app in marathon, the containers gets re-deployed with the changes required. Once in a while the container gets stuck and does not respond. Trying to stop the container also does not help. Restarting the docker service also does not work as the veth interface is held up for some reason. We end with restarting the instance which brings back the instance into working state.

**Steps to reproduce the issue:**
Issue is intermittent and I am not sure how to reproduces.

**Describe the results you received:**
docker containers get hung and any command like `docker stop` gets hung and they do not respond.

**Describe the results you expected:**
application gets redeployed and the containers get rotated.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens intermittently when deploying apps via marathon on mesos.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1014-azure
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 110.2GiB
Name: mslave9.prod-zipcash.az.om.net
ID: S6GN:YQLU:2QVG:77Z3:BNM4:BZRD:C6WU:E7RB:3KO6:G24U:N4WC:P4AW
Docker Root Dir: /mnt
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 repo.corp.olacabs.com:5000
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Instance details : Azure Standard D14 v2 instance.

**Docker stack trace**
```
# curl --unix-socket /var/run/docker.sock http:/./debug/pprof/goroutine?debug=2
goroutine 125416 [running]:
runtime/pprof.writeGoroutineStacks(0x272ee00, 0xc420150700, 0x30, 0xc4220a4390)
    /usr/local/go/src/runtime/pprof/pprof.go:603 +0x79
runtime/pprof.writeGoroutine(0x272ee00, 0xc420150700, 0x2, 0xc420d9d5a0, 0x4151a8)
    /usr/local/go/src/runtime/pprof/pprof.go:592 +0x44
runtime/pprof.(*Profile).WriteTo(0x270bf60, 0x272ee00, 0xc420150700, 0x2, 0xc420150700, 0x7f23b229b960)
    /usr/local/go/src/runtime/pprof/pprof.go:302 +0x3b5
net/http/pprof.handler.ServeHTTP(0xc4220a40d1, 0x9, 0x2747180, 0xc420150700, 0xc420ac2500)
    /usr/local/go/src/net/http/pprof/pprof.go:209 +0x1d1
net/http/pprof.(*handler).ServeHTTP(0xc420b35a50, 0x2747180, 0xc420150700, 0xc420ac2500)
    <autogenerated>:1 +0x74
github.com/docker/docker/api/server/router/debug.handlePprof(0x7f23b22074b8, 0xc4220a42d0, 0x2747180, 0xc420150700, 0xc420ac2500, 0xc4220a4240, 0x7f23b22074b8, 0xc4220a42d0)
    /go/src/github.com/docker/docker/api/server/router/debug/debug_routes.go:11 +0xb2
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f23b22074b8, 0xc4220a42d0, 0x2747180, 0xc420150700, 0xc420ac2500, 0xc4220a4240, 0x7f23b22074b8, 0xc4220a42d0)
    /go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f23b22074b8, 0xc4220a42a0, 0x2747180, 0xc420150700, 0xc420ac2500, 0xc4220a4240, 0xc421bc47c0, 0xc42024ba00)
    /go/src/github.com/docker/docker/api/server/middleware/version.go:58 +0x487
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f23b22074b8, 0xc4220a42a0, 0x2747180, 0xc420150700, 0xc420ac2500, 0xc4220a4240, 0x7f23b22074b8, 0xc4220a42a0)
    /go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x871
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2747180, 0xc420150700, 0xc420ac2500)
    /go/src/github.com/docker/docker/api/server/server.go:137 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc4202a6b40, 0x2747180, 0xc420150700, 0xc420ac2500)
    /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42011cff0, 0x2747180, 0xc420150700, 0xc420ac2500)
    /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4208ccd20, 0x2747180, 0xc420150700, 0xc420ac2500)
    /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4200af6b0, 0x2747180, 0xc420150700, 0xc420ac2500)
    /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420a6aaa0, 0x2748d80, 0xc421bc45c0)
    /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2668 +0x2ce
goroutine 1 [chan receive, 29961 minutes]:
main.(*DaemonCli).start(0xc4203e65d0, 0xc420187030, 0x0, 0x0)
    /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:307 +0x1a52
main.runDaemon(0xc420187030, 0xc4200fc750, 0x0)
    /go/src/github.com/docker/docker/cmd/dockerd/docker.go:78 +0x76
main.newDaemonCommand.func1(0xc42042a480, 0xc420214460, 0x0, 0x2, 0x0, 0x0)
    /go/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x5b
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc42042a480, 0xc420010220, 0x2, 0x2, 0xc42042a480, 0xc420010220)
    /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42042a480, 0x1873fc0, 0x1, 0xc420220330)
    /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42042a480, 0xc420220330, 0x0)
    /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
    /go/src/github.com/docker/docker/cmd/dockerd/docker.go:105 +0xe6
goroutine 17 [syscall, 29961 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 18 [syscall, 29929 minutes]:
os/signal.signal_recv(0x273c8c0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
goroutine 30 [chan receive]:
github.com/docker/docker/libcontainerd.(*remote).handleConnectionChange(0xc42008a8f0)
    /go/src/github.com/docker/docker/libcontainerd/remote_unix.go:148 +0xe2
created by github.com/docker/docker/libcontainerd.New
    /go/src/github.com/docker/docker/libcontainerd/remote_unix.go:122 +0x663
goroutine 27 [syscall, 29961 minutes]:
syscall.Syscall6(0xf7, 0x1, 0xb37, 0xc4200325b0, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4203e7d40, 0xc420032790, 0xc4200001a0, 0x0)
    /usr/local/go/src/os/wait_waitid.go:28 +0xa5
os.(*Process).wait(0xc4203e7d40, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/exec_unix.go:22 +0x4d
os.(*Process).Wait(0xc4203e7d40, 0x0, 0xc420001ba0, 0x1b4ed48)
    /usr/local/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc42012cdc0, 0x1b4ea80, 0x0)
    /usr/local/go/src/os/exec/exec.go:435 +0x62
github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon.func1(0xc42012cdc0, 0xc42008a8f0)
    /go/src/github.com/docker/docker/libcontainerd/remote_unix.go:440 +0x2b
created by github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon
    /go/src/github.com/docker/docker/libcontainerd/remote_unix.go:442 +0xb7c
goroutine 29 [select, 29961 minutes]:
github.com/docker/docker/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc4204d36c0)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/clientconn.go:891 +0x694
github.com/docker/docker/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(0xc4204d36c0)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/clientconn.go:620 +0x1d9
created by github.com/docker/docker/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/clientconn.go:621 +0x776
goroutine 15 [select, 21 minutes]:
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc420228f80, 0xc420215ff0, 0x5, 0x5, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:144 +0x556
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420415560, 0xc420215ff0, 0x5, 0x5, 0xc420ac5000, 0x7f23b229cc20, 0x0)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:332 +0x5c
io.ReadAtLeast(0x272e100, 0xc420415560, 0xc420215ff0, 0x5, 0x5, 0x5, 0xc421eded64, 0xc421e39c8f, 0xc421e39c88)
    /usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x272e100, 0xc420415560, 0xc420215ff0, 0x5, 0x5, 0xc421e39cb8, 0x43848e, 0xc420070340)
    /usr/local/go/src/io/io.go:325 +0x58
github.com/docker/docker/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc420215fe0, 0x7fffffff, 0xc420070340, 0x300000002, 0xc420070340, 0xc421e39d60, 0x43848e, 0xc420070340)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/rpc_util.go:218 +0x69
github.com/docker/docker/vendor/google.golang.org/grpc.recv(0xc420215fe0, 0x27485c0, 0x27b8918, 0xc420415560, 0x0, 0x0, 0x1989f20, 0xc421445d00, 0x7fffffff, 0x0, ...)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/rpc_util.go:314 +0x4d
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc42012d340, 0x1989f20, 0xc421445d00, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:376 +0xe6
github.com/docker/docker/vendor/github.com/containerd/containerd/api/grpc/types.(*aPIEventsClient).Recv(0xc4202215e0, 0xed2fb39f3, 0xd4f89d2, 0x0)
    /go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/api/grpc/types/api.pb.go:2116 +0x62
github.com/docker/docker/libcontainerd.(*remote).handleEventStream(0xc42008a8f0, 0x274f700, 0xc4202215e0)
    /go/src/github.com/docker/docker/libcontainerd/remote_unix.go:308 +0x49
created by github.com/docker/docker/libcontainerd.(*remote).startEventsMonitor
    /go/src/github.com/docker/docker/libcontainerd/remote_unix.go:302 +0x34f
goroutine 33 [IO wait]:
net.runtime_pollWait(0x7f23b2242600, 0x72, 0x7)
    /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420187568, 0x72, 0x2736000, 0x2728128)
    /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420187568, 0xc420488000, 0x8000)
    /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420187500, 0xc420488000, 0x8000, 0x8000, 0x0, 0x2736000, 0x2728128)
    /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e228, 0xc420488000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:181 +0x70
bufio.(*Reader).Read(0xc42024d740, 0xc4201502d8, 0x9, 0x9, 0x6, 0xc42001a668, 0xc42001a600)
    /usr/local/go/src/bufio/bufio.go:213 +0x312
io.ReadAtLeast(0x2729f40, 0xc42024d740, 0xc4201502d8, 0x9, 0x9, 0x9, 0x1b4dfd8, 0xc420248dd0, 0x20)
    /usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x2729f40, 0xc42024d740, 0xc4201502d8, 0x9, 0x9, 0xc420248e11, 0xc420fedda0, 0xc42102fd40)
    /usr/local/go/src/io/io.go:325 +0x58
github.com/docker/docker/vendor/golang.org/x/net/http2.readFrameHeader(0xc4201502d8, 0x9, 0x9, 0x2729f40, 0xc42024d740, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/docker/docker/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4201502a0, 0xc, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc4203ce060, 0xc420fedda0, 0xc420fedda0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/http_util.go:544 +0x2f
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc4204de900)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/http2_client.go:1057 +0xcd
created by github.com/docker/docker/vendor/google.golang.org/grpc/transport.newHTTP2Client
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/http2_client.go:250 +0xc91
goroutine 66 [select, 207 minutes]:
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc4204de900)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/http2_client.go:1130 +0x65a
created by github.com/docker/docker/vendor/google.golang.org/grpc/transport.newHTTP2Client
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/http2_client.go:280 +0x1055
goroutine 67 [select, 29961 minutes]:
github.com/docker/docker/vendor/google.golang.org/grpc.newClientStream.func3(0x2751140, 0xc4204de900, 0xc4204d3520, 0xc42012d340, 0xc420415560)
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:241 +0x3c9
created by github.com/docker/docker/vendor/google.golang.org/grpc.newClientStream
    /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:260 +0xd85
goroutine 16 [select, 29961 minutes, locked to thread]:
runtime.gopark(0x1b4ec08, 0x0, 0x1abe099, 0x6, 0x18, 0x2)
    /usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420047f50, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420047f50)
    /usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 54 [chan receive, 29929 minutes]:
github.com/docker/docker/pkg/signal.Trap.func1(0xc4204fee40, 0x272d6c0, 0xc420016190, 0xc4204eb3e0)
    /go/src/github.com/docker/docker/pkg/signal/trap.go:38 +0x77
created by github.com/docker/docker/pkg/signal.Trap
    /go/src/github.com/docker/docker/pkg/signal/trap.go:68 +0x148
goroutine 56 [chan receive, 29961 minutes]:
github.com/docker/docker/daemon.(*Daemon).setupDumpStackTrap.func1(0xc42012e780, 0x1accbbe, 0xf)
    /go/src/github.com/docker/docker/daemon/debugtrap_unix.go:18 +0x68
created by github.com/docker/docker/daemon.(*Daemon).setupDumpStackTrap
    /go/src/github.com/docker/docker/daemon/debugtrap_unix.go:26 +0xd0
goroutine 61 [IO wait, 29961 minutes]:
net.runtime_pollWait(0x7f23... 

```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
