### ISSUE TITLE
race on shutdown?

### ISSUE THREAD

**Issue by kolyshkin** [moby/moby#37735]
Testing PR https://github.com/moby/moby/pull/37358 on powerpc CI revealed a real bug (most probably unrelated to the PR).

CI logs show (from https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/11035/console):
> 01:46:49.181 FAIL: docker_cli_daemon_test.go:1770: DockerDaemonSuite.TestDaemonNoSpaceLeftOnDeviceError
> ...
> 01:46:49.182 ... Error: Error while stopping the daemon d51b1c53d414d : exit status 2

daemon logs show:

> panic: send on closed channel
>         
> goroutine 167 [running]:
> github.com/docker/docker/pkg/progress.chanOutput.WriteProgress(0xc0000a57a0, 0xc001238967, 0xc, > 0x0, 0x0, 0x104987cd9, 0xa, 0x2b7b5c9, 0x2b7b5c9, 0x0, ...)
>        /go/src/github.com/docker/docker/pkg/progress/progress.go:42 +0x98
> github.com/docker/docker/pkg/progress.(*Reader).updateProgress(0xc0000a3440, 0xc001c7e001)
>         /go/src/github.com/docker/docker/pkg/progress/progressreader.go:64 +0x130

Full log in the next message

**Comment by thaJeztah** [comment]
A workaround is in place, but would be good if we could find the root cause

**Comment by jfhamlin** [comment]
I've reproduced this many times on docker 18.06.1-ce running on AWS ECS. Every time I've seen it, the panic is preceded by errors about insufficient thin pool space. In case it helps, here's the tail end of /var/log/docker after one of these panics:

```
time="2018-11-13T04:57:34.081514556Z" level=info msg="Attempting next endpoint for pull after error: failed to register layer: devmapper: Thin Pool has 4254 free data blocks which is less than minimum required 4449 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"
time="2018-11-13T04:57:34.160117098Z" level=info msg="Layer sha256:f5c168f8eb5dca97033dd6879979a2b3a3f2144422d933d217ff2070f16b68b2 cleaned up"
time="2018-11-13T04:57:36.804420564Z" level=info msg="Layer sha256:9c70ca756704584bbbe1b41352e15536660104d5b17aacfe96f1c241382d7585 cleaned up"
time="2018-11-13T04:57:36.814667230Z" level=info msg="Layer sha256:14497c04782b58924d8fb689a0579a96ddd845e4d9584f3bd73b4c49754b0f68 cleaned up"
time="2018-11-13T04:57:36.826039876Z" level=info msg="Layer sha256:ccfcaf8fb471a2ec475db4fe91958b532e8cc1ba84ac42c51cb484346dc8ffc5 cleaned up"
time="2018-11-13T04:57:36.840501435Z" level=info msg="Layer sha256:7152b3dd92f68f075f10409f8a0060cc1e2cfe05bc39e9066d6962ab4fe16ccc cleaned up"
time="2018-11-13T04:57:36.850836352Z" level=info msg="Layer sha256:4bcdffd70da292293d059d2435c7056711fab2655f8b74f48ad0abe042b63687 cleaned up"
time="2018-11-13T04:57:36.851598569Z" level=error msg="Handler for POST /v1.19/containers/create returned error: devmapper: Thin Pool has 4248 free data blocks which is less than minimum required 4449 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"
time="2018-11-13T04:57:36.874578712Z" level=info msg="Attempting next endpoint for pull after error: failed to register layer: devmapper: Thin Pool has 4248 free data blocks which is less than minimum required 4449 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"
time="2018-11-13T04:57:36.885166164Z" level=info msg="Attempting next endpoint for pull after error: failed to register layer: devmapper: Thin Pool has 4248 free data blocks which is less than minimum required 4449 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"
time="2018-11-13T04:57:37Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/c92bf524c492fb0f49c668d7b999c0de73aa254ab26e73352e8f53456a5eeca1/shim.sock" debug=false pid=15419
time="2018-11-13T04:57:37.137580255Z" level=info msg="Layer sha256:c83c5ccf714d175d56ede407071952560e0b5b71ec13ed9c2e07763b4281455e cleaned up"
time="2018-11-13T04:57:37.159607045Z" level=info msg="Layer sha256:dd05337f7cfad305b293d633bd30b40b012a89d86b191decf0f5c1ee3bbf97ce cleaned up"
time="2018-11-13T04:57:37.261599037Z" level=info msg="Layer sha256:f715ed19c28b66943ac8bc12dbfb828e8394de2530bbaf1ecce906e748e4fdff cleaned up"
time="2018-11-13T04:57:38Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/47848ce95b049edc4d7d1b83d0621b9386ffddca056617c8a21198c483a4da1d/shim.sock" debug=false pid=15651
time="2018-11-13T04:57:39Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/88af0e14021ec74cc243d40d33f5ca569270275319fe79850446296bb49cf566/shim.sock" debug=false pid=15723
time="2018-11-13T04:57:42Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/d52ddaca6d137947389d88bef2a425ff4514a5adb8eefa8a2e4e72c27a406092/shim.sock" debug=false pid=15978
time="2018-11-13T04:57:43Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/013f3b8355a00483400d4339c4d7bbcfd96982254dbf46854da271b97936b169/shim.sock" debug=false pid=16076
time="2018-11-13T04:57:52Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/2c5d93b9eab1bd8598472cffeeceb62bb32d57fc65f56501a356c29e6b9280c7/shim.sock" debug=false pid=16340
time="2018-11-13T04:57:55Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/1ed21acd0d45a4d102f435b39719b5b83d67bbc028896e7db6348dba7d081ff9/shim.sock" debug=false pid=16494
panic: send on closed channel

goroutine 16579 [running]:
github.com/docker/docker/pkg/progress.chanOutput.WriteProgress(0xc4233b1200, 0xc425714e67, 0xc, 0x0, 0x0, 0x5577f03cabec, 0xa, 0x3a134c7, 0x3a134c7, 0x0, ...)
	/builddir/build/BUILD/docker-ce-18.06.1-ce/components/engine/_build/src/github.com/docker/docker/pkg/progress/progress.go:42 +0x68
github.com/docker/docker/pkg/progress.(*Reader).updateProgress(0xc4215ab5c0, 0xc4214be001)
	/builddir/build/BUILD/docker-ce-18.06.1-ce/components/engine/_build/src/github.com/docker/docker/pkg/progress/progressreader.go:64 +0xec
github.com/docker/docker/pkg/progress.(*Reader).Read(0xc4215ab5c0, 0xc4214be000, 0x8000, 0x8000, 0x8000, 0x8000, 0x0)
	/builddir/build/BUILD/docker-ce-18.06.1-ce/components/engine/_build/src/github.com/docker/docker/pkg/progress/progressreader.go:45 +0xda
bufio.(*Reader).fill(0xc4215ab620)
	/usr/lib/golang/src/bufio/bufio.go:100 +0x120
bufio.(*Reader).WriteTo(0xc4215ab620, 0x5577f0fe9ae0, 0xc42000fcb8, 0x7f353f5ba0e8, 0xc4215ab620, 0x8001)
	/usr/lib/golang/src/bufio/bufio.go:494 +0x10f
io.copyBuffer(0x5577f0fe9ae0, 0xc42000fcb8, 0x5577f0fe6460, 0xc4215ab620, 0x0, 0x0, 0x0, 0xc4214c6000, 0x8000, 0x8000)
	/usr/lib/golang/src/io/io.go:382 +0x36b
io.Copy(0x5577f0fe9ae0, 0xc42000fcb8, 0x5577f0fe6460, 0xc4215ab620, 0xc42000fc88, 0x7f353f622828, 0xc421a65fe0)
	/usr/lib/golang/src/io/io.go:362 +0x5c
os/exec.(*Cmd).stdin.func1(0x0, 0x5577eeeb2341)
	/usr/lib/golang/src/os/exec/exec.go:230 +0x57
os/exec.(*Cmd).Start.func1(0xc422ce0c60, 0xc421af2820)
	/usr/lib/golang/src/os/exec/exec.go:396 +0x29
created by os/exec.(*Cmd).Start
	/usr/lib/golang/src/os/exec/exec.go:395 +0x5e1
```

**Comment by free2k** [comment]
> A workaround is in place, but would be good if we could find the root cause

How can I avoid this problem?

**Comment by thaJeztah** [comment]
The workaround was merged I think; https://github.com/moby/moby/commit/7dac70324d0ce6acd23458b0bef06f099837d648

**Comment by lzhfromustc** [comment]
Since the Panic can be traced back to (*Reader).updateProgress() at [docker/pkg/progress/progressreader.go:64](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/pkg/progress/progressreader.go#L64), our buggy channel must be stored in Reader.out, and Reader.out is written in `NewProgressReader()`, at [docker/pkg/progress/progressreader.go:23](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/pkg/progress/progressreader.go#L23)

I will use "X" to denote `NewProgressReader()`. X is called by many places. I checked all possible call chains, ignored chains that didn't lead to a channel, and found four channels that may trigger this bug. 

(1)
channel Close:
https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/xfer/upload.go#L112-L114

How channel is stored to X:
[docker/distribution/xfer/upload.go:127](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/xfer/upload.go#L127) -> [docker/distribution/push_v2.go:424](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/push_v2.go#L424) -> [docker/distribution/push_v2.go:450](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/push_v2.go#L450) -> X

(2)
channel close:
https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/builder/builder-next/adapters/containerimage/pull.go#L512-L514

How channel is stored to X:
[docker/builder/builder-next/adapters/containerimage/pull.go:569](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/builder/builder-next/adapters/containerimage/pull.go#L569) -> [docker/plugin/blobstore.go:138](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/plugin/blobstore.go#L138) -> [docker/distribution/pull_v2.go:236](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull_v2.go#L236) -> X

(3)
channel Close:
https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/xfer/download.go#L244-L246

How channel is stored to X:
[docker/distribution/xfer/download.go:281](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/xfer/download.go#L281) -> [docker/distribution/pull_v2.go:236](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull_v2.go#L236) -> X
Or:
[docker/distribution/xfer/download.go:345](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/xfer/download.go#L345) -> X

(4)
channel Close:
https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/daemon/images/image_pull.go#L68-L72
https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/daemon/images/image_pull.go#L85

How channel is stored to v2Puller.config:
[docker/daemon/images/image_pull.go:84](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/daemon/images/image_pull.go#L84) -> [docker/distribution/pull.go:107](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull.go#L107) -> [docker/distribution/pull.go:38](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull.go#L38)

How v2Puller.config is stored to X:
[docker/distribution/pull_v2.go:545](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull_v2.go#L545) -> [docker/plugin/blobstore.go:138](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/plugin/blobstore.go#L138) -> [docker/distribution/pull_v2.go:236](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull_v2.go#L236) -> X
Or:
[docker/distribution/pull_v2.go:667](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull_v2.go#L667) -> [docker/plugin/blobstore.go:138](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/plugin/blobstore.go#L138) -> [docker/distribution/pull_v2.go:236](https://github.com/moby/moby/blob/d8772509d1a29b100c52c5c0f6cb5787a693db91/distribution/pull_v2.go#L236) -> X
