### ISSUE TITLE
Cannot switch to Windows Container due to HNS error: Element not found

### ISSUE THREAD

**Issue by zentby** [moby/moby#37754]
**Description**

When switching from Linux container to Windows container, it keeps failing with error messages. It will auto switch back to Linux container and windows container never works.

**Steps to reproduce the issue:**
1. Cleanup network (remove hns.data, remove all Virtual Switch etc )
2. Tried everything mentioned in other issues. e.g #34696
3. Re-install Docker for Windows
4. Can not switch to Windows container

**Describe the results you received:**

```
Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
```

And the detail message can be found in System Event:
```
fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Element not found. 
```

**Describe the results you expected:**

Should be able to switch to Windows container.

**Additional information you deem important (e.g. issue happens only occasionally):**

* I used to have VM running in Hyper-V
* I haven't touched windows container for almost a year

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
(The output is under linux container mode)

**Output of `docker info`:**

```
Containers: 0                                                                   
 Running: 0                                                                     
 Paused: 0                                                                      
 Stopped: 0                                                                     
Images: 3                                                                       
Server Version: 18.06.1-ce                                                      
Storage Driver: overlay2                                                        
 Backing Filesystem: extfs                                                      
 Supports d_type: true                                                          
 Native Overlay Diff: true                                                      
Logging Driver: json-file                                                       
Cgroup Driver: cgroupfs                                                         
Plugins:                                                                        
 Volume: local                                                                  
 Network: bridge host macvlan null overlay                                      
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog  
Swarm: inactive                                                                 
Runtimes: runc                                                                  
Default Runtime: runc                                                           
Init Binary: docker-init                                                        
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e                    
runc version: 69663f0bd4b60df09991c08812a60108003fa340                          
init version: fec3683                                                           
Security Options:                                                               
 seccomp                                                                        
  Profile: default                                                              
Kernel Version: 4.9.93-linuxkit-aufs                                            
Operating System: Docker for Windows                                            
OSType: linux                                                                   
Architecture: x86_64                                                            
CPUs: 2                                                                         
Total Memory: 1.934GiB                                                          
Name: linuxkit-00155d00a02e                                                     
ID: QJLZ:G64Z:JCBB:XXR3:NY3I:CCGK:KKII:ERFN:HFR7:5P2Y:RAJO:RBD3                 
Docker Root Dir: /var/lib/docker                                                
Debug Mode (client): false                                                      
Debug Mode (server): true                                                       
 File Descriptors: 22                                                           
 Goroutines: 47                                                                 
 System Time: 2018-09-04T03:09:49.5693953Z                                      
 EventsListeners: 1                                                             
Registry: https://index.docker.io/v1/                                           
Labels:                                                                         
Experimental: false                                                             
Insecure Registries:                                                            
 127.0.0.0/8                                                                    
Live Restore Enabled: false                                                     
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zentby** [comment]
It's awkward that I found the solution right after I created the ticket.

Followed the step [here](https://github.com/docker/for-win/issues/1126#issuecomment-332144830) that deleted the registry key in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nsi\{eb004a20-9b1a-11d4-9123-0050047759bc}`

And everything is working now!

**Comment by zzstuzor** [comment]
Nice - this worked for me too. I had like 11 entries with that GUID - I deleted all that I could (some weren't deleteable). Previously I was unable to delete the existing netnat (remove-netnat) but after deleting this GUID the netnats were all gone and docker was able to create its own network switch when launching dockerd
