### ISSUE TITLE
Nil Pointer Dereference at swarmkit/manager/orchestrator/task.go:121

### ISSUE THREAD

**Issue by rnataraja** [moby/moby#37883]
Iam seeing the following crash on a docker swarm manager. 
Version : 18.03.1, Iam running docker with a patch, but it is in totally unrelated area. 

I ran into an issue with plugin panic which is a known issue on 18.03.1. With no way to recovery from what I know, I also at some point cleaned up /var/lib/docker and /var/run/docker. 

But this is a crash none the less and should be fixed. Logs follow below:

Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.088523011-07:00" level=info msg="50b1b4067b4ddd5d became leader at term 3" module=raft node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.088539702-07:00" level=info msg="raft.node: 50b1b4067b4ddd5d elected leader 50b1b4067b4ddd5d at term 3" module=raft node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.105394306-07:00" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.105474437-07:00" level=error msg="failed to create predefined network bridge" error="name conflicts with an existing object" module=node node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.105508216-07:00" level=error msg="failed to create predefined network host" error="name conflicts with an existing object" module=node node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.105744252-07:00" level=info msg="dispatcher starting" module=dispatcher node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23-07:00" level=error msg="time=\"2018-09-19T16:46:23Z\" level=info msg=\"Get Capabilities was invoked \"" plugin=baf057d3ad106a927066fb8bd10cc46c2dff9d2ca0b4bba168041141ec1337f6
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23-07:00" level=error msg="time=\"2018-09-19T16:46:23Z\" level=info msg=\"Called Get Default Address Space\\n\"" plugin=baf057d3ad106a927066fb8bd10cc46c2dff9d2ca0b4bba168041141ec1337f6
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.107907074-07:00" level=debug msg="RequestPool(GlobalDefault, 10.255.0.0/16, , map[], false)"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.107952942-07:00" level=debug msg="Received set for ordinal 0, start 0, end 0, any false, release false, serial:false curr:0 \n"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.107974055-07:00" level=debug msg="Received set for ordinal 65535, start 0, end 0, any false, release false, serial:false curr:0 \n"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.108027648-07:00" level=debug msg="RequestAddress(GlobalDefault/10.255.0.0/16, 10.255.0.1, map[RequestAddressType:com.docker.network.gateway com.docker.network.ipam.serial:true])"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.108062055-07:00" level=debug msg="Received set for ordinal 1, start 0, end 0, any false, release false, serial:false curr:0 \n"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.108085883-07:00" level=debug msg="overlay network option: 4096"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.108105190-07:00" level=debug msg="Received set for ordinal 4096, start 0, end 0, any false, release false, serial:false curr:0 \n"
Sep 19 09:46:23 x.y.com dockerd[1385]: time="2018-09-19T09:46:23.123728561-07:00" level=debug msg="Root CA set successfully" cluster.id=mjm29j2s39hcpjb4m3w2d0ncb method="(*Server).UpdateRootCA" module=ca node.id=905bdhp0yginvumw9g3tplxei
Sep 19 09:46:23 x.y.com dockerd[1385]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 19 09:46:23 x.y.com dockerd[1385]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x564616b78966]
Sep 19 09:46:23 x.y.com dockerd[1385]: goroutine 471 [running]:

Sep 19 09:46:23 x.y.com dockerd[1385]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator.nodeMatches(0xc420b08640, 0xc420c04000, 0xc420c48370)
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/task.go:121 +0x36
Sep 19 09:46:23 x.y.com dockerd[1385]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator.IsTaskDirty(0xc420b08640, 0xc420ea1860, 0xc420c04000, 0x6001639e842)
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/task.go:85 +0x3a4
Sep 19 09:46:23 x.y.com dockerd[1385]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Updater).isTaskDirty(0xc420eaaeb0, 0xc420ea1860, 0x2a874a5772300a61)
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:528 +0x8d
Sep 19 09:46:23 x.y.com dockerd[1385]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Updater).isSlotDirty(0xc420eaaeb0, 0xc420e89628, 0x1, 0x1, 0x5646186f5f20)
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:532 +0x5e
Sep 19 09:46:23 x.y.com dockerd[1385]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Updater).Run(0xc420eaaeb0, 0x7f0b0aadc340, 0xc42013ce40, 0xc420b8a7a0, 0x1, 0x1)
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:139 +0x14e
Sep 19 09:46:23 x.y.com dockerd[1385]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Supervisor).Update.func1(0xc420eaaeb0, 0x7f0b0aadc340, 0xc42013ce40, 0xc420b8a7a0, 0x1, 0x1, 0xc42108fb20, 0xc420b38ca0, 0x19)
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:67 +0x63
Sep 19 09:46:23 x.y.com dockerd[1385]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Supervisor).Update
Sep 19 09:46:23 x.y.com dockerd[1385]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:66 +0x1e8

**Comment by rnataraja** [comment]
ping @cpuguy83 : Submitted.

**Comment by thaJeztah** [comment]
ping @cpuguy83 @dperny PTAL

**Comment by sgiacomel** [comment]
Hi, I experienced this as well, with both version 18.03 and 19.03.
Steps to reproduce:
- init a swarm with more than one node;
- create a service with at least one placement constraint;
- update the service removing completely the `Placement` field inside `TaskTemplate` => `ContainerSpec`. For example:

create: 
> "TaskTemplate":{"ContainerSpec":{"Image":"...","Command":["..."],"Args":["..."]},"Placement":{"Constraints":["node.role==manager"]}}

update: 
>"TaskTemplate":{"ContainerSpec":{"Image":"...","Command":["..."],"Args":["..."]}}

The workaround is leaving `Placement` empty:
> "TaskTemplate":{"ContainerSpec":{"Image":"...","Command":["..."],"Args":["..."]},"Placement":{}

**Comment by sgiacomel** [comment]
I reported here as well:
https://github.com/docker/swarmkit/issues/2947

**Comment by gbmeuk** [comment]
bumped into this on the latest versions in OpenSuSe package channels.

```
Information for package docker:
-------------------------------
Repository     : Main Update Repository
Name           : docker
Version        : 19.03.15_ce-lp152.2.9.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 158.3 MiB
Installed      : Yes
Status         : out-of-date (version 19.03.11_ce-lp152.1.1 installed)
Source package : docker-19.03.15_ce-lp152.2.9.1.src
Summary        : The Moby-project Linux container runtime
Description    : 
    Docker complements LXC with a high-level API which operates at the process
    level. It runs unix processes with strong guarantees of isolation and
    repeatability across servers.

    Docker is a great building block for automating distributed systems: large-scale
    web deployments, database clusters, continuous deployment systems, private PaaS,
    service-oriented architectures, etc.
```
Updated based on the info above but still failed to start. v20 isn't available in OpenSuse Leap channels yet and Docker don't seem to provide a repo?

```
Mar 09 19:28:42 lab2 dockerd[9876]: time="2021-03-09T19:28:42.005560847Z" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=kehi8t0b714ofk2mngpzjgd8k
Mar 09 19:28:42 lab2 dockerd[9876]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 09 19:28:42 lab2 dockerd[9876]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5615d4af3ab6]
Mar 09 19:28:42 lab2 dockerd[9876]: goroutine 283 [running]:
Mar 09 19:28:42 lab2 dockerd[9876]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator.nodeMatches(0xc0043852c0, 0xc004c64280, 0xc0075f7c40)
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/task.go:122 +0x36
Mar 09 19:28:42 lab2 dockerd[9876]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator.IsTaskDirty(0xc0043852c0, 0xc004c523c0, 0xc004c64280, 0x0)
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/task.go:86 +0x3f7
Mar 09 19:28:42 lab2 dockerd[9876]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Updater).isTaskDirty(0xc007d0b180, 0xc004c523c0, 0x6465316238746733)
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:530 +0x9e
Mar 09 19:28:42 lab2 dockerd[9876]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Updater).isSlotDirty(...)
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:534
Mar 09 19:28:42 lab2 dockerd[9876]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Updater).Run(0xc007d0b180, 0x5615d5ebec00, 0xc000c2ef40, 0xc0079355e0, 0x1, 0x1)
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:138 +0xd99
Mar 09 19:28:42 lab2 dockerd[9876]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Supervisor).Update.func1(0xc007d0b180, 0x5615d5ebec00, 0xc000c2ef40, 0xc0079355e0, 0x1, 0x1, 0xc000bffbc0, 0xc006256a20, 0x19)
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:66 +0x63
Mar 09 19:28:42 lab2 dockerd[9876]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update.(*Supervisor).Update
Mar 09 19:28:42 lab2 dockerd[9876]:         /home/abuild/rpmbuild/BUILD/docker-19.03.15_ce_99e3ed89195c/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go:65 +0x200
Mar 09 19:28:42 lab2 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 09 19:28:42 lab2 systemd[1]: Failed to start Docker Application Container Engine.
```
