### ISSUE TITLE
Daemon deadlock on some containers (18.03 CE)

### ISSUE THREAD

**Issue by mryan43** [moby/moby#37910]
Everyday, I have some containers randomly becoming deadlocked in my docker daemon. This causes commands such as "docker inspect" to hang forever for those containers.
The containers are managed by kubelet (1.10) running on ubuntu 16.04 in an LXC container.

I don't have an easy way to reproduce the issue. But I have a goroutine stack trace showing the deadlock. I'm not sure how to determine the root cause of the deadlock by looking at it, this is where I need some help.

Here's are my system versions : 
```Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.2
 Git commit:	0520e24
 Built:	Wed Mar 21 23:05:52 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:54 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
```
Containers: 187
 Running: 180
 Paused: 0
 Stopped: 7
Images: 151
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 188.2GiB
Name: sbuild14glc
ID: PYC6:IPBV:4VCQ:2UH7:ZTFG:RCGH:TOTN:6ZRO:JBE3:67ZK:PVGF:IUED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
```
Linux sbuild14glc 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
[goroutine-stacks-2018-09-25T072755Z.log](https://github.com/moby/moby/files/2414253/goroutine-stacks-2018-09-25T072755Z.log)

**Comment by cpuguy83** [comment]
Thanks for the report.

This looks like it's waiting on containerd after an exec start.

<details>

```
goroutine 62962078 [select]:
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc61e461c20, 0x241b588, 0xc42a34c980, 0x2ec5c40)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:256 +0x148
github.com/docker/docker/vendor/google.golang.org/grpc.recvResponse(0x7ff830b9d0b0, 0xc88f6efd10, 0xc42097c3e0, 0xc42097c400, 0x2ebc260, 0x2f430f0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:64 +0xae
github.com/docker/docker/vendor/google.golang.org/grpc.invoke(0x7ff830b9d0b0, 0xc88f6efd10, 0x1955896, 0x29, 0x22c3600, 0xc59d336f00, 0x22c36e0, 0xc985eafee0, 0xc42028c820, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:279 +0xd00
github.com/docker/docker/vendor/github.com/containerd/containerd.namespaceInterceptor.unary(0x190c3a6, 0x4, 0x7ff830b99030, 0xc420018038, 0x1955896, 0x29, 0x22c3600, 0xc59d336f00, 0x22c36e0, 0xc985eafee0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:18 +0xf6
github.com/docker/docker/vendor/github.com/containerd/containerd.(namespaceInterceptor).(github.com/docker/docker/vendor/github.com/containerd/containerd.unary)-fm(0x7ff830b99030, 0xc420018038, 0x1955896, 0x29, 0x22c3600, 0xc59d336f00, 0x22c36e0, 0xc985eafee0, 0xc42028c820, 0x241b560, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:34 +0xf6
github.com/docker/docker/vendor/google.golang.org/grpc.Invoke(0x7ff830b99030, 0xc420018038, 0x1955896, 0x29, 0x22c3600, 0xc59d336f00, 0x22c36e0, 0xc985eafee0, 0xc42028c820, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:141 +0xdf
github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1.(*tasksClient).Start(0xc6f6c41780, 0x7ff830b99030, 0xc420018038, 0xc59d336f00, 0x0, 0x0, 0x0, 0xc42a34d008, 0x15432d4, 0xc4200b19f0)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:423 +0xd4
github.com/docker/docker/vendor/github.com/containerd/containerd.(*process).Start(0xc88f6efc50, 0x2ebca60, 0xc420018038, 0x2ec60c0, 0xc88f6efc50)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/process.go:91 +0x142
github.com/docker/docker/libcontainerd.(*client).Exec(0xc4202fa850, 0x2ebca60, 0xc420018038, 0xc424717f40, 0x40, 0xd3b694bdc0, 0x40, 0xd4ebbb5e10, 0x0, 0xd1bb4d2fc0, ...)
	/go/src/github.com/docker/docker/libcontainerd/client_daemon.go:355 +0x4e8
github.com/docker/docker/daemon.(*Daemon).ContainerExecStart(0xc420406480, 0x7ff830b99030, 0xc420018038, 0xcd33862c11, 0x40, 0x7ff8301e0ad0, 0xc5a19b2de0, 0x2e9bea0, 0xc593446d60, 0x2e9bea0, ...)
	/go/src/github.com/docker/docker/daemon/exec.go:252 +0xb97
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainerExecStart(0xc42015fe40, 0x7ff830b9d0b0, 0xd1ea10e180, 0x2ebad60, 0xce2475ac40, 0xc819762800, 0xd1ea10e0f0, 0x0, 0x0)
```
</details>

A stack dump from containerd seems in order here.
You can get this by doing `docker-containerd-ctr pprof --debug-socket /run/docker/containerd/docker-containerd-debug.sock goroutines`

I also noticed you are on 18.03.0.
Please make sure to update at least to the latest patch release for 18.03, the issue may already be resolved.
Note that 18.06 is the latest CE release.

**Comment by mryan43** [comment]
After upgrading to 18.06.1CE, the problem seems to be gone (no deadlock in 5 days).

**Comment by cpuguy83** [comment]
Awesome, glad that worked out!

I believe Docker plans to split the packaging for Docker CE and containerd so that at least (in theory) containerd can be upgraded separately from dockerd in the future.

**Comment by Davidrjx** [comment]
for 18.06.2-ce, deadlock still exists
