### ISSUE TITLE
Can't start docker after downgrading from 18.06.1 to 18.03.1

### ISSUE THREAD

**Issue by fabiopedrosa** [moby/moby#38014]
After downgrading from 18.06.1 to 18.03.1 using `apt install docker-ce=18.03.1~ce-0~ubuntu`

I'm unable to start docker again, and using `sudo journalctl -fu docker.service` I'm seeing this:
```bash
Oct 10 21:17:19 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:19.077326499-07:00" level=info msg="Loading containers: start."
Oct 10 21:17:19 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:19.886042886-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:20.151921792-07:00" level=info msg="Loading containers: done."
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:20.196186939-07:00" level=info msg="Docker daemon" commit=9ee9f40 graphdriver(s)=overlay2 version=18.03.1-ce
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:20.236860079-07:00" level=info msg="Listening for connections" addr="[::]:2377" module=node node.id=jekuynk23ml225usol4s5c78l proto=tcp
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:20.236903655-07:00" level=info msg="Listening for local connections" addr=/var/run/docker/swarm/control.sock module=node node.id=jekuynk23ml225usol4s5c78l proto=unix
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:20.261093428-07:00" level=info msg="manager selected by agent for new session: {d0vr8w32wb4g1vowqcow5h4z3 192.168.51.110:2377}" module=node/agent node.id=jekuynk23ml225usol4s5c78l
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: time="2018-10-10T21:17:20.261331236-07:00" level=info msg="waiting 0s before registering session" module=node/agent node.id=jekuynk23ml225usol4s5c78l
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: panic: Copy for *types.BoolValue not implemented
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: goroutine 107 [running]:
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy.Copy(0x558cebba2e20, 0xc427ee2d6e, 0x558cebba2e20, 0xc42221299f)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy/copy.go:50 +0x3cb
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*ContainerSpec).CopyFrom(0xc427edf600, 0x558cebb67100, 0xc4229009a0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/specs.pb.go:1134 +0x957
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy.Copy(0x558cebb67100, 0xc427edf600, 0x558cebb67100, 0xc4229009a0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy/copy.go:48 +0x251
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*TaskSpec).CopyFrom(0xc4209d2058, 0x558cebbf0460, 0xc420a9d098)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/specs.pb.go:1026 +0x277
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy.Copy(0x558cebbf0460, 0xc4209d2058, 0x558cebbf0460, 0xc420a9d098)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy/copy.go:48 +0x251
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*ServiceSpec).CopyFrom(0xc4209d2028, 0x558cebbae940, 0xc420a9d068)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/specs.pb.go:905 +0xd4
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy.Copy(0x558cebbae940, 0xc4209d2028, 0x558cebbae940, 0xc420a9d068)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/deepcopy/copy.go:48 +0x251
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*Service).CopyFrom(0xc4209d2000, 0x558cebc02560, 0xc420a9d040)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/objects.pb.go:435 +0xcd
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*Service).Copy(0xc420a9d040, 0x19)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/objects.pb.go:426 +0x62
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*Service).CopyStoreObject(0xc420a9d040, 0x558ceb1967c9, 0x7)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/objects.pb.go:2323 +0x2d
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*tx).create(0xc427edc630, 0x558ceb1967c9, 0x7, 0x558cec74eac0, 0xc420a9d040, 0xc4210a71e0, 0x19)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:557 +0xca
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.RestoreTable(0x558cec74d020, 0xc427edc630, 0x558ceb1967c9, 0x7, 0xc4220da600, 0x18, 0x18, 0x0, 0x0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/object.go:44 +0x358
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.init.8.func2(0x558cec74d020, 0xc427edc630, 0xc423dfc038, 0x0, 0x0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/services.go:65 +0x14a
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*MemoryStore).Restore.func1(0x558cec74d020, 0xc427edc630, 0xc427ee8080, 0x558ce9d01ef8)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:821 +0x8f
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*MemoryStore).update(0xc4207ceac0, 0x0, 0x0, 0xc42128d440, 0x0, 0x0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:333 +0x175
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*MemoryStore).updateLocal(0xc4207ceac0, 0xc42128d440, 0x120, 0x558cebacae60)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:373 +0x49
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*MemoryStore).Restore(0xc4207ceac0, 0xc423dfc038, 0x485cda, 0x485cda)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:819 +0x4d
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/raft.(*Node).clusterSnapshot(0xc4200bac80, 0xc4213ec000, 0x485cda, 0x485cda, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/raft/storage.go:259 +0xc3
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/raft.(*Node).loadAndStart(0xc4200bac80, 0x7f06aaef4048, 0xc420c0b680, 0xc420f4fc00, 0xc4200bac80, 0xc4207ca800)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/raft/storage.go:76 +0xc3b
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/raft.(*Node).JoinAndStart(0xc4200bac80, 0x7f06aaef4048, 0xc420c0b680, 0x0, 0x0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/raft/raft.go:383 +0x108
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).Run(0xc4205a8680, 0x7f06aaf770b0, 0xc42076f770, 0x0, 0x0)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:526 +0x14d5
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).runManager.func1(0xc4205a8680, 0xc42114c130, 0xc421136c00, 0xc4207ec550)
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:857 +0x8f
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).runManager
Oct 10 21:17:20 pf-us1-sm6 dockerd[8034]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:856 +0x2ff
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: Failed to start Docker Application Container Engine.
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: docker.service: Unit entered failed state.
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: docker.service: Failed with result 'exit-code'.
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: Stopped Docker Application Container Engine.
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: docker.service: Start request repeated too quickly.
Oct 10 21:17:20 pf-us1-sm6 systemd[1]: Failed to start Docker Application Container Engine.

```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by AkihiroSuda** [comment]
As mentioned in https://github.com/moby/moby/issues/37806#issuecomment-419624182 , upgrading to 18.06.1 is likely to make this again. (or you need to remove /var/lib/docker)
