### ISSUE TITLE
Golang panic causes Dockerd to crash

### ISSUE THREAD

**Issue by turbo** [moby/moby#38735]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

A master node in our swarm instance is crash-looping because of a Go panic in dockerd. The main error is `fatal error: acquirep: invalid p state`, more details below.

**Steps to reproduce the issue:**

The problematic instance is available for testing. Reproduction outside of our environment hasn't been attempted.

**Describe the results you received:**

Here's the journal up to and including the crash: https://gist.github.com/turbo/9d89a765d599eacec53431c79e9b9ff1

After 2000 lines of stack trace, the daemon finally restarts here: https://gist.github.com/turbo/9d89a765d599eacec53431c79e9b9ff1#file-log-txt-L2279

And then crashes for good.

**Describe the results you expected:**

Dockerd should not panic.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Virtual machine at DigitalOcean
- Ubuntu 18.04
- Docker installed via Docker CE apt source

**Comment by thaJeztah** [comment]
```
Feb 08 21:03:33 node-1 dockerd[15016]: acquirep: p->m=0(0) p->status=3
Feb 08 21:03:33 node-1 dockerd[15016]: fatal error: acquirep: invalid p state
```

```
Feb 08 21:03:33 node-1 dockerd[15016]: runtime stack:
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.throw(0x56416c897e19, 0x19)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/panic.go:616 +0x83
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.acquirep1(0xc420046000)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/proc.go:4066 +0x15d
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.acquirep(0xc420046000)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/proc.go:4038 +0x2d
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.exitsyscallfast_pidle(0xc420c51140)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/proc.go:3096 +0x91
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.exitsyscallfast.func1()
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/proc.go:3039 +0x43
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.systemstack(0x0)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/asm_amd64.s:409 +0x72
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.mstart()
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/proc.go:1175
Feb 08 21:03:33 node-1 dockerd[15016]: goroutine 21 [syscall]:
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.notetsleepg(0x56416e0de3e0, 0x3694b37, 0x0)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/lock_futex.go:227 +0x46 fp=0xc42045bf60 sp=0xc42045bf30 pc=0x56416b2b3b56
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.timerproc(0x56416e0de3c0)
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/time.go:261 +0x2eb fp=0xc42045bfd8 sp=0xc42045bf60 pc=0x56416b2ee63b
Feb 08 21:03:33 node-1 dockerd[15016]: runtime.goexit()
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42045bfe0 sp=0xc42045bfd8 pc=0x56416b2ff1f1
Feb 08 21:03:33 node-1 dockerd[15016]: created by runtime.(*timersBucket).addtimerLocked
Feb 08 21:03:33 node-1 dockerd[15016]:         /usr/local/go/src/runtime/time.go:160 +0x109
Feb 08 21:03:33 node-1 dockerd[15016]: goroutine 1 [chan receive, 96 minutes]:
Feb 08 21:03:33 node-1 dockerd[15016]: main.(*DaemonCli).start(0xc4207275f0, 0xc42019ba40, 0x0, 0x0)
Feb 08 21:03:33 node-1 dockerd[15016]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:240 +0xc80
```
Which is coming from this part; https://github.com/docker/engine/blob/v18.09.1/cmd/dockerd/daemon.go#L229-L240


```go
	// The serve API routine never exits unless an error occurs
	// We need to start it as a goroutine and wait on it so
	// daemon doesn't exit
	serveAPIWait := make(chan error)
	go cli.api.Wait(serveAPIWait)

	// after the daemon is done setting up we can notify systemd api
	notifySystem()

	// Daemon is fully initialized and handling API traffic
	// Wait for serve API to complete
	errAPI := <-serveAPIWait
```


I did find some mentions of this error in https://github.com/golang/go/issues/10240, and https://github.com/coreos/bugs/issues/1909 (which is refering to an issue in the Go runtime https://github.com/golang/go/issues/20427)



@cpuguy83 any ideas?

**Comment by cpuguy83** [comment]
Runtime bug or perhaps some corrupted memory (maybe due to improper syncing in dockerd).

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
