### ISSUE TITLE
pkg/progress - panic due to the full of docker pool

### ISSUE THREAD

**Issue by wreulicke** [moby/moby#38766]
**Description**

Docker daemon is stopped due to the full of docker pool

**Steps to reproduce the issue:**

I'm not sure, but i think that docker daemon pulled image and then full of docker pool make panic docker daemon.

**Describe the results you received:**

* Web application in docker container did not respond
* Docker daemon was stopped
* I found log in `var/log/docker`

```
time="2019-02-15T11:33:49.017879072Z" level=info msg="Attempting next endpoint for pull after error: failed to register layer: devmapper: Thin Pool has 2563 free data blocks which is less than minimum required 4449 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"
panic: send on closed channel

goroutine 12920633 [running]:
github.com/docker/docker/pkg/progress.chanOutput.WriteProgress(0xc423451f80, 0xc42017b4a7, 0xc, 0x0, 0x0, 0x5581ea6512ec, 0xa, 0x19ccdb8, 0x19ccdb8, 0x0, ...)
	/builddir/build/BUILD/docker-ce-18.06.1-ce/components/engine/_build/src/github.com/docker/docker/pkg/progress/progress.go:42 +0x68
github.com/docker/docker/pkg/progress.(*Reader).updateProgress(0xc422303440, 0xc421b1a001)
	/builddir/build/BUILD/docker-ce-18.06.1-ce/components/engine/_build/src/github.com/docker/docker/pkg/progress/progressreader.go:64 +0xec
github.com/docker/docker/pkg/progress.(*Reader).Read(0xc422303440, 0xc421b1a000, 0x8000, 0x8000, 0x8000, 0x8000, 0x0)
	/builddir/build/BUILD/docker-ce-18.06.1-ce/components/engine/_build/src/github.com/docker/docker/pkg/progress/progressreader.go:45 +0xda
bufio.(*Reader).fill(0xc4223034a0)
	/usr/lib/golang/src/bufio/bufio.go:100 +0x120
bufio.(*Reader).WriteTo(0xc4223034a0, 0x5581eb2707e0, 0xc420176bc8, 0x7f5d9e11f808, 0xc4223034a0, 0x8001)
	/usr/lib/golang/src/bufio/bufio.go:494 +0x10f
io.copyBuffer(0x5581eb2707e0, 0xc420176bc8, 0x5581eb26d160, 0xc4223034a0, 0x0, 0x0, 0x0, 0xc422334000, 0x8000, 0x8000)
	/usr/lib/golang/src/io/io.go:382 +0x36b
io.Copy(0x5581eb2707e0, 0xc420176bc8, 0x5581eb26d160, 0xc4223034a0, 0xc420309920, 0x7f5d9e07eae0, 0xc421b54e80)
	/usr/lib/golang/src/io/io.go:362 +0x5c
os/exec.(*Cmd).stdin.func1(0x0, 0x5581e91384e1)
	/usr/lib/golang/src/os/exec/exec.go:230 +0x57
os/exec.(*Cmd).Start.func1(0xc421d422c0, 0xc421a02020)
	/usr/lib/golang/src/os/exec/exec.go:396 +0x29
created by os/exec.(*Cmd).Start
	/usr/lib/golang/src/os/exec/exec.go:395 +0x5e1
```

**Describe the results you expected:**

I expected docker daemon do not panic due to full of docker pool

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
(This output is after docker daemon restarted)

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Fri Oct 26 23:38:19 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Fri Oct 26 23:39:46 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**
(This output is after docker daemon restarted)

```
$ docker info
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 22.34GB
 Data Space Total: 23.33GB
 Data Space Available: 992MB
 Metadata Space Used: 5.083MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 20.08MB
 Thin Pool Minimum Free Space: 2.333GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.88-72.73.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.448GiB
Name: ip-10-222-85-172
ID: X56B:T7LR:WZR4:N2Q2:UVFF:7ZAJ:DBEA:OJOP:BNRY:FCIA:QAWZ:26ZH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* on AWS with ECS Optimized Instances
  * region: us-west-2
  * AMI: ami-0b2cc421c0d3015b4 (ECS Optimized Instances)
  * OS: Amazon Linux 

```
$ cat /etc/system-release
Amazon Linux AMI release 2018.03

$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-0b2cc421c0d3015b4

$ curl http://169.254.169.254/latest/meta-data/instance-type
c5.xlarge

$ sudo lvs
  LV          VG     Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool docker twi-a-t--- 21.73g             95.75  20.20
$ sudo vgs
  VG     #PV #LV #SN Attr   VSize  VFree
  docker   1   1   0 wz--n- 22.00g 228.00m
$ sudo lsblk
NAME                          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1                       259:2    0    8G  0 disk
├─nvme0n1p1                   259:3    0    8G  0 part /
└─nvme0n1p128                 259:4    0    1M  0 part
nvme1n1                       259:0    0   22G  0 disk
└─nvme1n1p1                   259:1    0   22G  0 part
  ├─docker-docker--pool_tdata 253:1    0 21.7G  0 lvm
  │ └─docker-docker--pool     253:2    0 21.7G  0 lvm
  └─docker-docker--pool_tmeta 253:0    0   24M  0 lvm
    └─docker-docker--pool     253:2    0 21.7G  0 lvm
$ sudo lvdisplay
  --- Logical volume ---
  LV Name                docker-pool
  VG Name                docker
  LV UUID                hUoSBD-HG1M-DCmD-Wvea-Ng9X-AoAy-ZNdTDf
  LV Write Access        read/write
  LV Creation host, time ip-10-222-85-172, 2019-01-23 03:14:28 +0000
  LV Pool metadata       docker-pool_tmeta
  LV Pool data           docker-pool_tdata
  LV Status              available
  # open                 0
  LV Size                21.73 GiB
  Allocated pool data    95.75%
  Allocated metadata     20.20%
  Current LE             5562
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:2

$ sudo pvdisplay
  --- Physical volume ---
  PV Name               /dev/nvme1n1p1
  VG Name               docker
  PV Size               22.00 GiB / not usable 3.00 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              5631
  Free PE               57
  Allocated PE          5574
  PV UUID               pcVGu5-tLik-52Vy-rHOk-4sj0-Pex9-jJEO5J

$ sudo vgdisplay
  --- Volume group ---
  VG Name               docker
  System ID
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  5
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                1
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               22.00 GiB
  PE Size               4.00 MiB
  Total PE              5631
  Alloc PE / Size       5574 / 21.77 GiB
  Free  PE / Size       57 / 228.00 MiB
  VG UUID               coeqia-Rd2o-elqE-dTfN-g1LM-CGn2-N1yJLG
```

**Comment by wreulicke** [comment]
In my condition, i think this case occurred if disk is full.

there are any workaround?

**Comment by cpuguy83** [comment]
No, this is a long standing issue and requires rewriting a lot.

**Comment by kolyshkin** [comment]
Without looking in too deep; I think it was previously reported in https://github.com/moby/moby/pull/37780 and (probably?) fixed (well, worked around) in https://github.com/moby/moby/pull/37780

The problem is the fix was not backported to the version @wreulicke used (18.06-ce) since it was no longer supported by the time the fix was made. So, I suggest to switch to 18.09.

Perhaps we can close this one?

**Comment by wreulicke** [comment]
@kolyshkin Oh! Thanks.  

I will update. so I close this issue.
I will create new issue If reproduced.
