### ISSUE TITLE
Enabling docker buildkit has broken CI build

### ISSUE THREAD

**Issue by shavo007** [moby/moby#39106]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

When i enable docker buildkit in my CI build, i start to get permission errors

**Steps to reproduce the issue:**
1. enable docker buildkit
2. run CI build on buildkite
3. get permission errors writing to files

The docker cache plugin builds my image with my node modules cached. 
This pipeline used to work but now, i get permission errors after i enable buildkit. That was the only change i made. 

**Describe the results you received:**
```
yarn run v1.15.2
--
  | warning Skipping preferred cache folder "/usr/local/share/.cache/yarn" because it is not writable.
  | warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-0".
  | $   eslint --fix src && rimraf reports pacts logs && cross-env NODE_ENV=test nyc mocha
  | /workdir/node_modules/mkdirp/index.js:90
  | throw err0;
  | ^
  |  
  | Error: EACCES: permission denied, mkdir '/workdir/node_modules/.cache'
  | at Object.mkdirSync (fs.js:773:3)
  | at sync (/workdir/node_modules/mkdirp/index.js:71:13)
  | at sync (/workdir/node_modules/mkdirp/index.js:77:24)
  | at sync (/workdir/node_modules/mkdirp/index.js:77:24)
  | at save (/workdir/node_modules/@babel/register/lib/cache.js:50:20)
  | at processTicksAndRejections (internal/process/task_queues.js:79:9)
  | at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
  | at internal/main/run_main_module.js:21:11
```

**Describe the results you expected:**
It should run the script successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
18.09.2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Its runnng on a buildkite agent

More details here https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/issues/13

**Comment by thaJeztah** [comment]
Do you have the corresponding  `package.json`,  `yarn.lock`, and `.npmrc` files as well (to reproduce the issue in https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/issues/13 ?).

**Comment by kevin-david** [comment]
Sorry to revive an old issue, but I was able to reproduce something similar. Let me know if I should open a new issue. This was also reported  [here](https://stackoverflow.com/questions/64766003/docker-using-ssh-in-builds-with-buildkit) by an SO user and I was able to reproduce it, so figured it was worth reporting as a bug.

With `DOCKER_BUILDKIT=1`:

```
user@container-host in ContainerBuild/ on kevin/docker_build 
› DOCKER_BUILDKIT=1 docker build --progress=plain --secret id=prod-db-password,src=prod-db-password.txt -t localhost:3200/user-build:registry .                                                                         [21:03:44]
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 3.46kB done
#2 DONE 0.1s

#3 resolve image config for docker.io/docker/dockerfile:1.0-experimental
#3 DONE 0.3s

#4 docker-image://docker.io/docker/dockerfile:1.0-experimental@sha256:cbd64...
#4 CACHED

#5 [internal] load .dockerignore
#5 DONE 0.0s

#6 [internal] load build definition from Dockerfile
#6 transferring dockerfile: 3.46kB done
#6 DONE 0.0s

#7 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0
#7 DONE 0.0s

#9 [1/8] FROM mcr.microsoft.com/dotnet/sdk:5.0
#9 DONE 0.0s

#10 [2/8] RUN id
#10 CACHED

#8 [internal] helper image for file operations
#8 CACHED

#16 [internal] load build context
#16 transferring context: 152B done
#16 DONE 0.0s

#11 [3/8] RUN id     && whoami     && ls -laR /var/lib/apt/lists     && touc...
#11 0.340 uid=0(root) gid=0(root) groups=0(root)
#11 0.342 root
#11 0.346 /var/lib/apt/lists:
#11 0.346 total 8
#11 0.346 drwxr-xr-x 2 root root 4096 Dec  9 23:22 .
#11 0.346 drwxr-xr-x 1 root root 4096 Dec 11 12:09 ..
#11 0.352 /var/lib/apt/lists:
#11 0.352 total 12
#11 0.352 drwxrwxrwx 1 root root 4096 Dec 29 21:03 .
#11 0.352 drwxr-xr-x 1 root root 4096 Dec 11 12:09 ..
#11 0.352 -rwxrwxrwx 1 root root    0 Dec 29 21:03 lock
#11 0.369 Reading package lists...
#11 0.388 E: Could not get lock /var/lib/apt/lists/lock - open (13: Permission denied)
#11 0.388 E: Unable to lock directory /var/lib/apt/lists/
#11 ERROR: executor failed running [/bin/sh -c id     && whoami     && ls -laR /var/lib/apt/lists     && touch /var/lib/apt/lists/lock     && chmod -R 777 /var/lib/apt/lists     && ls -laR /var/lib/apt/lists     && apt-get update     && apt-get install -y --no-install-recommends     ca-certificates     curl     jq     git     iputils-ping     libcurl4     libicu-dev     libunwind8     netcat     libssl1.0     gnupg     unzip     libgdiplus     procps     nodejs     npm     && npm install -g npm]: runc did not terminate sucessfully
------
 > [3/8] RUN id     && whoami     && ls -laR /var/lib/apt/lists     && touch /var/lib/apt/lists/lock     && chmod -R 777 /var/lib/apt/lists     && ls -laR /var/lib/apt/lists     && apt-get update     && apt-get install -y --no-install-recommends     ca-certificates     curl     jq     git     iputils-ping     libcurl4     libicu-dev     libunwind8     netcat     libssl1.0     gnupg     unzip     libgdiplus     procps     nodejs     npm     && npm install -g npm:
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c id     && whoami     && ls -laR /var/lib/apt/lists     && touch /var/lib/apt/lists/lock     && chmod -R 777 /var/lib/apt/lists     && ls -laR /var/lib/apt/lists     && apt-get update     && apt-get install -y --no-install-recommends     ca-certificates     curl     jq     git     iputils-ping     libcurl4     libicu-dev     libunwind8     netcat     libssl1.0     gnupg     unzip     libgdiplus     procps     nodejs     npm     && npm install -g npm]: runc did not terminate sucessfully
FAIL: 1
```

Without `DOCKER_BUILDKIT`:

```
user@container-host in ContainerBuild/ on kevin/docker_build 
› docker build --progress=plain --secret id=prod-db-password,src=prod-db-password.txt -t localhost:3200/user-build:registry .                                                                                           [21:03:26]
Sending build context to Docker daemon  33.79kB
Step 1/13 : FROM mcr.microsoft.com/dotnet/sdk:5.0
 ---> b8769fe1925c
Step 2/13 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Running in c51b12dda817
Removing intermediate container c51b12dda817
 ---> 37747b9385b1
Step 3/13 : RUN id
 ---> Running in 8161b3970745
uid=0(root) gid=0(root) groups=0(root)
Removing intermediate container 8161b3970745
 ---> 62269001bdc2
Step 4/13 : RUN id     && whoami     && ls -laR /var/lib/apt/lists     && touch /var/lib/apt/lists/lock     && chmod -R 777 /var/lib/apt/lists     && ls -laR /var/lib/apt/lists     && apt-get update     && apt-get install -y --no-install-recommends     ca-certificates     curl     jq     git     iputils-ping     libcurl4     libicu-dev     libunwind8     netcat     libssl1.0     gnupg     unzip     libgdiplus     procps     nodejs     npm     && npm install -g npm
 ---> Running in 5098e764b256
uid=0(root) gid=0(root) groups=0(root)
root
/var/lib/apt/lists:
total 8
drwxr-xr-x 2 root root 4096 Dec  9 23:22 .
drwxr-xr-x 1 root root 4096 Dec 11 12:09 ..
/var/lib/apt/lists:
total 12
drwxrwxrwx 1 root root 4096 Dec 29 21:03 .
drwxr-xr-x 1 root root 4096 Dec 11 12:09 ..
-rwxrwxrwx 1 root root    0 Dec 29 21:03 lock
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [258 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7860 B]
^C
```

Here's my OS/docker info:
```
user@container-host in ContainerBuild/ on kevin/docker_build 
› uname -a                                                                                                                                                                                                             [21:03:50]
Linux container-host 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 
user@container-host in ContainerBuild/ on kevin/docker_build 
› lsb_release -a                                                                                                                                                                                                       [21:04:04]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
 
user@container-host in ContainerBuild/ on kevin/docker_build 
› docker --version                                                                                                                                                                                                     [21:04:17]
Docker version 19.03.11, build dd360c7
```

**Comment by kevin-david** [comment]
Additional information: I managed to try this out with `Docker version 20.10.1, build 831ebea` and the issue does not reproduce. Not sure if 19.03 is still supported or not with `DOCKER_BUILDKIT`

**Comment by kevin-david** [comment]
One more data point... with 20.10.1, the issue persists but _only_ if `docker build` is run non-interactively - for example, as a part of a build system.

**Comment by thaJeztah** [comment]
> One more data point... with 20.10.1, the issue persists but only if docker build is run non-interactively for me - for example, as a part of a build system.

🤔 Interactively or non-interactively _shouldn't_ make a difference (assuming the example build you provided above, where no files are copied (`COPY`) from the host), because the build itself is done on the daemon side.

Is the build system otherwise identical as the "interactive" situation? Same docker version, Linux distro, and configuration? Would it be possible to get `docker version` and `docker info` output for both systems? (Wondering if it's related to (e.g.) storage driver, backing filesystem, kernel version, or AppArmor or SELinux).

I tried reproducing the "interactive" situation, "reverse engineering" your example Dockerfile from the output you provided with Docker 20.10;

```bash
mkdir repro-39106 && cd repro-39106

DOCKER_BUILDKIT=1 docker build --progress=plain -<<'EOF'
FROM mcr.microsoft.com/dotnet/sdk:5.0
RUN id \
 && whoami \
 && ls -laR /var/lib/apt/lists \
 && touch /var/lib/apt/lists/lock \
 && chmod -R 777 /var/lib/apt/lists \
 && ls -laR /var/lib/apt/lists \
 && apt-get update \
 && apt-get install -y --no-install-recommends\
    ca-certificates \
    curl \
    jq \
    git \
    iputils-ping \
    libcurl4 \
    libicu-dev \
    libunwind8 \
    netcat \
    libssl1.0 \
    gnupg \
    unzip \
    libgdiplus \
    procps \
    nodejs \
    npm \
 && npm install -g npm
EOF
```

**Comment by kevin-david** [comment]
I agree I found it extremely strange :)

> Is the build system otherwise identical as the "interactive" situation? Same docker version, Linux distro, and configuration?

Yes - exact same machine.

Here's the output common between interactive and non-interactive `docker version && docker info`:
```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:24:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)
```

Here is additional output from the interactive command:
```
Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: 
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu Core 16
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 27.76GiB
 Name: container-host
 ID: EPT2:TRQ4:3BVY:UIS4:L4YR:GGJ4:QS4Y:EKPE:R74B:TTTF:LQJL:6IG5
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
From this output;

```
Docker Root Dir: /var/snap/docker/common/var-lib-docker
```

It looks like docker was installed as a snap package; those are not the official docker builds, and I know there's been various issues with those packages, causing things to break (often in unexpected ways); are you seeing the same problem when installing the official docker packages from download.docker.com? (https://docs.docker.com/engine/install/ubuntu/)

**Comment by azhelev** [comment]
I have a somewhat similar issue. When buildkit is enabled a process inside the container can't find a directory that exists in the docker image
Dockerfile:
```
FROM maxmindinc/geoipupdate
WORKDIR /app
ARG GEOIPUPDATE_ACCOUNT_ID
ARG GEOIPUPDATE_LICENSE_KEY
ARG GEOIPUPDATE_EDITION_IDS=GeoIP2-City
RUN /usr/bin/entry.sh
RUN cp -rv /usr/share/GeoIP /app/geoip2
```
Log with buildkit
```
DOCKER_BUILDKIT=1 docker build --progress=plain --build-arg GEOIPUPDATE_ACCOUNT_ID --build-arg GEOIPUPDATE_LICENSE_KEY -t buildkit-test -f Dockerfile.geoip .
#1 [internal] load build definition from Dockerfile.geoip
#1 sha256:2ad20b7218745443c79da59f477cd5f2fbb2153292df0dd9219e6f1633632aaf
#1 transferring dockerfile: 249B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:8d333b1713d47b0b2678d022b073bd3e5978268335c9402c5a8a80789df8cacc
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/maxmindinc/geoipupdate:latest
#3 sha256:a48489e154807052c0ccf26cdae9b17d65ca01fb289715d679fe1cda902ff0a3
#3 DONE 2.3s

#4 [1/4] FROM docker.io/maxmindinc/geoipupdate@sha256:dd8cd60b79f98f7fd9fe5afe69579c83af54fb3b73ce17677338dd8df17550a3
#4 sha256:b1a1d5138135e3af0d888da9de2132e1d2acb109c33232b5dacd3c8de8029814
#4 resolve docker.io/maxmindinc/geoipupdate@sha256:dd8cd60b79f98f7fd9fe5afe69579c83af54fb3b73ce17677338dd8df17550a3 done
#4 sha256:dd8cd60b79f98f7fd9fe5afe69579c83af54fb3b73ce17677338dd8df17550a3 1.08kB / 1.08kB done
#4 sha256:445edd12ba2edfba5b7b3cb24b52dace8e74cb78a5f4371ee04884ade43b399f 946B / 946B done
#4 sha256:8ec32cc727c70b476f87b08a5268658da55ff819f01a80a1b03c3819a421ea09 1.40kB / 1.40kB done
#4 sha256:e7b2808e58eabb8fcd25542cb02fd1d8ac9f95784cf334ac47a8f382561977b6 0B / 2.03MB 0.1s
#4 sha256:0f8ba30f592fd3f2f31629a584abc69c41fdb9fd1391055597cf70d4b88b8759 0B / 840B 0.1s
#4 sha256:e7b2808e58eabb8fcd25542cb02fd1d8ac9f95784cf334ac47a8f382561977b6 2.03MB / 2.03MB 0.3s done
#4 sha256:0f8ba30f592fd3f2f31629a584abc69c41fdb9fd1391055597cf70d4b88b8759 840B / 840B 0.4s done
#4 extracting sha256:e7b2808e58eabb8fcd25542cb02fd1d8ac9f95784cf334ac47a8f382561977b6
#4 extracting sha256:e7b2808e58eabb8fcd25542cb02fd1d8ac9f95784cf334ac47a8f382561977b6 0.1s done
#4 extracting sha256:0f8ba30f592fd3f2f31629a584abc69c41fdb9fd1391055597cf70d4b88b8759 done
#4 DONE 0.6s

#5 [2/4] WORKDIR /app
#5 sha256:1cdd952602e24a3ea0d55a60fe1e9f79e0d080d00e5d1227d2cb17525a440772
#5 DONE 0.0s

#6 [3/4] RUN /usr/bin/entry.sh
#6 sha256:3458c3f0fba850d96c33cb26726a322e3db59ade54ab99ce5f432bdefe7df0be
#6 0.280 # STATE: Creating configuration file at /etc/GeoIP.conf
#6 0.281 # STATE: Running geoipupdate
#6 0.806 error retrieving updates: error creating database writer for GeoIP2-City: database directory is not available: stat /usr/share/GeoIP: no such file or directory
#6 ERROR: executor failed running [/bin/sh -c /usr/bin/entry.sh]: exit code: 1
------
 > [3/4] RUN /usr/bin/entry.sh:
------
executor failed running [/bin/sh -c /usr/bin/entry.sh]: exit code: 1
```

The directory mentioned here, `/usr/share/GeoIP`, does exists in the docker image.
```
$ docker run -it --rm --entrypoint /bin/sh maxmindinc/geoipupdate -c "ls -la /usr/share"
total 32
drwxr-xr-x    1 root     root          4096 May 11 16:33 .
drwxr-xr-x    1 root     root          4096 Apr 14 10:25 ..
drwxr-xr-x    2 root     root          4096 May 11 16:33 GeoIP
drwxr-xr-x    3 root     root          4096 Apr 14 10:25 apk
drwxr-xr-x    2 root     root          4096 Apr 14 10:25 man
drwxr-xr-x    2 root     root          4096 Apr 14 10:25 misc
drwxr-xr-x    2 root     root          4096 Apr 14 10:25 udhcpc

$ docker run -it --rm --entrypoint /bin/sh maxmindinc/geoipupdate -c "ls -la /usr/share/GeoIP"
total 8
drwxr-xr-x    2 root     root          4096 May 11 16:33 .
drwxr-xr-x    1 root     root          4096 May 11 16:33 ..
```

Log WITHOUT buildkit
```
$ docker build --build-arg GEOIPUPDATE_ACCOUNT_ID --build-arg GEOIPUPDATE_LICENSE_KEY -t buildkit-test -f Dockerfile.geoip .
Sending build context to Docker daemon  41.37MB
Step 1/7 : FROM maxmindinc/geoipupdate
latest: Pulling from maxmindinc/geoipupdate
540db60ca938: Already exists 
e7b2808e58ea: Pull complete 
0f8ba30f592f: Pull complete 
Digest: sha256:dd8cd60b79f98f7fd9fe5afe69579c83af54fb3b73ce17677338dd8df17550a3
Status: Downloaded newer image for maxmindinc/geoipupdate:latest
 ---> 8ec32cc727c7
Step 2/7 : WORKDIR /app
 ---> Running in 2d433135d43e
Removing intermediate container 2d433135d43e
 ---> f1e6e905a13a
Step 3/7 : ARG GEOIPUPDATE_ACCOUNT_ID
 ---> Running in ae739a9881b2
Removing intermediate container ae739a9881b2
 ---> 152cf800c291
Step 4/7 : ARG GEOIPUPDATE_LICENSE_KEY
 ---> Running in 19048760b867
Removing intermediate container 19048760b867
 ---> a315691d89c2
Step 5/7 : ARG GEOIPUPDATE_EDITION_IDS=GeoIP2-City
 ---> Running in f06dec7b15c4
Removing intermediate container f06dec7b15c4
 ---> 465973b5a728
Step 6/7 : RUN /usr/bin/entry.sh
 ---> Running in 1a9379a3b86f
# STATE: Creating configuration file at /etc/GeoIP.conf
# STATE: Running geoipupdate
Removing intermediate container 1a9379a3b86f
 ---> e8ea915d8ab6
Step 7/7 : RUN cp -rv /usr/share/GeoIP /app/geoip2
 ---> Running in d47d8ee05877
'/usr/share/GeoIP' -> '/app/geoip2'
Removing intermediate container d47d8ee05877
 ---> 4ddd98bc47c5
Successfully built 4ddd98bc47c5
Successfully tagged buildkit-test:latest
```

The host is a physical machine running Arch Linux, docker is installed from the distribution repositories.
```
$ uname -a
Linux ztop 5.12.2-arch1-1 #1 SMP PREEMPT Fri, 07 May 2021 15:36:06 +0000 x86_64 GNU/Linux

$ docker version 
Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c28948e
 Built:             Mon Apr 12 14:10:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.3
  Git commit:       8728dd246c
  Built:            Mon Apr 12 14:10:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.0
  GitCommit:        8c906ff108ac28da23f69cc7b74f8e7a470d1df0.m
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8c906ff108ac28da23f69cc7b74f8e7a470d1df0.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.12.2-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.13GiB
 Name: ztop
 ID: H2FD:WHBE:7UXO:FZFX:FD3D:XCSI:S2AV:TDSO:TFJR:GLWA:C6OR:DJU6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

I am able to reproduce the issue on Ubuntu 18.04, EC2 instance with latest updates, docker installed from official PPA
```
# uname  -a
Linux rioci11 5.4.0-1048-aws #50~18.04.1-Ubuntu SMP Tue May 4 17:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1048-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.91GiB
 Name: rioci11
 ID: YIJH:7TOF:NYW7:QJPJ:UMG2:PFWS:6C5T:XKRO:UMEV:IVHD:EKN3:STZU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

# docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

# dpkg -l | grep -i docker
ii  docker-ce                        5:20.10.6~3-0~ubuntu-bionic         amd64        Docker: the open-source application container engine
ii  docker-ce-cli                    5:20.10.6~3-0~ubuntu-bionic         amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras        5:20.10.6~3-0~ubuntu-bionic         amd64        Rootless support for Docker.
ii  docker-scan-plugin               0.7.0~ubuntu-bionic                 amd64        Docker scan cli plugin.

```

**Comment by furushchev** [comment]
Any update on this issue? I encountered the same error.

**Comment by thaJeztah** [comment]
@azhelev I see the `maxmindinc/geoipupdate` has a `VOLUME` defined for `/usr/share/GeoIP`:

```bash
docker inspect --format '{{json .Config.Volumes}}' maxmindinc/geoipupdate | jq .
{
  "/usr/share/GeoIP": {}
}
```

I think this may be the cause of the issue. There's a difference in how BuildKit and the "classic builder" handle volumes; the classic builder will use volume definitions during build; each build-step in the Dockerfile would get a fresh volume attached, and changes made to paths that are part of a `VOLUME` would not be persisted between build-steps, and would not end up in the final image. See [Notes about specifying volumes](https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes) in the docs:

> Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

_However_ (if I'm not mistaken), BuildKit does _not_ mount volumes during build, and instead writes to the path as-is; BuildKit considers the `VOLUME` to be "config" / "metadata", which will only be used when starting a container from the image.

What I expect is the case, is that `/usr/share/GeoIP` does not actually _exist_ in the image. For the "classic" builder, this would not be noticed, because it would mount a volume at that location, and (as a side-effect) if the mount-point for the volume does not exist, it is created first; docker would create an empty `/usr/share/GeoIP`, then mount a volume at that location. The same happens when running a container from the image;

```bash
docker run -dit --name=example --entrypoint=/bin/sh maxmindinc/geoipupdate

docker inspect --format '{{json .Mounts}}'  example | jq .
[
  {
    "Type": "volume",
    "Name": "92fadae5793da09d52935aa9ccab7f9b232844ae5411295349d13b139ff937e4",
    "Source": "/var/lib/docker/volumes/92fadae5793da09d52935aa9ccab7f9b232844ae5411295349d13b139ff937e4/_data",
    "Destination": "/usr/share/GeoIP",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```

The entrypoint script (`/usr/bin/entry.sh`) would normally be used at runtime (`docker run`) in which case the problem wouldn't occur.

Looking at the image itself; the `VOLUME` is added in `8ec32cc727c7`, but no directory is created for it, which confirms my reasoning above:

```
docker history maxmindinc/geoipupdate
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
8ec32cc727c7   2 months ago   VOLUME [/usr/share/GeoIP]                       0B        buildkit.dockerfile.v0
<missing>      2 months ago   ENTRYPOINT ["/usr/bin/entry.sh"]                0B        buildkit.dockerfile.v0
<missing>      2 months ago   COPY docker/entry.sh /usr/bin/entry.sh # bui…   1.61kB    buildkit.dockerfile.v0
<missing>      2 months ago   COPY geoipupdate /usr/bin/geoipupdate # buil…   4.99MB    buildkit.dockerfile.v0
<missing>      2 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B
<missing>      2 months ago   /bin/sh -c #(nop) ADD file:8ec69d882e7f29f06…   5.61MB
```

Does it work if you change your Dockerfile to create the directory first?

```dockerfile
FROM maxmindinc/geoipupdate
WORKDIR /app
ARG GEOIPUPDATE_ACCOUNT_ID
ARG GEOIPUPDATE_LICENSE_KEY
ARG GEOIPUPDATE_EDITION_IDS=GeoIP2-City
# create /usr/share/GeoIP if missing, and run the entrypoint script
RUN mkdir -p /usr/share/GeoIP && /usr/bin/entry.sh
RUN cp -rv /usr/share/GeoIP /app/geoip2
```

I should note that:

- with the classic builder, the content of `/usr/share/GeoIP` would not persist
- but with BuildKit (due to it not using volumes _during_ build), both `/usr/share/GeoIP` and `/app/geoip2` will persist in the final image, which would make your image larger. If you only need it once, and will only be building with BuildKit enabled, the `cp -rv /usr/share/GeoIP /app/geoip2` may not be needed (if you can use the default location), or perhaps would have to be changed to _move_ the files instead (but best to do so in the same step as `/usr/bin/entry.sh` otherwise it would still end up in an intermediate layer.

**Comment by thaJeztah** [comment]
> Any update on this issue? I encountered the same error.

@furushchev looking at the discussion above, this ticket has now collected multiple, not directly related issues (they may have "buildkit" in common, but root-cause of the issue may be different).
If you have details about "what" is not working for you (and steps to reproduce), could you open a new ticket instead?

**Comment by azhelev** [comment]
@thaJeztah thanks for the explanation, that makes perfect sense.
It does work if i create the directory first. Also i can use the generated file from the default location so that last RUN command is not needed indeed.

**Comment by thaJeztah** [comment]
Looks like this ticket went stale, and multiple releases (and updates to BuildKit) happened since this issue was originally reported, so it's possible that bugs (if any) that could cause issues here have been resolved since.


If you run into issues on a current version of Docker (23.0 at time of writing), and have exact steps to reproduce, feel free to open a new ticket instead.
