### ISSUE TITLE
docker inspect hang

### ISSUE THREAD

**Issue by Davidrjx** [moby/moby#39344]
**Description**

a kubernetes's node in NotReady status where docker inspect certain container with id but hangs. strace output does not have obvious problem and only futex syscall take long time and more calls. furthermore, please refer to stack dump goroutine lines abstract info from attachment files
[goroutine_lines.log](https://github.com/moby/moby/files/3271415/goroutine_lines.log)

**Steps to reproduce the issue:**
1. docker inspect container_id

**Describe the results you received:**
docker inspection on certain container hangs

**Describe the results you expected:**
docker inspection not hang and quit quickly

**Additional information you deem important (e.g. issue happens only occasionally):**
have happened multiple times but not often

**Output of `docker version`:**

```
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:47:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:46:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d-dirty (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.8GiB
Name: ai-1080ti-47
ID: Z75K:QNVD:W453:ZI3Z:2GA2:R7RQ:QO3E:JYVJ:G3JW:IV5T:6F6S:2FWP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy:8787
HTTPS Proxy: http://proxy:8787
No Proxy: 127.0.0.1,localhost
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
bare metal

**Comment by wenjianhn** [comment]
What is the stat of the process of the container? Is it in uninterruptible sleep?
You could use `ps -elf` to find out.

There is no stack in the attachment. Something with function info like the following is better.
goroutine 124 [semacquire, 94 minutes]:
sync.runtime_notifyListWait(0xc420cff5d0, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0x10f
sync.(*Cond).Wait(0xc420cff5c0)
        /usr/local/go/src/sync/cond.go:56 +0x82
github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc420cff580, 0xc420ae0000, 0x800, 0x4000, 0x4000, 0x4000, 0xc420170fc0)
        /go/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:134 +0x5b
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc420cff600, 0x55799fef49b0, 0x6, 0x7f5f23b71528, 0xc420cff580)
        /go/src/github.com/docker/docker/daemon/logger/copier.go:81 +0x900
created by github.com/docker/docker/daemon/logger.(*Copier).Run
        /go/src/github.com/docker/docker/daemon/logger/copier.go:48 +0x111

**Comment by smedefind** [comment]
We're seeing this too.

**Output of `docker version`**:
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`**:
```
Client:
 Debug Mode: false

Server:
 Containers: 48
  Running: 29
  Paused: 0
  Stopped: 19
 Images: 45
 Server Version: 19.03.1
 Storage Driver: zfs
  Zpool: local
  Zpool Health: ONLINE
  Parent Dataset: local/docker
  Space Used By Parent: 6995587072
  Space Available: 3673971392512
  Parent Quota: no
  Compression: lz4
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-55-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 251.6GiB
 Name: halfling-donor
 ID: ISWK:P2OR:I7TL:J4F6:K2EF:Z7S6:K3LM:EPLP:4K37:MWB2:YBFC:Z2MJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare Metal

`ps -elf` shows some processes in `t` state (stopped by debugger during the tracing)
e.g.
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     49091  0.0  0.0  14020     4 ?        t    Sep08   0:00 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/e7ee79658b2123e688f243d656dd3220eaa3e61754247ba90b9e5c327e334273/log.json --log-format json create --bundle /run/containerd/io.containerd.runtime.v1.linux/moby/e7ee79658b2123e688f243d656dd3220eaa3e61754247ba90b9e5c327e334273 --pid-file /run/containerd/io.containerd.runtime.v1.linux/moby/e7ee79658b2123e688f243d656dd3220eaa3e61754247ba90b9e5c327e334273/init.pid e7ee79658b2123e688f243d656dd3220eaa3e61754247ba90b9e5c327e334273
```

We see a number of the following in the stack trace.
```
goroutine 179 [semacquire, 6472 minutes]:
sync.runtime_SemacquireMutex(0xc0023e3254, 0xc000e1bf00)
        /usr/local/go/src/runtime/sema.go:71 +0x3f
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:50
github.com/docker/docker/daemon/exec.(*Store).List(0xc0023e3240, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/exec/exec.go:140 +0x1cc
github.com/docker/docker/daemon.(*Daemon).containerExecIds(0xc0008f01e0, 0xc001fd3f50)
        /go/src/github.com/docker/docker/daemon/exec.go:331 +0x95
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc0008f01e0)
        /go/src/github.com/docker/docker/daemon/exec.go:308 +0x179
created by github.com/docker/docker/daemon.NewDaemon
        /go/src/github.com/docker/docker/daemon/daemon.go:1042 +0x298a
```

I've attached a stack trace pulled via `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2`.
[stack.gz](https://github.com/moby/moby/files/3591162/stack.gz)

**Comment by cpuguy83** [comment]
containerd looks hung in this case, here is the offending goroutine:

```
goroutine 2781028 [select, 6475 minutes]:
github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc000f3e100, 0x8, 0xc0001b0080)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/transport.go:267 +0xce
github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/transport.go:278
github.com/docker/docker/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc0001b0080, 0x55eb5b32e120, 0xc0010d0200, 0x0, 0xc001d0a560, 0x0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:856 +0x70e
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0001b0080, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:721 +0x48
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc002180900, 0xc001d0a568, 0xc001d0a558, 0xc0006dc140, 0x0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:577 +0x7e
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc002180900, 0x55eb5b32e120, 0xc0010d0200, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:720 +0x102
github.com/docker/docker/vendor/google.golang.org/grpc.invoke(0x55eb5b4e2060, 0xc002fc62d0, 0x55eb5a42e55f, 0x2a, 0x55eb5b331840, 0xc001856cf0, 0x55eb5b32e120, 0xc0010d0200, 0xc0009a0000, 0xc000932c00, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:73 +0x143
github.com/docker/docker/vendor/github.com/containerd/containerd.namespaceInterceptor.unary(0x55eb5a3d4f49, 0x4, 0x55eb5b4e1fe0, 0xc000052048, 0x55eb5a42e55f, 0x2a, 0x55eb5b331840, 0xc001856cf0, 0x55eb5b32e120, 0xc0010d0200, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:35 +0xf4
github.com/docker/docker/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc0009a0000, 0x55eb5b4e1fe0, 0xc000052048, 0x55eb5a42e55f, 0x2a, 0x55eb5b331840, 0xc001856cf0, 0x55eb5b32e120, 0xc0010d0200, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:35 +0x10c
github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1.(*tasksClient).Create(0xc000f1e098, 0x55eb5b4e1fe0, 0xc000052048, 0xc001856cf0, 0x0, 0x0, 0x0, 0x0, 0xc001514040, 0x1e)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:1297 +0xd4
github.com/docker/docker/vendor/github.com/containerd/containerd.(*container).NewTask(0xc00265df80, 0x55eb5b4e1fe0, 0xc000052048, 0xc0006650e0, 0xc000d161f8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/container.go:264 +0x626
github.com/docker/docker/libcontainerd/remote.(*client).Start(0xc000ed0480, 0x55eb5b4e1fe0, 0xc000052048, 0xc001918040, 0x40, 0x0, 0x0, 0xc00271dc01, 0xc00208d610, 0x0, ...)
	/go/src/github.com/docker/docker/libcontainerd/remote/client.go:192 +0x445
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc0008f01e0, 0xc001b6ad80, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:199 +0x5f8
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc0008f01e0, 0xc001f24017, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000d06a80, 0x55eb58bb3394)
	/go/src/github.com/docker/docker/daemon/start.go:95 +0x1c0
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc000ddb9c0, 0x55eb5b4e2060, 0xc002df2270, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0300, 0xc002df21b0, 0xc000d06a01, 0xc002b64160)
	/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:203 +0x26c
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x55eb5b4e2060, 0xc002df2270, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0300, 0xc002df21b0, 0x55eb5b4e2060, 0xc002df2270)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0x17b
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x55eb5b4e2060, 0xc002df2240, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0300, 0xc002df21b0, 0x203000, 0x203000)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x60d
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x55eb5b4e2060, 0xc002df2240, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0300, 0xc002df21b0, 0x55eb5b4e2060, 0xc002df2240)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x82f
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x55eb5b4d1460, 0xc002c32000, 0xc0024c0200)
	/go/src/github.com/docker/docker/api/server/server.go:142 +0x225
net/http.HandlerFunc.ServeHTTP(0xc000e490c0, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0200)
	/usr/local/go/src/net/http/server.go:1995 +0x46
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0013689c0, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0000)
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:212 +0xe5
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc001711c00, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0000)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc0008c16c0, 0x55eb5b4d1460, 0xc002c32000, 0xc0024c0000)
	/usr/local/go/src/net/http/server.go:2774 +0xaa
net/http.(*conn).serve(0xc002c88be0, 0x55eb5b4e1fa0, 0xc002b8dbc0)
	/usr/local/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f6
```

I believe this is fixed in a newer patch of containerd. The update should be available soon... most recent patch is 1.2.9 which was just released. I see the `containerd.io` package is still at 1.2.6.

**Comment by thaJeztah** [comment]
the containerd.io 1.2.10 package is now available; are people still able to reproduce with that version?

**Comment by Davidrjx** [comment]
@cpuguy83 @thaJeztah thanks for your reply, your idea seems consistent. that is, in my case, docker-containerd's bug, isn't that?

**Comment by thaJeztah** [comment]
closing as this one went stale, but feel free to open a new ticket if you're still running into this on a current version of docker and containerd
