### ISSUE TITLE
panic: DockerSwarmSuite.TestSwarmJoinPromoteLocked test timed out after 5m0s

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39515]
New [failure](https://jenkins.dockerproject.org/job/Docker-PRs/54812/console) in PR #39509 I haven't seen before:
```
--- FAIL: Test (3896.19s)
panic: DockerSwarmSuite.TestSwarmJoinPromoteLocked test timed out after 5m0s [recovered]
	panic: DockerSwarmSuite.TestSwarmJoinPromoteLocked test timed out after 5m0s
```

Which does NOT match the symptoms of known flaky test issue #35263

**Comment by tonistiigi** [comment]
From the daemon logs in the bundle, unlock is blocked because the whole swarm runner is down.


```
goroutine 79 [chan receive, 4 minutes]:
github.com/docker/docker/daemon/cluster.(*Cluster).UnlockSwarm(0xc000109200, 0xc0009ae840, 0x34, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/swarm.go:349 +0x385
github.com/docker/docker/api/server/router/swarm.(*swarmRouter).unlockCluster(0xc0009423c0, 0x55fe67b35de0, 0xc0005a3620, 0x55fe67b250e0, 0xc0003e8620, 0xc000593000, 0xc0005a3410, 0xc000078701, 0xc0009c4580)
	/go/src/github.com/docker/docker/api/server/router/swarm/cluster_routes.go:142 +0x248
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x55fe67b35de0, 0xc0005a3620, 0x55fe67b250e0, 0xc0003e8620, 0xc000593000, 0xc0005a3410, 0x55fe67b35de0, 0xc0005a3620)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0x17b
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x55fe67b35de0, 0xc0005a3500, 0x55fe67b250e0, 0xc0003e8620, 0xc000593000, 0xc0005a3410, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x60d
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x55fe67b35de0, 0xc0005a3500, 0x55fe67b250e0, 0xc0003e8620, 0xc000593000, 0xc0005a3410, 0x1, 0x55fe677d7d01)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x82f
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x55fe67b35de0, 0xc0005a3500, 0x55fe67b250e0, 0xc0003e8620, 0xc000593000, 0xc0005a3410, 0x55fe67b35de0, 0xc0005a3500)
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:53 +0x4a4

```


```
goroutine 137 [select, 4 minutes]:
github.com/docker/docker/daemon/cluster.(*nodeRunner).Ready.func1(0xc000782060, 0xc000782000, 0xc0009f7b00, 0xc0000d2d80)
	/go/src/github.com/docker/docker/daemon/cluster/noderunner.go:80 +0xa2
created by github.com/docker/docker/daemon/cluster.(*nodeRunner).Ready
	/go/src/github.com/docker/docker/daemon/cluster/noderunner.go:79 +0xbe
```

This appears to be because the agent is not up.

```
goroutine 125 [chan receive, 4 minutes]:
github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).run.func7(0xc0000a9980, 0xc000969ae0, 0xd, 0x55fe67b35de0, 0xc0007894d0, 0xc0003f40f0, 0xc0000a9920)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:499 +0x4b
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/node.(*Node).run
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/node/node.go:498 +0xb2c
```

and agent is not up because either session is blocked or in a restart loop

```
goroutine 901 [select]:
github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc000ed6500, 0xc00009ad80, 0xc00085f2c0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/transport.go:267 +0xce
github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/transport.go:278
github.com/docker/docker/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc00083af00, 0x55fe679395a0, 0xc0003b47e0, 0x0, 0x55fe650e19f7, 0x55fe67856d20)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:856 +0x70e
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc00083af00, 0xc000e01db8, 0x55fe655e2406)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:721 +0x48
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc00083c120, 0xc000e01e38, 0xc000e01e28, 0x3, 0x55fe67b58700)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:577 +0x7e
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc00083c120, 0x55fe679395a0, 0xc0003b47e0, 0x60, 0x55fe679166e0)
	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:720 +0x102
github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredClientStream).RecvMsg(0xc0007f1be0, 0x55fe679395a0, 0xc0003b47e0, 0x55fe67b53000, 0xc0009a9ce0)
	/go/src/github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_metrics.go:160 +0x4d
github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*dispatcherSessionClient).Recv(0xc0009a9ce0, 0x55fe67b35d20, 0xc000b16b00, 0xc0007f1ac0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/dispatcher.pb.go:846 +0x64
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*session).start.func1(0xc000590a80, 0x55fe67b35d20, 0xc000b16b00, 0xc000d73180, 0xc0009a9c80, 0xc0009a9c90, 0xc0003b4660, 0xc0000d10e8)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/session.go:155 +0x19d
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*session).start
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/session.go:143 +0x19a
```

```
goroutine 878 [select]:
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*session).start(0xc000590a80, 0x55fe67b35d20, 0xc00085c340, 0xc000d73180, 0xc000db2d01, 0x1)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/session.go:159 +0x246
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*session).run(0xc000590a80, 0x55fe67b35d20, 0xc00085c340, 0x11541f338, 0xc000d73180)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/session.go:99 +0x237
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.newSession
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/session.go:85 +0x41f
```

extracted logs https://gist.github.com/tonistiigi/f08f04c24ab81ffa464c1eaceeb4e728

**Comment by andrewhsu** [comment]
I'm closing this issue because I see #39509 had all PR checks go green after a rebase.
