### ISSUE TITLE
windowsRS1 and windowsRS5-process are failing due to "Unable to delete '\gopath\src\github.com\docker\docker"

### ISSUE THREAD

**Issue by arkodg** [moby/moby#39694]
While raising this PR https://github.com/moby/moby/pull/39671, I've noticed that the `windowsRS5-process` and `windowsRS1` are failing every now and then with the following errors

```
Building remotely on azure-windows-rs1-4 (windows-rs1) in workspace /gopath/src/github.com/docker/docker
13:44:16 No credentials specified
13:44:16 Wiping out workspace first.
13:44:22 jenkins.util.io.CompositeIOException: Unable to delete '\gopath\src\github.com\docker\docker'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
13:44:22 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:86)
13:44:22 	at hudson.Util.deleteContentsRecursive(Util.java:260)
13:44:22 	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1285)
13:44:22 	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1281)
13:44:22 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3041)
13:44:22 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
13:44:22 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
13:44:22 	at hudson.remoting.Request$2.run(Request.java:369)
13:44:22 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
13:44:22 	at java.util.concurrent.FutureTask.run(Unknown Source)
13:44:22 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
13:44:22 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
13:44:22 	at java.lang.Thread.run(Unknown Source)
13:44:22 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to azure-windows-rs1-4
13:44:22 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
13:44:22 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
13:44:22 		at hudson.remoting.Channel.call(Channel.java:957)
13:44:22 		at hudson.FilePath.act(FilePath.java:1068)
13:44:22 		at hudson.FilePath.act(FilePath.java:1057)
13:44:22 		at hudson.FilePath.deleteContents(FilePath.java:1279)
13:44:22 		at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:30)
13:44:22 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1176)
13:44:22 		at hudson.scm.SCM.checkout(SCM.java:504)
13:44:22 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
13:44:22 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
13:44:22 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
13:44:22 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
13:44:22 		at hudson.model.Run.execute(Run.java:1816)
13:44:22 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:44:22 		at hudson.model.ResourceController.execute(ResourceController.java:97)
13:44:22 		at hudson.model.Executor.run(Executor.java:429)
13:44:22 jenkins.util.io.CompositeIOException: Unable to remove directory \gopath\src\github.com\docker\docker\integration-cli with directory contents: []
13:44:22 	at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:246)
13:44:22 	at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:201)
13:44:22 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:212)
13:44:22 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
13:44:22 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:83)
13:44:22 	at hudson.Util.deleteContentsRecursive(Util.java:260)
13:44:22 	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1285)
13:44:22 	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1281)
13:44:22 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3041)
13:44:22 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
13:44:22 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
13:44:22 	at hudson.remoting.Request$2.run(Request.java:369)
13:44:22 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
13:44:22 	at java.util.concurrent.FutureTask.run(Unknown Source)
13:44:22 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
13:44:22 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
13:44:22 	at java.lang.Thread.run(Unknown Source)
13:44:22 java.nio.file.FileSystemException: \gopath\src\github.com\docker\docker\integration-cli: The process cannot access the file because it is being used by another process.
```

**Comment by arkodg** [comment]
`java.nio.file.FileSystemException: \gopath\src\github.com\docker\docker\integration-cli: The process cannot access the file because it is being used by another process.` seems to be a big hint, any idea @ddebroy

**Comment by ddebroy** [comment]
Have not seen this specific exception before.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
