### ISSUE TITLE
dockerd and docker do not run well on NixOS

### ISSUE THREAD

**Issue by ORESoftware** [moby/moby#39712]
I ran this in a terminal on NixOS:

```bash
sudo dockerd
```

and then tried to run this in another terminal:

```bash
sudo docker ps
```

and I got

```console
INFO[2019-08-09T17:31:25.236948800Z] libcontainerd: containerd is still running    pid=19738
INFO[2019-08-09T17:31:25.237059962Z] parsed scheme: "unix"                         module=grpc
INFO[2019-08-09T17:31:25.237070312Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-08-09T17:31:25.237130872Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-08-09T17:31:25.237158523Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-08-09T17:31:25.237232833Z] pickfirstBalancer: HandleSubConnStateChange: 0xc0007a74f0, CONNECTING  module=grpc
ERRO[2019-08-09T17:31:35.237214701Z] failed connecting to containerd               error="failed to dial \"/var/run/docker/containerd/containerd.sock\": context deadline exceeded" module=libcontainerd
INFO[2019-08-09T17:31:35.337438989Z] killing and restarting containerd             module=libcontainerd pid=19738
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x555f4b862d20]

goroutine 54 [running]:
github.com/docker/docker/vendor/github.com/containerd/containerd.(*Client).Close(0x0, 0x0, 0x0)
	/build/source/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/containerd/containerd/client.go:536 +0x30
github.com/docker/docker/libcontainerd/supervisor.(*remote).monitorDaemon(0xc0007ed040, 0x555f4c9313c0, 0xc000799e40)
	/build/source/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:321 +0x24f
created by github.com/docker/docker/libcontainerd/supervisor.Start
	/build/source/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:90 +0x3b5
```

not sure what that error is about. the docker -v output is:

> Docker version 18.09.2, build 62479626f213818ba5b4565105a05277308587d5

**Comment by thaJeztah** [comment]
the nixos packages are not maintained  here, but by the NixOS community; https://github.com/NixOS/nixpkgs/blob/6dfd13ab34ded1d723c8482accdff15fdd1fb19a/pkgs/applications/virtualization/docker/default.nix


While it could be there's an issue in the code here, it's also possible that there's an issue with packaging; I do notice you're running an older version of docker (latest patch release of Docker 18.09 is 18.09.8, and docker 19.03.1 was released recently)

Could you report this issue in the NixOS issue tracker? https://github.com/NixOS/nixpkgs/issues

That way the package maintainers there can have a look first


/cc @vdemeester (who I know has helped maintain that package in the past)

**Comment by angristan** [comment]
@ORESoftware Why do you launch dockerd with `sudo dockerd`? 

You should install docker with

```nix
virtualisation.docker.enable = true;
```

Which will install all that's needed including a systemd service which supports socket activation.

**Comment by ORESoftware** [comment]
so `nixos-rebuild switch` after that and all will be well?

**Comment by angristan** [comment]
Try to start the daemon with `systemctl start docker` or add:

```nix
virtualisation.docker.enableOnBoot = true;
```

**Comment by ORESoftware** [comment]
ok I tried that, I got:

```
# systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

and then:

```
# journalctl -xe
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Service RestartSec=100ms expired, scheduling restart.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Start request repeated too quickly.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 19 17:57:56 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
Aug 19 17:58:01 ip-172-31-0-27.us-west-2.compute.internal /nix/store/hcg6pfc6hv8fhq3xaixap0llv5x0dfik-cron-4.1/bin/cron[31422]: (*system*) RELOAD (/etc/crontab)
lines 1493-1524/1524 (END)
```

I love when things just work

**Comment by angristan** [comment]
`journalctl -xeu docker`? Something is not quite right

**Comment by thaJeztah** [comment]
`journalctl -xe` is usually not very useful (doesn't give details why a unit failed); may want to use `journalctl -xu <service>`

**Comment by thaJeztah** [comment]
ah, sorry; @angristan just posted the same 😂

**Comment by ORESoftware** [comment]
I mean there is more output now idk:

```
-- Logs begin at Tue 2019-05-07 18:27:15 UTC, end at Mon 2019-08-19 18:26:20 UTC. --
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal dockerd[31419]: Error starting daemon: pid file found, ensure docker >
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Main process exited, code=exited, status=>
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Service RestartSec=100ms expired, schedul>
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Scheduled restart job, restart counter is>
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal dockerd[31435]: Error starting daemon: pid file found, ensure docker >
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Main process exited, code=exited, status=>
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Service RestartSec=100ms expired, schedul>
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Scheduled restart job, restart counter is>
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal dockerd[31448]: Error starting daemon: pid file found, ensure docker >
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Main process exited, code=exited, status=>
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 06 19:05:58 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 06 19:05:59 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Service RestartSec=100ms expired, schedul>
Aug 06 19:05:59 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Scheduled restart job, restart counter is>
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Aug 06 19:05:59 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Aug 06 19:05:59 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Start request repeated too quickly.
Aug 06 19:05:59 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 06 19:05:59 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980216007Z" level=info msg="l>
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980386639Z" level=info msg="p>
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980399639Z" level=info msg="s>
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980434529Z" level=info msg="c>
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980452179Z" level=info msg="C>
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980498130Z" level=info msg="p>
Aug 16 20:01:23 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:23.980553578Z" level=error msg=">
Aug 16 20:01:24 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:24.080790905Z" level=info msg="k>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: panic: runtime error: invalid memory address or nil poi>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: [signal SIGSEGV: segmentation violation code=0x1 addr=0>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: goroutine 43 [running]:
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: github.com/docker/docker/vendor/github.com/containerd/c>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]:         /build/source/components/engine/.gopath/src/git>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: github.com/docker/docker/libcontainerd/supervisor.(*rem>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]:         /build/source/components/engine/.gopath/src/git>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: created by github.com/docker/docker/libcontainerd/super>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]:         /build/source/components/engine/.gopath/src/git>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Main process exited, code=exited, status=>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Service RestartSec=100ms expired, schedul>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Scheduled restart job, restart counter is>
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[668]: time="2019-08-16T20:01:25.575441567Z" level=info msg="l>
Aug 16 20:01:26 ip-172-31-0-27.us-west-2.compute.internal dockerd[668]: time="2019-08-16T20:01:26.692690683Z" level=info msg="p>
Aug 16 20:01:27 ip-172-31-0-27.us-west-2.compute.internal dockerd[668]: Error starting daemon: error while opening volume store>
Aug 16 20:01:27 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Main process exited, code=exited, status=>
Aug 16 20:01:27 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 16 20:01:27 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Service RestartSec=100ms expired, schedul>
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Scheduled restart job, restart counter is>
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal dockerd[712]: time="2019-08-16T20:01:28.078880987Z" level=info msg="l>
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal dockerd[712]: time="2019-08-16T20:01:28.104737243Z" level=info msg="l>
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal dockerd[712]: time="2019-08-16T20:01:28.106294997Z" level=info msg="l>
Aug 16 20:01:28 ip-172-31-0-27.us-west-2.compute.internal dockerd[712]: time="2019-08-16T20:01:28.126773906Z" level=info msg="p>
```

**Comment by angristan** [comment]
Yes, docker is having a segmentation fault:

```
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980216007Z" level=info msg="l>
Aug 16 20:01:13 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:13.980386639Z" level=info msg="p>
Aug 16 20:01:23 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:23.980553578Z" level=error msg=">
Aug 16 20:01:24 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: time="2019-08-16T20:01:24.080790905Z" level=info msg="k>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: panic: runtime error: invalid memory address or nil poi>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: [signal SIGSEGV: segmentation violation code=0x1 addr=0>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: goroutine 43 [running]:
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: github.com/docker/docker/vendor/github.com/containerd/c>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]:         /build/source/components/engine/.gopath/src/git>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: github.com/docker/docker/libcontainerd/supervisor.(*rem>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]:         /build/source/components/engine/.gopath/src/git>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]: created by github.com/docker/docker/libcontainerd/super>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal dockerd[649]:         /build/source/components/engine/.gopath/src/git>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Main process exited, code=exited, status=>
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 16 20:01:25 ip-172-31-0-27.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by angristan** [comment]
On which channel are you?

```sh
sudo nix-channel --list
```

If you're on `19.03`, you don't have the latest version:

https://github.com/NixOS/nixpkgs/blob/5e5a51f7868df98d6db4331bb6cf149040ce474a/pkgs/applications/virtualization/docker/default.nix#L201-L211

Try to run

```
sudo nix-rebuild switch --upgrade
```

**Comment by ORESoftware** [comment]
@angristan  I have:

nixos https://nixos.org/channels/nixos-19.03

so I tried:

```
[root@ip-172-31-0-27:/interos/deploy/tmp/F0_jNPVQS]# sudo nix-rebuild switch --upgrade
sudo: nix-rebuild: command not found

[root@ip-172-31-0-27:/interos/deploy/tmp/F0_jNPVQS]# nix-rebuild switch --upgrade
nix-rebuild: command not found
```

jesus fucking christ lol

**Comment by ORESoftware** [comment]
I think you mean:

```
nixos-rebuild switch --upgrade
```

**Comment by angristan** [comment]
Here is my config: https://github.com/angristan/nixos-config/blob/master/configuration.nix#L338

**Comment by AkihiroSuda** [comment]
The issue seems closable now?

Other nix-specific issues should be reported to https://github.com/NixOS/nixpkgs/issues

**Comment by angristan** [comment]
No news from OP, so yes, sure.
