### ISSUE TITLE
Logging driver for GELF sends message with empty mandatory field "short_message"

### ISSUE THREAD

**Issue by Jonas-Heinrich** [moby/moby#40232]
**Description**

Docker, or rather the logging driver for *GELF*, sends its output without checking
if messages have any content in the mandatory field `short_message`. According to the [*GELF* payload specification](http://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification) this is explicitly forbidden and may result in exceptions.

In the following bug report I am using Graylog as an example for the consequences that
result downstream.

**Steps to reproduce the issue:**

- Run a local instance of Graylog 3 with docker compose version 3 in a default configuration as described [here](https://docs.graylog.org/en/3.1/pages/installation/docker.html).

Note that this is not core to the issue at hand, but merely serves as a nice demonstration of the consequences:

```version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    networks:
      - graylog
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.1
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge
```

- Run the hello-world docker container with gelf as a log driver:

```bash
docker run \
    --log-driver gelf \
    --log-opt gelf-address=udp://localhost:12201 \
    hello-world
```

**Describe the results you received:**

Docker now takes the output below, formats it into *GELF* and sends it to graylog:

```
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

This includes the empty lines that you see in the message above. With empty messages being forbidden in *GELF*, this may result in processing difficulties for a log handler downstream.

In the case of Graylog, this results in several exceptions (here is just one):

```
graylog_1        | 2019-11-21 11:10:39,416 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=8cd524f1-0c4f-11ea-86f4-0242ac170004, journalOffset=12, codec=gelf, payloadSize=308, timestamp=2019-11-21T11:10:39.295Z, remoteAddress=/172.23.0.1:41406} on input <5dd670a67fa7b70012e2ef6a>.
graylog_1        | 2019-11-21 11:10:39,417 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=8cd524f1-0c4f-11ea-86f4-0242ac170004, journalOffset=12, codec=gelf, payloadSize=308, timestamp=2019-11-21T11:10:39.295Z, remoteAddress=/172.23.0.1:41406}
graylog_1        | java.lang.IllegalArgumentException: GELF message <8cd524f1-0c4f-11ea-86f4-0242ac170004> (received from <172.23.0.1:41406>) has empty mandatory "short_message" field.
graylog_1        | 	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:252) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:86) [graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
graylog_1        | 	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
graylog_1        | 	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
graylog_1        | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Describe the results you expected:**

Normally, I would expect no error in Graylog since it would not have to deal with empty mandatory fields in the first place.

**Additional information you deem important (e.g. issue happens only occasionally):**

This bug affects all projects that use *GELF* as a logging format, including the elastic stack (though it may be handled differently there). It also extends to use in `docker-compose` files:

```
version: '3'
services:
  hello:
    image: hello-world
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://localhost:12201
        tag: "hello"
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-36-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.764GiB
 Name: ubuntu
 ID: VRJA:MIFX:EADV:AZ4W:EPIK:J6YZ:22ZY:VPUJ:QPQH:7ALR:VCCQ:HKBS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Run on a fresh install of Ubuntu 18.04 in VMWare Workstation Pro

**Comment by Jonas-Heinrich** [comment]
I know that this is similar to #37572, however I felt that given the scope of this report and the date that the original issue was opened, a new issue was justified.
