### ISSUE TITLE
All managers in a swarm terminating with segmentation fault every few minutes

### ISSUE THREAD

**Issue by davechallis** [moby/moby#40537]
**Description**

We have a swarm consisting of 3 dedicated managers, and ~10 worker nodes.

The swarm has reached a state where the managers are unable to stay up for more than a few minutes, and keep terminating with segmentation faults.

**Describe the results you received:**

The syslog output from `dockerd` preceding the segfault, and the segfault itself looks like:

```
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993074051Z" level=error msg="IPAM failure while releasing IP address 10.0.5.4/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993085418Z" level=error msg="IPAM failure while releasing IP address 10.0.4.3/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993096857Z" level=error msg="IPAM failure while releasing IP address 10.0.6.3/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993108199Z" level=error msg="IPAM failure while releasing IP address 10.0.14.4/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993119606Z" level=error msg="IPAM failure while releasing IP address 10.0.1.2/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993131049Z" level=error msg="IPAM failure while releasing IP address 10.0.7.16/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993142340Z" level=error msg="IPAM failure while releasing IP address 10.0.2.3/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993176130Z" level=error msg="IPAM failure while releasing IP address 10.0.15.6/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: time="2020-02-18T09:26:39.993287486Z" level=error msg="IPAM failure while releasing IP address 10.0.0.37/24" error="invalid pool id: "
Feb 18 09:26:39 swarm-manager dockerd[13197]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 18 09:26:39 swarm-manager dockerd[13197]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x559389f923bb]
Feb 18 09:26:39 swarm-manager dockerd[13197]: goroutine 281 [running]:
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNode(0xc00212e8c0, 0x55938b20afa0, 0xc0023b9000, 0xc003eac8c0, 0x0, 0xc0019b0120, 0x1, 0x1, 0x1)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:1055 +0x75b
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNodes(0xc00212e8c0, 0x55938b20afa0, 0xc0023b9000, 0x0, 0x0, 0x0)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:489 +0x1dd
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).doNetworkInit(0xc00212e8c0, 0x55938b20afa0, 0xc0023b9000, 0x0, 0x0)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:166 +0x4ab
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).init(0xc00212e8c0, 0x55938b20afa0, 0xc0023b9000, 0xc0023d8440, 0x0, 0x0, 0xc0023a2588, 0x0)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:174 +0x496
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run.func2(0x0, 0x0)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:122 +0xbc
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run(0xc00212e8c0, 0x55938b20afa0, 0xc000b67300, 0x0, 0x0)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:142 +0x391
Feb 18 09:26:39 swarm-manager dockerd[13197]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader.func6(0x55938b20afa0, 0xc000b67300, 0xc00212e8c0)
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1067 +0x5f
Feb 18 09:26:39 swarm-manager dockerd[13197]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader
Feb 18 09:26:39 swarm-manager dockerd[13197]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1066 +0xf8e
```

`systemd` then restarts `dockerd`,  which starts successfully, starts a leader election, elects a leader, then one of the manager nodes will then terminate with the segfault above.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens consistently, on each of the 3 manager nodes.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: pending
  NodeID: lg0j3wiypi1y5h8yqytidmdek
  Error: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
  Is Manager: true
  Node Address: 10.1.4.247
  Manager Addresses:
   10.1.4.247:2377
   10.1.5.196:2377
   10.1.6.89:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1058-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.851GiB
 Name: swarm-manager
 ID: VXAY:TLAM:4SAR:JWLO:YCWO:MKBN:HWQG:GRWV:32JS:E33E:FGAV:SIYT
 Docker Root Dir: /mnt/data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on AWS T2.medium instance type.

**Comment by thaJeztah** [comment]
Did a quick check on changes in those files;

- https://github.com/docker/engine/blob/v19.03.6/vendor/github.com/docker/swarmkit/manager/manager.go
- https://github.com/docker/engine/blob/v19.03.6/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go
- https://github.com/docker/engine/blob/v19.03.6/vendor/github.com/docker/swarmkit/manager/allocator/network.go

Last changes between those looks to be https://github.com/docker/engine/commit/0c38d56a6dae8c9c8379d29083b759005308ebc9, which was already in v19.03.5


Is this a fresh install, or did you update from a previous version? If so, what version of docker were you running before updating to v19.03.6 ?

**Comment by thaJeztah** [comment]
The `invalid pool id` error itself looks to be generated by libnetwork, in either of these locations;

- https://github.com/docker/engine/blob/v19.03.6/vendor/github.com/docker/libnetwork/ipam/allocator.go#L263
- https://github.com/docker/engine/blob/v19.03.6/vendor/github.com/docker/libnetwork/ipam/allocator.go#L455
- https://github.com/docker/engine/blob/v19.03.6/vendor/github.com/docker/libnetwork/ipam/allocator.go#L512

Last change in that file was in Aug 20, 2018, so also doesn't appear to have changed recently

**Comment by thaJeztah** [comment]
@dperny @arkodg any ideas?

**Comment by davechallis** [comment]
@thaJeztah it was recently (perhaps a week ago?) updated from 19.3.2, if that helps.

**Comment by thaJeztah** [comment]
Without looking at details yet; only file of the above ones that was modified in between was `vendor/github.com/docker/swarmkit/manager/manager.go`, which was changed in https://github.com/docker/engine/commit/f7dbee3eeaa1dd218116f85b8f60361acbd5b214 (https://github.com/docker/engine/pull/353) and https://github.com/docker/engine/commit/0c38d56a6dae8c9c8379d29083b759005308ebc9 (https://github.com/docker/engine/pull/374)

**Comment by thaJeztah** [comment]
Potentially relevant change (related to IPAM) in that last change is https://github.com/docker/swarmkit/pull/2890 / https://github.com/docker/swarmkit/pull/2891

**Comment by dperny** [comment]
I'm taking a look at this now. It's been officially added to my List Of Tasks for this week, because I consider it urgent.

**Comment by thaJeztah** [comment]
Thanks @dperny 👍

**Comment by dperny** [comment]
Here's my analysis:

The problem is on this line, in the Allocator's `allocateNode` function:

https://github.com/moby/moby/blob/4ac62b478d539d2539e49d7c710eaea482e47293/vendor/github.com/docker/swarmkit/manager/allocator/network.go#L1055

There are three possible nils here:
1. The `nwIDs` map itself
2. `attach`
3. `Network`

I note that the problem is past line 1041, which returns early if we're only allocating existing addresses (which happens when initializing the manager, as allocation state in libnetwork is only tracked locally, and we need to reinitialize its local state each time we change managers). This means that before this line, we can ignore any code path where `existingAddressesOnly == true`. The stack trace, which points to line 166, confirms this suspicion.

The map will not be the problem, because it is instantiated at the top of the `allocatedNode` function before any branching, and so is non-nil on all code paths.

With that established, I'm going to first trace the `attach` variable. It comes from iterating over `node.Attachments`.

Looking earlier in the method, I can see that we iterate through all of the node attachments, accessing the `Network` field, which means none of these attachments are nil, because if they were, we would segfault here, not later. However, there is a `break` here, so we may be exiting before the problematic attachment comes up. Because `node.Attachments` is a slice, it is ordered, and therefore a nil attachment would have to be at the end of the slice.

https://github.com/moby/moby/blob/4ac62b478d539d2539e49d7c710eaea482e47293/vendor/github.com/docker/swarmkit/manager/allocator/network.go#L1001-L1007

Note, too, that we cannot _add_ a nil attachment. The `lbAttachment` variable is used to capture the attachment matching the desired network from the loop. Later on, we see this:

https://github.com/moby/moby/blob/4ac62b478d539d2539e49d7c710eaea482e47293/vendor/github.com/docker/swarmkit/manager/allocator/network.go#L1015-L1022

This means that any attachment we add is guaranteed to be non-nil, but the `Network` field inside of it is not.

The fields in the attachment, including the `Network`, are populated later, in this block:

https://github.com/moby/moby/blob/4ac62b478d539d2539e49d7c710eaea482e47293/vendor/github.com/docker/swarmkit/manager/allocator/network.go#L1028-L1034

This leaves open the possibility that if a the call to `AllocateAttachment` failed, the `Network` could be nil. However, if `AllocateAttachment` _did_ fail, then we would log an error, and the logs provided do not show this error, so the problem is _not_ with a newly added attachment; it must be with an attachment already present on the node.

----

At this point, I have a few questions for @davechallis:

1. Is the Swarm "old". Has it been running for many years? If so, do you know what version it was initialized on?
2. Is it possible to view the output of `docker node inspect` before the swarm crashes? If so, can you please post it? If not, I have a workaround for viewing it, which involves using `swarm-rafttool` to dump the object store. This includes the full raft database, though, and constitutes an end-run around the usual API, which means I can't guarantee that providing the database this way wouldn't expose some sensitive information.

**Comment by dperny** [comment]
The question of whether the swarm is "old" is important, because a feeling of having seen this before somewhere lead me to this PR on Swarmkit: https://github.com/docker/swarmkit/pull/2764

But I'm not 100% sure that it's related, and if it is, I'm very much not sure how it could have not crashed until now.

**Comment by thaJeztah** [comment]
I recall I also had a refactor PR in that area; https://github.com/docker/swarmkit/pull/2823

**Comment by davechallis** [comment]
@dperny many thanks for investigating, super interesting to read the analysis.

It is indeed an old swarm, it was created around September 2018, with Docker 18.06 (there's a chance it was 18.09, but most logs going back that far have been rolled unfortunately).

Output I managed to grab from one of managers just before a crash is below (currently only 2/3 of the managers are starting, the first manager has gotten into a state where the Docker daemon crashes at startup with the segfault above, after we tried to force that node to become sole manager using `docker swarm init --force-new-cluster --advertise-addr foo:2377`):

```
[
    {
        "ID": "lg0j3wiypi1y5h8yqytidmdek",
        "Version": {
            "Index": 1990506
        },
        "CreatedAt": "2020-01-28T06:17:37.031126361Z",
        "UpdatedAt": "2020-02-19T09:29:58.250471984Z",
        "Spec": {
            "Labels": {},
            "Role": "manager",
            "Availability": "active"
        },
        "Description": {
            "Hostname": "swarm-manager02",
            "Platform": {
                "Architecture": "x86_64",
                "OS": "linux"
            },
            "Resources": {
                "NanoCPUs": 2000000000,
                "MemoryBytes": 4134858752
            },
            "Engine": {
                "EngineVersion": "19.03.6",
                "Plugins": [
                    {
                        "Type": "Log",
                        "Name": "awslogs"
                    },
                    {
                        "Type": "Log",
                        "Name": "fluentd"
                    },
                    {
                        "Type": "Log",
                        "Name": "gcplogs"
                    },
                    {
                        "Type": "Log",
                        "Name": "gelf"
                    },
                    {
                        "Type": "Log",
                        "Name": "journald"
                    },
                    {
                        "Type": "Log",
                        "Name": "json-file"
                    },
                    {
                        "Type": "Log",
                        "Name": "local"
                    },
                    {
                        "Type": "Log",
                        "Name": "logentries"
                    },
                    {
                        "Type": "Log",
                        "Name": "splunk"
                    },
                    {
                        "Type": "Log",
                        "Name": "syslog"
                    },
                    {
                        "Type": "Network",
                        "Name": "bridge"
                    },
                    {
                        "Type": "Network",
                        "Name": "host"
                    },
                    {
                        "Type": "Network",
                        "Name": "ipvlan"
                    },
                    {
                        "Type": "Network",
                        "Name": "macvlan"
                    },
                    {
                        "Type": "Network",
                        "Name": "null"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    },
                    {
                        "Type": "Volume",
                        "Name": "local"
                    }
                ]
            },
            "TLSInfo": {
               ...
            }
        },
        "Status": {
            "State": "unknown",
            "Message": "Node moved to \"unknown\" state due to leadership change in cluster",
            "Addr": "0.0.0.0"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.1.4.247:2377"
        }
    }
]
```

**Comment by dperny** [comment]
The fact that there are no network attachments on this output makes me think that my assessment of a nil attachment is correct. Unfortunately, I'm not sure how to get out of this bad state. I'm also still not 100% sure of the root cause...

**Comment by syphr42** [comment]
I just upgraded a cluster from 18.09 to 19.03.12 and I'm experiencing this same issue. This cluster started on 18.06. None of the managers can stay up for more than a minute or two until they seg fault. Logs look the same to me as above with the same error in `allocateNode`.
