### ISSUE TITLE
docker daemon exited when embedded DNS panic

### ISSUE THREAD

**Issue by tao12345666333** [moby/moby#40715]
**Description**

```
3月 18 22:52:44 localhost dockerd[24752]: time="2020-03-18T22:52:44.260463573+08:00" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/create
3月 18 22:52:44 localhost dockerd[24752]: time="2020-03-18T22:52:44.278716997+08:00" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/start
3月 18 22:52:44 localhost dockerd[24752]: time="2020-03-18T22:52:44.289235741+08:00" level=debug msg="Calling POST /v1.41/containers/3e79eacabe4e29c47545736cbaad76fddffdac1528c714a599c4b8acef1574c1/resize?h=13&w=123"
3月 18 22:52:45 localhost dockerd[24752]: time="2020-03-18T22:52:45.551236099+08:00" level=debug msg="Calling POST /v1.41/exec/a27e75f03020df52e21f31da481d751e727a37d0b873aed7e2e9c9bb0eda6672/resize?h=27&w=123"
3月 18 22:52:58 localhost dockerd[24752]: time="2020-03-18T22:52:58.402891147+08:00" level=debug msg="Calling POST /v1.41/exec/a27e75f03020df52e21f31da481d751e727a37d0b873aed7e2e9c9bb0eda6672/resize?h=6&w=123"
3月 18 22:53:13 localhost dockerd[24752]: time="2020-03-18T22:53:13.278160707+08:00" level=debug msg="Calling HEAD /_ping"
3月 18 22:53:13 localhost dockerd[24752]: time="2020-03-18T22:53:13.278488671+08:00" level=debug msg="Calling GET /v1.41/containers/json"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.723619823+08:00" level=debug msg="Calling HEAD /_ping"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.724235462+08:00" level=debug msg="Calling POST /v1.41/networks/uuu/connect"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.724317811+08:00" level=debug msg="form data: {\"Container\":\"7193d08d480c\",\"EndpointConfig\":{\"Aliases\":[],\"DriverOpts\":{},\"EndpointID\":\"\",\"Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"IPAMConfig\":{},\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"Links\":null,\"MacAddress\":\"\",\"NetworkID\":\"\"}}"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.725158479+08:00" level=debug msg="Assigning addresses for endpoint priceless_poincare's interface on network uuu"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.725177685+08:00" level=debug msg="RequestAddress(LocalDefault/172.19.0.0/16, <nil>, map[])"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.725201718+08:00" level=debug msg="Request address PoolID:172.19.0.0/16 App: ipam/default/data, ID: LocalDefault/172.19.0.0/16, DBIndex: 0x0, Bits: 65536, Unselected: 65532, Sequence: (0xe0000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:3 Serial:false PrefAddress:<nil> "
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.732037880+08:00" level=debug msg="Assigning addresses for endpoint priceless_poincare's interface on network uuu"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.732629981+08:00" level=debug msg="d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12 (2d5de39).addSvcRecords(7193d08d480c, 172.19.0.3, <nil>, true) updateSvcRecord sid:d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.732680112+08:00" level=debug msg="d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12 (2d5de39).addSvcRecords(7193d08d480c, 172.19.0.3, <nil>, false) updateSvcRecord sid:d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.735252480+08:00" level=debug msg="d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12 (2d5de39).addSvcRecords(7193d08d480c, 172.19.0.3, <nil>, true) updateSvcRecord sid:d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.735313819+08:00" level=debug msg="d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12 (2d5de39).addSvcRecords(7193d08d480c, 172.19.0.3, <nil>, false) updateSvcRecord sid:d090be39adc71b334a98f0e1cf938ec9b4b94f49680f2ef91bc7c91caf8c2b12"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.851635766+08:00" level=debug msg="EnableService 7193d08d480c554551037e18ec3b270f95c078dbc798e9495bef3eb88376e3d5 START"
3月 18 22:53:19 localhost dockerd[24752]: time="2020-03-18T22:53:19.851664825+08:00" level=debug msg="EnableService 7193d08d480c554551037e18ec3b270f95c078dbc798e9495bef3eb88376e3d5 DONE"
3月 18 22:53:23 localhost dockerd[24752]: time="2020-03-18T22:53:23.373728605+08:00" level=debug msg="Name To resolve: uuu."
3月 18 22:53:23 localhost dockerd[24752]: time="2020-03-18T22:53:23.375165920+08:00" level=debug msg="[resolver] query uuu. (A) from 172.17.0.2:41125, forwarding to udp:192.168.1.1"
3月 18 22:53:27 localhost dockerd[24752]: panic: runtime error: invalid memory address or nil pointer dereference
3月 18 22:53:27 localhost dockerd[24752]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x11 pc=0x55eebd258e5a]
3月 18 22:53:27 localhost dockerd[24752]: goroutine 1786 [running]:
3月 18 22:53:27 localhost dockerd[24752]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*resolver).ServeDNS(0xc000e4fdc0, 0x55eebefdb200, 0xc0009710e0, 0xc000c514d0)
3月 18 22:53:27 localhost dockerd[24752]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/resolver.go:487 +0x79a
3月 18 22:53:27 localhost dockerd[24752]: github.com/docker/docker/vendor/github.com/miekg/dns.(*Server).serveDNS(0xc00082d500, 0xc000c88400, 0x2c, 0x200, 0xc0009710e0)
3月 18 22:53:27 localhost dockerd[24752]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/miekg/dns/server.go:609 +0x2e2
3月 18 22:53:27 localhost dockerd[24752]: github.com/docker/docker/vendor/github.com/miekg/dns.(*Server).serveUDPPacket(0xc00082d500, 0xc000bd24f0, 0xc000c88400, 0x2c, 0x200, 0xc000c38830, 0xc000a83760)
3月 18 22:53:27 localhost dockerd[24752]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/miekg/dns/server.go:549 +0xb4
3月 18 22:53:27 localhost dockerd[24752]: created by github.com/docker/docker/vendor/github.com/miekg/dns.(*Server).serveUDP
3月 18 22:53:27 localhost dockerd[24752]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/miekg/dns/server.go:479 +0x27c
3月 18 22:53:27 localhost systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
3月 18 22:53:27 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
3月 18 22:53:29 localhost systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
3月 18 22:53:29 localhost systemd[1]: Stopped Docker Application Container Engine.
3月 18 22:53:29 localhost systemd[1]: Starting Docker Application Container Engine...
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.663975539+08:00" level=info msg="Starting up"
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.664209297+08:00" level=warning msg="Running experimental build"
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.669967834+08:00" level=debug msg="Listener created for HTTP on fd ()"
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.670801784+08:00" level=debug msg="Golang's threads limit set to 114210"
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.671365423+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.671392691+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
3月 18 22:53:29 localhost dockerd[4452]: time="2020-03-18T22:53:29.671436019+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc

```

**Describe the results you received:**

```
/ # dig @127.0.0.11 uuu       
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.41/exec/a27e75f03020df52e21f31da481d751e727a37d0b873aed7e2e9
c9bb0eda6672/json: read unix @->/var/run/docker.sock: read: connection reset by peer
```

When I started a container named `uuu` with new bridge network `uuu` and in other container try to run `dig @127.0.0.11 uuu` . The docker daemon exited.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           0.0.0-20200314012737-2e20eebe27
 API version:       1.41
 Go version:        go1.12.16
 Git commit:        2e20eebe27
 Built:             Mon Mar 16 20:14:30 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          0.0.0-20200314012737-2e20eebe27
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       2e20eebe27
  Built:            Mon Mar 16 20:11:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.3
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.0-zeta1-96-g44932b629b)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  year: A docker plugin, Happy New Year! (Jintao Zhang, v1.0.0)

Server:
 Containers: 10
  Running: 2
  Paused: 0
  Stopped: 8
 Images: 39
 Server Version: 0.0.0-20200314012737-2e20eebe27
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.5.8-100.fc30.x86_64
 Operating System: Fedora 30 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: localhost
 ID: UWEO:YNU5:7YUR:3BSN:5DA7F:GFXV:AGRL:MEFG
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 73
  System Time: 2020-03-18T23:19:35.598453317+08:00
  EventsListeners: 0
 HTTP Proxy: socks5://127.0.0.1:1080
 HTTPS Proxy: socks5://127.0.0.1:1080
 No Proxy: localhost,127.0.0.1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.1:5000
  127.0.0.0/8
 Live Restore Enabled: true


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by thaJeztah** [comment]
ping @SamWhited @arkodg PTAL

**Comment by SamWhited** [comment]
This looks like my fault; if the error is not nil the response can be nil in https://github.com/moby/libnetwork/blob/master/resolver.go#L487

I'll submit a patch shortly.

**Comment by thaJeztah** [comment]
Panic looks here https://github.com/moby/libnetwork/blob/264bffcb88c1b6b7471c04e3c6b3f301233a544b/resolver.go#L485-L487 probably `resp` is nil ?

**Comment by thaJeztah** [comment]
Oh, LOL; @SamWhited beat me to it
