### ISSUE TITLE
Zombie container can't stop lead to file descriptors leak

### ISSUE THREAD

**Issue by DanielQujun** [moby/moby#40735]
Recently our customer has found one of their k8s nodes become NotReady. And the message log spammed with 

```
http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
```
![too_many_open_files](http://qiniu.bobozhu.cn/too_many_files.png)

then we checked "lsof  2>/dev/null |grep '/var/run/docker.sock |wc -l " , and the number outputed exceeds over 3 millions

![lsof](http://qiniu.bobozhu.cn/docker.sock_lsof.png)

after deep scrolled the message log, we found It may cause by kubelet keep sending stop request to a container , and dockerd never returned success. It begins at 2019-11-20 quite a long time though...
```
Nov 20 11:07:01 D3C03U12-54-36 kubelet: E1120 11:07:01.345804   20864 kuberuntime_container.go:575] Container "docker://177664d50c3e0515dd9dff47f744d04fd370e5feea90ce77feb613dcd4240557" termination failed with gracePeriod 30: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
Nov 20 11:07:01 D3C03U12-54-36 kubelet: E1120 11:07:01.345976   20864 kuberuntime_container.go:65] Can't make a ref to pod "es-8b5b95b7d-7685k_middleware(9a90e312-7d2d-11e9-b0d1-0050569a77c6)", container es: selfLink was empty, can't make reference
Nov 20 11:07:01 D3C03U12-54-36 kubelet: E1120 11:07:01.346048   20864 kubelet_pods.go:1085] Failed killing the pod "es-8b5b95b7d-7685k": failed to "KillContainer" for "es" with KillContainerError: "rpc error: code = Unknown desc = operation timeout: context deadline exceeded"
Nov 20 11:07:33 D3C03U12-54-36 dockerd: time="2019-11-20T11:07:33.344877922+08:00" level=info msg="Container 177664d50c3e0515dd9dff47f744d04fd370e5feea90ce77feb613dcd4240557 failed to exit within 30 seconds of signal 15 - using the force"
Nov 20 11:07:43 D3C03U12-54-36 dockerd: time="2019-11-20T11:07:43.345529675+08:00" level=info msg="Container 177664d50c3e failed to exit within 10 seconds of kill - trying direct SIGKILL"
Nov 20 11:07:51 D3C03U12-54-36 rtvscand: CDefUtils::GetNewestDefs(): Missing DEFINFO.DAT.
Nov 20 11:08:08 D3C03U12-54-36 smcd: failed to run liveupdate.
Nov 20 11:08:08 D3C03U12-54-36 symcfgd: subscriber 43966 has left -- closed 0 remaining handles
Nov 20 11:09:03 D3C03U12-54-36 kubelet: E1120 11:09:03.344145   20864 remote_runtime.go:229] StopContainer "177664d50c3e0515dd9dff47f744d04fd370e5feea90ce77feb613dcd4240557" from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
Nov 20 11:09:03 D3C03U12-54-36 kubelet: E1120 11:09:03.344214   20864 kuberuntime_container.go:575] Container "docker://177664d50c3e0515dd9dff47f744d04fd370e5feea90ce77feb613dcd4240557" termination failed with gracePeriod 30: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
Nov 20 11:09:03 D3C03U12-54-36 kubelet: E1120 11:09:03.344407   20864 kuberuntime_container.go:65] Can't make a ref to pod "es-8b5b95b7d-7685k_middleware(9a90e312-7d2d-11e9-b0d1-0050569a77c6)", container es: selfLink was empty, can't make reference
Nov 20 11:09:03 D3C03U12-54-36 kubelet: E1120 11:09:03.344458   20864 kubelet_pods.go:1085] Failed killing the pod "es-8b5b95b7d-7685k": failed to "KillContainer" for "es" with KillContainerError: "rpc error: code = Unknown desc = operation timeout: context deadline exceeded"
Nov 20 11:09:35 D3C03U12-54-36 dockerd: time="2019-11-20T11:09:35.343618338+08:00" level=info msg="Container 177664d50c3e0515dd9dff47f744d04fd370e5feea90ce77feb613dcd4240557 failed to exit within 30 seconds of signal 15 - using the force"
Nov 20 11:09:45 D3C03U12-54-36 dockerd: time="2019-11-20T11:09:45.344263956+08:00" level=info msg="Container 177664d50c3e failed to exit within 10 seconds of kill - trying direct SIGKILL"
```

So we generate dockerd stack dump log, and the log shows over 60K goroutine was stuck in `container.wait`
```
danielqu@danielqu:~/Desktop/2020-03/yizhifu$ bash count_functions.sh 
      1 github.com/docker/docker/api/server.(*Server).serveAPI(0xc420092840, 0x5, 0x7)
      1 github.com/docker/docker/container.wait(0xc4201db8c0, 0x77359400, 0x2427ca0
  32753 github.com/docker/docker/container.wait(0xc4201db8c0, 0xffffffffc4653600, 0x162f9e0
      1 github.com/docker/docker/container.wait(0xc420238300, 0x77359400, 0x2427ca0
  32756 github.com/docker/docker/container.wait(0xc420238300, 0xffffffffc4653600, 0x162f9e0
      1 github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc420442c00),,
      1 github.com/docker/docker/daemon.(*statsCollector).run(0xc420285b80),,
      1 github.com/docker/docker/libcontainerd.(*remote).handleConnectionChange(0xc4203b88f0),,
      1 github.com/docker/docker/pkg/signal.DumpStacks(0x18fb82e, 0xf, 0x0
      1 github.com/docker/docker/pkg/signal.Trap.func1(0xc4202ec780, 0xc42043ebc0),
      1 github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).watchLoop(0xc42029a000),,
      1 github.com/docker/docker/vendor/github.com/docker/libnetwork/osl.removeUnusedPaths(),,
      1 github.com/docker/docker/vendor/github.com/tonistiigi/fifo.(*fifo).Read(0xc420476f00, 0xc420556000, 0x8000
      1 github.com/docker/docker/vendor/github.com/tonistiigi/fifo.(*fifo).Read(0xc420477080, 0xc42054e000, 0x8000
      2 github.com/docker/docker/vendor/github.com/tonistiigi/fifo.OpenFifo.func1(0x0, 0x2441520, 0xc4202851c0
      1 github.com/docker/docker/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc4200b4840, 0xc4202ec300, 0x0
      1 github.com/docker/docker/vendor/google.golang.org/grpc.(*addrConn).wait(0xc4200b4840, 0x24415e0, 0xc49a4bad80
```

As the log is too big to upload, here is the snippet:

```
goroutine 501 [chan receive, 78243 minutes]:
github.com/docker/docker/container.wait(0xc420238300, 0xffffffffc4653600, 0x162f9e0, 0xc420aeaae0)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/container/state.go:165 +0x62
github.com/docker/docker/container.(*State).WaitStop(0xc4203c95e0, 0xffffffffc4653600, 0x0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/container/state.go:188 +0x87
github.com/docker/docker/daemon.(*Daemon).Kill(0xc420442c00, 0xc420521a00, 0xc42181b548, 0x3)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/daemon/kill.go:147 +0x12c
github.com/docker/docker/daemon.(*Daemon).containerStop(0xc420442c00, 0xc420521a00, 0x1e, 0xc420521a00, 0x0)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/daemon/stop.go:75 +0x2ab
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc420442c00, 0xc420c993c7, 0x40, 0xc420bf99f0, 0xc42180bcb8, 0xc420b534d0)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/daemon/stop.go:32 +0xcd
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop(0xc420593e40, 0x24415e0, 0xc420b536b0, 0x243dd20, 0xc42176da00, 0xc42138d950, 0xc420b53530, 0x18eb8e5, 0x5)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:181 +0xe6
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm(0x24415e0, 0xc420b536b0, 0x243dd20, 0xc42176da00, 0xc42138d950, 0xc420b53530, 0x424168, 0x30)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:61 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x24415e0, 0xc420b536b0, 0x243dd20, 0xc42176da00, 0xc42138d950, 0xc420b53530, 0x19, 0x1c)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x24415e0, 0xc420b53680, 0x243dd20, 0xc42176da00, 0xc42138d950, 0xc420b53530, 0x1a08606, 0x415055)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5ca
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x24415e0, 0xc420b53680, 0x243dd20, 0xc42176da00, 0xc42138d950, 0xc420b53530, 0xc400000000, 0xc42180bd40)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x83f
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x243dd20, 0xc42176da00, 0xc42138d950)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x233
net/http.HandlerFunc.ServeHTTP(0xc42050ffa0, 0x243dd20, 0xc42176da00, 0xc42138d950)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420181a90, 0x243dd20, 0xc42176da00, 0xc42138d950)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420d786e0, 0x243dd20, 0xc42176da00, 0xc42138d950)
        /root/rpmbuild/BUILD/docker-ce/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420182500, 0x243dd20, 0xc42176da00, 0xc42138d950)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420b88a00, 0x243f960, 0xc420d47900)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d

```

then I debug the code and caught the culprit: `container.WaitStop` will never be exited until the container's state change to Stopped.
```
    }

    // 2. Wait for the process to die, in last resort, try to kill the process directly
    if err := killProcessDirectly(container); err != nil {
        if isErrNoSuchProcess(err) {
            return nil
        }
        return err
    }

    container.WaitStop(-1 * time.Second)
```

The execution logic here seems reasonable, send `kill -9 ` to container's PID, and waiting for container's state change if there is no err happened, I was stuck here for a long time until our customer tells us they executed  `kubectl delete po --force --grace-period=0` to kill the pod which container's PID has became a zombie. 

This makes sense that when docker sends signals to zombie PID will succeed, But the container's state may not change at this time.

IMHO, we should deal with this situation, although it rarely happens.

**versions**:
docker: 17.03.1-ce
I have checked the code, this issue may still exist in our master branch.

**Comment by DanielQujun** [comment]
related issues: 
1. [Docker stop container can't work, When container pid 1 becomes a zombie process #39407](https://github.com/moby/moby/issues/39407)
2. [Cannot stop container with zombie #35910](https://github.com/moby/moby/issues/359100

**Comment by thaJeztah** [comment]
So, IIUC, it waits for the container to die (which never happens), and kubernetes keeps connected to the API because it never returns (and the wait is `-1`, so indefinitely) correct?

**Comment by DanielQujun** [comment]
> So, IIUC, it waits for the container to die (which never happens), and kubernetes keeps connected to the API because it never returns (and the wait is `-1`, so indefinitely) correct?

yes, indeed.

**Comment by thaJeztah** [comment]
@cpuguy83 any suggestions what could be a good alternative?

**Comment by DanielQujun** [comment]
I try to reproduce the zombie container these days but did not succeed :flushed:

I suggest we could add a zombie condition check for container's PID in `killProcessDirectly` since this function is not executed frequently, but I'm not sure this is graceful. and we need to find a way to remove this container.

BTW, I'd like to know why do we add infinite wait chan after the kill. could you please shed some insight for it? @cpuguy83

**Comment by cpuguy83** [comment]
I cannot shed light here other than assuming the process will exit because we SIGKILL'd it.

I was thinking we could propagate a context and rely on that to cancel.

**Comment by DanielQujun** [comment]
I add a little patch for the zombie check, would you please take look. @cpuguy83 
https://github.com/moby/moby/pull/40749

I agree with propagate a context, I remember that there was pr or issue  "appreciate client context timeout"

**Comment by DanielQujun** [comment]
#40749 merged, Closing.

**Comment by onesolpark** [comment]
@DanielQujun How does kubernetes respond to the returned err (zombie process)
Does it delete the pods or does it change the pod status to error?
