### ISSUE TITLE
container can't be deleted if not restart docker

### ISSUE THREAD

**Issue by nfyxhan** [moby/moby#41424]
**Description**
there is a container can't be delete, and in my k8s node has a lot of log like this, it seems to timeout to call docker api
```
Sep 08 10:35:02 ucpcontroller01-test1-rgtjlk-tj1 kubelet[1368]: E0908 10:35:02.443078    1368 kubelet.go:1844] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m56.443196284s ago; threshold is 3m0s
Sep 08 10:35:06 ucpcontroller01-test1-rgtjlk-tj1 kubelet[1368]: E0908 10:35:06.040262    1368 kuberuntime_manager.go:940] PodSandboxStatus of sandbox "809f0ded195af14612de2b968c003a43b3f434e9
7822705517848802f0ee3fd0" for pod "static-testing-686d96c67-d4lwk_default(63cb40ad-4a16-49f2-aee8-e021f54eb8ce)" error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Steps to reproduce the issue:**
i wish i can repreoduce it

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
i dump the goroutine with `curl -s --unix-socket /run/containerd/containerd.sock http://./debug/pprof/goroutine?debug=2`, then it has so many goroutines waiting the lock
```
goroutine 12846732 [semacquire, 842 minutes]:
sync.runtime_SemacquireMutex(0xc004736684, 0xc004435400)
        /usr/local/go/src/runtime/sema.go:71 +0x3f
sync.(*Mutex).Lock(0xc004736680)
        /usr/local/go/src/sync/mutex.go:134 +0x101
github.com/docker/docker/daemon.(*Daemon).ContainerInspectCurrent(0xc00003a5a0, 0xc00105e2b0, 0x40, 0x0, 0xc001429300, 0x559846121880, 0xc001463ba0)
        /go/src/github.com/docker/docker/daemon/inspect.go:40 +0x90
        /go/src/github.com/docker/docker/daemon/inspect.go:40 +0x90
github.com/docker/docker/daemon.(*Daemon).ContainerInspect(0xc00003a5a0, 0xc00105e2b0, 0x40, 0x0, 0x5598457042d3, 0x4, 0x55984616c6c0, 0xc004435801, 0xc004bd0b00, 0xc0044357c8)
        /go/src/github.com/docker/docker/daemon/inspect.go:29 +0x11f
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersByName(0xc001079f40, 0x559846572940, 0xc0014411a0, 0x559846570c80, 0xc00478a380, 0xc00246d300, 0xc0014410b0, 0x559845705b35, 0x5)
        /go/src/github.com/docker/docker/api/server/router/container/inspect.go:15 +0x119
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersByName-fm(0x559846572940, 0xc0014411a0, 0x559846570c80, 0xc00478a380, 0xc00246d300, 0xc0014410b0, 0x5598441af0ad, 0x5598463d0860)
        /go/src/github.com/docker/docker/api/server/router/container/container.go:39 +0x6b
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x559846572940, 0xc0014411a0, 0x559846570c80, 0xc00478a380, 0xc00246d300, 0xc0014410b0, 0x559846572940, 0xc0014411a0)
        /go/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0xda
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x559846572940, 0xc001441170, 0x559846570c80, 0xc00478a380, 0xc00246d300, 0xc0014410b0, 0x203000, 0x203000)
        /go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x403
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x559846572940, 0xc001441170, 0x559846570c80, 0xc00478a380, 0xc00246d300, 0xc0014410b0, 0x559846572940, 0xc001441170)
        /go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x7c4
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x559846570c80, 0xc00478a380, 0xc00246d300)
        /go/src/github.com/docker/docker/api/server/server.go:141 +0x19a
net/http.HandlerFunc.ServeHTTP(0xc001934b60, 0x559846570c80, 0xc00478a380, 0xc00246d300)
        /usr/local/go/src/net/http/server.go:1964 +0x46
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0016a8d20, 0x559846570c80, 0xc00478a380, 0xc00246d300)
        /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x22c
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc00128aa00, 0x559846570c80, 0xc00478a380, 0xc00246d300)
        /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc000878270, 0x559846570c80, 0xc00478a380, 0xc00246d300)
        /usr/local/go/src/net/http/server.go:2741 +0xad
net/http.(*conn).serve(0xc00455a640, 0x559846572880, 0xc000ea3b00)
        /usr/local/go/src/net/http/server.go:1847 +0x648
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f7
```
after i restart docker, all of the lock is gone, and i compare the gouroutine with 
```
curl -s --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2 |grep "created by"|sort |uniq -c > g1
curl -s --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2 |grep "created by"|sort |uniq -c > g1
diff g1 g2
```
got the result
```
7c7
<      40 created by github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1
---
>     190 created by github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1
12c12
<      40 created by github.com/docker/docker/daemon/logger.(*Copier).Run
---
>     192 created by github.com/docker/docker/daemon/logger.(*Copier).Run
14a15
>       1 created by github.com/docker/docker/libcontainerd.(*queue).append
32,33c33,34
<       2 created by net/http.(*connReader).startBackgroundRead
<       8 created by net/http.(*Server).Serve
---
>       3 created by net/http.(*connReader).startBackgroundRead
>     493 created by net/http.(*Server).Serve
```
before restart, it has a goroutine that `created by github.com/docker/docker/libcontainerd.(*queue).append`, there is the full stack
```
goroutine 12792467 [select, 971 minutes]:
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*Stream).waitOnHeader(0xc00141a0f0, 0x10, 0xc001a06fd0)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:222 +0xd1
github.com/docker/docker/vendor/google.golang.org/grpc/transport.(*Stream).RecvCompress(0xc00141a0f0, 0x55984653a8b8, 0xc001a07088)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/transport/transport.go:233 +0x2d
github.com/docker/docker/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc000d905b0, 0x5598463c17c0, 0xc001038db0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:515 +0x629
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc00069a400, 0x5598463c17c0, 0xc001038db0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:395 +0x45
github.com/docker/docker/vendor/google.golang.org/grpc.invoke(0x559846572940, 0xc001038e70, 0x55984575b491, 0x2a, 0x5598463ba520, 0xc003864190, 0x5598463c17c0, 0xc001038db0, 0xc0001a6c00, 0xc
000880840, ...)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:83 +0x188
github.com/docker/docker/vendor/github.com/containerd/containerd.namespaceInterceptor.unary(0x559845704b8f, 0x4, 0x5598465728c0, 0xc00003e038, 0x55984575b491, 0x2a, 0x5598463ba520, 0xc0038641
90, 0x5598463c17c0, 0xc001038db0, ...)
        /go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:35 +0xf7
github.com/docker/docker/vendor/github.com/containerd/containerd.namespaceInterceptor.unary-fm(0x5598465728c0, 0xc00003e038, 0x55984575b491, 0x2a, 0x5598463ba520, 0xc003864190, 0x5598463c17c0
, 0xc001038db0, 0xc0001a6c00, 0x55984653a928, ...)
        /go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/grpc.go:51 +0xf6
github.com/docker/docker/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc0001a6c00, 0x5598465728c0, 0xc00003e038, 0x55984575b491, 0x2a, 0x5598463ba520, 0xc003864190, 0x5598463c17c0, 0xc
001038db0, 0x0, ...)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:35 +0x10b
github.com/docker/docker/vendor/google.golang.org/grpc.Invoke(0x5598465728c0, 0xc00003e038, 0x55984575b491, 0x2a, 0x5598463ba520, 0xc003864190, 0x5598463c17c0, 0xc001038db0, 0xc0001a6c00, 0x0
, ...)
        /go/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:60 +0xc3
github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1.(*tasksClient).Delete(0xc0018d6028, 0x5598465728c0, 0xc00003e038, 0xc003864190, 0x0, 0x0, 0x0, 0xed6e80f
84, 0x0, 0x0)
       /go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:430 +0xd4
github.com/docker/docker/vendor/github.com/containerd/containerd.(*task).Delete(0xc003a04b70, 0x5598465728c0, 0xc00003e038, 0x0, 0x0, 0x0, 0xc003a04b70, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/task.go:293 +0x265
github.com/docker/docker/libcontainerd.(*client).DeleteTask(0xc0001a2d20, 0x5598465728c0, 0xc00003e038, 0xc0036c5280, 0x40, 0x0, 0xc00237a6a0, 0x5598441a5a4c, 0x5598457042ad, 0x2, ...)
        /go/src/github.com/docker/docker/libcontainerd/client_daemon.go:514 +0xe0
github.com/docker/docker/daemon.(*Daemon).ProcessEvent(0xc00003a5a0, 0xc003ffa7c0, 0x40, 0x55984570495b, 0x4, 0xc003ffa7c0, 0x40, 0xc003ffa800, 0x40, 0x5c51, ...)
        /go/src/github.com/docker/docker/daemon/monitor.go:54 +0x236
github.com/docker/docker/libcontainerd.(*client).processEvent.func1()
        /go/src/github.com/docker/docker/libcontainerd/client_daemon.go:718 +0x130
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc003ffa700, 0x0, 0xc000166e80, 0xc000d262a0, 0xc0001a2d78, 0xc003ffa7c0, 0x40)
        /go/src/github.com/docker/docker/libcontainerd/queue.go:26 +0x3a
created by github.com/docker/docker/libcontainerd.(*queue).append
        /go/src/github.com/docker/docker/libcontainerd/queue.go:22 +0x186
```
i saw the source code, it block at the method  `DeleteTask` which has no timeout
```
if int(ei.Pid) == c.Pid {
	c.Lock()
	_, _, err := daemon.containerd.DeleteTask(context.Background(), c.ID)
	if err != nil {
		logrus.WithError(err).Warnf("failed to delete container %s from containerd", c.ID)
	}
        ......
        ......
}
```
**Output of `docker version`:**

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
> i saw the source code, it block at the method DeleteTask which has no timeout

I see that this PR is adding a 1 minute timeout to that code (but needs a rebase, as code was moved around) https://github.com/moby/moby/pull/39271/files#diff-c43715aa07d90f284fe1a3749983808bR55

I was wondering what the consequences would be to timeout there (as steps after would then not be executed), but also recalled we recently merged https://github.com/moby/moby/pull/41227, which would probably work around that


@cpuguy83 PTAL - think we should add a timeout there?

**Comment by cpuguy83** [comment]
I do :) https://github.com/moby/moby/pull/39271

**Comment by thaJeztah** [comment]
Yup; that's the one I linked above 😂

> I see that this PR is adding a 1 minute timeout to that code (but needs a rebase, as code was moved around) https://github.com/moby/moby/pull/39271/files#diff-c43715aa07d90f284fe1a3749983808bR55
