### ISSUE TITLE
Windows hns service is running but dockerd fails with - hnsCall failed in Win32: The service has not been started.

### ISSUE THREAD

**Issue by gakera** [moby/moby#41423]
I got chased out of the Docker repo with this issue, I wonder how long it will live here?
https://github.com/docker/for-win/issues/8226

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FC2D0E6A-B052-4774-9782-768A8F60F9E1/20200825162412

### Expected behavior

Switching to Windows containers should work. 

### Actual behavior

It don't work. 

```
Docker.Core.DockerException:
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Engines.DockerDaemonChecker.<CheckAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\DockerDaemonChecker.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WindowsContainersEngine.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible?
Yes, happens every time I switch to Windows containers
  - Is the problem new?
No, I reported this on SO like 9 months ago, and it's still a problem. https://stackoverflow.com/questions/58642314/docker-daemon-on-windows-10-crashing-when-started-hnscall-failed-in-win32-t
  - Did the problem appear with an update?
Maybe, there's like, an update every month...
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
Can I ship you my computer?
  - Windows Version: (now, no idea what it was when this first started). 
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
  - Docker Desktop Version: (now, but like this started way back last year).
λ docker -v
Docker version 19.03.12, build 48a66213fe
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No... just my desktop machine at work. 

### Steps to reproduce the behavior

  1. Have docker installed
  2. Switch to Windows Containers
  3. Crash / error
  4. Upload crash report
  5. Uninstall / Reinstall
  6. Repeat 100x steps 1-5
  7. Nothing happens for months
  8. Try again today
  9. "Reset factory settings", same results
 10. Upload crash report FC2D0E6A-B052-4774-9782-768A8F60F9E1/20200825162412
 11. Notice for the first time a "report issue" option
 12. Report issue
 13. Prepare for disappointment, and non-functioning Windows Containers forever.

**Comment by thaJeztah** [comment]
@daschott @msabansal ptal

**Comment by gakera** [comment]
Updated to latest docker version, still an issue 
```
λ docker -v
Docker version 19.03.12, build 48a66213fe
```

**Comment by thomaslazar** [comment]
I have the exact same issue. Can't really tell why. Colleagues with same windows and docker versions can switch.

**Comment by thomaslazar** [comment]
When i looked at the logs I had the following in the logfile.
```
[12:40:17.827][ApiProxy          ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.proxy.exe -daemonNamedPipe=\\.\pipe\docker_engine_windows  -dockerExe "C:\Program Files\Docker\Docker\resources\bin\docker.exe"  -host-names host.docker.internal,docker.for.win.host.internal,docker.for.win.localhost -gateway-names gateway.docker.internal,docker.for.win.gateway.internal,docker.for.win.http.internal -vm-names vm.docker.internal,docker-for-desktop,docker-desktop,kubernetes.docker.internal -host-ip 192.168.65.2 -gateway-ip 192.168.65.1 -vm-ip 192.168.65.3 -pki "C:\Users\lazart\AppData\Local\Docker\pki" -inject-hosts=True --windows-containers
[12:40:17.841][ApiProxy          ][Info   ] Started
[12:40:19.116][ApiProxy          ][Info   ] Watching for container start events to inject host entries
[12:40:19.116][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[12:40:19.116][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[12:40:19.116][ApiProxy          ][Info   ] open \\\\.\\pipe\\docker_engine_windows: The system cannot find the file specified.
[12:40:19.116][ApiProxy          ][Info   ] open \\\\.\\pipe\\docker_engine_windows: The system cannot find the file specified.
[12:40:19.116][ApiProxy          ][Info   ] proxy >> GET /v1.24/events\n
[12:40:19.116][ApiProxy          ][Info   ] open \\\\.\\pipe\\docker_engine_windows: The system cannot find the file specified.
[12:40:19.116][ApiProxy          ][Error  ] Error watch events stream: Error response from daemon: open \\\\.\\pipe\\docker_engine_windows: The system cannot find the file specified.
[12:40:19.116][ApiProxy          ][Info   ] proxy >> GET /v1.24/events\n
[12:40:19.116][ApiProxy          ][Info   ] open \\\\.\\pipe\\docker_engine_windows: The system cannot find the file specified.
[12:40:19.117][ApiProxy          ][Error  ] Error watch events stream: Error response from daemon: open \\\\.\\pipe\\docker_engine_windows: The system cannot find the file specified.
[12:40:19.117][ApiProxy          ][Info   ] proxy >> GET /v1.24/events\n
```

So when I went and started the `com.docker.proxy.exe` command manually and checked what pipes exist I found a peculiar thing  . 

```
[System.IO.Directory]::GetFiles("\\.\\pipe\\")
...
\\.\\pipe\\docker_engine
```

This named pipe isn't running normally.

So when I changed the above command to not use `docker_engine_windows` and instead called it with just `docker_engine` I get the following output. 

```
C:\Users\lazart>"C:\Program Files\Docker\Docker\resources\com.docker.proxy.exe" -daemonNamedPipe=\\.\pipe\docker_engine  -dockerExe "C:\Program Files\Docker\Docker\resources\bin\docker.exe"  -host-names host.docker.internal,docker.for.win.host.internal,docker.for.win.localhost -gateway-names gateway.docker.internal,docker.for.win.gateway.internal,docker.for.win.http.internal -vm-names vm.docker.internal,docker-for-desktop,docker-desktop,kubernetes.docker.internal -host-ip 192.168.65.2 -gateway-ip 192.168.65.1 -vm-ip 192.168.65.3 -pki "C:\Users\lazart\AppData\Local\Docker\pki" -inject-hosts=True --windows-containers
[36mINFO[0m[0000] Watching for container start events to inject host entries
[36mINFO[0m[0000] proxy >> HEAD /_ping

[36mINFO[0m[0000] proxy >> HEAD /_ping

[36mINFO[0m[0000] proxy >> HEAD /_ping

[36mINFO[0m[0000] proxy >> HEAD /_ping

[36mINFO[0m[0000] proxy >> HEAD /_ping

[36mINFO[0m[0000] proxy >> HEAD /_ping
```

So it seems to be working? I don't know. 

The question is, why is the `docker.exe` command opening up a `docker_engine` named pipe instead of a `docker_engine_windows` named pipe. And how do I tell it to not do that? 

Alternatively where do I tell the software to use `docker_engine` instead? 

And I run the newest Docker Desktop for Windows.

**Comment by gakera** [comment]
@thomaslazar I get the same results, running those commands, works for the later one, doesn't work for the first one.

**Comment by gakera** [comment]
I added this info to the Docker issue over at https://github.com/docker/for-win/issues/8226 - maybe they have an answer to the question.

**Comment by olljanat** [comment]
@gakera have btw tried uninstall + reinstall "Windows containers" feature? I mean that Windows internal feature (control panel -> programs/features...). That adds "hns" and "vmcompute" services to Windows and either of those is most probably broken on your machine.

**Comment by thomaslazar** [comment]
I "solved" this issue for me by installing Windows 10 inside a Hyper-V VM and jumping through some hoops to get virtualization running inside the VM and installing Docker for Windows there. 

I will have IT do a full reinstall of my laptop and hope it will sort itself out that way. Still an annoying bug though.
