### ISSUE TITLE
Docker service suddenly not starting Ubuntu 18.04 Raspberry Pi 2

### ISSUE THREAD

**Issue by Jamesking56** [moby/moby#41492]
Docker service has suddenly stopped starting on my Raspberry Pi 2 running Ubuntu 18.04.5 LTS

**Steps to reproduce the issue:**
1. No idea

**Describe the results you received:**

Running `sudo dockerd --debug` gives this output:

```
SIGILL: illegal instruction
PC=0x1d3ea14 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
github.com/docker/docker/vendor/github.com/moby/buildkit/session/secrets.init()
	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/session/secrets/secrets.go:16 fp=0x4127f2c sp=0x4127f2c pc=0x1d3ea14
runtime.doInit(0x3a757e8)
	/usr/local/go/src/runtime/proc.go:5228 +0x88 fp=0x4127f40 sp=0x4127f2c pc=0x974c18
runtime.doInit(0x3a7bf38)
	/usr/local/go/src/runtime/proc.go:5223 +0x4c fp=0x4127f54 sp=0x4127f40 pc=0x974bdc
runtime.doInit(0x3a7adb8)
	/usr/local/go/src/runtime/proc.go:5223 +0x4c fp=0x4127f68 sp=0x4127f54 pc=0x974bdc
runtime.doInit(0x3a7ee50)
	/usr/local/go/src/runtime/proc.go:5223 +0x4c fp=0x4127f7c sp=0x4127f68 pc=0x974bdc
runtime.doInit(0x3a738a8)
	/usr/local/go/src/runtime/proc.go:5223 +0x4c fp=0x4127f90 sp=0x4127f7c pc=0x974bdc
runtime.doInit(0x3a80380)
	/usr/local/go/src/runtime/proc.go:5223 +0x4c fp=0x4127fa4 sp=0x4127f90 pc=0x974bdc
runtime.main()
	/usr/local/go/src/runtime/proc.go:190 +0x204 fp=0x4127fe4 sp=0x4127fa4 pc=0x967080
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:868 +0x4 fp=0x4127fe4 sp=0x4127fe4 pc=0x99834c

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x14c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x34

goroutine 15 [select]:
github.com/docker/docker/vendor/go.opencensus.io/stats/view.(*worker).start(0x4151880)
	/go/src/github.com/docker/docker/vendor/go.opencensus.io/stats/view/worker.go:144 +0x98
created by github.com/docker/docker/vendor/go.opencensus.io/stats/view.init.0
	/go/src/github.com/docker/docker/vendor/go.opencensus.io/stats/view/worker.go:29 +0x54

trap    0x6
error   0x0
oldmask 0x0
r0      0x3a757e8
r1      0x0
r2      0x11
r3      0x1d3ea14
r4      0x4
r5      0x0
r6      0x1f81da8
r7      0x3a7582c
r8      0x0
r9      0x10
r10     0x3c000e0
fp      0x3adca88
ip      0x1
sp      0x4127f2c
lr      0x974c18
pc      0x1d3ea14
cpsr    0x80000010
fault   0x0
```

**Describe the results you expected:**

Docker service to start correctly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 17:07:23 2020
 OS/Arch:           linux/arm
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
@tonistiigi @AkihiroSuda ptal

**Comment by tonistiigi** [comment]
I don't think the shown trace location is related to the issue.

**Comment by Jamesking56** [comment]
I'm not sure what other info is needed for this, but I've tried reinstalling Docker to no avail

**Comment by Jamesking56** [comment]
I have managed to fix this on my raspberry pi.

I was installing/reinstalling the `docker` package using `apt` but realised I also had installed `docker-ce` package.

After reinstalling the `docker-ce` package, the issue was fixed and my docker service was working again.
