### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by aryamsft** [moby/moby#42161]
**Windows version: WindowsServer|2019-Datacenter-with-Containers|17763.1457.2009030514
Docker version
Client: Docker Engine - Enterprise
Version: 19.03.11
API version: 1.40
Go version: go1.13.11
Git commit: 0da829ac52
Built: 06/26/2020 17:20:46
OS/Arch: windows/amd64
Experimental: false**

I have someone who is seeing the below error, and they are also getting the error "The semaphore timeout period has expired". Anyone know what is causing the below?

_panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x113302b]

goroutine 1681 [running]:
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/hns.(*HNSEndpoint).IsAttached(0x0, 0xc000195980, 0x40, 0x25624a0, 0xc0015c6940, 0x479563)
C:/gopath/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/hns/hnsendpoint.go:104 +0x5b
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim.HotDetachEndpoint(0xc000195980, 0x40, 0xc0009fad80, 0x24, 0x0, 0x0)
C:/gopath/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/hnsendpoint.go:53 +0x62
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/windows.(*driver).Leave(0xc000c5d920, 0xc0009b8100, 0x40, 0xc000b44ec0, 0x40, 0x0, 0x0)
C:/gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/windows/windows.go:878 +0x156
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*endpoint).sbLeave(0xc001203600, 0xc000d96900, 0x0, 0x0, 0x0, 0x0, 0xc000c79008, 0xc001385500)
C:/gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/endpoint.go:754 +0x565
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*endpoint).Leave(0xc000b1f760, 0x25fd420, 0xc000d96900, 0x0, 0x0, 0x0, 0x0, 0x0)
C:/gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/endpoint.go:704 +0x1ba
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*sandbox).delete(0xc000d96900, 0xc000736300, 0x36cbef0, 0xc000ca29c0)
C:/gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox.go:224 +0x2d0
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*sandbox).Delete(0xc000d96900, 0xc000195980, 0x40)
C:/gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox.go:185 +0x37
github.com/docker/docker/daemon.(*Daemon).releaseNetwork(0xc00014c800, 0xc000c0c500)
            C:/gopath/src/github.com/docker/docker/daemon/container_operations.go:1018 +0x53e
github.com/docker/docker/daemon.(*Daemon).Cleanup(0xc00014c800, 0xc000c0c500)
            C:/gopath/src/github.com/docker/docker/daemon/start.go:244 +0x57
github.com/docker/docker/daemon.(*Daemon).ProcessEvent(0xc00014c800, 0xc000195980, 0x40, 0x21c12ec, 0x4, 0xc000195980, 0x40, 0x21c13d4, 0x4, 0xc000013a00003ef8, ...)
            C:/gopath/src/github.com/docker/docker/daemon/monitor.go:87 +0x6a0
github.com/docker/docker/libcontainerd/local.(*client).reapProcess.func1()
            C:/gopath/src/github.com/docker/docker/libcontainerd/local/local_windows.go:1379 +0x402
github.com/docker/docker/libcontainerd/queue.(*Queue).Append.func1(0xc000195900, 0x0, 0xc00038aff0, 0xc000fc02a0, 0xc00038a440, 0xc000195980, 0x40)
            C:/gopath/src/github.com/docker/docker/libcontainerd/queue/queue.go:28 +0x3f
created by github.com/docker/docker/libcontainerd/queue.(*Queue).Append
            C:/gopath/src/github.com/docker/docker/libcontainerd/queue/queue.go:24 +0x1d4_

**Comment by thaJeztah** [comment]
Not sure if I've seen this error, but I know that there was an update in the hcsshim package between 19.03.11 and 19.03.15 (https://github.com/moby/moby/pull/41192) community edition; note that the Docker Enterprise product went to Mirantis; it's worth checking if there's more recent versions available , and if the issue is reproducible on those
