### ISSUE TITLE
SIGSEGV in cluster networkdb every 30 minutes

### ISSUE THREAD

**Issue by tari** [moby/moby#42202]
**Description**

`dockerd` crashes every 30 minutes with `SIGSEGV`. When restarted (automatically by `systemd`), it will crash after another 30 minutes.

Logs suggest there's some kind of problem with network state:

```
Mar 25 08:23:08 celsian dockerd[529]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 25 08:23:08 celsian dockerd[529]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5606f3b038b8]
Mar 25 08:23:08 celsian dockerd[529]: goroutine 585 [running]:
Mar 25 08:23:08 celsian dockerd[529]: github.com/armon/go-radix.recursiveWalk(0x0, 0xc003386e08, 0x5606f4ca9800)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:519 +0x28
Mar 25 08:23:08 celsian dockerd[529]: github.com/armon/go-radix.recursiveWalk(0xc00359c0f0, 0xc003386e08, 0xc003386c00)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
Mar 25 08:23:08 celsian dockerd[529]: github.com/armon/go-radix.recursiveWalk(0xc002f9e330, 0xc003386e08, 0x19)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
Mar 25 08:23:08 celsian dockerd[529]: github.com/armon/go-radix.(*Tree).WalkPrefix(0xc003532410, 0xc00198a7a0, 0x1a, 0xc003386e08)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:473 +0xdb
Mar 25 08:23:08 celsian dockerd[529]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapTableEntries(0xc0028bbc20)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:396 +0x3c5
Mar 25 08:23:08 celsian dockerd[529]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState(0xc0028bbc20)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:362 +0x2d
Mar 25 08:23:08 celsian dockerd[529]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState-fm()
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:170 +0x2c
Mar 25 08:23:08 celsian dockerd[529]: github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc0028bbc20, 0x12a05f200, 0xc000d47ce0, 0xc003533300)
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x10a
Mar 25 08:23:08 celsian dockerd[529]: created by github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
Mar 25 08:23:08 celsian dockerd[529]:         /build/docker.io-sMo5uP/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x830
```

I'd guess there's some corrupt state in a `networkdb` that periodic maintenance trips over, since this machine has been experiencing periodic kernel panics that I haven't yet found the root cause of either. I believe an unclean shutdown may have left some persistent data in an invalid state that crashes the engine.

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 21 Feb 2021 18:18:35 +0100
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Feb 21 17:18:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 81
 Running: 5
 Paused: 0
 Stopped: 76
Images: 8
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: x9hu8zax14hjsleea7dt6k8b5
 Is Manager: true
 ClusterID: 19sv88tiep6lxg2p3z7xsnzbl
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 2
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.7.0.2
 Manager Addresses:
  10.7.0.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-14-cloud-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 861.9MiB
Name: celsian
ID: PSTI:72QD:KSQB:F6CX:5D63:VVLR:4BRA:E5CR:CIVD:OXDM:N3WC:2QNK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is a VM on Digital Ocean's platform.

**Comment by AkihiroSuda** [comment]
v18.09 is unmaintained. Please try v20.10

**Comment by tari** [comment]
20.10.5 seems to not be crashing. There were also some warnings printed during startup related to deleting stale objects that seem related to networking based on their names, so it seems the new version may have been able to recover from whatever bad data there was.

I'll close this now, keep an eye on things for a while, and reopen if the issue seems to not actually be fixed with the upgrade.
