### ISSUE TITLE
Analysis of docker swarm "dispatcher is stopped"

### ISSUE THREAD

**Issue by xinfengliu** [moby/moby#42314]
I have seen a few times that the swarm dispatcher is gone and the swarm cluster stopped working. The only way to recover is restarting the manager nodes.

I happen to have a stacktrace of the leader node captured at the problem time, the docker version is `19.03.12`.
[daemon-stack-trace.zip](https://github.com/moby/moby/files/6358233/daemon-stack-trace.zip)

In the stacktrace, there's no `dispatcher` stack, but there's a stack `becomeFollower`, this is abnormal. It is blocked in `(*LogBroker).Stop`

```
goroutine 613 [semacquire, 747 minutes]:
sync.runtime_SemacquireMutex(0xc000b1a184, 0x0, 0x1)
        /.GOROOT/src/runtime/sema.go:71 +0x49
sync.(*Mutex).lockSlow(0xc000b1a180)
        /.GOROOT/src/sync/mutex.go:138 +0xfe
sync.(*Mutex).Lock(...)
        /.GOROOT/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000b1a180)
        /.GOROOT/src/sync/rwmutex.go:98 +0x99
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*LogBroker).Stop(0xc000b1a180, 0x0, 0x0)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/broker.go:78 +0x3b
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeFollower(0xc000845860)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1111 +0x4d
```

Below code means if `becomeFollower()` is blocked, then `becomeLeader()` has no chance to run when the node is re-elected as the leader. Thus `dispatcher` will not be run.
```
// handleLeadershipEvents handles the is leader event or is follower event.
func (m *Manager) handleLeadershipEvents(ctx context.Context, leadershipCh chan events.Event) {
	// get the current leader and save it for logging leadership changes in
	// this loop
	oldLeader := m.getLeaderNodeID()
	for {
		select {
		case leadershipEvent := <-leadershipCh:
			m.mu.Lock()
			if m.stopped {
				m.mu.Unlock()
				return
			}
			newState := leadershipEvent.(raft.LeadershipState)

			if newState == raft.IsLeader {
				m.becomeLeader(ctx)
				leaderMetric.Set(1)
			} else if newState == raft.IsFollower {
				m.becomeFollower()
				leaderMetric.Set(0)
...
```

**Comment by xinfengliu** [comment]
The root cause of the lock blocking in above stacktrace is from `subscription` of `LogBroker`. (The lock chains are too complex, I don't want to expand it here).

```
goroutine 110766494 [select, 968 minutes]:
github.com/docker/docker/vendor/github.com/docker/go-events.(*Broadcaster).Write(0xc00c6e4550, 0x563f2c0da0c0, 0xc00822a000, 0x19, 0xc0074a7288)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/go-events/broadcast.go:48 +0xc6
github.com/docker/docker/vendor/github.com/docker/swarmkit/watch.(*Queue).Publish(...)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/watch/watch.go:182
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*subscription).watch.func1(0xc00110be00)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/subscription.go:219 +0x171
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*subscription).watch(0xc00822a000, 0xc0087e2ba0, 0xc001494fb0, 0x1)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/subscription.go:245 +0x3ad
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*subscription).Run.func1(0xc0154b2e00, 0xc00822a000, 0xc0087e2ba0)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/subscription.go:74 +0x5b
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*subscription).Run
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/subscription.go:72 +0x1cd
```
Corresponding codes:
```
func (b *Broadcaster) Write(event Event) error {
	select {
	case b.events <- event:   <== here
	case <-b.closed:
		return ErrSinkClosed
	}
	return nil
}
```
And 
```
goroutine 88980840 [semacquire, 968 minutes]:
sync.runtime_SemacquireMutex(0xc00822a00c, 0x0, 0x0)
        /.GOROOT/src/runtime/sema.go:71 +0x49
sync.(*RWMutex).RLock(...)
        /.GOROOT/src/sync/rwmutex.go:50
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*subscription).Contains(0xc00822a000, 0xc00ac3ed00, 0x19, 0xc009d98300)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/subscription.go:48 +0xef
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker.(*LogBroker).watchSubscriptions.func1(0x563f2c0da0c0, 0xc00822a000, 0xc008d70c48)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/logbroker/broker.go:177 +0x50
github.com/docker/docker/vendor/github.com/docker/go-events.MatcherFunc.Match(0xc008033940, 0x563f2c0da0c0, 0xc00822a000, 0x0)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/go-events/filter.go:13 +0x3c
github.com/docker/docker/vendor/github.com/docker/go-events.(*Filter).Write(0xc001da9bf0, 0x563f2c0da0c0, 0xc00822a000, 0x0, 0x1)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/go-events/filter.go:36 +0x58
github.com/docker/docker/vendor/github.com/docker/go-events.(*Broadcaster).run(0xc00c6e4550)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/go-events/broadcast.go:120 +0x257
created by github.com/docker/docker/vendor/github.com/docker/go-events.NewBroadcaster
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/go-events/broadcast.go:39 +0x1b0
...
```        
Corresponding codes:
```
func (b *Broadcaster) run() {
	defer close(b.closed)
	remove := func(target Sink) {
		for i, sink := range b.sinks {
			if sink == target {
				b.sinks = append(b.sinks[:i], b.sinks[i+1:]...)
				break
			}
		}
	}

	for {
		select {
		case event := <-b.events:
			for _, sink := range b.sinks {
				if err := sink.Write(event); err != nil {   <== here
...
```         

Above `goroutine 88980840` is doing `sink.Write(event)` but is blocked by the lock of `subscription`, the lock holder is `goroutine 110766494` which tries to push event to `b.events` but wait for `goroutine 88980840` to handle `b.events` in next cycle, so a deadlock happens.

**Comment by thaJeztah** [comment]
Thanks! If the issues is in the `Broadcaster` code, I see that is in the https://github.com/docker/go-events dependency; having a quick look at the history of that code, I see it was added by @stevvooe in https://github.com/docker/go-events/commit/bb7a0c680585c7b18bd870f57fc32c1354c5ae9b, which was an based on code from the https://github.com/docker/distribution repository, erm.., which was also implemented by @stevvooe https://github.com/distribution/distribution/commit/9f0c8d6616a99a13bdb106c743835ea314227151 😂 


@stevvooe @dperny ptal

**Comment by xinfengliu** [comment]
Hi @thaJeztah,
Thanks for your attention.

IMHO, it is not the problem of `Broadcaster` code. The codes causing potential deadlock is here:
https://github.com/docker/swarmkit/blob/master/manager/logbroker/subscription.go#L206-L220
```
	add := func(t *api.Task) {
		s.mu.Lock()   <== lock the subscription
		defer s.mu.Unlock()

		// Un-allocated task.
		if t.NodeID == "" {
			s.pendingTasks[t.ID] = struct{}{}
			return
		}

		delete(s.pendingTasks, t.ID)
		if _, ok := s.nodes[t.NodeID]; !ok {
			s.nodes[t.NodeID] = struct{}{}
			s.changed.Publish(s)  <== will call (*Broadcaster).Write()
		}
	}
```
And 
https://github.com/docker/swarmkit/blob/master/manager/logbroker/broker.go#L170-L178
```
func (lb *LogBroker) watchSubscriptions(nodeID string) ([]*subscription, chan events.Event, func()) {
	lb.mu.RLock()
	defer lb.mu.RUnlock()

	// Watch for subscription changes for this node.
	ch, cancel := lb.subscriptionQueue.CallbackWatch(events.MatcherFunc(func(event events.Event) bool {
		s := event.(*subscription)
		return s.Contains(nodeID)   <== will lock the subscription too when sink.Write(event) is called.
	}))
```
Not sure if it's safe to move `s.changed.Publish(s)` out of the lock, or any better ideas?

**Comment by thaJeztah** [comment]
I'd have to dive further into that code, as I'm not very familiar with those parts; hope @dperny may have some time to have a look (I think he may be out of office this week, but perhaps he's checking his notifications)

**Comment by dperny** [comment]
@xinfengliu I'm finally getting around to look at this. I think I see what your problem is. The queue gets deadlocked because CallbackWatch checks every event against a function, and the callback in this case acquires a lock that the function attempting to write is already using.

I think the fix you suggest is fine. The code would look something like this:

```go
    // manager/logbroker/subscription.go, (*subscription).watch
    add := func(t *api.Task) {
        s.mu.Lock()
        
        // Un-allocated task.
        if t.NodeID == "" {
            s.pendingTasks[t.ID] = struct{}{}
            s.mu.Unlock()
            return
        }
        
        delete(s.pendingTasks, t.ID)
        if _, ok := s.nodes[t.NodeID]; !ok {
            s.nodes[t.NodeID] = struct{}{}
            s.mu.Unlock()
            s.changed.Publish(s)
            return
        }
        
        s.mu.Unlock()
    }
```

**Comment by dperny** [comment]
The way the code is already designed, we don't have to rely on any locking when writing the subscription to that queue. The receiver double-checks things along the way. So we can do the `Publish` call outside of the lock no problem. The only downside is that without more re-architecting, we lose the protection of the defer. But this is such a small snippet, it shouldn't be a problem.

**Comment by xinfengliu** [comment]
@dperny 
>The way the code is already designed, we don't have to rely on any locking when writing the subscription to that queue. The receiver double-checks things along the way. So we can do the Publish call outside of the lock no problem.

Thanks for the confirmation. I have the same feeling about that.
