### ISSUE TITLE
panic: failed to get edge

### ISSUE THREAD

**Issue by Antiarchitect** [moby/moby#42414]
**Description**

Running multiple builds simultaneously on one docker daemon (K8s environment, dedicated dind dockers for CI purpose) got this (latest from the logs):
```
panic: failed to get edge
goroutine 135 [running]:
github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*pipeFactory).NewInputRequest(0xc000937ef8, 0x0, 0x31c7b80, 0xc00cf95300, 0xc01171
    /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:350 +0x1fe
github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*edge).createInputRequests(0xc002154500, 0x3, 0xc000937ef8, 0x0, 0xc01904e610)
    /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/edge.go:809 +0x31f
github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*edge).unpark(0xc002154500, 0xc01904e600, 0x1, 0x1, 0xc01904e620, 0x1, 0x1, 0xc019
    /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/edge.go:360 +0x17b
github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc0002f03f0, 0xc002154500)
    /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:136 +0x432
github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).loop(0xc0002f03f0)
    /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:104 +0x17b
created by github.com/docker/docker/vendor/github.com/moby/buildkit/solver.newScheduler
    /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:35 +0x1ad
```

**Describe the results you received:**
Docker pod has failed Liveness/Readiness after that probes which are:

```
livenessProbe:
  httpGet:
    path: /_ping
    port: 2375
readinessProbe:
  httpGet:
    path: /_ping
    port: 2375
```

and was killed by K8s

**Describe the results you expected:**
Docker operates normally

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens very infrequently

**Output of `docker version`:**

```
Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:42:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:46:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 
Server: 
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 189
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.12.1-1.el7.elrepo.x86_64
 Operating System: Alpine Linux v3.13 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.7GiB
 Name: production-app-gitlab-runners-docker-2
 ID: WDVE:XF3M:UUBU:YNOD:PUNM:EBCV:L6ED:FKXW:HGO4:IGTX:RH62:BUGB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://dockerhub.xxx/
 Live Restore Enabled: false
 Product License: Community Engine
 Default Address Pools:
   Base: 10.10.0.0/16, Size: 24

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using `docker:20.10.6-dind` from hub.docker.com
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

```
Linux worker-2.prod.xxx.xxx 5.12.1-1.el7.elrepo.x86_64 #1 SMP Fri Apr 30 15:49:43 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
@tonistiigi @AkihiroSuda PTAL

**Comment by Antiarchitect** [comment]
Yet one occasion:
```
2021-06-02T16:22:33.812258786Z panic: failed to get edge
2021-06-02T16:22:33.812315441Z goroutine 590 [running]:
2021-06-02T16:22:33.819898903Z github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*pipeFactory).NewInputRequest(0xc0009c7ef8, 0x0, 0x
31c7b80, 0xc00c62e380, 0xc01323b180, 0xc00b91f6a8, 0x0)
2021-06-02T16:22:33.819935290Z     /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:350 +0x1fe
2021-06-02T16:22:33.819946171Z github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*edge).createInputRequests(0xc00b91f2c0, 0x3, 0xc00
09c7ef8, 0x0, 0xc001fc7c90)
2021-06-02T16:22:33.819953664Z     /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/edge.go:809 +0x31f
2021-06-02T16:22:33.819959726Z github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*edge).unpark(0xc00b91f2c0, 0xc001fc7c80, 0x1, 0x1,
 0xc001fc7ca0, 0x1, 0x1, 0xc001fc7c90, 0x1, 0x1, ...)
2021-06-02T16:22:33.819972038Z     /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/edge.go:360 +0x17b
2021-06-02T16:22:33.819977108Z github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc0009a5110, 0xc00b91f2c0)
2021-06-02T16:22:33.819981787Z     /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:136 +0x432
2021-06-02T16:22:33.819986485Z github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).loop(0xc0009a5110)
2021-06-02T16:22:33.820008977Z     /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:104 +0x17b
2021-06-02T16:22:33.820013585Z created by github.com/docker/docker/vendor/github.com/moby/buildkit/solver.newScheduler
2021-06-02T16:22:33.820017703Z     /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:35 +0x1ad
```

**Comment by JoseAlvarezSonos** [comment]
We have the exact same issue, in the almost exact same setup (K8s, Jenkins CI, parallel builds):

dind panic: failed to get edge
dind
dind goroutine 226 [running]:
dind github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*pipeFactory).NewInputRequest(0xc001fbbef8, 0x0, 0x31c8c00, 0xc00157f3c0, 0xc011196ec0, 0xc000c3be28, 0xc015bf6930)
dind 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:350 +0x1fe
dind github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*edge).createInputRequests(0xc000c3ba40, 0x3, 0xc001fbbef8, 0x0, 0x45cda00)
dind 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/edge.go:809 +0x31f
dind github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*edge).unpark(0xc000c3ba40, 0xc016710e70, 0x1, 0x1, 0xc001fbbe48, 0x0, 0x0, 0x45cda00, 0x0, 0x0, ...)
dind 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/edge.go:360 +0x17b
dind github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc00029a380, 0xc000c3ba40)
dind 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:136 +0x432
dind github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).loop(0xc00029a380)
dind 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:104 +0x17b
dind created by github.com/docker/docker/vendor/github.com/moby/buildkit/solver.newScheduler
dind 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:35 +0x1ad

My only suspicion is that we are using buildkit cache and JFrog Artifactory, and I've heard some issues related to that, but still not sure if that's the real issue here. Any updates? Ideas? Suggestions?

**Comment by griffous** [comment]
We're also seeing this same issue using the most recently published `master` container
Buildkit container version: `master` (as at 3rd August)
Docker: `20.10.7` (native, not DinD)
Registry: Jfrog Artifactory

Very large parallel build (bake, and ~50 targets), with multiple `cache_from:` for each.

```
time="2021-08-03T07:38:30Z" level=warning msg="failed to update distribution source for layer sha256:f2c1838b1bf6f194200b3ecb16e6e23da1715bb3cf472ec7dfadd4a6f89aa7fa: content digest sha256:f2c1838b1bf6f194200b3ecb16e6e23da1715bb3cf472ec7dfadd4a6f89aa7fa: not found"
panic: failed to get edge

goroutine 65 [running]:
github.com/moby/buildkit/solver.(*pipeFactory).NewInputRequest(0xc008d13f18, 0x0, 0x16aedb8, 0xc001c0eec0, 0xc003e34640, 0xc008203e28, 0xc00610b680)
	/src/solver/scheduler.go:354 +0x24b
github.com/moby/buildkit/solver.(*edge).createInputRequests(0xc0076c0280, 0x3, 0xc008d13f18, 0x0, 0xc00ac0b3f0)
	/src/solver/edge.go:809 +0x328
github.com/moby/buildkit/solver.(*edge).unpark(0xc0076c0280, 0xc00ac0b3e0, 0x1, 0x1, 0xc00ac0b400, 0x1, 0x1, 0xc00ac0b3f0, 0x1, 0x1, ...)
	/src/solver/edge.go:360 +0x17a
github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc0003a0930, 0xc0076c0280)
	/src/solver/scheduler.go:136 +0x425
github.com/moby/buildkit/solver.(*scheduler).loop(0xc0003a0930)
	/src/solver/scheduler.go:104 +0x168
created by github.com/moby/buildkit/solver.newScheduler
	/src/solver/scheduler.go:35 +0x1b3
```

**Comment by Antiarchitect** [comment]
I believe somewhere here: https://github.com/moby/buildkit/blob/06e8602caa280ca2ff1225ea0218456c845fc485/solver/edge.go#L809
There `e.edge.Vertex.Inputs()[int(dep.index)]` is nil.

**Comment by thaJeztah** [comment]
I think this was fixed in current version. 
Let me close this ticket for now, as it looks like it went stale.
