### ISSUE TITLE
panic in TestConcurrencyWithWait

### ISSUE THREAD

**Issue by charlesxsh** [moby/moby#42696]
**Description**
TestConcurrencyWithWait has panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5a383a]

goroutine 16 [running]:
github.com/docker/docker/libnetwork/iptables.(*ChainInfo).Forward(0x0, 0x60c248, 0x2, 0xc00001c390, 0x10, 0x10, 0x4d2, 0x60c3d5, 0x3, 0x60d950, ...)
        /go/src/github.com/docker/docker/libnetwork/iptables/iptables.go:297 +0x3a
github.com/docker/docker/libnetwork/iptables.RunConcurrencyTest.func2(0x0, 0x0)
        /go/src/github.com/docker/docker/libnetwork/iptables/iptables_test.go:213 +0xba
github.com/docker/docker/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000022b40, 0xc000012500)
        /go/src/github.com/docker/docker/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by github.com/docker/docker/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /go/src/github.com/docker/docker/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```
**Steps to reproduce the issue:**
```
go test -run TestConcurrencyWithWait github.com/docker/docker/libnetwork/iptables
```
**Describe the results you received:**
panic

**Describe the results you expected:**
test should pass

**Additional information you deem important (e.g. issue happens only occasionally):**

go version go1.16.5 linux/amd64

**Comment by ch33hau** [comment]
Hi @thaJeztah , I have created a PR for this issue, other tests are using the shared variables that were only initiated once in the first test, that's why they are panicked. 

Appreciate it if you could take a look =)
