### ISSUE TITLE
Docker daemon stuck in activating state and unlimited memory increase after abnormal power failure

### ISSUE THREAD

**Issue by lyyao09** [moby/moby#43072]
**Description**
Docker daemon stuck in activating state and unlimited memory increase after abnormal power failure.
```
[root@node01 docker]# service docker status
Redirecting to /bin/systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─restart.conf
   Active: activating (start) since Tue 2021-12-07 15:44:32 CST; 1min 18s ago
     Docs: https://docs.docker.com
 Main PID: 274797 (dockerd)
    Tasks: 481
   Memory: 15.4G  // abnormal
   CGroup: /system
```

Eventually, node memory resources will be exhausted, and docker daemon was killed by oom and continue starting...
```
[root@node01 docker]# service docker status
Redirecting to /bin/systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─restart.conf
   Active: deactivating (stop-sigterm)
     Docs: https://docs.docker.com
 Main PID: 274797 (dockerd)
    Tasks: 481
   Memory: 247.3G   // increasing
   CGroup: /system.slice/docker.service
           └─274
```

**Steps to reproduce the issue:**
1.Start the node after abnormal power failure, and no necessary conditions were found.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@node01files]# docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
[root@node01 files]# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 67
  Running: 62
  Paused: 0
  Stopped: 5
 Images: 49
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
   seccomp
   Profile: default
 Kernel Version: 3.10.0-957.21.3.el7.x86_64
 Operating System: CentOS 7.6
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 256GiB
 Name: node01
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
  File Descriptors: 366
  Goroutines: 290
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

goroutine info:
```
goroutine 1 [runnable]:
github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).List.func1(0xc000c0b7a0, 0xc000968200, 0xc000c0b7a0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:292 +0x236
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).View(0xc000931e00, 0xc0009683f8, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:725 +0xaa
github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).List(0xc007951950, 0xc00356e600, 0x5e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:279 +0x1b3
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*cache).kmap(0xc00793a300, 0x5621330cf1a0, 0xc003544580, 0x0, 0x5e, 0xc00356e540)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/cache.go:43 +0x286
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*cache).list(0xc00793a300, 0x5621330cf1a0, 0xc003544580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/cache.go:164 +0x7e
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).List(0xc0034002c0, 0xc00356e540, 0x5e, 0x5621330cf1a0, 0xc003544580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:517 +0x205
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).getEndpointsFromStore(0xc002186540, 0xc0033c93d8, 0x7, 0x5621330c9920, 0xc0035197a0, 0xc0033c913e)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:190 +0x343
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).reservePools(0xc001319600)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:977 +0x4c1
github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc000c41780, 0x9, 0x10, 0xc000846300, 0xc00213db00, 0xc000c41780, 0x9)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:245 +0x615
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c1e0, 0xc0001e9080, 0xc00213db00, 0xc000f50000, 0xc00000c1e0, 0xc0006f6ee8, 0xc00213db00)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:855 +0xa9
github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c1e0, 0xc0001d7ac0, 0xc0001fe0e0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:490 +0x50b
github.com/docker/docker/daemon.NewDaemon(0x5621330a14c0, 0xc0001d7ac0, 0xc0001e9080, 0xc000846300, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:1147 +0x2be8
main.(*DaemonCli).start(0xc000886060, 0xc000992420, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x743
main.runDaemon(...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
main.newDaemonCommand.func1(0xc0001d02c0, 0xc000886000, 0x0, 0x3, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7c
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001d02c0, 0xc00004e0d0, 0x3, 0x3, 0xc0001d02c0, 0xc00004e0d0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d02c0, 0x0, 0x0, 0x10)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x191
```
The error occurred in the following call chain:
```
NewDaemon —> restore() —>initNetworkController —> libnetwork.New(netOptions...) —> c.reservePools() —>  n.getEndpointsFromStore() —> store.List —> ds.cache.list(kvObject) —> c.kmap(kvObject) —> c.ds.store.List(keyPrefix) 
```

Finally error location:
```
// List returns the range of keys starting with the passed in prefix
func (b *BoltDB) List(keyPrefix string) ([]*store.KVPair, error) {
	var (
		db  *bolt.DB
		err error
	)
	b.Lock()
	defer b.Unlock()

	kv := []*store.KVPair{}

	if db, err = b.getDBhandle(); err != nil {
		return nil, err
	}
	defer b.releaseDBhandle()

	err = db.View(func(tx *bolt.Tx) error {
		bucket := tx.Bucket(b.boltBucket)
		if bucket == nil {
			return store.ErrKeyNotFound
		}

		cursor := bucket.Cursor()
		prefix := []byte(keyPrefix)

		for key, v := cursor.Seek(prefix); bytes.HasPrefix(key, prefix); key, v = cursor.Next() {

			dbIndex := binary.LittleEndian.Uint64(v[:libkvmetadatalen])
			v = v[libkvmetadatalen:]
			val := make([]byte, len(v))    // finally, an error is reported here
			copy(val, v)

			kv = append(kv, &store.KVPair{
				Key:       string(key),
				Value:     val,
				LastIndex: dbIndex,
			})
		}
		return nil
	})
	if len(kv) == 0 {
		return nil, store.ErrKeyNotFound
	}
	return kv, err
}
```

So, under what circumstances will the memory request cycle here?

**Comment by thaJeztah** [comment]
Could possibly be corruption of that boltdb database 🤔. If that is ` /var/lib/docker/network/files/local-kv.db`, then I  _think_ that file can be deleted, and it will be regenerated when docker is started again (also see, e.g. https://github.com/moby/moby/issues/34370, and possibly some other tickets mentioning that file). But it won't hurt to keep a copy of it 😅 (I'm not too familiar with that code, or at least, would have to dive into it)

**Comment by lyyao09** [comment]
@thaJeztah Thanks for your prompt reply. Deleting the db file is indeed a recovery method, I‘m wondering if the problem can be found in advance and throw error instead of eating memory all the time?

**Comment by thaJeztah** [comment]
>  I‘m wondering if the problem can be found in advance and throw error instead of eating memory all the time?

That's a good question. So, we use the `boltdb` project/library for that database file; perhaps that provides some "integrity check" feature (I haven't worked much with the library myself, and have never looked). Question is of course if such an integrity check would detect the problem _without_ also ending in some loop (and memory consumption), but it's worth looking for.

If you (or someone else arriving here) are interested in doing some research in that area; the original implementation of `boltdb` was in https://github.com/boltdb/bolt (in case there's discussions around this in that issue tracker), but that's no longer maintained, and work has moved to https://github.com/etcd-io/bbolt.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
