### ISSUE TITLE
Docker runs well but the docker command will get "Unexpected fault address" (`github.com/docker/cli/cli/command.ShowHelp.func1`)

### ISSUE THREAD

**Issue by dyoueco** [moby/moby#43102]
My docker run with docker-compose and all the containers run well. But when I send any docker related command even docker command without any parameters I got the "Unexpected fault address"

**Steps to reproduce the issue:**
1. send "docker ps" or "docker" 
2. It fails with msg listed below
3.

**Describe the results you received:**

```
unexpected fault address 0x55c4454038c0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x55c4454038c0 pc=0x55c4454038c0]

goroutine 1 [running]:
runtime.throw(0x55c44ca2fbe9, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x74 fp=0xc0005b78c8 sp=0xc0005b7898 pc=0x55c44b42cb34
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:741 +0x285 fp=0xc0005b7900 sp=0xc0005b78c8 pc=0x55c44b443a45
text/template/parse.New(...)
	/usr/local/go/src/text/template/parse/parse.go:131
text/template/parse.Parse(0x55c44ca2e6a6, 0x3, 0x55c44caa88d9, 0x3b, 0x0, 0x0, 0x0, 0x0, 0xc000460130, 0x2, ...)
	/usr/local/go/src/text/template/parse/parse.go:63 +0x45 fp=0xc0005b7988 sp=0xc0005b7900 pc=0x55c44ba0ae85
text/template.(*Template).Parse(0xc00014c680, 0x55c44caa88d9, 0x3b, 0xc000182100, 0xc0005b7ae0, 0x55c44ba396f2)
	/usr/local/go/src/text/template/template.go:210 +0x825 fp=0xc0005b7a98 sp=0xc0005b7988 pc=0x55c44ba2be65
github.com/docker/cli/vendor/github.com/spf13/cobra.tmpl(0x55c44d0b7398, 0xc000010020, 0x55c44caa88d9, 0x3b, 0x55c44d08cba0, 0xc0000e4b00, 0xc0000e4b00, 0xc0005b7b00)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/cobra.go:160 +0x92 fp=0xc0005b7af0 sp=0xc0005b7a98 pc=0x55c44ba312d2
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).HelpFunc.func1(0xc0000e4b00, 0x55c44deaaa30, 0x0, 0x0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:396 +0xbb fp=0xc0005b7b60 sp=0xc0005b7af0 pc=0x55c44ba3f1fb
main.setHelpFunc.func1(0xc0000e4b00, 0x55c44deaaa30, 0x0, 0x0)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:166 +0x28c fp=0xc0005b7be8 sp=0xc0005b7b60 pc=0x55c44ca288ac
github.com/docker/cli/cli/command.ShowHelp.func1(0xc0000e4b00, 0x55c44deaaa30, 0x0, 0x0, 0x55c44ba3f4a0, 0xc0005b7c48)
	/go/src/github.com/docker/cli/cli/command/cli.go:121 +0x83 fp=0xc0005b7c18 sp=0xc0005b7be8 pc=0x55c44ba4c603
main.newDockerCommand.func1(0xc0000e4b00, 0x55c44deaaa30, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:44 +0x78 fp=0xc0005b7c70 sp=0xc0005b7c18 pc=0x55c44ca280f8
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000e4b00, 0x55c44deaaa30, 0x0, 0x0, 0xc0000e4b00, 0x55c44deaaa30)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x472 fp=0xc0005b7d30 sp=0xc0005b7c70 pc=0x55c44ba34ef2
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e4b00, 0xc00043d860, 0xc0000e4b00, 0x55c44deaaa30)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x375 fp=0xc0005b7e10 sp=0xc0005b7d30 pc=0x55c44ba35a75
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc00043d860, 0x55c44d0b7398, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1eb fp=0xc0005b7ef8 sp=0xc0005b7e10 pc=0x55c44ca26b2b
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xfc fp=0xc0005b7f88 sp=0xc0005b7ef8 pc=0x55c44ca26e3c
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x263 fp=0xc0005b7fe0 sp=0xc0005b7f88 pc=0x55c44b42f3a3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005b7fe8 sp=0xc0005b7fe0 pc=0x55c44b463ac1

goroutine 19 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x55c44de7b1e0)
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:1010 +0x8d
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:411 +0xd8
```

**Describe the results you expected:**

```
CONTAINER ID   IMAGE               COMMAND                  CREATED        STATUS      PORTS                                                                                  NAMES
b9242a59071c   eclipse-mosquitto   "/docker-entrypoint.…"   6 months ago   Up 6 days   0.0.0.0:1883->1883/tcp, :::1883->1883/tcp, 0.0.0.0:9001->9001/tcp, :::9001->9001/tcp   mqtt
9d63fd43f946   kylemanna/openvpn   "ovpn_run"               9 months ago   Up 6 days   0.0.0.0:1194->1194/udp, :::1194->1194/udp                                              openvpn
57e580d915c7   mysql               "docker-entrypoint.s…"   9 months ago   Up 6 days   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                   dbRaw
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I have stopped docker and rm the files in /var/run/docker and related docker files but get the same result after start docker
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It's physical server

**Comment by AkihiroSuda** [comment]
Please provide the version of Docker, and how you installed it

**Comment by dyoueco** [comment]
The docker version is : 
20.10.12 Community version
I installed docker via command:
sudo curl -fsSL https://get.docker.com/ | sh

Host OS and version: Ubuntu with 20.04.03

CPU arch: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz

**Comment by kaffarell** [comment]
I think you should move this issue to the docker/cli repository because it seems it only regards the cli interface.

**Comment by dyoueco** [comment]
I see. Tks.
