### ISSUE TITLE
An error "No error following JSON procError payload" occurred when starting the container with --security-opt seccomp

### ISSUE THREAD

**Issue by ZxyNull0** [moby/moby#43730]
**Description**
I got an error when starting the container with the seccomp option. I would have liked to test which syscalls are used by the ping command and impose restrictions on the container by catching the syscalls.
Dockerfile is as follows
```Dockerfile
FROM alpine:latest
CMD ["ping","-c5","8.8.8.8"]
```
seccomp_ping.json
```json
{
  "defaultAction": "SCMP_ACT_ERRNO",
  "architectures": [
    "SCMP_ARCH_X86_64",
    "SCMP_ARCH_X86",
    "SCMP_ARCH_X32"
  ],
  "syscalls": [
    {
      "names": [
        "arch_prctl",
        "bind",
        "clock_gettime",
        "clone",
        "close",
        "connect",
        "dup2",
        "epoll_pwait",
        "execve",
        "exit",
        "exit_group",
        "fcntl",
        "futex",
        "getpid",
        "getsockname",
        "getuid",
        "ioctl",
        "mprotect",
        "nanosleep",
        "open",
        "poll",
        "read",
        "recvfrom",
        "rt_sigaction",
        "rt_sigprocmask",
        "rt_sigreturn",
        "sendto",
        "set_tid_address",
        "setitimer",
        "setsockopt",
        "socket",
        "write",
        "writev"
      ],
      "action": "SCMP_ACT_ALLOW"
    }
  ]
}
```

**Steps to reproduce the issue:**
1.Build image and run it,it would be fail.
```bash
$ sudo docker build -t pingtest .
$ sudo docker run --rm -it --security-opt seccomp=seccomp_ping.json pingtest
docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc did not terminate successfully: exit status 2: panic: No error following JSON procError payload.

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.parseSync(0x56551adf30b8, 0xc000010b20, 0xc0002268a0, 0xc00027f9e0, 0x0)
        github.com/opencontainers/runc/libcontainer/sync.go:93 +0x307
github.com/opencontainers/runc/libcontainer.(*initProcess).start(0xc000297cb0, 0x0, 0x0)
        github.com/opencontainers/runc/libcontainer/process_linux.go:440 +0x5ef
github.com/opencontainers/runc/libcontainer.(*linuxContainer).start(0xc000078700, 0xc000209680, 0x0, 0x0)
        github.com/opencontainers/runc/libcontainer/container_linux.go:379 +0xf5
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Start(0xc000078700, 0xc000209680, 0x0, 0x0)
        github.com/opencontainers/runc/libcontainer/container_linux.go:264 +0xb4
main.(*runner).run(0xc0002274c8, 0xc0000200f0, 0x0, 0x0, 0x0)
        github.com/opencontainers/runc/utils_linux.go:312 +0xd2a
main.startContainer(0xc00025c160, 0xc000076400, 0x1, 0x0, 0x0, 0xc0002275b8, 0x6)
        github.com/opencontainers/runc/utils_linux.go:455 +0x455
main.glob..func2(0xc00025c160, 0xc000246000, 0xc000246120)
        github.com/opencontainers/runc/create.go:65 +0xbb
github.com/urfave/cli.HandleAction(0x56551ad3b040, 0x56551ade81e8, 0xc00025c160, 0xc00025c160, 0x0)
        github.com/urfave/cli@v1.22.1/app.go:523 +0x107
github.com/urfave/cli.Command.Run(0x56551aa566f5, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x56551aa5f509, 0x12, 0x0, ...)
        github.com/urfave/cli@v1.22.1/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc000254000, 0xc000132000, 0xf, 0xf, 0x0, 0x0)
        github.com/urfave/cli@v1.22.1/app.go:276 +0x7e8
main.main()
        github.com/opencontainers/runc/main.go:163 +0xd3f
: unknown.
```

**Describe the results you received:**

Look up 
**Describe the results you expected:**
Works fine without using seccomp
```bash
$ sudo docker run --rm -it pingtest
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=127 time=42.139 ms
64 bytes from 8.8.8.8: seq=1 ttl=127 time=42.646 ms
64 bytes from 8.8.8.8: seq=2 ttl=127 time=42.098 ms
64 bytes from 8.8.8.8: seq=3 ttl=127 time=42.484 ms
64 bytes from 8.8.8.8: seq=4 ttl=127 time=42.007 ms

--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 42.007/42.274/42.646 ms
```
If it is because the system call does not meet the normal operation,Shouldn't the error be like this?
```
starting container process caused: close exec fds: open /proc/self/fd: operation not permitted: unknown.
```
After I execute the same command many times, the error sometimes becomes `operation not permitted: unknown`，sometimes it will become`panic: No error following JSON procError payload`.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:07:52 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:41 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 49
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-113-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.741GiB
 Name: ubuntu
 ID: ST25:BXLH:DEYW:VVCG:HDNG:RODU:YZTI:ZGFM:DKTO:Y4AZ:HN5G:K4UG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://127.0.0.1:7890
 HTTPS Proxy: http://127.0.0.1:7890
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://hub-mirror.c.163.com/
  https://docker.mirrors.ustc.edu.cn/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Looks like the error is coming from runc 🤔 I see you're running an older version of containerd and runc; are you still able to reproduce this on the current version?

**Comment by ZxyNull0** [comment]
> Looks like the error is coming from runc 🤔 I see you're running an older version of containerd and runc; are you still able to reproduce this on the current version?

Yes，But not every execution can be triggered, multiple executions may trigger once. like this
![1655711183899](https://user-images.githubusercontent.com/81354529/174552039-c5b91c5c-4121-463f-9fe5-27986e8ad1c2.png)
.

**Comment by thaJeztah** [comment]
Translating the locations of the trace to the v1.1.3 runc release

https://github.com/opencontainers/runc/blob/v1.1.3/libcontainer/sync.go#L118
https://github.com/opencontainers/runc/blob/v1.1.3/libcontainer/process_linux.go#L460
https://github.com/opencontainers/runc/blob/v1.1.3/libcontainer/container_linux.go#L354
https://github.com/opencontainers/runc/blob/v1.1.3/libcontainer/container_linux.go#L239
https://github.com/opencontainers/runc/blob/v1.1.3/utils_linux.go#L289
https://github.com/opencontainers/runc/blob/v1.1.3/utils_linux.go#L429
https://github.com/opencontainers/runc/blob/v1.1.3/create.go#L65
...
https://github.com/opencontainers/runc/blob/v1.1.3/main.go#L163

The panic is triggered here; https://github.com/opencontainers/runc/blob/v1.1.3/libcontainer/sync.go#L118

```go
		// We handle this case outside fn for cleanliness reasons.
		var ierr *initError
		if sync.Type == procError {
			if err := dec.Decode(&ierr); err != nil && !errors.Is(err, io.EOF) {
				return fmt.Errorf("error decoding proc error from init: %w", err)
			}
			if ierr != nil {
				return ierr
			}
			// Programmer error.
			panic("No error following JSON procError payload.")
```

Your last stack-trace still seems to be based on an older version of runc though? (v1.0.x, not v1.1.x ?), based on this line in the trace (which moved to line 460 in later versions);

```
github.com/opencontainers/runc/libcontainer/process_linux.go:440 +0x5ef
```

I tried reproducing the panic, but so far haven't been able to; that said, I'm wondering if the code should produce a panic in that case, or if an error should be enough (not the root cause, but to prevent the panic from happening)?
