### ISSUE TITLE
docker swarm hang

### ISSUE THREAD

**Issue by pigwow** [moby/moby#43791]
### Description

All commands related to docker swarm do not respond.

### Reproduce

After node A is added to the cluster, all requests for invoking docker.swarmkit.v1.Control on node A do not respond.

goroutine 6334162 [select]:
github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc006a1a000)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/transport.go:312 +0x85
github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/transport.go:331
github.com/docker/docker/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc005e55500, {0x564c59625360, 0xc005a3c390}, 0x0)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:871 +0xba
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0x2)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:736 +0x25
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc004cee240, 0xc005ecca20, 0xc005ecc9f0)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:594 +0xd3
github.com/docker/docker/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc004cee240, {0x564c59625360, 0xc005a3c390})
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:735 +0x11f
github.com/docker/docker/vendor/google.golang.org/grpc.invoke({0x564c59792188, 0xc005693500}, {0x564c58f9c984, 0xc0006a0000}, {0x564c59625160, 0xc000011788}, {0x564c59625360, 0xc005a3c390}, 0x564c579c1b01, {0xc007430c40, ...})
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:73 +0xd7
github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ClientMetrics).UnaryClientInterceptor.func1({0x564c59792188, 0xc005693500}, {0x564c58f9c984, 0x25}, {0x564c59625160, 0xc000011788}, {0x564c59625360, 0xc005a3c390}, 0x564c5a777fa0, 0x564c5970d948, ...)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_metrics.go:112 +0x117
github.com/docker/docker/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc000957c00, {0x564c59792188, 0xc005693500}, {0x564c58f9c984, 0x25}, {0x564c59625160, 0xc000011788}, {0x564c59625360, 0xc005a3c390}, {0xc00148ec10, ...})
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:35 +0x21f
github.com/docker/docker/vendor/google.golang.org/grpc.Invoke(...)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/google.golang.org/grpc/call.go:60
github.com/docker/docker/vendor/github.com/docker/swarmkit/api.(*controlClient).ListNodes(0xc00029a4d8, {0x564c59792188, 0xc005693500}, 0xc00029a4d8, {0xc00148ec10, 0x1, 0x1})
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/api/control.pb.go:3128 +0xc9
github.com/docker/docker/daemon/cluster.(*Cluster).GetNodes(0xc000285440, {{0x0}})
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/daemon/cluster/nodes.go:32 +0x2b3
github.com/docker/docker/api/server/router/swarm.(*swarmRouter).getNodes(0xc0020547e0, {0x24ab44312b06349f, 0xc00558f4d0}, {0x564c59763c60, 0xc0065940e0}, 0xc006ca7f00, 0xc0052c1600)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/api/server/router/swarm/cluster_routes.go:308 +0xc2
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1({0x564c597921c0, 0xc0066d12c0}, {0x564c59763c60, 0xc0065940e0}, 0x564c5939d020, 0xc00148ebd0)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0x15b
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1({0x564c597921c0, 0xc0066d1290}, {0x564c59763c60, 0xc0065940e0}, 0x203001, 0x40)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x4d8
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1({0x564c597921c0, 0xc0066d1290}, {0x564c59763c60, 0xc0065940e0}, 0xc006ca7f00, 0xc00148eb80)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x664
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1({0x564c59763c60, 0xc0065940e0}, 0xc006ca7e00)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/api/server/server.go:142 +0x2fa
net/http.HandlerFunc.ServeHTTP(0xc006ca7c00, {0x564c59763c60, 0xc0065940e0}, 0x564c596da300)
        /opt/buildtools/golang_go-1.17.5/src/net/http/server.go:2047 +0x2f
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0013be300, {0x564c59763c60, 0xc0065940e0}, 0xc006ca7b00)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:212 +0x202
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0x0, {0x564c59763c60, 0xc0065940e0}, 0x564c57a1bc90)
        /usr1/workspace/docker_x86_build/build/BUILD_TMP/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x9e
net/http.serverHandler.ServeHTTP({0xc0066d1110}, {0x564c59763c60, 0xc0065940e0}, 0xc006ca7b00)
        /opt/buildtools/golang_go-1.17.5/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc002101220, {0x564c597921c0, 0xc006881200})
        /opt/buildtools/golang_go-1.17.5/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /opt/buildtools/golang_go-1.17.5/src/net/http/server.go:3034 +0x4e8

### docker version

```bash
Version:           19.03.15
```

### docker info

```bash
docker info No response
```

**Comment by sam-thibault** [comment]
Version 19.03 has reached end of life.  Are you able to reproduce this on a newer version?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
