### ISSUE TITLE
Docker daemon crashes when pulling specific image

### ISSUE THREAD

**Issue by borgdb** [moby/moby#44074]
### Description

Pulling image `rancher/hyperkube:v1.22.7-rancher1` causes the pull to fail with `unexpected EOF` while extracting one of the layers, caused by dockerd crashing with error `panic: runtime error: makeslice: cap out of range`. It always crashes on the same layer, but not always at the same extracted size. And very rarely, the command succeeds.

docker pull output (related docker debug logs attached below):
```
v1.22.7-rancher1: Pulling from rancher/hyperkube
24496884391b: Already exists
f435b93609c6: Pull complete
92aff9d29613: Pull complete
07f825930b1c: Pull complete
89a49db15eff: Pull complete
d900046171d5: Pull complete
f130a99965b2: Pull complete
205522516f87: Extracting [=======>                                           ]  39.55MB/275.4MB
53b182af9ba7: Download complete
bde2d4b856c8: Download complete
47f7a04c83d5: Download complete
unexpected EOF
```

Any ideas what could be causing this? Tried pulling a random large image (slightlytyler/large-image-test:latest) but that was successful.

### Reproduce

sudo docker pull rancher/hyperkube:v1.22.7-rancher1

### Expected behavior

docker pull should be successful, with output similar to 

```
Digest: sha256:75c5647f811204526fc6f8f17703a284d9235d96498bd27469dc988fa06884f2
Status: Downloaded newer image for rancher/hyperkube:v1.22.7-rancher1
docker.io/rancher/hyperkube:v1.22.7-rancher1
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-46-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.763GiB
 Name: HOSTNAME
 ID: HSKQ:IQRV:ULG4:RKTV:WRDK:754R:EYQO:TUM7:JSER:RWLI:KZQ2:WUFA
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 24
  Goroutines: 34
  System Time: 2022-09-01T11:35:29.537221897+03:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

[docker_debug_logs.txt](https://github.com/moby/moby/files/9468180/docker_debug_logs.txt)

**Comment by thaJeztah** [comment]
Thanks for reporting!

Hmm.. interesting, so the trace is below (I temored the timstamps for readability);

```
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:22.767640160+03:00" level=debug msg="pulling blob \"sha256:205522516f8791e4c9e876fe5c8672b1f0b3ff336cd867da543b622514eb8ee2\""
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:22.768034744+03:00" level=debug msg="pulling blob \"sha256:bde2d4b856c854c5272fd4ee4279f4d9218e38d220957932cfb92f335a215515\""
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:22.767653389+03:00" level=debug msg="pulling blob \"sha256:53b182af9ba728c9000d626f6ccd303c18e9a8c9f5ed2a487b902caec3277bde\""
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:23.262100665+03:00" level=debug msg="Downloaded 53b182af9ba7 to tempfile /var/lib/docker/tmp/GetImageBlob419903003"
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:23.262322425+03:00" level=debug msg="pulling blob \"sha256:47f7a04c83d59d4a0b9bcb971d67223081923018dc8c2c01e75629610a47fbcb\""
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:24.370704283+03:00" level=debug msg="Downloaded bde2d4b856c8 to tempfile /var/lib/docker/tmp/GetImageBlob296590819"
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:26.151476363+03:00" level=debug msg="Downloaded 47f7a04c83d5 to tempfile /var/lib/docker/tmp/GetImageBlob1013125662"
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:27.558019691+03:00" level=debug msg="Downloaded 205522516f87 to tempfile /var/lib/docker/tmp/GetImageBlob367089950"
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:27.559056445+03:00" level=debug msg="Using /usr/bin/unpigz to decompress"
HOSTNAME dockerd[30078]: time="2022-09-01T10:33:27.560274572+03:00" level=debug msg="Applying tar in /var/lib/docker/overlay2/5ceefcf8c43fea1b691a67a246d88cdd678f89837f936a8fe905ea5ff4ed44ba/diff" storage-driver=overlay2
HOSTNAME dockerd[30078]: panic: runtime error: makeslice: cap out of range
HOSTNAME dockerd[30078]: goroutine 363 [running]:
HOSTNAME dockerd[30078]: io.copyBuffer({0x7f10284f01c0, 0xc0009f11c0}, {0x56541bc4aca0, 0xc0006e6000}, {0x0, 0x0, 0x0})
HOSTNAME dockerd[30078]:         /usr/local/go/src/io/io.go:420 +0x117
HOSTNAME dockerd[30078]: io.Copy(...)
HOSTNAME dockerd[30078]:         /usr/local/go/src/io/io.go:382
HOSTNAME dockerd[30078]: github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/storage.(*bitBucketFilePutter).Put(0x2, {0x0, 0x0}, {0x56541bc4aca0, 0xc0006e6000})
HOSTNAME dockerd[30078]:         /go/src/github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/storage/getter.go:99 +0xa5
HOSTNAME dockerd[30078]: github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/asm.NewInputTarStream.func1()
HOSTNAME dockerd[30078]:         /go/src/github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go:87 +0x223
HOSTNAME dockerd[30078]: created by github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/asm.NewInputTarStream
HOSTNAME dockerd[30078]:         /go/src/github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go:45 +0x2b0
HOSTNAME systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

The issue starts around this line; https://github.com/moby/moby/blob/a89b84221c8560e7a3dee2a653353429e7628424/vendor/github.com/vbatts/tar-split/tar/storage/getter.go#L98

Which uses `CRCTable`, which is defined a couple of lines below that; https://github.com/moby/moby/blob/a89b84221c8560e7a3dee2a653353429e7628424/vendor/github.com/vbatts/tar-split/tar/storage/getter.go#L103-L104

- I had a look at the `CRCTable` to double-check if it wasn't overwritten anywhere, but that doesn't appear to be the case.
- The value for the `crc64.ISO` const also wasn't updated recently; last update in Go was 13 Years ago in https://github.com/golang/go/commit/1a5cd2c0e1809c600e73f9895abc07c14156f7c1 (go 1.0)


The only thing I see is that tar-split has a newer release available; https://github.com/vbatts/tar-split/compare/v0.11.1...v0.11.2

At a glance, I don't see changes to this code, but possibly this fix could be related (but doesn't mention an error / bug related) https://github.com/vbatts/tar-split/commit/8d76363085552a669042fe2912160843d0d3766b (https://github.com/vbatts/tar-split/pull/54).

Continuing; we then get to the go stdlib and runtime;

https://github.com/golang/go/blob/26cdea3acca29db94541236f0037a20aa22ce2d7/src/io/io.go#L381-L382

```go
func Copy(dst Writer, src Reader) (written int64, err error) {
    return copyBuffer(dst, src, nil)
}
```

In `io.copyBuffer`, we end up in this code path;

```go
	if buf == nil {
		size := 32 * 1024
		if l, ok := src.(*LimitedReader); ok && int64(size) > l.N {
			if l.N < 1 {
				size = 1
			} else {
				size = int(l.N)
			}
		}
		buf = make([]byte, size)
```

The last line of the above is where the `panic: runtime error: makeslice: cap out of range` seems to be triggered; https://github.com/golang/go/blob/26cdea3acca29db94541236f0037a20aa22ce2d7/src/io/io.go#L420

```go
buf = make([]byte, size)
```

https://github.com/golang/go/blob/26cdea3acca29db94541236f0037a20aa22ce2d7/src/runtime/slice.go#L83-L95

```go
func makeslice(et *_type, len, cap int) unsafe.Pointer {
	mem, overflow := math.MulUintptr(et.size, uintptr(cap))
	if overflow || mem > maxAlloc || len < 0 || len > cap {
		// NOTE: Produce a 'len out of range' error instead of a
		// 'cap out of range' error when someone does make([]T, bignumber).
		// 'cap out of range' is true too, but since the cap is only being
		// supplied implicitly, saying len is clearer.
		// See golang.org/issue/4085.
		mem, overflow := math.MulUintptr(et.size, uintptr(len))
		if overflow || mem > maxAlloc || len < 0 {
			panicmakeslicelen()
		}
		panicmakeslicecap()
```

Which comes from https://github.com/golang/go/blob/26cdea3acca29db94541236f0037a20aa22ce2d7/src/runtime/slice.go#L30-L32

```go
func panicmakeslicecap() {
	panic(errorString("makeslice: cap out of range"))
}
```

I wonder if it could also be a bug in Go :thinking: 20.10.17 was compiled with go1.17.11, and there's been two patch releases for 1.17 since; https://github.com/golang/go/compare/go1.17.11...go1.17.13

I do see some changes in go that went in after go1.17; https://github.com/golang/go/commits/go1.19/src/runtime/slice.go

- https://github.com/golang/go/commit/4efa216c9d753c0853aa96a8c54ed5014fbc12e6
- https://github.com/golang/go/commit/40f82f8a092ac1f23eb3af86f34b7436a6fc19e0

**Comment by borgdb** [comment]
Yep the makeslice function was as far as I got, and if I understood correctly, `make([]byte, size)` would have to somehow cause the condition `len > cap` to be true in order to trigger that specific error - which I couldn't see how.

After digging further, the issue was happening on all (4) virtual machines running on a specific ESXI host. I was unable to replicate the issue again after moving the VMs to a different ESXI host. I will investigate further & update, but at this point it looks unlikely to be an issue with Moby.

**Comment by sam-thibault** [comment]
Thanks for the update.  I will close the issue for now based on your comment.
