### ISSUE TITLE
Netflows is corrupted under Windows Server 2019

### ISSUE THREAD

**Issue by jcarnus** [moby/moby#44225]
### Description

Hi,
We have a docker (running a java app under jetty) which is streaming ZIP file. While the Jetty webserver works perfectly when installed on Windows Server 2019, when it run under a docker (expose to -p 80:80), the downloaded zip file got corrupted. This reproduce like 5% of the time. I have tested docker 20.10.0 to 20.10.13 and the bug remains.

I notice the same type of net flows corruption when using another docker running nginx. (leading to client producing such type of stack:
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620) ~[sunjce_provider.jar:1.8.0_342]
at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)

### Reproduce

Run a docker serving big file under Windows Server 2019 and compare the output.

### docker version

```bash
Client: Mirantis Container Runtime
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        6ee42dc
 Built:             03/11/2021 13:24:56
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       1e08f21e79
  Built:            03/11/2021 13:23:32
  OS/Arch:          windows/amd64
  Experimental:     false
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Docker Buildx (Docker Inc., v0.8.2-tp-docker)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 34
 Server Version: 20.10.0
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.3287)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: XXX
 ID: TC2L:DRL6:WABN:GQF5:J7UY:546Q:J7DE:7E7W:5GYO:QVTI:PIYJ:S74C
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Live Restore Enabled: false
```

**Comment by jcarnus** [comment]
Hi,
We do not open such ticket. But we manage to resolve the issue by disabling the Windows 2019 RSC feature at network level https://kb.vmware.com/s/article/2129176.
I can guarantee that if docker is not used (so same webserver) directly installed on the host, the issue do not exists. So there is something with Docker broking the network flow only when RSC feature is enabled.

Thanks

**Comment by corhere** [comment]
The fact that disabling RSC is a workaround suggests that the issue is most likely something which only Microsoft can resolve. You could escalate the issue with Microsoft if that option is available to you, or [you could try reporting the bug against Microsoft/Windows-Containers](https://github.com/microsoft/Windows-Containers/issues/new?assignees=&labels=bug&template=bug_report.md&title=).

**Comment by jcarnus** [comment]
Done as per https://github.com/microsoft/Windows-Containers/issues/301
