### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference - net.networkNumberAndMask

### ISSUE THREAD

**Issue by warrenc5** [moby/moby#44636]
### Description

` time="2022-12-14T13:02:52.251062361+11:00" level=info msg="Firewalld: docker zone already exists, returning"
Dec 14 13:02:53 leet dockerd[19455]: time="2022-12-14T13:02:53.464619478+11:00" level=info msg="Firewalld: interface docker0 already part of docker zone, returning"
Dec 14 13:02:53 leet dockerd[19455]: time="2022-12-14T13:02:53.506756165+11:00" level=info msg="Firewalld: interface docker0 already part of docker zone, returning"
Dec 14 13:02:53 leet dockerd[19455]: time="2022-12-14T13:02:53.563470265+11:00" level=warning msg="Failed to allocate ipam pool(s) for network \"lab_lnet2_2\" (e829418354e9fbc1917b2d1c197b97a73e5eaabe47403227e82ba3a4e22b71a9): Pool overlaps with other one on this address space"
Dec 14 13:02:53 leet dockerd[19455]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 14 13:02:53 leet dockerd[19455]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56279bf3b540]
Dec 14 13:02:53 leet dockerd[19455]: goroutine 1 [running]:
Dec 14 13:02:53 leet dockerd[19455]: net.networkNumberAndMask(0xc000d4ae18?)
Dec 14 13:02:53 leet dockerd[19455]:         /usr/local/go/src/net/ip.go:498
Dec 14 13:02:53 leet dockerd[19455]: net.(*IPNet).Contains(0xc0001eb6c0?, {0xc000e4a050, 0x10, 0xc000550b40?})
Dec 14 13:02:53 leet dockerd[19455]:         /usr/local/go/src/net/ip.go:522 +0x27
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*endpoint).assignAddressVersion(0xc0001b1760, 0x4, {0x56279df1e3a0, 0xc0012e1110})
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/endpoint.go:1138 +0x23d
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*endpoint).assignAddress(0xc0001eb6c0?, {0x56279df1e3a0, 0xc0012e1110}, 0x1, 0x0)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/endpoint.go:1088 +0x13b
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).reservePools(0x56279df03798?)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:987 +0x850
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/docker/libnetwork.New({0xc0002ef400, 0x9, 0x10})
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:245 +0x74f
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc0000001e0, 0xc0001df080, 0xc000b4e720)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/daemon/daemon_unix.go:856 +0x65
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/daemon.(*Daemon).restore(0xc0000001e0)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/daemon/daemon.go:490 +0x525
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/daemon.NewDaemon({0x56279df164a0?, 0xc0002ec3c0}, 0xc0001df080, 0xc00095a0c0)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/daemon/daemon.go:1152 +0x2fd7
Dec 14 13:02:53 leet dockerd[19455]: main.(*DaemonCli).start(0xc000c72c90, 0xc000a82a20)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x9f0
Dec 14 13:02:53 leet dockerd[19455]: main.runDaemon(...)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:14
Dec 14 13:02:53 leet dockerd[19455]: main.newDaemonCommand.func1(0xc000aa4000?, {0xc000c72c30?, 0x3?, 0x3?})
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x5c
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc000aa4000, {0xc00004e090, 0x3, 0x3})
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:850 +0x67c
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000aa4000)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:958 +0x39c
Dec 14 13:02:53 leet dockerd[19455]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:895
Dec 14 13:02:53 leet dockerd[19455]: main.main()
Dec 14 13:02:53 leet dockerd[19455]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x15d
Dec 14 13:02:53 leet systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 14 13:02:53 leet systemd[1]: docker.service: Failed with result 'exit-code'.
`

### Reproduce

systemctl restart docker

journalctl -f -u docker -p debug

### Expected behavior

it was running and I rebooted now this. 
(when I reboot - I'm unsure if this is already mounted - as it's a user pam_mount.

/dev/mapper/work on /media/wozza/WORK type ext4 (rw,relatime,helper=crypt)

my daemon.conf
{
   "data-root": "/media/work/docker/",
   "insecure-registries": ["localhost:5000"]
}

### docker version

```bash
docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

### docker info

```bash
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
```

### Additional Info

ii  docker-ce      5:20.10.21~3-0~debian-bullseye amd64

**Comment by max-wittig** [comment]
We've seen the same error on production on an arm64 machine, running [gitlab-runner](https://gitlab.com/gitlab-org/gitlab-runner). We're also not sure how to reproduce it though.

```sh
Mar 27 01:32:29 machine01 dockerd[1157]: time="2023-03-27T01:32:29.109446604Z" level=info msg="[core] [Channel #4] Channel Connectivity change to CONNECTING" module=grpc
Mar 27 01:32:29 machine01 dockerd[1157]: time="2023-03-27T01:32:29.109589216Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel Connectivity change to READY" module=grpc
Mar 27 01:32:29 machine01 dockerd[1157]: time="2023-03-27T01:32:29.109623972Z" level=info msg="[core] [Channel #4] Channel Connectivity change to READY" module=grpc
Mar 27 01:32:29 machine01 dockerd[1157]: time="2023-03-27T01:32:29.110262287Z" level=info msg="[graphdriver] trying configured driver: overlay2"
Mar 27 01:32:29 machine01 dockerd[1157]: time="2023-03-27T01:32:29.130550248Z" level=info msg="Loading containers: start."
Mar 27 01:32:29 machine01 dockerd[1157]: panic: runtime error: index out of range [0] with length 0
Mar 27 01:32:29 machine01 dockerd[1157]: goroutine 1 [running]:
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/libnetwork.(*controller).reservePools(0xaaeb4ed4cee0?)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libnetwork/controller.go:862 +0x878
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/libnetwork.New({0x40008aaaf0, 0x9, 0xe})
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libnetwork/controller.go:233 +0x5bc
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0x400062c240, 0x4000db8330)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:851 +0x3c
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/daemon.(*Daemon).restore(0x400062c240)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:478 +0x414
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/daemon.NewDaemon({0xaaeb4ed60f38?, 0x400027cac0}, 0x40005c6b00, 0x4000c64240)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:1085 +0x23a4
Mar 27 01:32:29 machine01 dockerd[1157]: main.(*DaemonCli).start(0x4000b46f90, 0x4000c0f6c0)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:200 +0x7e8
Mar 27 01:32:29 machine01 dockerd[1157]: main.runDaemon(...)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:14
Mar 27 01:32:29 machine01 dockerd[1157]: main.newDaemonCommand.func1(0x4000c36000?, {0x4000b46f30?, 0x3?, 0x3?})
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:38 +0x68
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x4000c36000, {0x4000136010, 0x3, 0x3})
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:916 +0x5c8
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4000c36000)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
Mar 27 01:32:29 machine01 dockerd[1157]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:968
Mar 27 01:32:29 machine01 dockerd[1157]: main.main()
Mar 27 01:32:29 machine01 dockerd[1157]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:102 +0x170
Mar 27 01:32:29 machine01 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by max-wittig** [comment]
I've switched the runner to debug mode. It won't even come up anymore.
This might be more useful:

```sh
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.734479052Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.736978002Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION-STAGE-1]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.739301110Z" level=debug msg="/usr/sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION-STAGE-1]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.741649727Z" level=debug msg="/usr/sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION-STAGE-1]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.744061835Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.746462587Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -I DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.748785612Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.751044105Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -I DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP]"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.753442674Z" level=debug msg="Network (b5c6af0) restored"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.753799160Z" level=debug msg="Endpoint (43d9947) restored to network (7071c07)"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755246369Z" level=debug msg="Allocating IPv4 pools for network runner-bkk98fh1-project-170203-concurrent-3-job-111930801-network (7071c07666ab65ab69f73d83bbeb6d169d752376a5d993ad3d574c3f48f5ee8c)"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755276588Z" level=debug msg="RequestPool(LocalDefault, 192.168.198.0/24, , map[], false)"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755305207Z" level=debug msg="RequestAddress(LocalDefault/192.168.198.0/24, 192.168.198.1, map[RequestAddressType:com.docker.network.gateway])"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755323349Z" level=debug msg="Request address PoolID:192.168.198.0/24 App: ipam/default/data, ID: LocalDefault/192.168.198.0/24, DBIndex: 0x0, Bits: 256, Unselected: 254, Sequence: (0x80000000, 1)->(0x0, 6)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:192.168.198.1 "
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755513870Z" level=debug msg="Assigning addresses for endpoint runner-bkk98fh1-project-170203-concurrent-3-5bd4e3e06038a351-build-2's interface on network runner-bkk98fh1-project-170203-concurrent-3-job-111930801-network"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755535851Z" level=debug msg="RequestAddress(LocalDefault/192.168.198.0/24, 192.168.198.2, map[])"
Mar 27 07:55:24 machine01 dockerd[2134]: time="2023-03-27T07:55:24.755553837Z" level=debug msg="Request address PoolID:192.168.198.0/24 App: ipam/default/data, ID: LocalDefault/192.168.198.0/24, DBIndex: 0x0, Bits: 256, Unselected: 253, Sequence: (0xc0000000, 1)->(0x0, 6)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:192.168.198.2 "
Mar 27 07:55:24 machine01 dockerd[2134]: panic: runtime error: index out of range [0] with length 0
Mar 27 07:55:24 machine01 dockerd[2134]: goroutine 1 [running]:
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/libnetwork.(*controller).reservePools(0xabaa451ccee0?)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libnetwork/controller.go:862 +0x878
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/libnetwork.New({0x40005fc850, 0x9, 0xe})
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libnetwork/controller.go:233 +0x5bc
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0x4000578480, 0x40005cb890)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:851 +0x3c
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/daemon.(*Daemon).restore(0x4000578480)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:478 +0x414
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/daemon.NewDaemon({0xabaa451e0f38?, 0x40008b02c0}, 0x40008cf080, 0x40005cb950)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:1085 +0x23a4
Mar 27 07:55:24 machine01 dockerd[2134]: main.(*DaemonCli).start(0x4000bed4d0, 0x4000aecee0)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:200 +0x7e8
Mar 27 07:55:24 machine01 dockerd[2134]: main.runDaemon(...)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:14
Mar 27 07:55:24 machine01 dockerd[2134]: main.newDaemonCommand.func1(0x4000958000?, {0x4000bed470?, 0x3?, 0x3?})
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:38 +0x68
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x4000958000, {0x400004e090, 0x3, 0x3})
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:916 +0x5c8
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4000958000)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
Mar 27 07:55:24 machine01 dockerd[2134]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:968
Mar 27 07:55:24 machine01 dockerd[2134]: main.main()
Mar 27 07:55:24 machine01 dockerd[2134]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:102 +0x170
Mar 27 07:55:24 machine01 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by thaJeztah** [comment]
Assuming this is v23.0.1, it looks like the panic is happening on this line; https://github.com/moby/moby/blob/v23.0.1/libnetwork/controller.go#L862

**Comment by thaJeztah** [comment]
This was the other discussion I recalled; https://github.com/moby/moby/issues/45057#issuecomment-1440281055

**Comment by akerouanton** [comment]
Looking back at stack traces dumped here; @max-wittig you're hitting the same issue as described in #45057 and fixed in #45310 (released in v24.0 and backported to v20.10) and #45314 (released in v24.0).

@warrenc5 As for what you saw, I'm not entirely sure this is the same issue, but:

* `ipamV4Info` would have to be in an invalid state too to trigger this stack trace ;
* This error message is unexpected at startup time: `Failed to allocate ipam pool(s) for network "lab_lnet2_2" (e829418354e9fbc1917b2d1c197b97a73e5eaabe47403227e82ba3a4e22b71a9): Pool overlaps with other one on this address space`
* I see dockerd `data-dir` is on a `/media`, and is backed by some dm-crypt setup. What's the backing storage device?

**Comment by warrenc5** [comment]
Ok, thanks for the investigation. Btw - I haven't had this issue again, but will reply for completness.

I guess ipamV4Info was invalid. 
I don't know why. 
Lots of removing networks and restarting firewalld and docker maybe?

Overlapping address pools is expected as I do have multiple composures with the same settings - and I just 'docker network rm'  when I need to switch.

The backing storage device is a block device - dm-crypt->md (raid1)->mmc&usb (so pretty normal)

Thanks again.

**Comment by thaJeztah** [comment]
Thanks for the extra information!


As to the issue at hand, some "off the bat" thoughts;

- Panics aren't "great", so we should probably look if we _want_ a panic to happen here (or handle it more gracefully)
- We _could_ handle the situation, and make the daemon return a 500 (internal server error), but that is assuming we're still able to run the daemon in "degraded state" (and/or ways to recover, such as "remove network X, as it's broken / corrupted")
- But of course, of corruption happened (for whatever reason), a panic _could be warranted_ (stop everything, because something is severely broken, and we can't safely continue running). (Some information about "what" is broken could potentially be useful here of course)

@akerouanton any thoughts? Is this something we can recover from, or should it remain to be a panic (possibly a nicer one if we can)?
