### ISSUE TITLE
TestRemoveForce may panic when testing with parallel 

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#44654]
### Description

        Oh! interesting; looks like we have a panic in a test (looks like it may need some fixes for `t.Parallel()`?)

```
#19 60.21 === Failed
#19 60.22 === FAIL: cli/command/container TestRemoveForce (unknown)
#19 60.22 panic: runtime error: invalid memory address or nil pointer dereference
#19 60.22 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaf8060]
#19 60.22 
#19 60.22 goroutine 209 [running]:
#19 60.22 github.com/docker/cli/cli/command/container.TestRemoveForce.func1({0xc000470c60?, 0xc000479f78?}, {0xc88d86, 0xb}, {0xa0?, 0x9f?, 0x47?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/rm_test.go:25 +0x140
#19 60.22 github.com/docker/cli/cli/command/container.(*fakeClient).ContainerRemove(0xc88d86?, {0xdc98f8?, 0xc00012a000?}, {0xc88d86?, 0xc000479f78?}, {0x8?, 0x0?, 0x0?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/client_test.go:87 +0x4a
#19 60.22 github.com/docker/cli/cli/command/container.runRm.func1({0xdc98f8, 0xc00012a000}, {0xc88d86?, 0xc0001deec0?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/rm.go:65 +0x13e
#19 60.22 github.com/docker/cli/cli/command/container.parallelOperation.func2.1({0xc88d86, 0xb})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/utils.go:156 +0x5f
#19 60.22 created by github.com/docker/cli/cli/command/container.parallelOperation.func2
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/utils.go:155 +0x1b5
#19 60.22 
#19 60.22 === FAIL: cli/command/container TestRemoveForce/without_force (unknown)
#19 60.22 panic: runtime error: invalid memory address or nil pointer dereference
#19 60.22 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaf8060]
#19 60.22 
#19 60.22 goroutine 209 [running]:
#19 60.22 github.com/docker/cli/cli/command/container.TestRemoveForce.func1({0xc000470c60?, 0xc000479f78?}, {0xc88d86, 0xb}, {0xa0?, 0x9f?, 0x47?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/rm_test.go:25 +0x140
#19 60.22 github.com/docker/cli/cli/command/container.(*fakeClient).ContainerRemove(0xc88d86?, {0xdc98f8?, 0xc00012a000?}, {0xc88d86?, 0xc000479f78?}, {0x8?, 0x0?, 0x0?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/client_test.go:87 +0x4a
#19 60.22 github.com/docker/cli/cli/command/container.runRm.func1({0xdc98f8, 0xc00012a000}, {0xc88d86?, 0xc0001deec0?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/rm.go:65 +0x13e
#19 60.22 github.com/docker/cli/cli/command/container.parallelOperation.func2.1({0xc88d86, 0xb})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/utils.go:156 +0x5f
#19 60.22 created by github.com/docker/cli/cli/command/container.parallelOperation.func2
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/utils.go:155 +0x1b5
#19 60.22 
#19 60.22 DONE 1565 tests, 2 skipped, 2 failures in 59.815s
#19 ERROR: process "/bin/sh -c gotestsum -- -coverprofile=/tmp/coverage.txt $(go list ./... | grep -vE '/vendor/|/e2e/')" did not complete successfully: exit code: 1
------
 > [test 2/2] RUN --mount=type=bind,target=.,rw     --mount=type=cache,target=/root/.cache     --mount=type=cache,target=/go/pkg/mod     gotestsum -- -coverprofile=/tmp/coverage.txt $(go list ./... | grep -vE '/vendor/|/e2e/'):
#19 60.22 github.com/docker/cli/cli/command/container.(*fakeClient).ContainerRemove(0xc88d86?, {0xdc98f8?, 0xc00012a000?}, {0xc88d86?, 0xc000479f78?}, {0x8?, 0x0?, 0x0?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/client_test.go:87 +0x4a
#19 60.22 github.com/docker/cli/cli/command/container.runRm.func1({0xdc98f8, 0xc00012a000}, {0xc88d86?, 0xc0001deec0?})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/rm.go:65 +0x13e
#19 60.22 github.com/docker/cli/cli/command/container.parallelOperation.func2.1({0xc88d86, 0xb})
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/utils.go:156 +0x5f
#19 60.22 created by github.com/docker/cli/cli/command/container.parallelOperation.func2
#19 60.22 	/go/src/github.com/docker/cli/cli/command/container/utils.go:155 +0x1b5
#19 60.22 
#19 60.22 DONE 1565 tests, 2 skipped, 2 failures in 59.815s
```

_Originally posted by @thaJeztah in https://github.com/docker/cli/issues/3915#issuecomment-1353139500_

**Comment by vvoland** [comment]
The original issue was opened in the correct repo 😄 
Closing this one as this is a CLI issue.
