### ISSUE TITLE
dockerd SIGSEGV

### ISSUE THREAD

**Issue by roy-work** [moby/moby#44966]
### Description

`dockerd` crashes with the following segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5566ba6fffc3]
goroutine 57169 [running]:
github.com/docker/docker/vendor/github.com/moby/buildkit/cache.computeBlobChain.func4.1({0x5566bbc43098, 0xc00550f040})
        /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/cache/blobs.go:224 +0x10e3
github.com/docker/docker/vendor/github.com/moby/buildkit/util/flightcontrol.(*call).run(0xc005d55200)
        /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/util/flightcontrol/flightcontrol.go:121 +0x5e
sync.(*Once).doSlow(0x5566b94d6125?, 0x5?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(0xc001821a28?, 0xc005e102d0?)
        /usr/local/go/src/sync/once.go:65 +0x1f
created by github.com/docker/docker/vendor/github.com/moby/buildkit/util/flightcontrol.(*call).wait
        /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/util/flightcontrol/flightcontrol.go:164 +0x44a
```

### Reproduce

We're not sure. Docker is a component of our CI system, which is what it uses to run containers. This fails mid-build, and we aren't exactly sure what container is causing this. (Or why it has changed recently.)

### Expected behavior

That `dockerd` doesn't segfault.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:45:58 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:45:58 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 59
  Running: 1
  Paused: 0
  Stopped: 58
 Images: 38
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-1101-azure
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 72
 Total Memory: 141.6GiB
 Name: agent-HKdZGIU7-vm
 ID: 35deb20c-0361-432e-8697-cdb8779e908c
 Docker Root Dir: /mnt/docker-root
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

I suspect that this may coincide with the release of `docker-ce_23.0.0-1~ubuntu.18.04~bionic_amd64.deb` on the 2nd. I think we were _just_ upgraded to this version.

**Comment by roy-work** [comment]
This seems linked to the phases of our build where we either build, tag, or push docker images. With that entire portion of our CI pipeline commented out, I can get a build to pass without `dockerd` crashing.

That does seem to agree w/ the stack in the segfault, which seems to implicate buildkit. (And we use buildkit.)

Unfortunately, we run a "monorepo", so we build ~56 images in this pipeline, so I'm not sure if it is one in particular.

**Comment by neersighted** [comment]
Duplicate https://github.com/moby/moby/issues/44918.
