### ISSUE TITLE
invalid memory address or nil pointer dereference on image.NewFromJSON

### ISSUE THREAD

**Issue by kub3let** [moby/moby#45454]
### Description

Since some docker update (about 2-5 weeks) I'm seeing 1-2 crashes a week, this is affecting multiple systems so it's not a hardware issue.

The only thing changed is install of zabbix 2 agent, wondering whether this has to do with it.

stack trace:
```
May 03 14:06:34 docker1 dockerd[858]: panic: runtime error: invalid memory address or nil pointer dereference
May 03 14:06:34 docker1 dockerd[858]: runtime/debug.Stack()
May 03 14:06:34 docker1 dockerd[858]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.newPanicError({0x560c0aa89800?, 0x560c0c0b6590})
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:35 +0x2c
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:184 +0x3b
May 03 14:06:34 docker1 dockerd[858]: panic({0x560c0aa89800, 0x560c0c0b6590})
May 03 14:06:34 docker1 dockerd[858]:         /usr/local/go/src/runtime/panic.go:884 +0x212
May 03 14:06:34 docker1 dockerd[858]: encoding/json.(*decodeState).object(0xc00190cbd0, {0x560c0ac6e960?, 0xc001531900?, 0x0?})
May 03 14:06:34 docker1 dockerd[858]:         /usr/local/go/src/encoding/json/decode.go:745 +0x1b5e
May 03 14:06:34 docker1 dockerd[858]: encoding/json.(*decodeState).value(0xc00190cbd0, {0x560c0ac6e960?, 0xc001531900?, 0x90?})
May 03 14:06:34 docker1 dockerd[858]:         /usr/local/go/src/encoding/json/decode.go:374 +0x45
May 03 14:06:34 docker1 dockerd[858]: encoding/json.(*decodeState).unmarshal(0xc00190cbd0, {0x560c0ac6e960?, 0xc001531900?})
May 03 14:06:34 docker1 dockerd[858]:         /usr/local/go/src/encoding/json/decode.go:181 +0x1de
May 03 14:06:34 docker1 dockerd[858]: encoding/json.Unmarshal({0xc0013b4000, 0x2913, 0x2914}, {0x560c0ac6e960, 0xc001531900})
May 03 14:06:34 docker1 dockerd[858]:         /usr/local/go/src/encoding/json/decode.go:108 +0x125
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/image.NewFromJSON({0xc0013b4000, 0x2913, 0x2914})
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/image/image.go:279 +0x56
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/image.(*store).Get(0xc0000a9090, {0xc00043d590, 0x47})
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/image/store.go:211 +0x4e
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/image.(*store).imagesMap(0xc0000a9090, 0x1)
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/image/store.go:329 +0x21b
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/image.(*store).Map(0x0?)
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/image/store.go:316 +0x1e
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/daemon/images.(*ImageService).Images(0xc0005100c0, {0x560c0ae27638?, 0xc001d66640?}, {0x0?, {0xc000d24df
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/daemon/images/images.go:80 +0x3c5
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/daemon/images.(*ImageService).ImageDiskUsage.func1()
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/daemon/images/service.go:246 +0xb0
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc0009c9f56, 0xc001491180, 0xc001a9e768?)
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:189 +0x6f
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall(0xc001491130?, 0x560c0ae0c520?, {0x560c0a367bb8?, 
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:191 +0xa5
May 03 14:06:34 docker1 dockerd[858]: created by github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).DoChan
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:129 +0x315
May 03 14:06:34 docker1 dockerd[858]: goroutine 1110528 [running]:
May 03 14:06:34 docker1 dockerd[858]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func1.2()
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:158 +0x2a
May 03 14:06:34 docker1 dockerd[858]: created by github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func1
May 03 14:06:34 docker1 dockerd[858]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:158 +0x2b2
May 03 14:06:34 docker1 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 03 14:06:34 docker1 systemd[1]: docker.service: Failed with result 'exit-code'.
May 03 14:06:36 docker1 systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
May 03 14:06:36 docker1 systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
May 03 14:06:36 docker1 systemd[1]: Stopped Docker Application Container Engine.
```

update history:
```
root@docker1:/var/log/apt# zcat history.log.* | grep docker -B 2
Start-Date: 2023-01-27  09:21:59
Commandline: apt full-upgrade -y
Upgrade: containerd.io:amd64 (1.6.12-1, 1.6.15-1), docker-ce-rootless-extras:amd64 (5:20.10.21~3-0~debian-buster, 5:20.10.23~3-0~debian-buster), docker-scan-plugin:amd64 (0.21.0~debian-buster, 0.23.0~debian-buster), docker-ce:amd64 (5:20.10.21~3-0~debian-buster, 5:20.10.23~3-0~debian-buster), docker-ce-cli:amd64 (5:20.10.21~3-0~debian-buster, 5:20.10.23~3-0~debian-buster)
--
Start-Date: 2023-03-19  12:13:08
Commandline: apt full-upgrade -y
Install: docker-buildx-plugin:amd64 (0.10.2-1~debian.10~buster, automatic), docker-compose-plugin:amd64 (2.16.0-1~debian.10~buster, automatic)
Upgrade: containerd.io:amd64 (1.6.15-1, 1.6.18-1), docker-ce-rootless-extras:amd64 (5:20.10.23~3-0~debian-buster, 5:23.0.1-1~debian.10~buster), docker-ce:amd64 (5:20.10.23~3-0~debian-buster, 5:23.0.1-1~debian.10~buster), docker-ce-cli:amd64 (5:20.10.23~3-0~debian-buster, 5:23.0.1-1~debian.10~buster)
--
Start-Date: 2023-04-03  12:44:17
Commandline: apt full-upgrade -y
Upgrade: zabbix-agent2:amd64 (1:6.4.0-1+debian10, 1:6.4.1-1+debian10), containerd.io:amd64 (1.6.18-1, 1.6.20-1), docker-ce-rootless-extras:amd64 (5:23.0.1-1~debian.10~buster, 5:23.0.2-1~debian.10~buster), docker-buildx-plugin:amd64 (0.10.2-1~debian.10~buster, 0.10.4-1~debian.10~buster), docker-compose-plugin:amd64 (2.16.0-1~debian.10~buster, 2.17.2-1~debian.10~buster), docker-ce:amd64 (5:23.0.1-1~debian.10~buster, 5:23.0.2-1~debian.10~buster), docker-ce-cli:amd64 (5:23.0.1-1~debian.10~buster, 5:23.0.2-1~debian.10~buster)
--
Start-Date: 2023-04-14  19:22:33
Commandline: apt full-upgrade -y
Upgrade: docker-ce-rootless-extras:amd64 (5:23.0.2-1~debian.10~buster, 5:23.0.3-1~debian.10~buster), docker-ce:amd64 (5:23.0.2-1~debian.10~buster, 5:23.0.3-1~debian.10~buster), docker-ce-cli:amd64 (5:23.0.2-1~debian.10~buster, 5:23.0.3-1~debian.10~buster)
--
Start-Date: 2023-04-19  10:01:52
Commandline: apt full-upgrade -y
Upgrade: docker-ce-rootless-extras:amd64 (5:23.0.3-1~debian.10~buster, 5:23.0.4-1~debian.10~buster), docker-ce:amd64 (5:23.0.3-1~debian.10~buster, 5:23.0.4-1~debian.10~buster), docker-ce-cli:amd64 (5:23.0.3-1~debian.10~buster, 5:23.0.4-1~debian.10~buster)
--
Start-Date: 2023-04-28  20:34:00
Commandline: apt full-upgrade -y
Upgrade: zabbix-agent2:amd64 (1:6.4.1-1+debian10, 1:6.4.2-1+debian10), zabbix-agent2-plugin-postgresql:amd64 (6.4.0-1+debian10, 0:6.4.2-1+debian10), docker-ce-rootless-extras:amd64 (5:23.0.4-1~debian.10~buster, 5:23.0.5-1~debian.10~buster), zabbix-agent2-plugin-mongodb:amd64 (6.4.0-1+debian10, 0:6.4.2-1+debian10), docker-compose-plugin:amd64 (2.17.2-1~debian.10~buster, 2.17.3-1~debian.10~buster), docker-ce:amd64 (5:23.0.4-1~debian.10~buster, 5:23.0.5-1~debian.10~buster), docker-ce-cli:amd64 (5:23.0.4-1~debian.10~buster, 5:23.0.5-1~debian.10~buster)
```

### Reproduce

Actually can't tell, docker is just crashing randomly, no other system events that show why.

### Expected behavior

Docker should not crash

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:17:29 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:29 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 22
  Running: 21
  Paused: 0
  Stopped: 1
 Images: 104
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 4.19.0-23-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.817GiB
 Name: docker1
 ID: PUTV:DSOR:53TR:UVXJ:FKSL:LSNN:R4S3:P6G5:I4CX:RUNN:ZTOT:ATLT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Thanks for reporting!

Trying to find where exactly it's failing; so the code seems to be going from;
https://github.com/moby/moby/blob/94d3ad69cc598b5a8eb8a643d6999375953512e8/image/store.go#L211

And then panics.. here?
https://github.com/moby/moby/blob/94d3ad69cc598b5a8eb8a643d6999375953512e8/image/image.go#L279-L281

Ultimately ending up here;
https://github.com/golang/go/blob/go1.19.8/src/encoding/json/decode.go#L742-L745

```go
if d.errorContext == nil {
	d.errorContext = new(errorContext)
}
d.errorContext.FieldStack = append(d.errorContext.FieldStack, f.name)
```


Where it panics. Which is.. odd; that's just Go stdLib unmarshaling JSON, and the only thing that could be `nil` there would be `d.errorContext` (which is checked the line before), unless `decodeState` itself is becoming `nil` somehow (which I can't see happening AFAICS) 🤔 I don't even see anything where concurrency could be an issue in those specific locations.

**Comment by kub3let** [comment]
Wow that was a quick reply, thank you @thaJeztah 

I just double checked and searched for the other crashes, here is a stack trace of another system `docker3`

However it seems to be another issue, I first thought they where related, really weird.

I will run a memtest later tonight.

```
Apr 28 20:28:38 docker3 dockerd[881]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 28 20:28:38 docker3 dockerd[881]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x5654cd3d4ddd]
Apr 28 20:28:38 docker3 dockerd[881]: goroutine 2141815 [running]:
Apr 28 20:28:38 docker3 dockerd[881]: github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0008c2780)
Apr 28 20:28:38 docker3 dockerd[881]: #011/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1528 +0xa9d
Apr 28 20:28:38 docker3 dockerd[881]: created by github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
Apr 28 20:28:38 docker3 dockerd[881]: #011/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/internal/transport/http2_client.go:365 +0x18ff
Apr 28 20:28:38 docker3 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 28 20:28:38 docker3 systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 28 20:28:41 docker3 systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Apr 28 20:28:41 docker3 systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
Apr 28 20:28:41 docker3 systemd[1]: Stopped Docker Application Container Engine.
```

**Comment by thaJeztah** [comment]
Yes, that's odd indeed 😬 

One thing I noticed is your `apt full-upgrade -y` commands, which (I think?) would also update the distro itself; have the systems been rebooted since? Also curious if upgrading caused the versions of docker-ce to be upgraded to the packages matching the new distro version (if any). I know older versions of our packaging used a naming format that could result in package not being upgraded to the new distro version.


Oh! And I just see @corhere mentioning on our slack;

> There are a couple of miscompilation bugs which have been fixed in go1.19.9; maybe this panic is a manifestation of one of those?

So it _could_ be a Golang runtime issue 🤔

**Comment by kub3let** [comment]
I can't find any more error logs but I think there was at least one more crash.

So it most likely started on 28 april with the `docker-ce:amd64 5:23.0.5-1~debian.10~buster` package

Servers had been rebooted at least twice in the meantime.

I could upgrade the systems to debian bullseye, the current os buster only has support until august.

They have been running fine and there is nothing in the monitoring/logs beside the docker crash, but given that both errors are memory related I will shut them down now and run memtest for at least an hour.

**Comment by kub3let** [comment]
After 2 hours I canceled memtest, passed without any errors.

Is there any ETA for go 1.19.9 docker release ?

**Comment by neersighted** [comment]
23.0.6 has been released, and is built with go1.19.9. Could you please test this version in your environment?

**Comment by kub3let** [comment]
I updated all my hosts to `docker-ce 5:23.0.6-1` `containerd.io 1.6.21-1`

I will close the issue for now and open it again in case I get another crash.

**Comment by kub3let** [comment]
I just had another crash, I assume this is also one that could normally not happen ? 

I'm really suspecting the RAM now and will RMA it.

```
May 14 13:20:00 docker3 dockerd[918]: panic: runtime error: invalid memory address or nil pointer dereference
May 14 13:20:00 docker3 dockerd[918]: runtime/debug.Stack()
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.newPanicError({0x55f42c201320?, 0x55f42d82f590})
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:35 +0x2c
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:184 +0x3b
May 14 13:20:00 docker3 dockerd[918]: panic({0x55f42c201320, 0x55f42d82f590})
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/runtime/panic.go:884 +0x212
May 14 13:20:00 docker3 dockerd[918]: strings.(*Builder).grow(...)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/strings/builder.go:69
May 14 13:20:00 docker3 dockerd[918]: strings.(*Builder).Grow(...)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/strings/builder.go:82
May 14 13:20:00 docker3 dockerd[918]: strings.Join({0xc000f697b0, 0x2, 0x2}, {0x55f42bf27694, 0x88?})
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/strings/strings.go:443 +0x165
May 14 13:20:00 docker3 dockerd[918]: path/filepath.join({0xc000f697b0?, 0x88?, 0x55f42c5a6928?})
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path_unix.go:45 +0x85
May 14 13:20:00 docker3 dockerd[918]: path/filepath.Join(...)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:226
May 14 13:20:00 docker3 dockerd[918]: path/filepath.walk({0xc0016b7280, 0x7d}, {0x55f42c5a6928, 0xc0016a9520}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:451 +0x1c5
May 14 13:20:00 docker3 dockerd[918]: path/filepath.walk({0xc0016b6f80, 0x77}, {0x55f42c5a6928, 0xc0016a8f70}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:458 +0x285
May 14 13:20:00 docker3 dockerd[918]: path/filepath.walk({0xc0013d93b0, 0x66}, {0x55f42c5a6928, 0xc001593ee0}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]: path/filepath.walk({0xc0013d93b0, 0x66}, {0x55f42c5a6928, 0xc001593ee0}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:458 +0x285
May 14 13:20:00 docker3 dockerd[918]: path/filepath.walk({0xc00098e770, 0x62}, {0x55f42c5a6928, 0xc00157add0}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:458 +0x285
May 14 13:20:00 docker3 dockerd[918]: path/filepath.walk({0xc0010ffda0, 0x5e}, {0x55f42c5a6928, 0xc0014b1ba0}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:458 +0x285
May 14 13:20:00 docker3 dockerd[918]: path/filepath.Walk({0xc0010ffda0, 0x5e}, 0xc000f69bf0)
May 14 13:20:00 docker3 dockerd[918]:         /usr/local/go/src/path/filepath/path.go:521 +0x6c
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/pkg/directory.calcSize({0x55f42c59f450, 0xc000056068}, {0xc0010ffda0, 0x5e})
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/pkg/directory/directory_unix.go:17 +0x145
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/pkg/directory.Size(...)
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/pkg/directory/directory.go:7
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/daemon/graphdriver/overlay2.(*Driver).DiffSize(0xc00011e400, {0xc000ae3a80, 0x40}, {0xc000b937c0, 0x45})
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/daemon/graphdriver/overlay2/overlay.go:714 +0xd3
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/layer.(*mountedLayer).Size(0xc0000aa460?)
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/layer/mounted_layer.go:51 +0x63
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/daemon/images.(*ImageService).GetContainerLayerSize(0xc000920540, {0xc000bf0100, 0x40})
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/daemon/images/image_unix.go:26 +0x1bb
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc00090c480, 0xc00218ff00?, 0xc0009d0070, 0xc000f69ee0)
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/daemon/list.go:236 +0x96
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc00090c480, 0xc0021e7380, 0xf42c5840c0?)
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/daemon/list.go:202 +0x1a5
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/daemon.(*Daemon).Containers(...)
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/daemon/list.go:108
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/daemon.(*Daemon).ContainerDiskUsage.func1()
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/daemon/disk_usage.go:17 +0x5e
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc000f69f56, 0xc001e9b680, 0xc001df9768?)
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:189 +0x6f
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall(0xc001e9b040?, 0x55f42c584300?, {0x55f42bae8bf4?, 
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:191 +0xa5
May 14 13:20:00 docker3 dockerd[918]: created by github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).DoChan
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:129 +0x315
May 14 13:20:00 docker3 dockerd[918]: goroutine 724169 [running]:
May 14 13:20:00 docker3 dockerd[918]: github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func1.2()
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:158 +0x2a
May 14 13:20:00 docker3 dockerd[918]: created by github.com/docker/docker/vendor/golang.org/x/sync/singleflight.(*Group).doCall.func1
May 14 13:20:00 docker3 dockerd[918]:         /go/src/github.com/docker/docker/vendor/golang.org/x/sync/singleflight/singleflight.go:158 +0x2b2
May 14 13:20:00 docker3 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 14 13:20:00 docker3 systemd[1]: docker.service: Failed with result 'exit-code'.
```

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 20
  Running: 19
  Paused: 0
  Stopped: 1
 Images: 132
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 4.19.0-24-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.66GiB
 Name: docker3
 ID: PUTV:DSOR:53TR:UVXJ:FKSL:LSNN:R4S3:P6G5:I4CX:RUNN:ZTOT:ATLT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by kub3let** [comment]
Another memtest for 8 hours passed, I will update to bullseye today which comes with another kernel.

**Comment by corhere** [comment]
That most recent panic is just as impossible as the previous ones. It's deep into a recursive tree traversal, so the same code path must have already been executed multiple times over without panicking. The caller of `strings.Builder.Grow` is [`var b Builder; b.Grow(n)`](https://cs.opensource.google/go/go/+/refs/tags/go1.19.9:src/strings/strings.go;l=442-443). _The only arguments are a pointer to a zero-valued struct and an integer!_ The actual panicking line is, effectively, [`copy(buffer_that_was_just_allocated, []byte(nil))`](https://cs.opensource.google/go/go/+/refs/tags/go1.19.9:src/strings/builder.go;l=69)

Could attempting to access (ostensibly) freshly heap-allocated memory be the common thread between the three panics? It's unfortunate that two of the three panics were in a singleflight group as the faulting memory address is not captured in that case.

@kub3let were you using any monitoring solution for Docker prior to installing the Zabbix 2 agent? It sounds like [the Zabbix agent polls the Docker daemon for container stats](https://www.zabbix.com/documentation/current/en/manual/extensions/plugins#:~:text=Docker,also%3A%0AConfiguration%20parameters) so installing it could be significant in that certain code paths in the daemon are being exercised more frequently than before. That still doesn't explain or excuse the panics, though it raises the possibility that whatever's wrong might have also affected the older daemon version, too, if the circumstances were right.

**Comment by kub3let** [comment]
@corhere I had no Agent on the system before, only an external Icinga2 server that would query the services themselves with simple TCP/HTTP checks but not interact with the Docker daemon. 

Given the many different issues I think it's very unlikely that Docker is the issue and instead it's the memory which manifests now due to Zabbix2 Agent hammering the Docker daemon.

The only thing that's weird to me I would have expected services themselves to crash (segfaults etc.) and restart due to healthcheck but it's always the whole Docker service.

I will close the issue for good and update this thread with my findings from time to time.
