### ISSUE TITLE
Building an image from another with EXPOSE set causes assignment to entry in nil map panic

### ISSUE THREAD

**Issue by bmhughes** [moby/moby#45904]
### Description

Using an image with `EXPOSE` set to build another causes an unexpected EOF error. Stacktrace in the dockerd log:

```log
2023-07-07T15:13:02.598039188Z][dockerd][I] 2023/07/07 15:13:02 http: panic serving @: assignment to entry in nil map
[2023-07-07T15:13:02.598044788Z][dockerd][I] goroutine 1944 [running]:
[2023-07-07T15:13:02.598084688Z][dockerd][I] net/http.(*conn).serve.func1()
[2023-07-07T15:13:02.598085188Z][dockerd][I] 	/usr/local/go/src/net/http/server.go:1854 +0xbf
[2023-07-07T15:13:02.598091788Z][dockerd][I] panic({0x45f660, 0xb6a8d0})
[2023-07-07T15:13:02.598092188Z][dockerd][I] 	/usr/local/go/src/runtime/panic.go:890 +0x263
[2023-07-07T15:13:02.598100788Z][dockerd][I] github.com/docker/docker/daemon/containerd.containerConfigToOciImageConfig(...)
[2023-07-07T15:13:02.598101388Z][dockerd][I] 	/go/src/github.com/docker/docker/daemon/containerd/image_import.go:397
[2023-07-07T15:13:02.598107688Z][dockerd][I] github.com/docker/docker/daemon/containerd.generateCommitImageConfig({0xc001470498, {0x0, 0x0}, {0xc000c437d8, 0x5}, {0x0, 0x0}, {0xc000c43b27, 0x5}, {0x0, ...}, ...}, ...)
[2023-07-07T15:13:02.598108188Z][dockerd][I] 	/go/src/github.com/docker/docker/daemon/containerd/image_commit.go:138 +0x40e
[2023-07-07T15:13:02.598115388Z][dockerd][I] github.com/docker/docker/daemon/containerd.(*ImageService).CommitImage(0xc0008853e0, {0xb8f660, 0xc000c4f7c0}, {{0x0, 0x0}, {0x0, 0x0}, 0xc00104b900, 0xc00104b180, {0xc0011a7640, ...}, ...})
[2023-07-07T15:13:02.598115888Z][dockerd][I] 	/go/src/github.com/docker/docker/daemon/containerd/image_commit.go:82 +0x73b
[2023-07-07T15:13:02.598125288Z][dockerd][I] github.com/docker/docker/daemon/containerd.(*ImageService).CommitBuildStep(0xc0008853e0, {0xb8f660, 0xc000c4f7c0}, {{0x0, 0x0}, {0x0, 0x0}, 0xc00104b900, 0xc00104b180, {0xc0011a7640, ...}, ...})
[2023-07-07T15:13:02.598125788Z][dockerd][I] 	/go/src/github.com/docker/docker/daemon/containerd/image_commit.go:308 +0x110
[2023-07-07T15:13:02.598141588Z][dockerd][I] github.com/docker/docker/builder/dockerfile.(*Builder).commitContainer(0xc0012b8cc0, {0xb8f660, 0xc000c4f7c0}, 0xc0010b2b60, {0xc0011a7640, 0x40}, 0xc00104b180)
[2023-07-07T15:13:02.598142088Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/internals.go:61 +0x168
[2023-07-07T15:13:02.598160688Z][dockerd][I] github.com/docker/docker/builder/dockerfile.(*Builder).commit(0xc0012b8cc0, {0xb8f660, 0xc000c4f7c0}, 0xc0010b2b60, {0xc0012a7d80?, 0xc001340060?})
[2023-07-07T15:13:02.598161188Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/internals.go:45 +0x1aa
[2023-07-07T15:13:02.598167788Z][dockerd][I] github.com/docker/docker/builder/dockerfile.dispatchLabel({0xb8f660, 0xc000c4f7c0}, {0xc0010b2b60, 0xc000c6b628, 0xc0012b8cc0, {0xb80f60, 0xc0011a46c0}, 0xc000bc2560}, 0x1e24a85?)
[2023-07-07T15:13:02.598168088Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/dispatchers.go:83 +0x258
[2023-07-07T15:13:02.598172088Z][dockerd][I] github.com/docker/docker/builder/dockerfile.dispatch({0xb8f660, 0xc000c4f7c0}, {0xc0010b2b60, 0xc000c6b628, 0xc0012b8cc0, {0xb80f60, 0xc0011a46c0}, 0xc000bc2560}, {0xb7be40, 0xc00111cde0})
[2023-07-07T15:13:02.598172188Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/evaluator.go:74 +0x529
[2023-07-07T15:13:02.598177488Z][dockerd][I] github.com/docker/docker/builder/dockerfile.(*Builder).dispatchDockerfileWithCancellation(0xc0012b8cc0, {0xb8f660, 0xc000c4f7c0}, {0xc000b1d380, 0x1, 0xc0011a4660?}, {0x0, 0x0, 0x0?}, 0x5c, ...)
[2023-07-07T15:13:02.598177788Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:296 +0x8f2
[2023-07-07T15:13:02.598181088Z][dockerd][I] github.com/docker/docker/builder/dockerfile.(*Builder).build(0xc0012b8cc0, {0xb8f660, 0xc000c4f7c0}, {0xb80f60, 0xc0011a46c0}, 0xc0011a49f0)
[2023-07-07T15:13:02.598181288Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:211 +0x2e5
[2023-07-07T15:13:02.598184688Z][dockerd][I] github.com/docker/docker/builder/dockerfile.(*BuildManager).Build(0xc0008868c0, {0xb8f708, 0xc0011a44b0}, {{0xb789c0, 0xc0011a4540}, {{0xb6b940, 0xc000c22a50}, {0xb6c5e0, 0xc000c22a68}, {0xb6c5e0, ...}, ...}, ...})
[2023-07-07T15:13:02.598184888Z][dockerd][I] 	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:98 +0x358
[2023-07-07T15:13:02.598188288Z][dockerd][I] github.com/docker/docker/api/server/backend/build.(*Backend).Build(0xc0007d0870, {0xb8f708, 0xc0011a44b0}, {{0xb789c0, 0xc0011a4540}, {{0xb6b940, 0xc000c22a50}, {0xb6c5e0, 0xc000c22a68}, {0xb6c5e0, ...}, ...}, ...})
[2023-07-07T15:13:02.598188488Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/backend/build/backend.go:69 +0x186
[2023-07-07T15:13:02.598191788Z][dockerd][I] github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0xc0008333c0, {0xb8f708, 0xc0011a44b0}, {0xb8e130, 0xc0000ed500}, 0xc0010d4800, 0xc0012df760?)
[2023-07-07T15:13:02.598191988Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/router/build/build_routes.go:280 +0x7a6
[2023-07-07T15:13:02.598195288Z][dockerd][I] github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1({0xb8f708, 0xc0011a44b0}, {0xb8e130?, 0xc0000ed500?}, 0x36cf80?, 0xc0010ab550?)
[2023-07-07T15:13:02.598195488Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:26 +0x15b
[2023-07-07T15:13:02.598198788Z][dockerd][I] github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1({0xb8f708, 0xc0011a4480}, {0xb8e130, 0xc0000ed500}, 0xc000d787e8?, 0xc000d787a0?)
[2023-07-07T15:13:02.598199188Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x4d7
[2023-07-07T15:13:02.598213688Z][dockerd][I] github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1({0xb8f708, 0xc0011a4480}, {0xb8e130?, 0xc0000ed500?}, 0xc0010d4800, 0xc0010ab500?)
[2023-07-07T15:13:02.598213888Z][dockerd][I] 	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x649
[2023-07-07T15:13:02.598217288Z][dockerd][I] github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1({0xb8e130, 0xc0000ed500}, 0xc0010d4700)
[2023-07-07T15:13:02.598217488Z][dockerd][I] 	/go/src/github.com/docker/docker/api/server/server.go:53 +0x1ce
[2023-07-07T15:13:02.598220888Z][dockerd][I] net/http.HandlerFunc.ServeHTTP(0xc0010d4600?, {0xb8e130?, 0xc0000ed500?}, 0xc000d789e8?)
[2023-07-07T15:13:02.598221088Z][dockerd][I] 	/usr/local/go/src/net/http/server.go:2122 +0x2f
[2023-07-07T15:13:02.598224288Z][dockerd][I] github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001a7e00, {0xb8e130, 0xc0000ed500}, 0xc000d37600)
[2023-07-07T15:13:02.598224488Z][dockerd][I] 	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
[2023-07-07T15:13:02.598227588Z][dockerd][I] net/http.serverHandler.ServeHTTP({0xb7ec58?}, {0xb8e130, 0xc0000ed500}, 0xc000d37600)
[2023-07-07T15:13:02.598227788Z][dockerd][I] 	/usr/local/go/src/net/http/server.go:2936 +0x316
[2023-07-07T15:13:02.598230988Z][dockerd][I] net/http.(*conn).serve(0xc0012661b0, {0xb8f708, 0xc000fd0360})
[2023-07-07T15:13:02.598231188Z][dockerd][I] 	/usr/local/go/src/net/http/server.go:1995 +0x612
[2023-07-07T15:13:02.598234388Z][dockerd][I] created by net/http.(*Server).Serve
[2023-07-07T15:13:02.598234588Z][dockerd][I] 	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

Looks like https://github.com/moby/moby/blob/7d548c6c0000a0e3bb350f30264d650050f2b25b/daemon/containerd/image_import.go#L397 is indeed attemping to assign to a nil map.

### Reproduce

1. Build an image with `EXPOSE` present.
2. Use that image to build another container.
3. http: panic serving @: assignment to entry in nil map

### Expected behavior

Image builds.

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.2-38-g8e70a1b23e
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       8e70a1b23e965d86ec8c2feb77605196ae124630
  Built:            Fri Jun  2 15:58:50 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 24.0.2-38-g8e70a1b23e
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.62GiB
 Name: docker-desktop
 ID: 910ad59a-5183-40fd-9cd7-20465a51ca46
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by thaJeztah** [comment]
Thanks for reporting; this looks to be an issue with the "classic builder" (non-BuildKit) integration with the containerd image store enabled.

@bmhughes out of curiosity; how did you hit this issue? The BuildKit builder is now the default when building from the command-line, so curious if you explicitly disabled buildkit (e.g. through the `DOCKER_BUILDKIT=0` env-var), or are you using some other tool that connects with the Engine API to do the build?

We should of course fix this bug, but we're curious if there are specific reasons for you to be using the classic-builder (as it's being deprecated).

**Comment by bmhughes** [comment]
Hi @thaJeztah!

I've hit this through using chef test-kitchen, specifically with the [kitchen-dokken](https://github.com/test-kitchen/kitchen-dokken) driver which I believe uses the docker-api gem to directly use the engine API, so I'm forced to indirectly use the classic builder at this point.

**Comment by thaJeztah** [comment]
Ah, thanks for the extra information.

> specifically with the [kitchen-dokken](https://github.com/test-kitchen/kitchen-dokken) driver which I believe uses the docker-api gem to directly use the engine API, so I'm forced to indirectly use the classic builder at this point.

Hm.. yes, that project should probably consider moving to use the BuildKit API, although developing for that API is slightly more involved. There has been some discussion to provide the legacy API endpoints, but to back them by BuildKit (but with a limited set of functionality purely for backward compatibility).



I opened a PR to fix this issue; https://github.com/moby/moby/pull/45920
