### ISSUE TITLE
Swarm mode: Ports filtered between two dock on same overlay network but different hosts.

### ISSUE THREAD

**Issue by neroita** [moby/moby#46385]
### Description

Hi , 
I've setup 4 vm on vmware esxi:
dmain (docker manager)
d01,d02,d03 (docker worker)
All vm are ubuntu 22.04 , docker 24.05 ( I've also try with debian ).
I've create the swarm and join nodes:
`ID                            HOSTNAME   STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
wlg4eo64k5j57wpr3laa6zb6d     d01        Ready     Active                          24.0.5
s03apb4agqbbwss3vi5mu7nft     d02        Ready     Active                          24.0.5
tu5xtll3so945mo16xnfemioe     d03        Ready     Active                          24.0.5
p984umcz54jt4opuij83u2ed6 *   dmain      Ready     Active         Leader           24.0.5`

If I run two dock from a service on the same node I can ping between the two AND comunicate between ports.
If I move one on a node and one on another I can ping but CAN'T comunicate between ports.
This is a test made with nl -l 1000 on a node and a nmap on other node:
same node:        1000/tcp open
different node:  1000/tcp filtered

This is the network definition:
`[
    {
        "Name": "pippo_net",
        "Id": "9cv8vw1kdqt8mwjt9ruund0pt",
        "Created": "2023-08-31T15:51:46.829400641Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.5.0/24",
                    "Gateway": "10.0.5.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "f5c07cecb60d5f866019c7ba37a611001fb7d43bd36e1619051acf53e68a9313": {
                "Name": "pippo_agent.wlg4eo64k5j57wpr3laa6zb6d.xd6c1karhzflxdlvz2nhzgp3p",
                "EndpointID": "a21f3b77466a38afaf5013765186a5ce53b3add8011c1f69cb0e87002f7facb3",
                "MacAddress": "02:42:0a:00:05:0b",
                "IPv4Address": "10.0.5.11/24",
                "IPv6Address": ""
            },
            "lb-swarmpit_net": {
                "Name": "pippo_net-endpoint",
                "EndpointID": "bb82dd92afd381af4780bc6be832f141c87f0c8e8a07f2d6d86431dbb21090ef",
                "MacAddress": "02:42:0a:00:05:0e",
                "IPv4Address": "10.0.5.14/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4101"
        },
        "Labels": {
            "com.docker.stack.namespace": "pippo"
        },
        "Peers": [
            {
                "Name": "f05ab9dbd658",
                "IP": "10.0.30.200"
            },
            {
                "Name": "4066916b6f5b",
                "IP": "10.0.30.101"
            },
            {
                "Name": "c87417002761",
                "IP": "10.0.30.102"
            },
            {
                "Name": "cee67ea006c2",
                "IP": "10.0.30.103"
            }
        ]
    }
]`
what am I doing wrong ?

### Reproduce

1) [MANAGEMENT] docker swarm init --advertise-addr <my ip>
2) [WORKER 1,2,3] docker swarm join......
3) docker service create ....
4) 

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 9
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: p984umcz54jt4opuij83u2ed6
  Is Manager: true
  ClusterID: hq32icl0m5ty3xak6xua6ms3f
  Managers: 1
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.30.200
  Manager Addresses:
   10.0.30.200:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-82-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: dmain
 ID: f7db4405-183f-4a9f-8e8e-6d9165c903c0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by neroita** [comment]
Hi all , 
I've replicate the entire environment on centos 8 and I get the same problem.
I've deploy portainer for swarm mode ( using one main app and one agent on every node ) and it won't work ,
after some debugging I found that scanning the agent port always work from the same node but NON from different 
node.

SAME NODE:
`root@4611888a6705:/# nmap 192.168.1.5
Starting Nmap 7.80 ( https://nmap.org ) at 2023-09-01 09:36 UTC
Nmap scan report for portainer_agent.7sygohhg8u1ik9nvktd119kzj.z4ovxlunb48qta3tsvbtimwhw.portainer_agentnet (192.168.1.5)
Host is up (0.0000020s latency).
Not shown: 999 closed ports
PORT     STATE SERVICE
9001/tcp open  tor-orport
MAC Address: 02:42:C0:A8:01:05 (Unknown)`

DIFFERENT NODE:
`root@4611888a6705:/# nmap 192.168.1.5
Starting Nmap 7.80 ( https://nmap.org ) at 2023-09-01 09:36 UTC
Nmap scan report for portainer_agent.7sygohhg8u1ik9nvktd119kzj.z4ovxlunb48qta3tsvbtimwhw.portainer_agentnet (192.168.1.5)
Host is up (0.0000020s latency).
Not shown: 999 closed ports
PORT     STATE SERVICE
9001/tcp open  tor-orport
MAC Address: 02:42:C0:A8:01:05 (Unknown)`

Now , I've try three different environment with latest docker-ce ( ubuntu 22.04 , debian 12 , centos 8 ) and I get the 
same result everywhere , is there somethink I don't understand or this is a big bug ?

thanks in advance,
marco.

**Comment by delloncba** [comment]
I figured out how to encrypt the network as @neroita sugested and i can confirm that while it does solve the problem, i think it's not the expected behavior.

**Comment by delloncba** [comment]
The problem still persists as the network is encrypted. After some time running well, ports get filtered again.

23/12/04 19:02:30 INFO Utils: Successfully started service 'sparkWorker' on port 7000.
23/12/04 19:02:30 INFO Worker: Worker decommissioning not enabled.
23/12/04 19:02:30 INFO Worker: Starting Spark worker spark-worker-a:7000 with 2 cores, 16.0 GiB RAM
23/12/04 19:02:30 INFO Worker: Running Spark version 3.5.0
23/12/04 19:02:30 INFO Worker: Spark home: /opt/spark
23/12/04 19:02:30 INFO ResourceUtils: ==============================================================
23/12/04 19:02:30 INFO ResourceUtils: No custom resources configured for spark.worker.
23/12/04 19:02:30 INFO ResourceUtils: ==============================================================
23/12/04 19:02:30 INFO JettyUtils: Start Jetty 0.0.0.0:8081 for WorkerUI
23/12/04 19:02:30 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
23/12/04 19:02:31 INFO WorkerWebUI: Bound WorkerWebUI to 0.0.0.0, and started at http://0.0.0.0:8081
23/12/04 19:02:31 INFO Worker: Connecting to master spark-master:7077...
23/12/04 19:02:31 WARN Worker: Failed to connect to master spark-master:7077
org.apache.spark.SparkException: Exception thrown in awaitResult:
        at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
        at org.apache.spark.deploy.worker.Worker$$anon$1.run(Worker.scala:313)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Failed to connect to spark-master/10.0.2.5:7077
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
        at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
        ... 4 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark-master/10.0.2.5:7077
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
23/12/04 19:02:45 INFO Worker: Retrying connection to master (attempt # 1)
23/12/04 19:02:45 INFO Worker: Connecting to master spark-master:7077...
23/12/04 19:02:45 INFO TransportClientFactory: Successfully created connection to spark-master/10.0.2.5:7077 after 3 ms (0 ms spent in bootstraps)
23/12/04 19:02:45 INFO Worker: Successfully registered with master spark://spark-master:7077
23/12/05 13:21:49 INFO Worker: spark-master:7077 Disassociated !
23/12/05 13:21:49 ERROR Worker: Connection to master failed! Waiting for master to reconnect...
23/12/05 13:21:49 INFO Worker: spark-master:7077 Disassociated !
23/12/05 13:21:49 ERROR Worker: Connection to master failed! Waiting for master to reconnect...
23/12/05 13:21:49 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:21:49 INFO Worker: Not spawning another attempt to register with the master, since there is an attempt scheduled already.
23/12/05 13:21:49 INFO TransportClientFactory: Found inactive connection to spark-master/10.0.2.6:7077, creating a new one.
23/12/05 13:22:03 INFO Worker: Retrying connection to master (attempt # 1)
23/12/05 13:22:03 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:22:17 INFO Worker: Retrying connection to master (attempt # 2)
23/12/05 13:22:17 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:22:31 INFO Worker: Retrying connection to master (attempt # 3)
23/12/05 13:22:31 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:22:45 INFO Worker: Retrying connection to master (attempt # 4)
23/12/05 13:22:45 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:22:59 INFO Worker: Retrying connection to master (attempt # 5)
23/12/05 13:22:59 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:23:13 INFO Worker: Retrying connection to master (attempt # 6)
23/12/05 13:23:13 INFO Worker: Connecting to master spark-master:7077...
23/12/05 13:23:49 WARN NettyRpcEnv: Ignored failure: java.io.IOException: Connecting to spark-master/10.0.2.6:7077 timed out (120000 ms)
23/12/05 13:23:49 WARN Worker: Failed to connect to master spark-master:7077

A port scan shows that port 7077 is being filtered on spark-master (node 1)

nmap -p 7077 spark-master

Starting Nmap 7.80 ( https://nmap.org ) at 2023-12-05 18:04 UTC
Nmap scan report for spark-master (10.0.2.6)
Host is up (0.000044s latency).
Other addresses for spark-master (not scanned): 10.0.2.5
rDNS record for 10.0.2.6: cluster-spark-dapi_spark-master.yxm9ui9rauhsj228rsp8emuu7.ylbdg8vi9w8hc4evn9w28dnhk.cluster-spark-nw

PORT     STATE    SERVICE
7077/tcp filtered unknown

$ sudo docker network inspect cluster-spark-nw
[
    {
        "Name": "cluster-spark-nw",
        "Id": "9c3feu2mjihjggxm6qujuazsk",
        "Created": "2023-12-04T15:02:20.888823888-04:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.2.0/24",
                    "Gateway": "10.0.2.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "97a111bd88c2e53ba6b2e7bd6db9165becf9e68672b59bf92f8a2f92b1eaf944": {
                "Name": "cluster-spark-dapi_spark-master.yxm9ui9rauhsj228rsp8emuu7.ylbdg8vi9w8hc4evn9w28dnhk",
                "EndpointID": "b690209f3467fe19d3967aaa9ae38a52bd23c04040fcd6cc670e3a0c0021a0fb",
                "MacAddress": "XX:XX:XX:XX:XX:XX",
                "IPv4Address": "10.0.2.6/24",
                "IPv6Address": ""
            },
            "lb-cluster-spark-nw": {
                "Name": "cluster-spark-nw-endpoint",
                "EndpointID": "bf6808d330e0080990205721117dec9a387e0b581f5717b769c4f51cb060732b",
                "MacAddress": "XX:XX:XX:XX:XX:XX",
                "IPv4Address": "10.0.2.7/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4098",
            "encrypted": "true"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "4d6b821c2fa5",
                "IP": "10.0.17.211"
            }
        ]
    }
]

**Comment by reisub83** [comment]
Same problem with docker 27.1.0

Fortunately, adding the **encrypted** option to the network as a workaround allowed us to overcome the issue. Let's hope the overhead isn't too impactful on overall performance.
