### ISSUE TITLE
Docker Service Fails to Start in Swarm Mode After a Kernel Update

### ISSUE THREAD

**Issue by JannisDev** [moby/moby#46825]
### Description

I upgraded the kernel of my ubuntu server 22.04 from 5.15.0-83-generic to 5.19.0-43-generic and got an error similar to issue [#29180](https://github.com/moby/moby/issues/29180).

As described in issue [#29180](https://github.com/moby/moby/issues/29180), I removed the node that was a manager from swarm, which worked fine, and deleted the /var/lib/docker/swarm folder on the corrupted node. After that, I was able to start the docker service and rejoin the node to the swarm.

I am not really sure if the problem is related to the kernel update or the fact that I updated docker from 24.0.6 to 24.0.7, or something else.

### Reproduce

1. apt install linux-image-5.19.0-43-generic
2. /sbin/reboot
3. systemctl start docker.service

### Expected behavior

The service should start, but there is always an error

```
# systemctl start docker.service
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.
```
```
# journalctl -xeu docker.service
The job identifier is 4066.
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: time="2023-11-17T07:03:40.468017035Z" level=panic msg="tocommit(48669) is out of range [lastIndex(48650)]. Was the raft log corrupted, truncated, or lost?" module=raft node.id=xsx92qih1r8hj53rms48763gb
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: panic: (*logrus.Entry) 0xc000792700
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: goroutine 300 [running]:
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: github.com/sirupsen/logrus.(*Entry).log(0xc0009e0af0, 0x0, {0xc000cc97a0, 0x63})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:260 +0x4d6
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: github.com/sirupsen/logrus.(*Entry).Log(0xc0009e0af0, 0x0, {0xc001276d10?, 0x2?, 0x2?})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:304 +0x4f
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: github.com/sirupsen/logrus.(*Entry).Logf(0xc0009e0af0, 0x0, {0x55bf0219b7f8?, 0x55bf004f0d45?}, {0xc004f13c40?, 0x55bf02644820?, 0x59f111f13956c200?})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:349 +0x85
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: github.com/sirupsen/logrus.(*Entry).Panicf(0xbe0a?, {0x55bf0219b7f8?, 0x550c7dc3243185be?}, {0xc004f13c40?, 0xc19bf4749bdc06a7?, 0x80deb1fe72be5d74?})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:387 +0x34
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: go.etcd.io/etcd/raft/v3.(*raftLog).commitTo(0xc0009e0b60, 0xbe1d)
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/log.go:237 +0x103
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: go.etcd.io/etcd/raft/v3.(*raft).handleHeartbeat(_, {0x8, 0x7035419add9d798e, 0x5e0e1edd6f878b0e, 0xc, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/raft.go:1508 +0x45
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: go.etcd.io/etcd/raft/v3.stepFollower(_, {0x8, 0x7035419add9d798e, 0x5e0e1edd6f878b0e, 0xc, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/raft.go:1434 +0x3d8
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: go.etcd.io/etcd/raft/v3.(*raft).Step(_, {0x8, 0x7035419add9d798e, 0x5e0e1edd6f878b0e, 0xc, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/raft.go:975 +0x1335
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: go.etcd.io/etcd/raft/v3.(*node).run(0xc000a3b6e0)
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/node.go:356 +0x925
Nov 17 07:03:40 swarm-manager02 dockerd[344369]: created by go.etcd.io/etcd/raft/v3.RestartNode
Nov 17 07:03:40 swarm-manager02 dockerd[344369]:         /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/node.go:244 +0x24a
Nov 17 07:03:40 swarm-manager02 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit docker.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 2.
Nov 17 07:03:40 swarm-manager02 systemd[1]: docker.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit docker.service has entered the 'failed' state with result 'exit-code'.
Nov 17 07:03:40 swarm-manager02 systemd[1]: docker.service: Unit process 344547 (iptables) remains running after unit stopped.
Nov 17 07:03:40 swarm-manager02 systemd[1]: docker.service: Consumed 1.595s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit docker.service completed and consumed the indicated resources.
Nov 17 07:03:42 swarm-manager02 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ Automatic restarting of the unit docker.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Nov 17 07:03:42 swarm-manager02 systemd[1]: Stopped Docker Application Container Engine.
░░ Subject: A stop job for unit docker.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A stop job for unit docker.service has finished.
░░
░░ The job identifier is 4149 and the job result is done.
Nov 17 07:03:42 swarm-manager02 systemd[1]: docker.service: Consumed 1.595s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit docker.service completed and consumed the indicated resources.
Nov 17 07:03:42 swarm-manager02 systemd[1]: docker.service: Start request repeated too quickly.
Nov 17 07:03:42 swarm-manager02 systemd[1]: docker.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit docker.service has entered the 'failed' state with result 'exit-code'.
Nov 17 07:03:42 swarm-manager02 systemd[1]: Failed to start Docker Application Container Engine.
░░ Subject: A start job for unit docker.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit docker.service has finished with a failure.
░░
░░ The job identifier is 4149 and the job result is failed.
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: oj8fjf7p5t6wuih969cnpsrmg
  Is Manager: true
  ClusterID: xlr3necmcq6a1b7kwpe44q5i8
  Managers: 3
  Nodes: 7
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.15.29.22
  Manager Addresses:
   10.15.29.21:2377
   10.15.29.22:2377
   10.15.29.23:2377
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-43-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.831GiB
 Name: swarm-manager02
 ID: 5b9037f5-a566-4e43-ba7f-3fc530a3432f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

If there is any additional information that is missing, please let me know and I will try to provide as much as I can.

**Comment by ArpitKRS** [comment]
/asign this issue to me please and let's discuss over it

**Comment by JannisDev** [comment]
Sorry, I don't know how to assign this to you. Also, because we needed this server, I reinstalled it and don't have a chance to test anything.

> /asign this issue to me please and let's discuss over it

**Comment by chrisprintfactory** [comment]
Same issue here, after kernel update. Seems to be only on the manager node in our cluster. We have 1 and recreation of the swarm is necessary after the error.

Got the following error running dockerD to start the Manager Node:

`PANI[2024-01-20T09:13:02.545069278Z] 37429e02367a901c state.commit 8418 is out of range [10000, 10000]  module=raft node.id=unstg0yeiahpxk2atth88kfcq
panic: (*logrus.Entry) 0xc0005a07e0

goroutine 314 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0005a03f0, 0x0, {0xc0003d9860, 0x41})
        /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:260 +0x491
github.com/sirupsen/logrus.(*Entry).Log(0xc0005a03f0, 0x0, {0xc000c70f90?, 0x4?, 0x4?})
        /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Entry).Logf(0xc0005a03f0, 0x0, {0x55b359744918?, 0x55b357a8fabb?}, {0xc000d4b480?, 0x55b359c5bc40?, 0x0?})
        /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:349 +0x7c
github.com/sirupsen/logrus.(*Entry).Panicf(0x2710?, {0x55b359744918?, 0x0?}, {0xc000d4b480?, 0x0?, 0x0?})
        /root/build-deb/engine/vendor/github.com/sirupsen/logrus/entry.go:387 +0x2e
go.etcd.io/etcd/raft/v3.(*raft).loadState(0xc000b70420, {0x1?, 0x1?, 0x0?})
        /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/raft.go:1698 +0x1a3
go.etcd.io/etcd/raft/v3.newRaft(0xc000bd2f80)
        /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/raft.go:355 +0x67a
go.etcd.io/etcd/raft/v3.NewRawNode(0x55b359c5b380?)
        /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/rawnode.go:48 +0x17
go.etcd.io/etcd/raft/v3.RestartNode(0xc000cc2300?)
        /root/build-deb/engine/vendor/go.etcd.io/etcd/raft/v3/node.go:239 +0x1f
github.com/moby/swarmkit/v2/manager/state/raft.(*Node).JoinAndStart(0xc000cc2300, {0x55b35a22d898?, 0xc000bdcaf0?})
        /root/build-deb/engine/vendor/github.com/moby/swarmkit/v2/manager/state/raft/raft.go:421 +0x7d6
github.com/moby/swarmkit/v2/manager.(*Manager).Run(0xc0008c9a40, {0x55b35a22d860?, 0xc000de2ba0?})
        /root/build-deb/engine/vendor/github.com/moby/swarmkit/v2/manager/manager.go:574 +0x249f
github.com/moby/swarmkit/v2/node.(*Node).runManager.func1(0x0?)
        /root/build-deb/engine/vendor/github.com/moby/swarmkit/v2/node/node.go:1032 +0x65
created by github.com/moby/swarmkit/v2/node.(*Node).runManager in goroutine 307
        /root/build-deb/engine/vendor/github.com/moby/swarmkit/v2/node/node.go:1031 +0x518`
