### ISSUE TITLE
Dockerd panic: runtime error: index out of range

### ISSUE THREAD

**Issue by UberIzual** [moby/moby#47322]
### Description

Feb  4 17:34:33 mgmt-1 esfdaemon[2884]: 0
Feb  4 17:34:34 mgmt-1 dockerd[3765]: panic: runtime error: index out of range [-1]
Feb  4 17:34:34 mgmt-1 dockerd[3765]: goroutine 1692014149 [running]:
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api.encodeVarintLogbroker(...)
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:1712
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api.(*SubscriptionMessage).MarshalToSizedBuffer(0xc8c0149530, {0xc713d29100, 0x3e, 0x3e})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:1620 +0x32a
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api.(*SubscriptionMessage).Marshal(0xc36229f800?)
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:1566 +0x56
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x55754929e268, 0xc4389d07f0}, {0x0, 0x0, 0x0}, 0x0})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:402 +0xa2
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x80?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x55754929e268, 0xc4389d07f0})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x27b
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0x60?, 0x38?, 0x1a?}, {0x0, 0x0, 0x0}, {0x55754926a140?, 0xc4389d07f0?})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x79
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x7f21e46bc158?, 0xc8c0149530?}, 0x2?)
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xa5
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/golang/protobuf/proto.Marshal(...)
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/golang/protobuf/proto/wire.go:23
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x5575491a3860, 0xc8c0149530})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/grpc/encoding/proto/proto.go:45 +0x4e
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/grpc.encode({0x7f21f4258900?, 0x55754a738d10?}, {0x5575491a3860?, 0xc8c0149530?})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/grpc/rpc_util.go:594 +0x44
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/grpc.prepareMsg({0x5575491a3860?, 0xc8c0149530?}, {0x7f21f4258900?, 0x55754a738d10?}, {0x0, 0x0}, {0x0, 0x0})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:1692 +0xd2
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/google.golang.org/grpc.(*serverStream).SendMsg(0xc232615260, {0x5575491a3860?, 0xc8c0149530})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/google.golang.org/grpc/stream.go:1569 +0xf3
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0xc21413e1e0, {0x5575491a3860?, 0xc8c0149530?})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:156 +0x33
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api.(*logBrokerListenSubscriptionsServer).Send(0xc4f1d51ad0?, 0xc4f1d51ad0?)
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:1149 +0x2b
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/manager/logbroker.(*LogBroker).ListenSubscriptions(0xc0013c82a0, 0xc3045081e0?, {0x557549292df0, 0xc2139b41e0})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/manager/logbroker/broker.go:367 +0x90b
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api.(*authenticatedWrapperLogBrokerServer).ListenSubscriptions(0xc0011adb78, 0x557549288660?, {0x557549292df0, 0xc2139b41e0})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:658 +0xca
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api.(*raftProxyLogBrokerServer).ListenSubscriptions(0xc00156ae10, 0x55754919cbc0?, {0x557549292710, 0xc29e9fc540})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:1933 +0x19b
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api._LogBroker_ListenSubscriptions_Handler({0x557548f7ba60?, 0xc00156ae10}, {0x55754928ea50, 0xc21413e1e0})
Feb  4 17:34:34 mgmt-1 dockerd[3765]: #011/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/moby/swarmkit/v2/api/logbroker.pb.go:1136 +0xbc
Feb  4 17:34:34 mgmt-1 dockerd[3765]: github.com/docker/docker/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1({0x557548f7ba60, 0xc00156ae10}, {0x55754928f428?, 0xc232615260}, 0x557546d3b019?, 0x557549254678)
      #

### Reproduce

swarm cluster manager dockerd crashed,  don't find a reproduce step.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:32 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:32 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
[root@mgmt-1 harbor]# docker info
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 36
  Running: 13
  Paused: 0
  Stopped: 23
 Images: 40
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan jhinno/network-plugin:v5.3 macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: pholttqef3uduodr2ykn4os35
  Is Manager: true
  ClusterID: ww1yjms50uodh200irzqfmnt0
  Managers: 5
  Nodes: 83
  Default Address Pool: 12.0.0.0/16  
  SubnetSize: 16
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 
...
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-305.el8.x86_64
 Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 503.5GiB
 Name: mgmt-1
 ID: 84fc58cd-a6bb-4c15-a028-9ca9f47b3d75
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  ...
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
```

**Comment by thaJeztah** [comment]
@corhere @dperny looks like some panic in Swarm code (related to logging?)

**Comment by thaJeztah** [comment]
- opened a PR in swarmkit that should probably address this; https://github.com/moby/swarmkit/pull/3260

**Comment by thaJeztah** [comment]
fixed by https://github.com/moby/moby/pull/53208
